### PR TITLE
fix: `FactoriesCache` undefined method `Config\DocTypes::__set_state`

### PR DESCRIPTION
**Pull request by ddevsr**
**Description**
See [#7859 (Comment)](https://github.com/codeigniter4/CodeIgniter4/issues/7859#issuecomment-1693678605).

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
@kenjis seemed to be proposing an alternate fix:

> If it is possible, I would like to use `new DocTypes()`.

**Comment by paulbalandan** [comment]
I would also like `new DocTypes`.  In our unreleased (yet) phpstan extension, `config(DocTypes::class)` would be flagged.

**Comment by kenjis** [comment]
```php
<?php

namespace App\Controllers;

use Config\DocTypes;

class Home extends BaseController
{
    public function index(): string
    {
        $iterator = new \CodeIgniter\Debug\Iterator();

        $iterator->add('config()', static function () {
            $config = config(DocTypes::class);
        });
        $iterator->add('new', static function () {
            $config = new DocTypes();
        });

        return $iterator->run(300000);
    }
}
```


Test | Time | Memory
-- | -- | --
config() | 0.2692 | 0 Bytes
new | 0.0278 | 0 Bytes

**Comment by kenjis** [comment]
@ddevsr Do you really need to share the instance with Factories?

**Comment by kenjis** [comment]
@ddevsr Can you try #7872 ?

**Comment by ddevsr** [comment]
@kenjis I have tried, same result `undefined method Config\DocTypes::__set_state`

image
image
image
image

**Comment by kenjis** [comment]
@ddevsr Please clear the cache.

**Comment by ddevsr** [comment]
@kenjis Oh, sorry. I can confirm works

**Pull request closed without merging**
