### PR TITLE
refactor: upgrade to PHP 8.1 with rector

### LINKED ISSUE #6921: Dev: drop PHP 7.4 support
PHP 7.4 reached the end of life on 28 Nov 2022.
https://www.php.net/supported-versions.php

- [x] update minimum version to PHP 8.0
  - #7924 
- [x] update PSR\Log to v3. See #4936
- [x] update PSR\Log to v2
  - #7967 
- [x] refactor for PHP 8.0
  - #8354 
  - #7964

### PR DESCRIPTION
**Pull request by kenjis**
> [!IMPORTANT]  
**All refactoring will be performed just prior to the release of v4.5.0.**

**Description**
Supersedes #7964
Closes #6921

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by ddevsr** [comment]
@kenjis I suggest rules `ChangeSwitchToMatchRector` by `Rector\Php80\Rector\Switch_\ChangeSwitchToMatchRector`

**Comment by kenjis** [comment]
Doesn't it included in `LevelSetList::UP_TO_PHP_81`?

**Comment by ddevsr** [comment]
> Doesn't it included in `LevelSetList::UP_TO_PHP_81`?

Sorry i didnt read it

**Comment by kenjis** [comment]
@samsonasik When rector is executed on this branch, rector enters an infinite loop, because of the following files:
```
            __DIR__ . '/system/Common.php',
            __DIR__ . '/system/Helpers/filesystem_helper.php',
            __DIR__ . '/system/Helpers/text_helper.php',
            __DIR__ . '/system/Helpers/form_helper.php',
            __DIR__ . '/system/Helpers/html_helper.php',
            __DIR__ . '/system/Helpers/number_helper.php',
```
Rector adds too many `declare(strict_types=1);` lines to them.
Is this a bug?

**Comment by samsonasik** [comment]
@kenjis probably, could you create a reproducible at https://getrector.com/demo and report at https://github.com/rectorphp/rector/ ? Thank you.

**Comment by kenjis** [comment]
@samsonasik These files with too many `declare(strict_types=1)` are all functions, not class files.
But I cannot make a simple reproducible sample code.

**Comment by samsonasik** [comment]
@kenjis the `DeclareStrictTypesRector` can be skipped if it make too many changes, and create separate PR to enable that?

**Comment by samsonasik** [comment]
Actually, the `DeclareStrictTypesRector` is not part of any set list now, so should not apply the changes except registered, I can't see any addition of `declare(strict_types=1)` now in github diff

**Comment by samsonasik** [comment]
@kenjis could you rebase and retry add `DeclareStrictTypesRector`, run `composer update`, and verify if no longer infinite loop on latest rector 1.0.3? Thank you.

**Comment by kenjis** [comment]
@samsonasik Thank you! It worked fine.
```
[OK] 148 files have been changed by Rector  
```

**Review by michalsn — APPROVED** [review]

**Review by samsonasik — APPROVED** [review]

**Pull request merged**
