### PR TITLE
apply rector: set auto import FQCN

### PR DESCRIPTION
**Pull request by samsonasik**
automatically move FQCN to use statements with rector option: 

```php
$parameters->set(Option::AUTO_IMPORT_NAMES, true);
```

**Checklist:**
- [x] Securely signed commits
- [x] Conforms to style guide

### CODE REVIEW

**Comment by samsonasik** [comment]
All green 🎉

**Review by michalsn — APPROVED** [review]
I believe this is something we want to happen but I will wait for confirmation from others.

**Comment by samsonasik** [comment]
rebased

**Review by MGatner — APPROVED** [review]
This is definitely my preferred coding style. I would like @lonnieezell to weigh in on if we want to enforce this versus just applying it once.

**Comment by samsonasik** [comment]
rebased, patched with latest develop, squashed.

**Comment by samsonasik** [comment]
Rebased, patched with latest develop, squashed. I am going to merge tomorrow if no more review on it ;)

**Review by MGatner — APPROVED** [review]
I think Lonnie has had plenty of time - I'm fine with this.

**Comment by samsonasik** [comment]
merged 🎉 thank you @MGatner @michalsn for the review.

**Pull request merged**
