### PR TITLE
feat: add `--host` option to `spark routes`

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
- add option to specify host in the request URL

```diff
--- a/app/Config/Routes.php
+++ b/app/Config/Routes.php
@@ -31,6 +31,9 @@ $routes->set404Override();
 // route since we don't have to scan directories.
 $routes->get('/', 'Home::index');
 
+$routes->get('/', 'Account::index', ['hostname' => 'account.example.com']);
+$routes->get('/', 'Media::index', ['subdomain' => 'media']);
+
 /*
  * --------------------------------------------------------------------
  * Additional Routing
```
```console
$ php spark routes

CodeIgniter v4.3.1 Command Line Tool - Server Time: 2023-02-02 05:25:26 UTC+00:00

+--------+-------+------+------------------------------+----------------+---------------+
| Method | Route | Name | Handler                      | Before Filters | After Filters |
+--------+-------+------+------------------------------+----------------+---------------+
| GET    | /     | »    | \App\Controllers\Home::index |                | toolbar       |
+--------+-------+------+------------------------------+----------------+---------------+
```
```console
$ php spark routes --host account.example.com

CodeIgniter v4.3.1 Command Line Tool - Server Time: 2023-02-02 05:25:31 UTC+00:00

Host: account.example.com
+--------+-------+------+---------------------------------+----------------+---------------+
| Method | Route | Name | Handler                         | Before Filters | After Filters |
+--------+-------+------+---------------------------------+----------------+---------------+
| GET    | /     | »    | \App\Controllers\Account::index |                | toolbar       |
+--------+-------+------+---------------------------------+----------------+---------------+
```
```console
$ php spark routes --host media.example.com

CodeIgniter v4.3.1 Command Line Tool - Server Time: 2023-02-02 05:25:34 UTC+00:00

Host: media.example.com
+--------+-------+------+-------------------------------+----------------+---------------+
| Method | Route | Name | Handler                       | Before Filters | After Filters |
+--------+-------+------+-------------------------------+----------------+---------------+
| GET    | /     | »    | \App\Controllers\Media::index |                | toolbar       |
+--------+-------+------+-------------------------------+----------------+---------------+
```

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by michalsn — APPROVED** [review]

**Comment by datamweb** [comment]
@kenjis my routes:
```php
$routes->get('/', 'Home::index');

$routes->get('/', 'Account::index', ['hostname' => 'account.example.com']);

$routes->get('/b1', 'Home::bPage', ['hostname' => 'blog.example.com']);
$routes->get('/a2', 'Home::aPage', ['hostname' => 'blog.example.com']);

$routes->get('login', 'Login::postIndex');
$routes->post('login', 'Login::postIndex');
```
**result :**
```console
C:\Users\ppars\OneDrive\Desktop\CodeIgniter4-4.4>php spark routes --host account.example.com

CodeIgniter v4.3.1 Command Line Tool - Server Time: 2023-02-03 15:05:56 UTC+00:00

Host: account.example.com
+--------+-------+------+-----------------------------------+----------------+---------------+
| Method | Route | Name | Handler                           | Before Filters | After Filters |
+--------+-------+------+-----------------------------------+----------------+---------------+
| GET    | /     | »    | \App\Controllers\Account::index   |                | toolbar       |
| GET    | login | »    | \App\Controllers\Login::postIndex |                | toolbar       |
| POST   | login | »    | \App\Controllers\Login::postIndex |                | toolbar       |
+--------+-------+------+-----------------------------------+----------------+---------------+
```

In that case I expect the result to be as follows:
```console
C:\Users\ppars\OneDrive\Desktop\CodeIgniter4-4.4>php spark routes --host account.example.com

CodeIgniter v4.3.1 Command Line Tool - Server Time: 2023-02-03 15:10:56 UTC+00:00

Host: account.example.com
+--------+-------+------+---------------------------------+----------------+---------------+
| Method | Route | Name | Handler                         | Before Filters | After Filters |
+--------+-------+------+---------------------------------+----------------+---------------+
| GET    | /     | »    | \App\Controllers\Account::index |                | toolbar       |
+--------+-------+------+---------------------------------+----------------+---------------+
```

**Comment by datamweb** [comment]
And my routes:
```php
$routes->get('/', 'Home::index');

$routes->get('/', 'Account::index', ['hostname' => 'account.example.com']);

$routes->get('/b1', 'Home::bPage', ['hostname' => 'blog.example.com']);
$routes->get('/a2', 'Home::aPage', ['hostname' => 'blog.example.com']);

```
**result :**
```console
C:\Users\ppars\OneDrive\Desktop\CodeIgniter4-4.4>php spark routes --host blog.example.com

CodeIgniter v4.3.1 Command Line Tool - Server Time: 2023-02-03 15:40:15 UTC+00:00

Host: blog.example.com
+--------+-------+------+------------------------------+----------------+---------------+
| Method | Route | Name | Handler                      | Before Filters | After Filters |
+--------+-------+------+------------------------------+----------------+---------------+
| GET    | /     | »    | \App\Controllers\Home::index |                | toolbar       |
| GET    | b1    | »    | \App\Controllers\Home::bPage |                | toolbar       |
| GET    | a2    | »    | \App\Controllers\Home::aPage |                | toolbar       |
+--------+-------+------+------------------------------+----------------+---------------+
```

In that case I expect the result to be as follows:
```console
C:\Users\ppars\OneDrive\Desktop\CodeIgniter4-4.4>php spark routes --host blog.example.com

CodeIgniter v4.3.1 Command Line Tool - Server Time: 2023-02-03 15:41:08 UTC+00:00

Host: blog.example.com
+--------+-------+------+------------------------------+----------------+---------------+
| Method | Route | Name | Handler                      | Before Filters | After Filters |
+--------+-------+------+------------------------------+----------------+---------------+
| GET    | b1    | »    | \App\Controllers\Home::bPage |                | toolbar       |
| GET    | a2    | »    | \App\Controllers\Home::aPage |                | toolbar       |
+--------+-------+------+------------------------------+----------------+---------------+
```

It seems that this PR needs changes.

**Comment by michalsn** [comment]
@datamweb This command should list all the routes that are available for the specified hostname. 
* You can access `account.example.com/login`. 
* The same will be if you set host to `blog.example.com` - you will see the `/` and `login` routes because you can access `blog.example.com/login`.

**Comment by kenjis** [comment]
Yes, this command shows all routes that are available for the specified hostname.

**Comment by datamweb** [comment]
Okay, I get it, my take on this PR was wrong. 
Thanks all.

**Pull request merged**
