### PR TITLE
Rename collectors _*.tpl.php to _*.tpl

### PR DESCRIPTION
**Pull request by MGatner**
**Description**
Fix for #2275

**Checklist:**
- [X] Securely signed commits
- [X] Component(s) with PHPdocs
- [X] Unit testing, with >80% coverage
- [ ] User guide updated
- [X] Conforms to style guide

### CODE REVIEW

**Comment by jim-parry** [comment]
Just to be clear, the template filenames ending with .php breaks the toolbar as released? and simply renaming those files fixes this and merits a hotfix?

**Comment by MGatner** [comment]
Sort of. The toolbar uses View Parser for the collector views. Parser used to require a PHO extension, so even though these were templates they were prefixed “.tpl.php”. When they are called by the toolbar they are simply passed as “.tpl” but the Parser uses to apply “.php” to that, which it doesn’t anymore since other formats are acceptable. So it actually looks for the “.tpl” versions - which don’t exist because they are “.tpl.php”.

**Comment by MGatner** [comment]
The hotfix is debatable - the framework is usable but the debug toolbar won’t work on this release as-is.

**Comment by jim-parry** [comment]
I have to do a hotfix for the framework distro ... didn't create the build properly :'(

**Comment by jim-parry** [comment]
Not related to this PR, but might influence hotfix decision. Expecting Lonnie here shortly, or perhaps we should switch to slack to discuss it?
@lonnieezell @MGatner

**Comment by jim-parry** [comment]
I spoke too soon, re framework hotfix. There is a defect in the build script for it, but not affecting the distro as it turns out.

**Pull request merged**
