### PR TITLE
[UG] RTD Theme graphic improvements

### PR DESCRIPTION
**Pull request by LittleJ**
**Description**
Fixes and color changes. See commits for a detailed list.

### CODE REVIEW

**Comment by LittleJ** [comment]
Please wait, there is an issue with the font

**Comment by LittleJ** [comment]
It's OK now. I confused "Raleway" (Google Font) and "Railway" (Third-party Font).

I did not apply the font to all the text because it is not an "easy to read" font. So I just applied it to the headers, and to "Codeigniter4" on the sidebar header.

**Comment by LittleJ** [comment]
Bonus:
- Added CI's logo in the sidebar
- Fixed an issue regarding a missing font, it's an issue with the (original) theme itself
The console is clear now.

**Comment by LittleJ** [comment]
I have doubts about the font. What do you think ? Is it the good font ?

**Comment by LittleJ** [comment]
@lonnieezell I have doubts about the font. What do you think ? Is it the good font ?

**Comment by LittleJ** [comment]
This last change affects only the content, not headers. Still wondering about the font.

**Comment by lonnieezell** [comment]
@LittleJ Raleway is the final font that was decided on, not Railway. Which is good, because I'm really not a fan of Railway as the header font currently.

**Comment by LittleJ** [comment]
Well... "Raleway" is not the same font as the logo. The "g" is not the same. The default RTD theme font is closer to the expected result :-s It's "Lato".

**Comment by LittleJ** [comment]
I think that:
- Either we find the original font, which looks more like the "Lato" font
- Either we say that "Raleway" is the new official font, and we change the writing in the logo

What do you think ?

**Comment by natanfelles** [comment]
Hi. Is not Amble Bold Italic?
Captura de tela de 2020-02-27 18-29-56

https://www.fontsquirrel.com/fonts/amble

**Comment by LittleJ** [comment]
Thanks Natan for the info :-) Here are the two versions:

**Amble**
AMBLE

**Raleway**
RALEWAY

**Comment by LittleJ** [comment]
It doesn't have to be all with the same font. But probably at least the titles. To make reference to the official graphical charter.

**Comment by lonnieezell** [comment]
The correct logo to look at is not the one on the current site, but the one on the forums. Is that what you're referencing?

**Comment by LittleJ** [comment]
@lonnieezell No... You are right. I'm referencing to the logo currently in the documentation. Indeed, there is another one on the website. I have to change it.

**Comment by LittleJ** [comment]
@lonnieezell Do you have a high quality version of the logo ? I reproduced it in photoshop.

Here is the new version ?  What do you think ?

NL-RALEWAY

And should the font be loaded locally ?

**Comment by LittleJ** [comment]
@lonnieezell & @MGatner : This work is ready for review. With PR #2628 and PR #2646, we now get a design in accordance with the graphic charter for the debug toolbar, the "Welcome" page, and the user guide.

**Comment by LittleJ** [comment]
This last commit adds a unique ID to each page dynamically. Why ? Because it allows to apply a different CSS style on each page, and therefore to have personalized pages (home, about...) without modifying or adding files to the RTD theme. I'm planning improvements on the documentation, to make it clearer.

**Comment by LittleJ** [comment]
Here is a preview of the latest version

Capture d’écran 2020-03-01 à 07 29 35

Capture d’écran 2020-03-01 à 07 30 25

Capture d’écran 2020-03-01 à 07 31 33

**Comment by truelineinfotech** [comment]
it's looking pretty good.

**Comment by LittleJ** [comment]
**IMPORTANT**

**I added instructions in PR #2646 on how to update the RTD theme without losing all this work. I did not change the theme, I extended it with options they offer.**

I couldn't commit it here because it's in conflict with changes I made on the other PR. It's becoming complicated for me now to add more changes without merging PRs 😞

----

PS: Thank you @truelineinfotech 😄

**Comment by lonnieezell** [comment]
Sorry about the delay, busy weekend. I'll look around at lunch and see if I can find a better logo than what's on the website. I know I used to have one... 

Which PR should be finalized first? This or #2646?

**Comment by LittleJ** [comment]
@lonnieezell This one is about the user guide. It brings changes to comply to the graphic charter.

The other one is misleading... it is about the Welcome page in reality. I wrote "Debug bar" because there is one shared file that has been modified, but with no impact on the debug bar. You can generate the CSS from the SASS version, you won't see any change.

Both are separated for now. The priority is up to you. But this pull request should be "easier" to check. 

Please note that I couldn't add contribution information in this pull request. So I did it on the other pull request. Because of conflicts.

**Comment by LittleJ** [comment]
@lonnieezell Other discussions we have with the community shouldn't be blocking this PR. The user guide's files and design are still independent for now.

**Comment by lonnieezell** [comment]
Looks good. Thanks. Merging.

**Pull request merged**
