### PR TITLE
chore: automate merging develop to next minor branch

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
Source: https://github.com/everlytic/branch-merge

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by michalsn** [comment]
Won't it produce too many unnecessary commits? Also, there is a question about conflicts.

**Comment by paulbalandan** [comment]
Hmm, you're right. Maybe instead of every push to `develop` we can set the action to `on: workflow_call`? This means we can manually merge thru the GitHub platform directly instead of using local computer.

**Comment by michalsn** [comment]
Yes, that would be better. But I wonder if the merge commit will be marked as `verified`.

**Comment by paulbalandan** [comment]
It seems it's not the case unless we use a PAT and setup signing info in the repo.

**Comment by paulbalandan** [comment]
I'll close this for now.

**Pull request closed without merging**
