### PR TITLE
Introducing new URL helper method called this_url().

### PR DESCRIPTION
**Pull request by npwsamarasinghe**
This PR address #4116 issue.

A new method that mostly same as the current_url(). But based on the site_url() instead of base_url().

Thanks.

### CODE REVIEW

**Comment by michalsn** [comment]
We need tests, a user guide, and a [changelog](https://github.com/codeigniter4/CodeIgniter4/blob/develop/user_guide_src/source/changelogs/v4.0.5.rst) update before we can merge this.

**Comment by paulbalandan** [comment]
@npwsamarasinghe Do not make merge commits in your fork when you update your copy with the latest develop. Such commits will show up in your PRs here.

**Comment by MGatner** [comment]
@npwsamarasinghe I copied the tests from `current_url()` and update them for my expectations from your new method. Some of the results do not meet this expectations. Please either correct the test cases for your intention or fix your method.

**Comment by paulbalandan** [comment]
@MGatner I think this is closable too.

**Comment by MGatner** [comment]
Superseded by #4675

**Pull request closed without merging**
