### PR TITLE
feat: QueryBuilder join() raw SQL string support

### PR DESCRIPTION
**Pull request by kenjis**
~~Needs to rebase after merging #5817~~

Related #3832

**Description**
- `join()` supports `RawSql`

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by lonnieezell — CHANGES_REQUESTED** [review]
Looks fine to me, but does need docs, like 5817

**Comment by kenjis** [comment]
Added the docs.

**Comment by kenjis** [comment]
Rebased.
Please review.

**Review by michalsn — APPROVED** [review]

**Comment by kenjis** [comment]
@michalsn Thank you!

**Pull request merged**
