### PR TITLE
feat: [Entity] add changedValues() function

### PR DESCRIPTION
**Pull request by christianberkman**
**Description**
Suggesting to introduce a function `Entity::changedValues()` that returns an array of original and changed values of new or changed attributes only. I use this for my project logging capability where I desire to only log changed values.

I have implemented this function in my own `EntityBase` class and have been using it in my live project. Code is not yet optimized and tested but can do if given the go ahead.

Would this be a welcome function to implement in the `Entity` class?

Sample output

```
name =>
   original => 'Peter'
   changed => 'John'
date_birth =>
   original => null,
   changed => '2024-08-01'
```

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by neznaika0** [comment]
You should study the framework in more detail. This has already been implemented.
Set `$onlyChanged = true`  you will only get the changed properties.
https://github.com/codeigniter4/CodeIgniter4/blob/1d3336b7cc07349886178d14757ef5c5885c1da6/system/Entity/Entity.php#L222
https://github.com/codeigniter4/CodeIgniter4/blob/1d3336b7cc07349886178d14757ef5c5885c1da6/system/Entity/Entity.php#L180

**Comment by christianberkman** [comment]
I did come across that, however that would only give the actual (updated) value and would not include the original value? If the use case is too little, I understand.

**Comment by kenjis** [comment]
@christianberkman Thank you for trying to improve CI4!
This seems to be useful for logging/auditing, but it seems the need is too little to implement it in the framework.

**Comment by neznaika0** [comment]
A good solution is to expand the `Entity`

**Pull request closed without merging**
