### PR TITLE
Inflector dashizer function additional whitespaces replace

### PR DESCRIPTION
**Pull request by mostafakhudair**
Allow helper dashizer function replaces whitespaces and underscores with dashes

### CODE REVIEW

**Comment by michalsn** [comment]
Sorry but this could be a breaking change for some people. Probably the same result can be achieved by using `url_title()` helper function.

**Comment by MGatner** [comment]
How about a second parameter that is a list of characters to replace, similar to `trim()`, that defaults to underscore?

**Comment by michalsn** [comment]
That would be an acceptable solution. However, personally I would rather avoid situations where we add parameters to existing functions - especially when it can be handled by the other function (I think it can).

**Comment by MGatner** [comment]
Generally I agree, but since this one is such a parallel to existing string manipulation functions I'm not opposed to it. But yes, this largely just recreates str_replace with array input 😋

**Comment by paulbalandan** [comment]
The desired output of the PR can be achieved by a mix of `dasherize` and `underscore`.
```php
dasherize(underscore('my dog_spot')); // my-dog-spot
```
So leveling up the capability of `dasherize` is too much.

**Pull request closed without merging**
