### PR TITLE
Move built-in generators to Generators folder

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
Move generator commands to `Generators` folder for a bit of consistency.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by paulbalandan** [comment]
I'm not sure what happened but changing the namespace in the `view()` made phpunit spew out the contents of the view?
```
PHPUnit 8.5.8 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.2.15 with Xdebug 2.6.1
Configuration: /home/travis/build/codeigniter4/CodeIgniter4/phpunit.xml.dist
<@php
namespace {namespace};
use CodeIgniter\Database\Migration;
class {class} extends Migration
{
	public function up()
	{
		$this->forge->addField([
			'id'         => [
				'type'       => 'VARCHAR',
				'constraint' => 128,
				'null'       => false,
			],
			'ip_address' => [
				'type'       => 'VARCHAR',
				'constraint' => 45,
				'null'       => false,
			],
			'timestamp'  => [
				'type'       => 'INT',
				'constraint' => 10,
				'unsigned'   => true,
				'null'       => false,
				'default'    => 0,
			],
			'data'       => [
				'type'       => 'TEXT',
				'null'       => false,
				'default'    => '',
			],
		]);
		$this->forge->addKey('id', true);
		$this->forge->addKey('timestamp');
		$this->forge->createTable('', true);
	}
	//--------------------------------------------------------------------
	public function down()
	{
		$this->forge->dropTable('', true);
	}
}
.............................................................   61 / 3385 (  1%)
```

**Comment by michalsn** [comment]
Well, that's strange... maybe tomorrow I will be able to dig into it more.

**Comment by paulbalandan** [comment]
OK. I have found that PHPUnit will `include` all PHP files it will find as defined in the path in `phpunit.xml`. To circumvent this, make all views end with `.tpl`. This way it will not be included and its contents will be spewed out to the terminal.

**Comment by paulbalandan** [comment]
Another Nirvana. Just found out that we can actually exclude files and directories in the XML file. So, no need to worry about file extensions.

**Pull request merged**
