### PR TITLE
chore: add PHP 8.4 to test-phpunit.yml

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
See #9116

- add PHP 8.4 to test-phpunit.yml
- add `--ignore-platform-req=php` temporarily to `@composer update --working-dir=utils`

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
Psalm does not work at the moment.

```
Error: Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - vimeo/psalm[5.0.0, ..., 5.13.1] require php ^7.4 || ~8.0.0 || ~8.1.0 || ~8.2.0 -> your php version (8.4.0-dev) does not satisfy that requirement.
    - vimeo/psalm[5.14.0, ..., 5.25.0] require php ^7.4 || ~8.0.0 || ~8.1.0 || ~8.2.0 || ~8.3.0 -> your php version (8.4.0-dev) does not satisfy that requirement.
    - Root composer.json requires vimeo/psalm ^5.0 -> satisfiable by vimeo/psalm[5.0.0, ..., 5.25.0].

Script @composer update --working-dir=utils handling the post-autoload-dump event returned with error code 2
Error: Process completed with exit code 2.
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/10481362060/job/29030725682?pr=9133

**Comment by kenjis** [comment]
Why  doesn't `continue-on-error: true` work?
Screenshot 2024-08-21 10 33 05

**Comment by paulbalandan** [comment]
You should add `continue-on-error` as part of the workflow step. So, you must add on reusable-phpunit-test.yml

**Comment by kenjis** [comment]
We do not support PHP 8.4 in v4.5.x.

**Pull request closed without merging**
