### PR TITLE
Access to undeclared static property Fix

### PR DESCRIPTION
**Pull request by Terrorboy**
image

-----------------------
different from the specified

\vendor\kint-php\kint\src\Kint.php
image

### CODE REVIEW

**Comment by Terrorboy** [comment]
If you don't fix this, the framework won't work

**Comment by kenjis** [comment]
Sorry, "codeigniter4/framework" has out of dated composer.json.

The workaround is to revert the following changes:
```diff
--- a/system/CodeIgniter.php
+++ b/system/CodeIgniter.php
@@ -249,7 +249,7 @@ class CodeIgniter
          */
        $config = config('Config\Kint');

-        Kint::$max_depth          = $config->maxDepth;
+        Kint::$depth_limit        = $config->maxDepth;
        Kint::$display_called_from = $config->displayCalledFrom;
        Kint::$expanded            = $config->expanded;

@@ -261,7 +261,7 @@ class CodeIgniter
        RichRenderer::$folder = $config->richFolder;
        RichRenderer::$sort  = $config->richSort;
        if (! empty($config->richObjectPlugins) && is_array($config->richObjectPlugins)) {
-            RichRenderer::$object_plugins = $config->richObjectPlugins;
+            RichRenderer::$value_plugins = $config->richObjectPlugins;
        }
        if (! empty($config->richTabPlugins) && is_array($config->richTabPlugins)) {
            RichRenderer::$tab_plugins = $config->richTabPlugins;
```

**Comment by kenjis** [comment]
See #5531

**Comment by Terrorboy** [comment]
Has confirmed. thank you!

**Comment by kenjis** [comment]
@Terrorboy This was fixed. v4.1.6 was re-released.

**Comment by Terrorboy** [comment]
@kenjis Thanks for the quick fix.

**Pull request closed without merging**
