### PR TITLE
[Testing] Use assertEqualsWithDelta() when possible

### PR DESCRIPTION
**Pull request by samsonasik**
**Description**

Run latest rector dev-main to apply `assertEqualsWithDelta()` when possible.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by samsonasik** [comment]
Ready to merge 👍

**Comment by samsonasik** [comment]
Rebased 👍

**Review by kenjis — APPROVED** [review]
LGTM!

**Comment by samsonasik** [comment]
@kenjis thank you for the review

**Review by MGatner — COMMENTED** [review]
TIL
> PHP_FLOAT_EPSILON (float)
> Smallest representable positive number x, so that x + 1.0 != 1.0. Available as of PHP 7.2.0.

**Pull request merged**
