### PR TITLE
Test RedirectResponse problem report

### LINKED ISSUE #1393: RedirectResponse does not set cookies
**Describe the bug**

In a Controller, the following code works:

```php
return $this->response->redirect(route_to('admin'))
->setCookie('foo', 'bar', YEAR)
->setCookie('login_time', $login_time, YEAR);
```

It does not works:

```php
return redirect()->route('admin')
->setCookie('foo', 'bar', YEAR)
->setCookie('login_time', $login_time, YEAR);
```

**CodeIgniter 4 version**

4.0.0-alpha.2

**Affected module(s)**

HTTP

**Expected behavior, and steps to reproduce if appropriate**

Expected cookies to be set.

**Context**
 - OS: [Debian]
 - Web server [PHP]
 - PHP version [7.2]

### PR DESCRIPTION
**Pull request by jim-parry**
Added tests for response->redirect() and redirect(), and both seem ok.
Closes #1393

### CODE REVIEW

**Comment by jim-parry** [comment]
@natanfelles Made an adjustment to Common::redirect() that looks like it has fixed the problem.

**Comment by natanfelles** [comment]
Not solved. But I see a light:

https://github.com/codeigniter4/CodeIgniter4/blob/fb60b92f8bacbc2e28c148c4faafe28091147ac4/system/HTTP/Response.php#L759

Headers are sent before the fluent method `->setCookie()` is called

**Comment by natanfelles** [comment]
And is called again in `send()`:

https://github.com/codeigniter4/CodeIgniter4/blob/fb60b92f8bacbc2e28c148c4faafe28091147ac4/system/HTTP/Response.php#L633-L651

Maybe because of this works with the Response but not with RedirectResponse.

Firefox Raw Headers repeat some headers: https://github.com/codeigniter4/CodeIgniter4/issues/1393#issuecomment-439128266 - because of the headers sent in `redirect()` and `send()`, again. 

Something tells me this is there in bootstrap.php

**Comment by jim-parry** [comment]
sendHeader() in redirect() looks out of place, I agree.
I eliminated it, and that does not affect the unit tests - they still pass.
This could very well be something not-testable with unit testing ... headers are a pain at the best of times with phpunit.
In any case, I pushed the change.

**Comment by jim-parry** [comment]
The travis-ci failure is from Redis tests, not related. This is good to test.

**Pull request merged**
