### PR TITLE
fix: large HTTP input crashes framework

### LINKED ISSUE #6246: Large HTTP Input Crashes
### PHP Version

7.4

### CodeIgniter4 Version

4.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

_No response_

### What happened?

When `php://input` exceeds the PHP memory limit it crashes the framework. 

>  `CONTENT_LENGTH` is *only* set on POST requests and refers specifically to the size of the POST content. The POST content is **always** available from `php://input`, whether it is valid or not. The problem is that we read the input stream regardless of POST validity - we should instead be doing something like checking 
>
> `if (isset($_SERVER['CONTENT_LENGTH']) && $_SERVER['CONTENT_LENGTH'] > get_post_max_value()) ...`
>
> This will prevent reading invalid POST content into the request body. We will also need to check if there are other locations where `php://input` is accessed, and if those need similar checks or if we should somehow invalidate the resource. 

https://github.com/codeigniter4/CodeIgniter4/pull/4748#issuecomment-859526582 for resolution

### Steps to Reproduce

https://github.com/codeigniter4/CodeIgniter4/pull/4748

### Expected Output

Need to be able to handle inputs that exceed memory limit so a developer can manipulate them (via streams probably). 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #6246

- add the conditions not to get the body from `php://input`

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
I think `$body` should be a stream, not a string.

Now and also in this PR  `$body` is set from `php://input` when a POST request comes,
but normally we do not use `$body`, but use data from `$_POST` superglobal.

**Review by lonnieezell — APPROVED** [review]
I think this is fine for now, but I agree - switching it to use streams would be much more capable for large inputs.

**Review by michalsn — APPROVED** [review]

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @kenjis

**Review by MGatner — COMMENTED** [review]
Thanks! Looks great.

**Pull request merged**
