### PR TITLE
docs: replace tab with space

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
- replace tab with space

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPdocs
- [] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by paulbalandan — APPROVED** [review]
Can we somehow come up with a bash script that checks for usage of tabs then replace them with spaces?

**Comment by kenjis** [comment]
Simple replacement might break the RST format.

Eventually, we won't need to use tabs in user guide.
After that, it is better to add a script to check there is no tabs.

**Review by MGatner — APPROVED** [review]
Thanks!!

**Comment by kenjis** [comment]
@paulbalandan I made a PR to check RST files with pre-commit: #5106

**Pull request merged**
