### PR TITLE
Use DocBlocks to document Config classes' properties

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
In CI3, we used arrays to manage configurations. That's why we only used multiline comments (`T_COMMENT`) to document each config. However, in CI4 we have shifted to config classes. Class properties are structural elements that needs to have its documentation in DocBlocks (`T_DOC_COMMENT`). In here, we can add more information on each config variable by defining its type, adding linkable references, etc. This also helps static code analysis tools detect errors in usage by knowing the types used. Plus side also is that in IDEs the definition of the config class' properties will be shown when you hover your mouse over the property. These benefits are deprived on the use of regular comments.

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by paulbalandan** [comment]
Latest test failure is on Predis, which is unrelated here. I think we should somehow modify or remove the metadata test for both Redis and Predis, as current tests results are very volatile.

**Comment by MGatner** [comment]
This was a lot of work! I hope you had some help from Rector or some automation IDE. I think this is great but I would like to look through them a bit more before I merge, or unless someone else can complete a review. 

Re: P/Redis tests I agree. It has been on my list to stand up a GitHub Action for PHPUnit testing and then bring up the idea of dropping Travis. Not sure if that would change consistency of results but it would be a good time to assess things like that.

**Comment by paulbalandan** [comment]
@MGatner any feedback on this PR?

Changes here are 98% changing the pipes `|` to asterisks `*`, 1% adding `@var` type hints, and 1% importing classes used instead of using FQCN.

**Review by MGatner — APPROVED** [review]
Yes I think this is ready to go!

**Comment by paulbalandan** [comment]
Thanks for that! 👌

**Pull request merged**
