### PR TITLE
chore: `disableProcessTimeout` in `analyze` script

### PR DESCRIPTION
**Pull request by ddevsr**
**Description**

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by paulbalandan** [comment]
Where does it timeout? phpstan or rector?

**Comment by MGatner** [comment]
It's what we recommend in DevKit. I always add it myself, not sure if it has ever prevented a timeout or not though.

**Review by MGatner — APPROVED** [review]

**Review by kenjis — APPROVED** [review]
In my environment, Rector times out.

**Comment by kenjis** [comment]
@ddevsr Can you also update https://github.com/codeigniter4/devkit/blob/edf1036c56ee09b322261f0bc9eae9dc4f5fffa8/composer.json#L51 ?

**Comment by ddevsr** [comment]
> @ddevsr Can you also update https://github.com/codeigniter4/devkit/blob/edf1036c56ee09b322261f0bc9eae9dc4f5fffa8/composer.json#L51 ?

@kenjis Done

**Comment by samsonasik** [comment]
Thank you @ddevsr

**Pull request merged**
