### PR TITLE
Fix #4288 FeatureTest dies when throws RedirectException/cached page

### LINKED ISSUE #4288: Bug: FeatureTest dies when throws RedirectException/cached page
**Describe the bug**
`CodeIgniter::run()` may call `exit()` and if you hit the point, FeatureTest (phpunit) dies.

https://github.com/codeigniter4/CodeIgniter4/blob/18d0c3cfa4b765d2cb3b7dd662b03643e818a006/system/CodeIgniter.php#L328
https://github.com/codeigniter4/CodeIgniter4/blob/18d0c3cfa4b765d2cb3b7dd662b03643e818a006/system/CodeIgniter.php#L345
https://github.com/codeigniter4/CodeIgniter4/blob/18d0c3cfa4b765d2cb3b7dd662b03643e818a006/system/CodeIgniter.php#L1139-L1144

**CodeIgniter 4 version**
develop branch

**Affected module(s)**
CodeIgniter.php, Tests

**Expected behavior, and steps to reproduce if appropriate**
phpunit does not die.

**Context**
- OS: [macOS 10.15.7]
- Web server [n/a]
- PHP version [7.4.15]

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fix #4288

- I copied `system/bootsrap.php` to `system/Test/create_app.php`, and changed to `MockCodeIgniter`.
- Removed redundant code in `Test/create_app.php`.
- Move code that runs only once to `Test/bootsrap.php`.
- Move `Test/create_app.php` code to `CIUnitTestCase`.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
Oh no! Too many tests failed.

**Comment by kenjis** [comment]
Aha! We can remove `create_app.php`.
I will do it tomorrow.

**Review by MGatner — COMMENTED** [review]
It looks to me like `new MockCodeIgniter(new App())` can happen right in `CIUnitTestCase`; maybe that's what you meant by "remove create_app.php"? Let me know when this is done, it merits a close look because we use Test/bootstrap.php for more than just PHPUnit.

**Comment by kenjis** [comment]
@MGatner Yes. I've done!

**Review by MGatner — COMMENTED** [review]
Looks better! I would still like to look over the bootstrap changes more closely on desktop but I think this is the right direction.

**Review by paulbalandan — APPROVED** [review]
The addition of `DotEnv` in `system/Test/bootstrap.php` will also fix #3992 .

**Comment by MGatner** [comment]
I will give this a final look this morning.

**Comment by MGatner** [comment]
Everything checks out! I'm a little apprehensive about this since we funnel so much through **bootstrap.php** but I think this is a good and needed change.

**Review by MGatner — APPROVED** [review]

**Pull request merged**
