### PR TITLE
#4302 - postgre wrong placement of IGNORE part of statment (insert)

### LINKED ISSUE #4302: Bug: BaseBuilder->_insert
For Postgress database this 

`$model->ignore(true)->insert($data);`

```
	protected function _insert(string $table, array $keys, array $unescapedKeys): string
	{
		return 'INSERT ' . $this->compileIgnore('insert') . 'INTO ' . $table . ' (' . implode(', ', $keys) . ') VALUES (' . implode(', ', $unescapedKeys) . ')';
	}
```

gives 
INSERT ON CONFLICT DO NOTHINGINTO table() value()

Here are two mistakes 
1) not a NOTHINGINTO but a   NOTHING INTO
2) INSERT INTO table() value() ON CONFLICT DO NOTHING  -- for postgress

I recommend adding  in CodeIgniter\Database\Postgre\Builder  

```
protected function _insert(string $table, array $keys, array $unescapedKeys): string
	{
		return 'INSERT INTO ' . $table . ' (' . implode(', ', $keys) . ') VALUES (' . implode(', ', $unescapedKeys) . ') 
  ' . $this->compileIgnore('insert') ;
	}
```

### PR DESCRIPTION
**Pull request by nowackipawel**
Fixes #4302

### CODE REVIEW

**Comment by kenjis** [comment]
A test failed.
https://github.com/codeigniter4/CodeIgniter4/pull/4304/checks?check_run_id=1930346223

And can you add a test case for this fix?

**Review by MGatner — CHANGES_REQUESTED** [review]
I think wrapping this in `trim()` should resolve the test failures.

**Comment by paulbalandan** [comment]
For squash later.

**Review by MGatner — APPROVED** [review]
I approve the code but I'm unfamiliar with what this is doing in the underlying database. Someone else please sign off on that.

**Review by michalsn — APPROVED** [review]
We need the same fix for `_insertBatch()`.

**Review by michalsn — APPROVED** [review]

**Pull request merged**
