### PR TITLE
fix: `is_cli()` returns `true` when `$_SERVER['HTTP_USER_AGENT']` is missing

### LINKED ISSUE #5336: Bug: `is_cli()` returns `true` on Apache
### PHP Version

7.4

### CodeIgniter4 Version

4.1.5

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

_No response_

### What happened?

`is_cli()` returns `true` after upgrade to 4.1.5 from 4.0.

### Steps to Reproduce

Navigate to the site.

### Expected Output

`is_cli()` returns `false`.

### Anything else?

From https://forum.codeigniter.com/thread-80530-post-391559.html

The environment is:
- Apache 2.0 Handler
- no `$_SERVER['HTTP_USER_AGENT']`
- has `$_SERVER['argv']`
- has `$_SERVER['REMOTE_ADDR']`

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #5336

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
These were changes pretty recently by @paulbalandan to address other issues - he should take a look.

**Review by paulbalandan — COMMENTED** [review]
I'm not sure how to approach this. The recent changes in the `is_cli()` method were to account for cron jobs running in `php-cgi` (#4699 fixed by #4725), edge case in #4739, as well as #4843 and #4848. Obviously, accepting this fix would fail cronjobs in cgi fixed previously.

I still believe the proper fix for this is in my https://github.com/codeigniter4/CodeIgniter4/issues/5336#issuecomment-973801389 by expanding the `isset` calls. Also, seen in StackOverflow https://stackoverflow.com/a/25967493

**Comment by kenjis** [comment]
Thanks.

#4699 is `cgi-fcgi`.
#4739 does not show why. What's the issue to solve?
#4843 is `fpm-fcgi`.
#4848 is `fpm-fcgi`.

> Obviously, accepting this fix would fail cronjobs in cgi fixed previously.

I agree with it.
It seems there are users who do not use `php-cli` with cron.

**Comment by kenjis** [comment]
@paulbalandan I added conditions.

I removed `HTTP_USER_AGENT` and `argv` conditions, because #5336 has `argv` and no `HTTP_USER_AGENT` with Apache environment.

**Comment by paulbalandan** [comment]
#4739 was raised by @najdanovicivan in the Slack channel. I cannot remember the issue then, but adding the `argv` checks fixes his issue.

**Comment by kenjis** [comment]
Searched slack, and I found Ivan said the following causes the issue.
```php
if (! isset($_SERVER['REMOTE_ADDR'], $_SERVER['HTTP_USER_AGENT']))
{
   return true;
}
```
And said `$_SERVER[‘argv’]` is not set.

The following is the fixed code at that time:
```php
		if (PHP_SAPI === 'cli')
		{
			return true;
		}

		if (defined('STDIN'))
		{
			return true;
		}

		if (stristr(PHP_SAPI, 'cgi') && getenv('TERM'))
		{
			return true;
		}

		if (! isset($_SERVER['REMOTE_ADDR'], $_SERVER['HTTP_USER_AGENT']) && isset($_SERVER['argv']) && count($_SERVER['argv']) > 0)
		{
			return true;
		}

		// if source of request is from CLI, the `$_SERVER` array will not populate this key
		return ! isset($_SERVER['REQUEST_METHOD']);
```

**Comment by kenjis** [comment]
@najdanovicivan Do you have any problem with this PR?

**Comment by najdanovicivan** [comment]
> @najdanovicivan Do you have any problem with this PR?

All good here. I had issues with some web requests being treated as CLI due to missing HTTP_USER_AGENT

**Review by paulbalandan — APPROVED** [review]
Since all involved parties are okay with this, then it is good to go.

**Comment by MGatner** [comment]
💪

**Pull request merged**
