### PR TITLE
docs: fix Sphinx errors

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
- fix Sphinx errors

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [x] User guide updated
- [] Conforms to style guide

### CODE REVIEW

**Review by MGatner — APPROVED** [review]
I'm not that familiar with Sphinx and syntax but I trust you to proceed if these changes are all fixes.

**Comment by MGatner** [comment]
If you want a better review I think @paulbalandan has some Sphinx experience.

**Comment by kenjis** [comment]
Now "Test User Guide" check fails. See #6368
This PR fixes the errors.

I also think the way in this PR is the correct way to describe FQCN.

**Comment by kenjis** [comment]
It looks good!
https://codeigniter4.github.io/CodeIgniter4/libraries/email.html#CodeIgniter\Email\Email
https://codeigniter4.github.io/CodeIgniter4/database/query_builder.html#CodeIgniter\Database\BaseBuilder

Compare:
https://codeigniter4.github.io/userguide/libraries/email.html#class-reference
https://codeigniter4.github.io/userguide/database/query_builder.html#class-reference
Cannot link to the class.

**Pull request merged**
