### PR TITLE
Run phpunit tests on changed PHP files only

### PR DESCRIPTION
**Pull request by paulbalandan**
**Checklist:**
- [x] Securely signed commits

### CODE REVIEW

**Comment by michalsn** [comment]
Should we add `composer.json` to this?

**Comment by paulbalandan** [comment]
Added more files.

**Comment by michalsn** [comment]
I guess the `test-phpunit.yml` file should also be added.

**Review by michalsn — APPROVED** [review]

**Comment by MGatner** [comment]
**utils/** just has the Rector parameters and I don't think should be included. @samsonasik?

**Comment by samsonasik** [comment]
@MGatner yes, `utils` can be excluded. If we want to add `utils`, it should be added to `test-rector.yml`.

**Review by samsonasik — APPROVED** [review]

**Pull request merged**
