### PR TITLE
fix: bug on stuck content-type header in Feature Testing

### PR DESCRIPTION
**Pull request by baycik**
Supersedes #7079

When I use FeatureTestTrait if I use `withBodyFormat('json')` function on one request all subsequent requests are sent with `content-type: application/json` even if their body format is not 'json'.

This bug started when I upgraded CI from 4.0.x to 4.2.11. After long investigation I think I found the source of the problem. On line 289 initialization of request has been changed to `Services::request($config, true)` so for each subsequent test request same instance is used. That's why if content-type on one request is set then all other requests are sent with this header. We need some reset mechanism.

**Description**
Explain what you have changed, and why.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
@baycik Thank you for sending PR!
This seems good.

Can you squash the commits? It is only one line change.

**Comment by baycik** [comment]
Yes it contains unnecesarry changes becase initially I thought to comment return statement to reset content-type header before every request;
Unfortunately I can't find how to do the squishing on github. So if this PR is not suitable to you make the change your self to fix the bug.

**Comment by kenjis** [comment]
> Unfortunately I can't find how to do the squishing on github.

Just squash the commits on your local PC, and force push to GitHub.
But if you can't do it, no problem.

**Review by kenjis — APPROVED** [review]

**Comment by kenjis** [comment]
@baycik Thank you!

**Pull request merged**
