### PR TITLE
Support for [option disabled] n form_dropdown.

### PR DESCRIPTION
**Pull request by nowackipawel**
`
form_dropdown(['name'=>'foo', 'disabled_options' => ['bar']], [...options...]);
`
will produce:
`<option value="bar" disabled>....</option>`

### CODE REVIEW

**Comment by jreklund** [comment]
Personally I see this as a hack more than actually solving the issue.

```function form_dropdown($data = '', $options = [], $selected = [], $extra = '', $disabled = [])```

Not sure how this project are about creating breaking changes, but this will be cleaner:

```function form_dropdown($data = '', $options = [], $selected = [],  $disabled = [], $extra = '')```

**Comment by lonnieezell** [comment]
> Not sure how this project are about creating breaking changes, but this will be cleaner:

We try to follow semantic versioning, which means any BC change would require us to put out a v5. Not ready for that.

**Comment by lonnieezell** [comment]
Not a fan of the change, sorry. And there's no tests.

**Comment by nowackipawel** [comment]
@lonnieezell : am I wrong or there is no way to mark options as disabled right now?
Mine version is not breaking the compatibility of  form_dropdown but  because of it extending it with no to mix html code with form_helper functions.

**Pull request closed without merging**
