### PR TITLE
Handle key generation when key is not present in .env

### LINKED ISSUE #6838: Bug: `spark key:generate` doesn't generate `encryption.key` if no template
### PHP Version

7.4

### CodeIgniter4 Version

4.2.10

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

_No response_

### What happened?

Try deleting all entries in `.env` so you can sort out which ones to use.
But when running `spark key:generate` no `encryption.key` is created even though the message on the shell is successful.

### Steps to Reproduce

remove all `.env` then run `php spark key:generate`

### Expected Output

In `.env` should create `encryption.key =` even without template

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
Fixes #6838

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by paulbalandan** [comment]
`key:generate` relies on `env()` to get the replaceable key. If the key is commented out, `env()` will return `''`.
```php
$currentKey = env('encryption.key', '');
```

**Comment by paulbalandan** [comment]
Okay. I got what you mean. This is because `preg_replace()` did not find the old key in the file because it thinks it is an empty string.

**Comment by paulbalandan** [comment]
@totoprayogo1916 Kindly check new code

**Review by datamweb — APPROVED** [review]

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @paulbalandan

**Pull request merged**
