### PR TITLE
Fix XSS

### PR DESCRIPTION
**Pull request by MashinaMashina**
Add esc

Fix XSS in session and variables. Now I see this: https://prnt.sc/q69wnx

### CODE REVIEW

**Comment by lonnieezell** [comment]
I don't think this works. Esc only works on strings I and it should be handled for that strings based on the line you changed. 

Not sure exactly what code situation this is fixing for, but doesn't initially seem like a correct implementation. Can you provide code you're using that has made that present in the toolbar to begin with?

**Comment by MashinaMashina** [comment]
esc support arrays https://codeigniter4.github.io/userguide/general/common_functions.html

> If $data is an array, then it loops over it, escaping each ‘value’ of the key/value pairs.

View data has HTML code https://prnt.sc/q6ac9r

$_GET data using esc function, but varData dont using

**Comment by MashinaMashina** [comment]
Or we can use like that print_r(esc($value), true), but with using esc(print_r($value, true))

**Comment by MashinaMashina** [comment]
Use $_SESSION[1] = "<H1>XSS</H1>";

Or use setVar with html code

**Comment by MashinaMashina** [comment]
@lonnieezell merge pls this commit to CI

**Comment by lonnieezell** [comment]
Already fixed in 68026f8b68d0a81f67520eb9ba9154ed8f471aac

**Pull request closed without merging**
