### PR TITLE
[ci skip] add some useful badges - README.md

### PR DESCRIPTION
**Pull request by truelineinfotech**
**Description**
add some useful badges :  downloads, latest release, stars, license, contributions

**Checklist:**
- [x] update readme.md -add badges
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by lonnieezell** [comment]
I agree. Nice addition. I'm not sure how helpful stars is since it will most of the time be viewed on GitHub where stars shows at the top of the screen, but it doesn't hurt anything either, so merging. thanks!

**Comment by lonnieezell** [comment]
Oops - latest release and License wasn't working correctly. Could you please take a look at them and submit another PR?

**Comment by truelineinfotech** [comment]
sure

**Comment by truelineinfotech** [comment]
image

**Pull request merged**
