### PR TITLE
Add min_dims rule for image file uploads

### PR DESCRIPTION
**Pull request by sys4soft**
Aditional image file upload rule requested here:
https://forum.codeigniter.com/thread-79421.html

**Description**
Add min_dims rule to image file uploads (complement to the max_dims rule already present in the framework)

Already tested and working.

João Ribeiro

### CODE REVIEW

**Comment by lonnieezell** [comment]
I'm glad you were able to test this locally and it works, but we need regression tests in place to make sure nothing breaks in the future. You can see the tests over [here](https://github.com/codeigniter4/CodeIgniter4/tree/develop/tests/system/Images) as references.

**Comment by MGatner** [comment]
This will also need to be pointed at `4.2` branch (and possibly rebased) because `develop` is currently locked to style changes.

**Comment by kenjis** [comment]
@sys4soft Could you write test code for this?
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#unit-testing

**Comment by sys4soft** [comment]
> @sys4soft Could you write test code for this? https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#unit-testing

Sorry, kenjis, but I've never done PHPUnit tests in my life :(
Don't know how to do it and I'm really busy at work right now.

**Comment by paulbalandan** [comment]
Hi, and thanks for your contribution! As this PR has been standing for a couple of months now and no effort has been seen to add the necessary unit testing to confirm the patch, we can conclude that there's no more interest in moving this forward.

We love to see and appreciate all contributions coming in from the community. However, please make it an effort to make it easy for maintainers to verify your code (that you want to be part of the framework core) through unit testing. You cannot (and we cannot, either) expect to write only source code and delegate the testing part to others. Unfortunately, that's not how OSS works.

Closing this for now. We'd still love to see you around contributing to the framework. Feel free to open a new PR once all necessary testing is in place. Thanks!

**Pull request closed without merging**
