### PR TITLE
perf: RouteCollection $routes optimization

### PR DESCRIPTION
**Pull request by kenjis**
~~Needs #7174~~
~~This PR should go to `4.4` branch.~~

**Description**
Ref https://github.com/codeigniter4/CodeIgniter4/issues/6889#issuecomment-1402605541

- change `RouteCollection::$routes` structure

Before:
```
     * [
     *     verb => [
     *         routeName => [
     *             'route' => [
     *                 routeKey(regex) => handler,
     *             ],
     *         ],
     *     ],
     *     // redirect route
     *     '*' => [
     *         routeName => [
     *             'route' => [
     *                 routeKey(regex)(from) => [routeKey(regex)(to) => handler],
     *             ],
     *             'redirect' => statusCode,
     *         ]
     *     ],
     * ]
```
After:
```
     * [
     *     verb => [
     *         routeKey(regex) => [
     *             'name'    => routeName
     *             'handler' => handler,
     *             'from'    => from,
     *         ],
     *     ],
     *     // redirect route
     *     '*' => [
     *          routeKey(regex)(from) => [
     *             'name'     => routeName
     *             'handler'  => [routeKey(regex)(to) => handler],
     *             'from'     => from,
     *             'redirect' => statusCode,
     *         ],
     *     ],
     * ]
```

- add `RouteCollection::$routesName`

**Benchmark**
`app/Config/Routes.php`:
```php
helper('text');

for ($i = 0; $i < 5000; $i++) {
    $from[] = random_string('alpha');
}

timer('register 5001 routes');

for ($i = 0; $i < 5000; $i++) {
    $routes->get($from[$i], 'Home::index' . $i);
}
$routes->get('last', 'Last::last');
timer('register 5001 routes');
d(timer()->getElapsedTime('register 5001 routes'));

$_SERVER['REQUEST_METHOD'] = 'GET';
$requet                    = \Config\Services::incomingrequest(null, false);
$router                    = new \CodeIgniter\Router\Router($routes, $requet);

timer('find last route');
$router->handle('last');
timer('find last route');
dd(timer()->getElapsedTime('find last route'));
```

register 5001 routes:
```
 v4.2.7:  0.0243 seconds
 v4.3.1:  10.2108
This PR:  0.0259
```

find last route:
```
 v4.2.7:  0.0417 seconds
 v4.3.1:  0.0456
This PR:  0.0458
```

macOS 12.6.6
PHP 8.1.20 (cli) (built: Jun  8 2023 20:06:33) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.20, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.20, Copyright (c), by Zend Technologies

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
With Xdebug turned off, updated the benchmarks.

**Comment by samsonasik** [comment]
It seems the changes are only internal, and it doesn't change the usage. I think it can go to the next 4.3.2 release with add note for change structure in case user utilize the structure of it.

**Comment by kenjis** [comment]
Updated the benchmark and added docs.

**Comment by datamweb** [comment]
@kenjis I do not have a correct understanding of this PR. Will the shield be affected?
https://github.com/codeigniter4/shield/blob/3412fac1a2a59d80ddca5c34812e2b2c24c113ec/src/Auth.php#L109-L125

**Comment by kenjis** [comment]
@datamweb No. This is an internal change to the`RouteCollection`. 
Unless you extend the class, nothing will change.

**Review by lonnieezell — APPROVED** [review]

**Pull request merged**
