### PR TITLE
chore: move preload.php

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Follow-up #6088
[
`codeigniter4/framework`](https://github.com/codeigniter4/framework) also should have this file.

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
If `preload.php` is on `framework` part, which in `vendor/` location already, the documentation usage may need update:

https://github.com/codeigniter4/CodeIgniter4/blob/197e99633e8fde8b66eecb1f896dcea29481897a/admin/starter/preload.php#L51

https://github.com/codeigniter4/CodeIgniter4/blob/197e99633e8fde8b66eecb1f896dcea29481897a/admin/starter/preload.php#L19

Or probably better change to:

```php
'include' => __DIR__ . '/system',
```

on inside `framework`

**Comment by kenjis** [comment]
Update the comment.

The `preload.php` should be located in the project root folder.

If it is only in appstarter,
1. devs who do not use appstarter can't get it easily.
2. when it is updated, devs can't update it easily.

**Review by samsonasik — APPROVED** [review]
Looks good 👍

**Comment by samsonasik** [comment]
Thank you @kenjis

**Pull request merged**
