### PR TITLE
Split Session Configuration

### PR DESCRIPTION
**Pull request by mostafakhudair**
Move session configuration into new Config\Session Class

### CODE REVIEW

**Comment by MGatner** [comment]
What happened here? This looked like a good approach, though probably something we would have to assess for breaking changes. I think adding configuration files to **app/** is generally okay though.

**Comment by mostafakhudair** [comment]
I don't figure out where is the issue, Travis build doesn't clear to me

**Comment by paulbalandan** [comment]
Try to close reopen your PR to restart Travis build.

**Comment by paulbalandan** [comment]
I do not know what exit code 9 for phpunit means so I guess you should try to test your changes locally first. If this is php's exit code channeled through phpunit, then this could be a `SIGKILL` signal that resulted from multiple fatal errors. Not sure though.

**Comment by mostafakhudair** [comment]
Anything new? I'm thinking of pulling a new request

**Comment by mostafakhudair** [comment]
Anything new? I'm thinking of pulling a new request

**Comment by mostafakhudair** [comment]
Anything new? I'm thinking of pulling a new request

**Comment by paulbalandan** [comment]
Please do as you will. 😁

**Pull request closed without merging**
