### PR TITLE
required rule error fix

### LINKED ISSUE #4971: Bug: false value is blocked in required rule
**Direction**
This is a bug question. I had found the error cause.
Is the empty function in required rule.
A disclaimer: You can clean more the code to a best development experience.

**Describe the bug**
When I use the required rule, the value false is blocked.

**CodeIgniter 4 version**
The composer version presents this error.

**Affected module(s)**
The module Validation/Rules is the only affected.

**Expected behavior, and steps to reproduce if appropriate**
To reproduce this error, you can create a database table with a boolean value or number in a field. 
Before, you try add false  value in the field.

**Context**
 - OS: [Manjaro Linux, latest]
 - Web server [spark server, latest]
 - PHP version [8.0.8]

### PR DESCRIPTION
**Pull request by OzRib**
Fixes #4971

**Description**
I modified the required rule in Validation/Rules. 
I did it because the required rule blocks the false value when the user try to send a false value to the database.
This problem affected one of my applications when I update the  available value in a product field.
So I decided to solve this problem and helps the community.
The modification is short. Nothing too big.
I updated one of the tests because my objective is modify this behavior.
This a new pull request. More clean, more readable. I think more acceptable.
A little modification but I needed modify this.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
Something still isn't right. I think the goal should be to make the code match the User Guide for `required`:

> Fails if the field is an empty array, empty
string, null or false.

Passing when `is_bool()` means that `false` will pass. I was shocked the tests didn't catch this, only to find that we don't have a test case for this!

My recommendation: update the test files *first* to have explicit cases for each of those inputs mentioned in the User Guide, *then* fix the code to pass the tests. 

One more thing to pay attention to: it seems that `permit_empty` should be the logical opposite of `required`, *except* that when both are present `required` should take precedence.

**Review by MGatner — CHANGES_REQUESTED** [review]
Please update tests for `false`, etc, then make sure the code aligns.

**Comment by OzRib** [comment]
@MGatner okay. Doing

**Comment by OzRib** [comment]
@MGatner I've finished my modifications. 

- [x] Added explicit tests
- [x] Updated tests cases
- [x] Fixed code to pass the tests

But I have a question. Where I can modify the documentation? 
Or only you guys can update the documentation?
My suggestion is modify to accept false value because when the PHP calls a database request, boolean values are turned in integer values. 
Without conflicts.
At least in the MySQL database.

**Comment by MGatner** [comment]
You can modify the User Guide files in this same repo - look in the **user_guide** directory in the root. 

But before you go further: we cannot change what this function accepts arbitrarily. The User Guide is very clear that `false` is not a passing input. I ran a few edge case tests myself:

https://3v4l.org/rTPMd

Surprisingly, the current framework code works as expected. I think it is because `trim()` only accepts a `string` so when `null` or `false` are passed in they get cast to `''`. I would still like to see this method rewritten to make that a little more clear, as well as actual tests added for these cases, but I don't think there is a bug.

**Comment by OzRib** [comment]
Okay. I'll close the PR. 
If I send a new PR will be to turn the code more clean.

**Pull request closed without merging**
