### PR TITLE
fix: `@return` in filter.tpl.php

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
See #6310 

- fix `@return` in `filter.tpl.php`

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by michalsn — COMMENTED** [review]
Why `null` is not an option?

**Comment by kenjis** [comment]
Because there is not `null` in the interface.
https://github.com/codeigniter4/CodeIgniter4/blob/6c187ddfc7da0a9591e5cd2de92f0362753e0f3f/system/Filters/FilterInterface.php#L34

The fewer types the better. is there any reason why we need `null`?

**Review by MGatner — APPROVED** [review]

**Comment by MGatner** [comment]
`null`/`void` is kind of a bogus return type distinction in PHP. I think matching the interface is the way to go.

**Comment by michalsn** [comment]
> The fewer types the better. is there any reason why we need null?

Nah, I haven't checked the interface. Sounds good. I probably saw `null` somewhere else.

**Review by michalsn — APPROVED** [review]

**Pull request merged**
