### PR TITLE
Apply Rector: CountArrayToEmptyArrayComparisonRector

### PR DESCRIPTION
**Pull request by samsonasik**
Change count array comparison to empty array comparison to improve performance

**Checklist:**
- [x] Securely signed commits

### CODE REVIEW

**Comment by samsonasik** [comment]
All green :tada:

**Comment by samsonasik** [comment]
Checked benchmark with 1000000 at https://phpsandbox.io/n/cool-limit-q2mg seems sometime faster, sometime slower, or same. 

Tested locally, compare with `$array !== []` is 2x faster.

**Review by paulbalandan — APPROVED** [review]
I've seen this trend in some repo. Is this check also more performant than truthy checks? I mean if `if ($array !== []` is faster than `if ($array)`?

**Comment by samsonasik** [comment]
@paulbalandan thank you for the review.

**Pull request merged**
