### PR TITLE
refactor: use ::class to config() param

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
`::class` keyword is better than string for IDE or static analysis.

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by datamweb — APPROVED** [review]

**Review by samsonasik — APPROVED** [review]

**Review by TimexPeachtree — APPROVED** [review]
Code looks great for refactor more concise. 
want to check if this has going to be in a major update 4.4.x or within 4.3.x

**Comment by kenjis** [comment]
`develop` means 4.3.x now.

**Comment by mostafakhudair** [comment]
Why should the framework care about the IDE?
`::class` means more code line.

**Comment by datamweb** [comment]
> Why should the framework care about the IDE?

Because it guides the developers. and provides more details when programming.

**Comment by kenjis** [comment]
1. If we use `::class`, IDE can navigate us to the Config property.
   Screenshot 2023-06-26 7 34 28

2. When we use `::class`, IDE can autocomplete the classname.
   Screenshot 2023-06-26 7 37 53

**Comment by kenjis** [comment]
> `::class` means more code line.

If you mean `use` statements like `use Config\Exceptions;`,
I think it is better to write all `use` statements for all dependencies.
Then all classes on which this class depends will be visible.
Too many `uses`statements mean too many dependencies, which may be an issue in class design.

`config('classname')` hides the dependency.

And if you use IDE, the `use` statement will be added automatically.

**Pull request merged**
