### PR TITLE
fix forceHTTPS bug #2633

### PR DESCRIPTION
**Pull request by michalsn**
**Description**
When CI was installed in a subfolder, the redirection to https did not include this folder.
See: #2633

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by michalsn** [comment]
Tests are failing just because I didn't have much luck with some time object 😅

**Comment by MGatner** [comment]
Looks like the test failure was a fluke timing incident. Maybe worth looking into as a separate bug. I think this is ready but I’d like to take a closer look when not on mobile - thanks for taking it on!

**Comment by MGatner** [comment]
Above concern aside I think this is a fine solution. I probably would have done `preg_replace()` on `current_url()` but I don’t know that either solution does better or faster work. Let me know your thoughts on the `rtrim` then we can merge.

**Comment by michalsn** [comment]
My thoughts on `rtrim` - deliver a clear hostname - without a forward slash at the end. But after your comment, I actually checked one more time how the code looks like in `URI::createURIString` and if there is no slash at the end we add it anyway... so `rtrim` has no sense here after all. Just pushed a change.

The thing with using `current_url` is that besides changing the protocol to `https`, we also have to change `baseURL` (in case app is running in a folder), so... string manipulation would be messy. We have a nice class that can handle this for us, so why not use it - that was my thinking when choosing this approach.

**Comment by lonnieezell** [comment]
Looks good to me. Thanks! 

Merging.

**Pull request merged**
