### PR TITLE
Command "key:generate"

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
Added new command for encryption key generation to `.env` file.

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [x] Conforms to style guide

### CODE REVIEW

**Comment by paulbalandan** [comment]
Tests are failing. 😢

**Comment by michalsn** [comment]
How about making one of the methods (hex or base64) a default one? There is no much difference and it would be just easier for developers to type `key:generate`.

I would add support for the key length (with default value).

I'm also wondering should we support the case when there is no `env` file at all (even this default one shipped with the framework). Maybe it's a good idea to mention in the description that we will place a key in the `env` file.

**Comment by paulbalandan** [comment]
Ok. I will do the default encoding and description update. For the support for key length, I don't pretty much understood what you mean. Can you explain a bit more?

**Comment by michalsn** [comment]
The length of the encryption key should vary depending on the encryption algorithm we use. 
https://codeigniter.com/user_guide/libraries/encryption.html#setting-your-encryption-key

**Comment by michalsn** [comment]
What do you think about checking if `env` file actually exists before trying to making a copy?

Also, the last thing - maybe we should replace `hex` with `hext2bin` - since you made it a default method it won't be a big problem to type it and we would keep the names consistency.

**Comment by paulbalandan** [comment]
If the default shipped `env` file is not actually existing before copy, what should be our course of action then? Should we throw an exception, or just output the `$newKey` and an error message to `STDERR`?

**Comment by michalsn** [comment]
Yes, probably just a nice error message that says the `env` file is not available and then we should print the key on the screen.

**Comment by michalsn** [comment]
This is really nice feature. Thank you!

**Pull request merged**
