### PR TITLE
fix: Builder insert()/update() does not accept an object

### LINKED ISSUE #6210: Bug: Builder insert()/update() does not accept an object
### PHP Version

7.4

### CodeIgniter4 Version

4.0.4 

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL 5.56

### What happened?

Hi, I have a problem with DB Builder 
Log:
`CRITICAL - 2022-06-30 09:24:34 --> Argument 1 passed to CodeIgniter\Database\BaseBuilder::update() must be of the type array or null, object given, called in ....php on line 41 `

My mine 40 & line 41: 
```php
$builder = $this->dbmail->table(self::TABLE); 
$builder->update($undelivered, ['undelivered_id' => $undelivered->undelivered_id]); 
```

According to documentation: 
```php
$object = new Myclass(); 
$builder->where('id', $id); 
$builder->update($object); 
```
https://codeigniter4.github.io/CodeIgniter4/database/query_builder.html#builder-update

Builder insert() have a same problem.

### Steps to Reproduce

Just do Builder update with object.

### Expected Output

No critical or any other error

### Anything else?

 Looks like the error is in all versions from 4.0.4 until current

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #6210

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by MGatner — APPROVED** [review]

**Comment by kenjis** [comment]
Added changelog.

**Review by MGatner — COMMENTED** [review]
We've gotten very lenient with breaking changes. This is out of sync with the User Guide but is actual risk of breaking any method extensions. I would like more of the team to sign off on this. 

My opinion: extensions of the `BaseBuilder` should be implementing `_insert()` so `insert()` is unlikely to be extended (and could probably be `final` at some point). Developers extending this should be doing rather advanced work and able to cope with this change. Given these points I am in favor.

**Review by michalsn — APPROVED** [review]
This is more like a bug fix that will accidentally introduce a breaking change for some rare cases, but I have no problem with that. It's not like we woke up one day and said

> Hey, this method should also support objects.

The behavior was documented before and was there even in v3, so from my perspective everything is fine.

**Review by samsonasik — APPROVED** [review]

**Comment by MGatner** [comment]
Thanks for the feedback all! @kenjis I think we're good unless you have more thoughts.

**Pull request merged**
