### PR TITLE
Config Property Types

### PR DESCRIPTION
**Pull request by MGatner**
**Description**
Applies non-breaking property types to Config files in `App`. Applied by Rector.

**Checklist:**
- [X] Securely signed commits
- [X] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [X] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
This should all be safe to change with the possible exception of `Email` which has some odd initial definitions.

**Comment by MGatner** [comment]
Actually this may not work because of the class extensions in `CodeIgniter\Test\Mock` config classes. I have to drop this for now but will think on that later.

**Comment by kenjis** [comment]
> Fatal error: Type of CodeIgniter\Test\Mock\MockCLIConfig::$baseURL must be string (as in class Config\App) in /home/runner/work/CodeIgniter4/CodeIgniter4/system/Test/Mock/MockCLIConfig.php on line 40

**Comment by MGatner** [comment]
I saw that, there are a few other Configs in there that break as well. If we want to move forward with this I think the approach would be to remove the properties from the Mock Config files and use their constructors to change the values that need changing. That way they would still work with whatever is in a user's **app/Config** folder, typed or not.

**Comment by kenjis** [comment]
It would be impossible to ensure that an existing app or tests would never break 
because a Type Error would occur if the configuration class were inherited.

**Comment by MGatner** [comment]
But that is only if the developer manually updates their Config folder with the new files. This should be safe with the caveat of these Mock classes, which we can fix internally but can't guarantee that extensions don't exist.

**Comment by kenjis** [comment]
> But that is only if the developer manually updates their Config folder with the new files. 

Yes, you are correct!

**Comment by kenjis** [comment]
#6214 was merged.

**Pull request closed without merging**
