### PR TITLE
Update File.php

### PR DESCRIPTION
**Pull request by WinterSilence**
**Description**
Issue #2476

**Checklist:**
- [ ] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by Instrye** [comment]
”1048576‬“ is not a number. you can copy "1048576"
Snipaste_2020-01-13_17-16-56

**Comment by WinterSilence** [comment]
@Instrye where u see strings?

**Comment by lonnieezell** [comment]
Still a number of tests failing. See: https://travis-ci.org/codeigniter4/CodeIgniter4/jobs/636365038?utm_medium=notification&utm_source=github_status

**Comment by lonnieezell** [comment]
@WinterSilence will you be able to get the tests fixed for this?

**Comment by lonnieezell** [comment]
Fixes not incoming. Closing.

**Pull request closed without merging**
