### PR TITLE
Update of BaseModel.php to fix INSERT issue

### PR DESCRIPTION
**Pull request by katie1348**
Applied the fix that enables the INSERT to work correctly when inserting a row that already contains data.

Each pull request should address a single issue and have a meaningful title.

Description
Applied the fix suggested by @arbitmcdonald in Bug: onlyChanged is currently true for INSERT codeigniter4#4247

Checklist:

[x]  Securely signed commits
[x]  Component(s) with PHPdocs
[x]  Unit testing, with >80% coverage
[x]  User guide updated
[x]  Conforms to style guide

### CODE REVIEW

**Comment by paulbalandan** [comment]
We would need tests to verify that the fix is actually working.

**Comment by paulbalandan** [comment]
You can take at a look at `tests/system/Models/` dir to check the tests for the Model.

**Comment by katie1348** [comment]
OK, so it looks like the error is a coding standards error of == rather than ===.

Does his mean I need to start the process from the beginning to make this change?

**Comment by paulbalandan** [comment]
No need to open new PR. You can do the edit directly here.

**Comment by paulbalandan** [comment]
Replaced by #4980

**Pull request closed without merging**
