### PR TITLE
chore: update test-deptrac.yml

### PR DESCRIPTION
**Pull request by ddevsr**
**Description**
Follow-up #8627

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by ddevsr** [comment]
@kenjis You forgot remove tools phive

**Review by kenjis — APPROVED** [review]
Thank you!

**Review by MGatner — APPROVED** [review]

**Comment by MGatner** [comment]
Please consider if https://github.com/codeigniter4/devkit/blob/develop/src/Template/.github/workflows/deptrac.yml needs updating as well.

**Comment by kenjis** [comment]
This, too.
https://github.com/codeigniter4/.github/blob/main/.github/workflows/deptrac.yml

**Pull request merged**
