### PR TITLE
Debug bar: Dark/light mode + Complete CSS refactoring

### PR DESCRIPTION
**Pull request by LittleJ**
**Description**

Many devices and applications have a "dark mode" nowadays. I use it on my computer, and I develop applications with this feature.

When I use the current debug bar, it sometimes gives a contrast which is tiring for the eyes. So I thought it might be interesting to add this feature, which ultimately requires only a few lines of code.

Colors are similar to Chrome's console, using dark mode on Mac OS.

**Checklist:**
- [x] Securely signed commits
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide
- [x] Component(s) with PHPdocs (N/A)

### CODE REVIEW

**Comment by MGatner** [comment]
I like the concept, especially as a dark user myself! You might also want to set defaults with a CSS media query, so "unspecified" tries to match the browser/OS setting rather than defaulting to light:
```
@media (prefers-color-scheme: dark) {

}
```

**Comment by LittleJ** [comment]
Thank you for your feedback ! But suddenly it was a little bit more "complicated" to achieve :-) Indeed...

1 / By default, we use CSS and media queries of course
2 / But we must allow the user to change the mode if he wants to. A "light mode user" may want to use the dark mode, and a "dark mode user" may want to use the light mode.

So here is the result I get.

**Comment by natanfelles** [comment]
Just for inspiration: https://github.com/JCSama/CodeIgniter-develbar

**Comment by LittleJ** [comment]
> https://github.com/JCSama/CodeIgniter-develbar

Thank you, indeed :-) Let's finish this work on dark/light mode, and maybe, if people are interested, we could work on design improvements for the debug bar ;-)

**Comment by MGatner** [comment]
Yeah this is looking great! I think the white icon is fine, it is very small so not too glaring.

Is this ready to go? More changes you wanted to make?

**Comment by MGatner** [comment]
Actually one request: the font color should be specified for dark mode. If it inherits the color it could end up being unreadable. Example: this actual dark-themed CI4 site using your updates.
Screen Shot 2020-01-09 at 2 35 15 PM

**Comment by LittleJ** [comment]
Thank you for your feedback ! Here is the thing...

I wanted to add the "dark/light" feature, without changing colors. Because, when I worked on the css file, there are many things that came through my mind. There is really place for improvement. And there is @natanfelles 's comment too, talking about future design improvements that could be done.

So, I started to write things down (brainstorming). And I would really appreciate if you could take a few minutes to have a look at this: https://littlej.github.io/ci4-debug-bar-design/build/html/

Then, you tell me what you think :-) I am OK adding colors, but maybe it would be better to agree on the "color scheme" first ?

Thank you again for the time you are giving me !

**Comment by LittleJ** [comment]
Please note that there some similar issues right now with the current css.

Simple example:
1/ Load CI default page (fresh install)
2/ Add a style to body with a color, like this: body { color: red; }

And now you get a toolbar with red labels :-D

That is one of the reasons I started doing those suggestions. Because I create apps with CSS. It is all about user experience. And when I am done doing this, I open the console and sometimes find a weird interface :-D And I don't like to have Debugbar styles in the app's css, that what is happening today :-)

**Comment by lonnieezell** [comment]
I like this idea a lot. And agree there are plenty of places for improvement in the Toolbar. 

Are you all happy with the place this is at currently or should we still expect more changes to come soon?

**Comment by LittleJ** [comment]
Note: I am willing to work on CSS improvements. Do not hesitate to tell me if you want me to continue.

**Comment by lonnieezell** [comment]
@LittleJ yes, please continue. :)

**Comment by LittleJ** [comment]
@MGatner @lonnieezell Hey ! Sorry for the late answer, I was on a business trip in Paris. I did continue, and I am still working on the new stylesheet, as I am honored to contribute to CI. You can count on me, but I just need a few more days, because I did not have much spare time this week. Thank you for your comprehension ! ;-)

**Comment by lonnieezell** [comment]
No worries - we have a little bit of time. I'm shooting to get RC-4 out by end of next week, assuming that we get the release figured out in time. 

I'm going to change the title to WIP. When you've got it ready, remove that and let me know and I'll take a gander.

**Comment by LittleJ** [comment]
Hello there !

It took me hours to do the complete refactoring of the CSS. I tried to stay as close as possible to the current design, while making a significant number of improvements.

Here are the main new features:
- Conversion of CSS into SASS version
- Added many detailed comments
- Added variables (example: you can change "$ base-size: 16px;" and this automatically modifies the other elements: titles, paragraphs, tables' content, etc...)
- Color cleaning and standardization (with the definition of the graphic charter)
- Standardization of measurements (there were mixes between "em" and "px")
- Standardization of views between the different tabs (spacing, rendering of tables, colors used ...)
- Cleaned unused and / or duplicated styles
- Cross-browser optimizations
- Preventive measures to prevent conflicts with other stylesheets
- And countless small improvements ... (examples to illustrate: the toggle icon is now the same size as the toolbar because there was a gap because of the borders, the "responsive breakpoint" for the icons was not adapted to the content of the toolbar ...)

I couldn't do a commit for every change, as it is a complete refactoring, in another "language" (SASS).

I really hope you will like it ! :-)

**Comment by MGatner** [comment]
@littlej This is looking great, and clearly you’ve done a lot of work! I will be doing reviews coming up soon, and unless Lonnie gets to it first I will be sure to look this over. Thank you very much for your contributions

**Comment by lonnieezell** [comment]
Just did a quick scan. Will have to pull down the code and give it a live play but definitely appreciate the hard work! 

My only concern is the fact that it's using SASS for 2 reasons: 

1. If a user just clones the repo it won't work for them. Now it requires node installed and a pre-processor for everyone. 
2. We need to update our release/packaging scripts to build it and include it since CI has always had "download and go" packages that don't require a bunch of external tooling. 

Personally I'm a huge fan of SASS, and I think it benefits us here. In order to make it all work though we have to get those items as non-issues. 

#1 can only ever be partially solved, I think? The only way to ensure it is always up to date is to use something like a pre-commit hook that builds it. That requires all users to have their environment setup correctly to run it. We might be able to take advantage of GitHub actions but I'm not sure. 

#2 is probably up to me, which means we cannot integrate this until after the next RC release (which is hopefully the last), since I have to figure out Jim's process for doing releases before I can add anything to them. 

Simplest option would be just to include raw CSS like we used to.

**Comment by LittleJ** [comment]
@lonnieezell I understand, and I will think about it too. I will help as much as possible. If it takes longer, then we could always generate a "classic" / uncompressed version for the next release, you are right.

But above all, I would very much like to know if the result suits you. In my opinion, this is the most important thing to know. For the rest, there will be no problem, but only solutions ;-)

**Comment by lonnieezell** [comment]
@LittleJ What's the simplest command to build this? Care to make it easy for me lol

**Comment by lonnieezell** [comment]
@LittleJ I think it's looking great! Good work. 

The only thing I've seen that needs a bit of help is on the `Vars` page under the `Session` heading when session not started, the text "Session doesn't seem to be active." is small and very hard to read due to color. 

Other than that - keep it up :)

**Comment by LittleJ** [comment]
Hello ! Sorry for the late answer, busy week... Here is the new version :-)

**Your request** @lonnieezell 
I thought the same about the color, but the class is entitled ".muted". So I was wondering how "muted" it should be :-D I changed colors from dark to light gray (for the dark theme) and light to dark gray (for the light theme). But not everywhere, because ".muted" is used in other locations (like in the "Files" tab). It should be OK now ;-)

**Other changes**
First, I just wanted to generate an uncompressed version of the CSS file. But there were comments appearing where it shouldn't be. So I changed the commenting style to get a clean version. Now we have standalone "CSS" and "SASS" versions. Anyone is free to use one or the other.

**Drawback**
The only issue is that if someone (else than me) wants to improve the design (for everyone). Then he has to modify the SASS version in order to generate the CSS version. Meaning, "CORE developers" have to use the SASS version, but not "simple/random CI developers" (they have the choice).

**Note**
@MGatner I know you told me you were busy. But I would have liked to know if it works with the dark theme you were using last time. It should, but I want to be sure as I like when things are done right ;-) If you have time, juste copy-paste the new stylesheet, there is nothing to install or compile in order to use it.

**Comment by LittleJ** [comment]
@lonnieezell With an uncompressed version of the CSS, there is no problem for the developers. It is the same thing as today. But, what to do with these SASS files (used by core developers/contributors) ? There are 4 solutions I see:

1/ Use Github to generate the CSS version (one of your initial ideas). Which i found not totally adapted as the developers have to see the result before pulling it. So it is not really a "complete" solution.

2/ Ask them to generate the CSS from the SASS version. You have rules for PHP contributions, there could be one for CSS contributions too.

3/ Remove the SASS version. Maybe put it in a separated repo. But the issue will only be moved elsewhere.

4/ Forget about the SASS version. We only keep the final CSS. I just lose part of my work. It happens... too bad for me :-)

Note that if we create a new homepage (other thread), we will have the same CSS issues. The homepage should use the same graphic chart that has been defined... The homepage CSS could even be the same as the debug bar CSS. Meaning there is only one big CSS file for the whole framework, which will just be included in the homepage too (it is possible).

If you don't want complications, the simplest solution is just to keep the CSS version only. But it will probably leave less space and ease for future improvements.
If you want a simple solution, while keeping the SASS version, you make it mandatory for core developers/contributors to use it.
Else, there are solutions, but none is "simple"... :-)

**Comment by LittleJ** [comment]
@lonnieezell I was thinking about something like this too, for the settings. What do you think ?

Capture d’écran 2020-02-13 à 19

**Comment by lonnieezell** [comment]
I like that. Go for it.

**Comment by MGatner** [comment]
@LittleJ I forked your branch and tried it on the new CI4 Welcome Page. It looks really good! On question on behavior... it seems to be dark by default and regardless of my OS setting, unless I change it with the `toolbar-theme` button. Is that intended? I had suggested the `prefers-color-scheme: dark` media query above - its fine if you decided that was too much but I want to make sure that if that is the intended behavior it isn't a bug.

Re: SASS I definitely think hanging onto the SASS files in the main repo is a boon! What do you and @lonnieezell think about this: move the instructions for generating the CSS files into their own file in the **contributing** folder and add the SASS files there in a sub-folder as well.

**Comment by lonnieezell** [comment]
@MGatner I like the idea of moving it into a subfolder. We do have to ensure we update those as part of the release cycle, still, though. Handled through the scripts in `/admin`. That can always be a different PR, though, as I'd love to see this included before the hopeful release on the 24th.

**Comment by LittleJ** [comment]
Hey ! Sorry, I was on a business trip...
I think it is going to be complicated to do all the modifications (dropdown menu) before the 24th. And maybe some other members will want to verify the code and pass into some sort of validator... It could take time. Maybe we could stick to this version for now (dark mode + CSS refactoring), and improve it after (dropdown menu + fullscreen mode).
You decide what is best, and I will do my best to help out :-)

PS: I find it complicated to see the changes you made on Github. So I mainly rely on your comments.

**Comment by lonnieezell** [comment]
If we can get just the CSS + dark mode refactor that would be awesome. And if that could be reorganized like @MGatner mentioned that would be awesomer. :)

**Comment by LittleJ** [comment]
I am a little confused... Do I have to make the changes based on the fork ? Or do I have to confirm a pull request somewhere ? What is the next step ? :-)

**Comment by LittleJ** [comment]
By the way, thank you for your answers on the other pull request @lonnieezell. I was clearly not using the right words to express myself. I got confused too, my english is sometimes limited :-)

**Comment by lonnieezell** [comment]
Nope - no one has submitted PRs against your PR. I believe the only changes have been in comments. 

Basically we are just looking for a PR with what you have plus any changes just recently asked for.

**Comment by MGatner** [comment]
@LittleJ We would love to have this in the initial release! Could you (before Monday) (before Sunday night actually) realistically get these tasks done?

1. Change the light/dark mode default to be dependent on `@media prefers-color-scheme: dark`
2. Create a new file, **contributing/css.rst**
3. Move instructions from **system/Debug/Toolbar/Views/SASS/toolbar.scss** to the new doc and add anything else someone might need to know
4. Create a new folder, **admin/css/** and add the SASS files (and anything else needed to generate the CSS)

**Comment by LittleJ** [comment]
Yes I think it is possible. I just had to wait for the week-end to have a little bit more time ;-)

**Comment by LittleJ** [comment]
I will send the changes later today. And I will be available for fixes/revisions if needed.

**Comment by MGatner** [comment]
That’s great news! Thanks so much - I’m excited this will be part of the launch.

**Comment by LittleJ** [comment]
@MGatner I cannot reproduce your bug on my mac. If i clear the cache, I get the right color by default (light), the one that is set in the system's settings. Is it possible that you used the "switch theme" button and the cookie was still alive ? Because the color is stored like the position.

**Comment by LittleJ** [comment]
@lonnieezell While we wait for an answer from @MGatner, I moved the instructions. Could you have a look and check if my translations are good ? Thank you !

**Comment by MGatner** [comment]
Okay that's great! No worries about my experience, I could have switched theme earlier like you said. I'm a CSS lightweight so I trust you to know what you're doing.

The docs and SCSS files look good! I'll let Lonnie have one last look at it but we'll plan to merge it tonight barring any further input. Thank you so much, this is a great asset to the framework

**Comment by LittleJ** [comment]
No, no, it is my pleasure ! :-) I will do more improvements after this release. It is just a question of time/deadline.

**Comment by lonnieezell** [comment]
Looks great! Thanks so much. Merging.

**Pull request merged**
