### PR TITLE
Controller form data validation correction

### PR DESCRIPTION
**Pull request by atishamte**
Controller form validation changes

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by atishamte** [comment]
Is any other changes required in this commit?

**Comment by jim-parry** [comment]
Sorry - just looked at this now.
I see you are adding default values to some parameters. Is this in reponse to an issue?
I also notice that you remove mention of $_POST for validation ... is there a reason for that?

**Comment by atishamte** [comment]
The changes is referring to the conversation I had with @lonnieezell.
The changes are with respect to all request types, but it was there only for Post method

Please refer the link
https://github.com/codeigniter4/CodeIgniter4/pull/1769

Look for controller.php file discussion with him.

**Comment by jim-parry** [comment]
Makes sense ... I thought I remembered some discussion about this :)

**Pull request merged**
