### PR TITLE
Fix that Pager::getCurrentPage() try to return string type

### PR DESCRIPTION
**Pull request by MashinaMashina**
https://github.com/codeigniter4/CodeIgniter4/issues/2467

### CODE REVIEW

**Comment by MGatner** [comment]
I haven't dug into this yet, but isn't using `getCurrentPage()` in the Model circular since we are using it to store the page? Sorry if I have misunderstood.

Also I'd recommend casting instead of using `intval()` if all you're doing is ensuring a string is an int: `(int) $page`

**Comment by lonnieezell** [comment]
Looking at this and I think there's a bigger issue here, actually. With the Model always accessing a shared instance of the pager, if you have multiple models doing pagination on a single page it is going to have issues. 

First step, then, is to get a new instance of the pager: 

```
$pager = \Config\Services::pager(null, null, true);
```

Then an automated way to handle a unique pager name is needed, with the ability for a developer to set the $_GET variable name to differentiate between multiple pagers.

**Comment by lonnieezell** [comment]
@MashinaMashina are you able to make changes to this?

**Comment by MashinaMashina** [comment]
@lonnieezell okay, soon I'll send this.

But instead $pager = \Config\Services::pager(null, null, true); it must be $pager = \Config\Services::pager(null, null, false);

**Comment by lonnieezell** [comment]
@MashinaMashina any opportunity to make these changes in the next week or two?

**Comment by MGatner** [comment]
@MashinaMashina it looks to me like this was covered by #2489 (which is now showing conflicts here). Can this PR be closed?

**Comment by lonnieezell** [comment]
Yes, pretty sure this was fixed by that commit. Closing.

**Pull request closed without merging**
