### PR TITLE
[Rector] Update rector to ^0.10

### PR DESCRIPTION
**Pull request by samsonasik**
**Checklist:**
- [x] Securely signed commits

### CODE REVIEW

**Comment by samsonasik** [comment]
Hi @TomasVotruba , I treid to update `rector/rector` to ^0.10, and in this case, I got the following notice:

```bash
vendor/bin/rector process system/CLI/BaseCommand.php --dry-run

Could not process "system/CLI/BaseCommand.php" file, due to:                                                   
         "Analyze error: "Error (Call to undefined function CodeIgniter\CLI\is_cli()) thrown while looking for class    
         CodeIgniter\CLI\CLI.". Include your files in "$parameters->set(Option::AUTOLOAD_PATHS, [...]);" in "rector.php"
         config.                                                                                                        
         See https://github.com/rectorphp/rector#configuration".  
```

The `s_cli()` function is on `system/Common.php`. Looking at autoload paths, it should already included:

```php
$parameters->set(Option::PATHS, [__DIR__ . '/app', __DIR__ . '/system', __DIR__ . '/tests']);
```

even if I tried manually add `system/Common.php`:

```php
$parameters->set(Option::PATHS, [__DIR__ . '/app', __DIR__ . '/system', __DIR__ . '/system/Common.php', __DIR__ . '/tests']);
```

it still got above notice, any idea to resolve it? Thank you.

**Review by MGatner — COMMENTED** [review]
Looks like some work yet to be done here, but I would be glad to see us on the latest.

**Comment by TomasVotruba** [comment]
I tried to isolate the code but there is too many other packages.

It seems it fails on this minimal code:

```php
use CodeIgniter\CLI\CLI;

class SomeClass
{
	public function showHelp()
	{
		CLI::write('...');
	}
}
```


```
class CLI
{
	public static function init()
    {
       return is_cli();
    }
}

// this is called for some reason
CLI::init();
```

Could you create minimal reproducibel repository?

**Comment by samsonasik** [comment]
I will try

**Comment by samsonasik** [comment]
@TomasVotruba I created a minimal repo that show that the autoload file with code `die;` is skipped there:

https://github.com/samsonasik/rector-issue-010-autoload

Somehow, the `system/Test/bootstrap.php` is not loaded/ignored, as I tried add : 

```php
die('stop here');
```

in top of `system/Test/bootstrap.php`, and it not stopped:

Screen Shot 2021-03-22 at 23 27 19

In rector `0.9`, it will print : "stop here", while in rector `0.10`, it just skipped.

**Comment by samsonasik** [comment]
@TomasVotruba I created rector issue for it https://github.com/rectorphp/rector/issues/5951

**Comment by samsonasik** [comment]
@TomasVotruba I found temporary solution by add : 

```php
require_once __DIR__ . '/system/Test/bootstrap.php';
```

outside rector config https://github.com/codeigniter4/CodeIgniter4/pull/4468/commits/1eb86d89ad75c5596807ce5fa385837bb7d6d051 to ensure require_once loaded.

**Comment by samsonasik** [comment]
All green 🎉

**Review by MGatner — APPROVED** [review]

**Comment by TomasVotruba** [comment]
@samsonasik This should help https://github.com/rectorphp/rector/pull/5964

**Comment by samsonasik** [comment]
@TomasVotruba thank you 👍

**Pull request merged**
