### PR TITLE
fix: respondNoContent() returns Kint script in development mode

### LINKED ISSUE #7346: Bug: API\ResponseTrait::respondNoContent() returns Kint script in development mode
### PHP Version

7.4, 8.0, 8.1, 8.2

### CodeIgniter4 Version

4.1.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

_No response_

### What happened?

Postman return malformed response for respondNoContent(), because Kint active in development mode.

I have delete method in controller that return no content response `$this->respondNoContent()` in development mode, but when we access using postman it returns `Parse Error: The server returned a malformed response`. I try to find out why, in ReponseTrait.php turns out when $data null and $status is numeric then it's match with no content response, it skip the JSON formatter, the response is in text and debugger attach Kint toolbar so the postman says "malformed response". In production mode it works.

```php
protected function respond($data = null, ?int $status = null, string $message = '')
    {
        if ($data === null && $status === null) {
            $status = 404;
            $output = null;
        } elseif ($data === null && is_numeric($status)) {
            $output = null;
        } else {
            $status = empty($status) ? 200 : $status;
            $output = $this->format($data);
        }

        if ($output !== null) {
            if ($this->format === 'json') {
                return $this->response->setJSON($output)->setStatusCode($status, $message);
            }

            if ($this->format === 'xml') {
                return $this->response->setXML($output)->setStatusCode($status, $message);
            }
        }

        return $this->response->setBody($output)->setStatusCode($status, $message);
    }
```

### Steps to Reproduce

Create a controller:

```php
class Activities extends BaseController
{
    use ResponseTrait;

    public function delete($id)
    {
        $this->authorize(PERMISSION_ACTIVITY_DELETE);

        if ($this->activityService->delete($id)) {
            return $this->respondNoContent();
        }

        return $this->respond([
            'code' => 500,
            'status' => 'SERVER_ERROR',
            'errors' => 'Delete activity failed.'
        ], $code);
    }
}
```

use postman or other rest clients to hit the endpoint `DELETE /activities/1`

### Expected Output

Return response 204 No content

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by anggadarkprince**
**Description**
Fixes #7346 about API\ResponseTrait::respondNoContent() returns Kint script in development mode.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
Thank you.

You need GPG sign all your commits.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#signing

Can you write test code to prove the bug fix?
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#unit-testing

**Comment by kenjis** [comment]
We do not use `git merge`. Please use `git rebase` to update your PR branch.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#updating-your-branch

And please sign all your commits.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#gpg-signing-old-commits

**Comment by anggadarkprince** [comment]
is it correct now?

**Comment by kenjis** [comment]
Good! Thank you.

**Comment by anggadarkprince** [comment]
I add content type checking on unit test, to make sure it returns non-HTML format, 

```php
public function testNoContent()
{
    $controller = $this->makeController();

    $this->invoke($controller, 'respondNoContent', ['']);

    $this->assertStringStartsWith('application/json', $this->response->getHeaderLine('Content-Type'));
    $this->assertSame('No Content', $this->response->getReason());
    $this->assertSame(204, $this->response->getStatusCode());
}
```

because in Toolbar.php it checks the type

```php
// Non-HTML formats should not include the debugbar
// then we send headers saying where to find the debug data
 // for this response
 if ($request->isAJAX() || strpos($format, 'html') === false) {
    $response->setHeader('Debugbar-Time', "{$time}")
         ->setHeader('Debugbar-Link', site_url("?debugbar_time={$time}"));

    return;
}
```

**Review by kenjis — APPROVED** [review]

**Review by MGatner — APPROVED** [review]

**Comment by MGatner** [comment]
Thank you!

**Pull request merged**
