### PR TITLE
SubQuery related test cases w.r.t #1775

### PR DESCRIPTION
**Pull request by atishamte**
SubQuery related test cases w.r.t #1775

**Checklist:**
- [x] Securely signed commits
- [x] Unit testing, with >80% coverage
- [x] Conforms to style guide

### CODE REVIEW

**Comment by lonnieezell** [comment]
Please provide a better explanation on what this is fixing and its intended usage. Also a test to ensure it's working correctly and docs if needed.

**Comment by atishamte** [comment]
Yes. It's under WIP. I am building the test cases and documentation

**Comment by lonnieezell** [comment]
Sorry. Missed that!

**Comment by atishamte** [comment]
Travis ci build is completed, then too showing in progress.

**Comment by lonnieezell** [comment]
So - no code changes needed to support this? 

Don't know why GitHub is showing the tests as pending... but if you're done I can merge.

**Comment by atishamte** [comment]
Yes. i am done with this PR. You can proceed with the merge

**Pull request merged**
