### PR TITLE
WIP [DEBUG+WP] From CSS to SASS + Graphic improvements

### PR DESCRIPTION
**Pull request by LittleJ**
**List of changes:**
- Converted the "Welcome" page CSS to SASS
- Made the "Welcome" page conform to the graphic charter
- Small improvements on the "Welcome" page (soften colors, changed HTML structure a bit...)
- Updated the documentation for contributors
- Added a lot of comments to make the work easier for contributors

**Benefits of SASS in this case:**
- Half of the SASS files are shared with the debug toolbar
- Clean and commented files for contributors
- Force contributors to conform to the graphic charter

**Suggestion**
Why not extend this SASS version to use it for the future CI's website ? The "Welcome" page has a mobile menu and everything. This could be one "CodeIgniter.css" for everything.

**Checklist:**
- [x] Securely signed commits
- [x] Contribution guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by LittleJ** [comment]
@lonnieezell & @MGatner : This work is ready for review. With PR #2628 and PR #2646, we now get a design in accordance with the graphic charter for the debug toolbar, the "Welcome" page, and the user guide.

**Comment by MGatner** [comment]
Thanks, this is great! I’ll have to fork it to an install to check it out but it looks like really quality work. @lonnieezell what is the best way to get LittleJ connected with the web team? Trello?

**Comment by LittleJ** [comment]
After the previous conversations I had with Lonnie, I changed the logo because it was not the right one. The police did not match.

**Comment by LittleJ** [comment]
**Here is a preview of the latest changes**

Capture d’écran 2020-03-02 à 13

Capture d’écran 2020-03-02 à 13 17 11

Capture d’écran 2020-03-02 à 13 17 17

Capture d’écran 2020-03-02 à 13 17 41

Capture d’écran 2020-03-02 à 13 17 54

**Comment by LittleJ** [comment]
@lonnieezell So, we've got a navbar, a heroe section, text sections, a footer, buttons, icons, code preview... All is responsive. What is missing to make a website ?

Maybe we don't need fancy stuff like Bootstrap or jQuery to build a website which will have like what... 10 pages max ? We could have a single "codeigniter.css".

Interesting facts... If i go further... I can actually merge the "Welcome" page SASS with the debug bar SASS (without any changes). And create the SASS version for the documentation (with only very small changes). And you could use one single "codeigniter.css" to manage the look of the "Welcome" page, the debug bar, the documentation, and... the website. I thought about it, we could even automate things (just copying the CSS version where it's needed).

**Comment by MGatner** [comment]
@littlej this is amazing! Thanks for all this work! I am definitely in favor of getting you to work with the web team on some consistency in implementation. Branding, styling, and the website are more the domain of the council so I will wait for Lonnie on this one but it has my full support.

**Comment by John-Betong** [comment]
I do like the new welcome page because it looks very clean and modern. 

I took the liberty to remove a couple of HTML warnings using the W3.org Validtaikon tool: Please note H2 and H3 tags will now require sizing, etc

# New Page:
https://validator.w3.org/nu/?doc=https%3A%2F%2Fci4-strict.tk%2Fwelcome-new
https://ci4-strict.tk/welcome-new

# Old Page:
https://validator.w3.org/nu/?doc=https%3A%2F%2Fci4-strict.tk%2Fwelcome-message
https://ci4-strict.tk/welcome-message

**Comment by LittleJ** [comment]
@John-Betong Thank you for your positive feedback ! I see the warnings regarding the titles. I will make changes accordingly (later today or tomorrow). And I will probably make <h2> titles slightly bigger 😄  Nice catch 😉

**Comment by LittleJ** [comment]
Hey all ! I fixed the titles, it should be OK 😉

**Comment by lonnieezell** [comment]
@LittleJ just pulled and built the latest and I'm seeing a couple of small issues: 

1. inner lists on the index page have a spacing issue
Screen Shot 2020-03-03 at 10 22 11 AM

2. Font of "CodeIgniter" looks to be in Lato as the primary font. Can we make that Raleway to match?

**Comment by LittleJ** [comment]
@lonnieezell You commented on the wrong PR. Because my branches are incorrectly named 😄

I just checked and don't get the same result. You  can see it in my screenshots. Can you give me further information on the device and browser you are using ? There's something I'm missing.

**Comment by lonnieezell** [comment]
Ah, did not use make clean, just a straight make html. Will check that out later. And make sure I'm looking at the right thing lol

**Comment by lonnieezell** [comment]
@LittleJ is this still relevant with the other work you're doing?

**Comment by LittleJ** [comment]
I guess not. I'm going to close it for now.
Sorry for the late answer, as you know, the world is going crazy 😄

**Pull request closed without merging**
