### PR TITLE
fix: Publisher $restrictions regex to FCPATH

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
- fix regex

Related: #5792

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by haugli92** [comment]
Add `|woff2?|`. Im not the best on regex, can someone validate it?

**Comment by kenjis** [comment]
@haugli92 Thanks!
Added.

**Comment by kenjis** [comment]
@haugli92 Thanks!
Added.

**Review by samsonasik — APPROVED** [review]

**Comment by MGatner** [comment]
I missed this one but I think it is now unduly restricting `.htm` files (that was the original intent of `htm?`. Do we need `htm??` for some reason?

**Comment by MGatner** [comment]
Also `woff2` should've been covered by `woff?`, right?

**Comment by MGatner** [comment]
Ah, nope - I'm a dummy, never mind me. 🤦‍♂️

**Pull request merged**
