### PR TITLE
add ext-mbstring to required and update regex that sanitize file name

### PR DESCRIPTION
**Pull request by samsonasik**
Like in my comment at https://github.com/codeigniter4/CodeIgniter4/issues/2784#issuecomment-609515200 , that in other forum in facebook, I got people ask about `php spark serve` error as well, and solved by install mbstring extension. I also updated regex that sanitize file name.

**Checklist:**
- [x] Securely signed commits
- [x] Unit testing, with >80% coverage
- [x] User guide updated

### CODE REVIEW

**Comment by samsonasik** [comment]
preg_replace with `\p{L}` seems not rollback char like `Ä` properly.

**Comment by samsonasik** [comment]
fixed the regex with add both `/u` with `\p{L}` additon.

**Comment by samsonasik** [comment]
travis build green with added test to cover unicode in filename :tada:

**Comment by samsonasik** [comment]
clean up `a-zA-Z` as already covered by `\p{L}` in regex sanitize file name

**Comment by samsonasik** [comment]
travis build green :tada:

**Comment by lonnieezell** [comment]
Looks great to me. I'm not concerned with the composer.json addition since it was already a requirement, we just hadn't specified it anywhere for the use to know about I guess. Thanks!

**Comment by truelineinfotech** [comment]
Capture

mb-string

need to add  `"ext-mbstring": "*"` on packagist site.

**Comment by samsonasik** [comment]
it already added. just need a new release.

**Pull request merged**
