### PR TITLE
chore: preparation for PHPStan 2: remove CheckUseStatementsAfterLicenseRule

### PR DESCRIPTION
**Pull request by samsonasik**
**Description**

The `CheckUseStatementsAfterLicenseRule` rule is rely on`previous` attribute, which no longer exists in PHPStan 2, I think this can be removed.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by samsonasik** [comment]
Ready to merge 👍

**Comment by paulbalandan** [comment]
I was thinking days ago if this rule can be adapted to phpstan v2? or this rule has gone completely unnecessary?

**Comment by samsonasik** [comment]
This rule was exists in the day the docblock location was mixed, since likely when creating new file, we copy paste existing code and modify, so location unmatch with `@license` placed after use can be seen and verify manually, that's will be rare use case imo.

To make adaptable to v2, it can be modified to use `FileNode` or `Namespace_`, loop its stmt until found a `Use_` with next  stmt with `@license` doc, but I am not sure if it worth the effort

**Review by paulbalandan — APPROVED** [review]
TBH, with our current tooling I think this rule is no longer necessary, so I'm ok with this being deleted.

**Review by michalsn — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @paulbalandan @michalsn for the review, let's merge 👍

**Pull request merged**
