### PR TITLE
Updated redis session handler to support redis 5.0.x

### LINKED ISSUE #2121: Redis
**Direction**
If you use Redis > 4 Function Redis::delete() is deprecated

**Describe the bug**
Use redis 5,0,0

**CodeIgniter 4 version**
beta4

**Affected module(s)**
cache module

**Expected behavior, and steps to reproduce if appropriate**
need to use unlink function instated delete of phpredis library in class RedisHandler in delete function

**Context**
 - OS: Debian
 - Web server Nginx
 - PHP version 7,3,8

### PR DESCRIPTION
**Pull request by tangix**
Fixes #2121 

**Description**
Updated RedisHandler to support redis 5.0.x and php 7.3.x by removing deprecated calls and updating ping() handling. This while maintaining backward compatibility with redis 4.1.x and php 7.2.x

**Checklist:**
- [X] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [X] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
Redis tests all seem to be failing since this was merge.

**Comment by tangix** [comment]
The failed builds are happening down in the cache handler but for the same reason - the deprecated delete() call;
https://travis-ci.org/codeigniter4/CodeIgniter4/jobs/571193301
My commit addressed the issues in Sessionhandler: system/Session/Handlers/RedisHandler.php

**Comment by tangix** [comment]
I see in the travis log that the build infrastructure was changed between this PR and now - job 4904 was running PHP 7.2.16/7.3.2 and 4927 PHP 7.2.21/7.3.8 could something else has changed in the testing process as well, like error level?

**Comment by MGatner** [comment]
You're totally right! Sorry for the false accusation. I think we'll need backup from @lonnieezell on this one.

**Pull request merged**
