### PR TITLE
feat: QueryBuilder raw SQL string support

### PR DESCRIPTION
**Pull request by kenjis**
Related: #4355, #3970, #5810

**Description**
See https://forum.codeigniter.com/showthread.php?tid=80720

- add `RawSql` class
- `select()` supports `RawSql`
- `where()` supports `RawSql`
- `like()` supports `RawSql`

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by iRedds** [comment]
Is it possible to add a second argument to the constructor to pass the binding?
As for BaseConnection::query();
```php 
new RawSql('a = ? AND b = ?', [1, 2]);
new RawSql('a = :a AND b = :b', ['a'=>1, 'b' => 2]);
```

**Comment by kenjis** [comment]
@iRedds I'm not sure.

Can you tell me what's good if it is possible?
Use case?

**Comment by iRedds** [comment]
Usage example above.
It seems to me that it will be convenient with a large SQL statement and a large number of variables.

For example, for such a query (from https://github.com/codeigniter4/CodeIgniter4/issues/5810 )
```php
$builder->orLike("(SELECT COALESCE(GROUP_CONCAT(CONCAT(corr.description, ' ', corr.note) ORDER BY corr.order_field ASC SEPARATOR ' '), '') FROM correspondence corr WHERE corr.contact_fk = c. contact_id AND 1 = 1)", "", "both", false);
```
Although this query does not use value substitution, this is a possible situation.

**Comment by kenjis** [comment]
@iRedds What's about escaping?
If we need to escape the values, RawSql must have DB Connection.

**Comment by iRedds** [comment]
It seems to me that there are two options without using DBC
1. The developer himself will escape the values.
2. The binds will be transferred to the $binds property when processing the RawSql instance.

**Comment by kenjis** [comment]
I do not see much need for binding, so I will not include it in this PR.

**Review by lonnieezell — CHANGES_REQUESTED** [review]
I think this solution is fine, and I don't see an issue with leaving binds out. Being raw SQL I don't think that's unexpected.   Thanks @kenjis 

But it does need docs added.

**Comment by kenjis** [comment]
I added docs.

**Review by michalsn — APPROVED** [review]
I thought that the `$escape` parameter would do the trick for this type of scenario but I guess I was wrong. I think it is a good addition.

**Comment by kenjis** [comment]
@michalsn Thank you!

**Pull request merged**
