### PR TITLE
Update TravisCI config for PHP7.4

### LINKED ISSUE #2293: Lack of test on Travis for PHP 7.4 and tests don't run on upcoming PHP versions
**Describe the bug**
For now Travis configuration have not set test for PHP 7.4. Other problem is that tests on upcoming PHP version won't run.

**CodeIgniter 4 version**
RC2.1

**Affected module(s)**
none

### PR DESCRIPTION
**Pull request by lonnieezell**
- Include 7.4 in builds.
- Cache vendor directory for hopefully faster builds. 

Fixes #2293

### CODE REVIEW

**Comment by MGatner** [comment]
Looks like GD isn’t available? Is that a new default in 7.4? or maybe a Travis issue?

**Comment by MGatner** [comment]
Looks like TravisCI had some updates for PHP extension issues. It's unclear if this PR precedes those? https://travis-ci.community/t/some-extensions-are-missing-in-php-7-4-0-zip-gmp-sodium/6320/8

Maybe try bumping this PR to see if the build succeeds this time?

**Comment by musmanikram** [comment]
@lonnieezell @MGatner I replicated your code with some fixes for PHP 7.4
Can you please have a look on my PR: 

https://github.com/codeigniter4/CodeIgniter4/pull/2537

**Comment by MGatner** [comment]
It looks good to me! Simple, working. All 7.4 tests passed too. I’ll let Lonnie make the final call since he worked on this one but I approve.

**Comment by musmanikram** [comment]
@lonnieezell i think now you can close this PR.

**Comment by lonnieezell** [comment]
Ah, yeah. Thanks!

**Pull request closed without merging**
