### PR TITLE
docs: fixed installation images and typo

### PR DESCRIPTION
**Pull request by sammyskills**
**Description**
- Updated the welcome image in https://codeigniter4.github.io/CodeIgniter4/installation/troubleshooting.html#how-do-i-know-if-my-install-is-working to use CodeIgniter 4.4.1
- Updated the debugbar image in https://codeigniter4.github.io/CodeIgniter4/tutorial/index.html#debug-toolbar to use CodeIgniter 4.4.1
- Fixed typo in https://codeigniter4.github.io/CodeIgniter4/installation/installing_composer.html#adding-codeigniter4-upgrading

See https://forum.codeigniter.com/showthread.php?tid=88400&pid=412786#pid412786

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
Thank you. 
But the DebugBar's numbers are very big.
Is really your CI4 slow and used the memory that much?

I checked with PHP 8.1 and `spark serve`, but I got around 20ms.
```
PHP 8.1.23 (cli) (built: Aug 31 2023 19:06:23) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.23, Copyright (c) Zend Technologies
    with Xdebug v3.2.1, Copyright (c) 2002-2023, by Derick Rethans
    with Zend OPcache v8.1.23, Copyright (c), by Zend Technologies
```
Screenshot 2023-09-22 6 46 31

**Comment by sammyskills** [comment]
Interestingly, I didn't pay much attention to that until now. 

My CI4 has just shield installed and I'm beginning to wonder why it is that much. I use PHP 8.2.

I'll check and revert accordingly.

**Comment by kenjis** [comment]
I checked clean CI4 (`develop`) with no change.

**Comment by sammyskills** [comment]
After uninstalling shield, the best I could get is around 75ms. I don't know if it has to do with my system configuration (windows) or not.
image

**Comment by sammyskills** [comment]
Maybe I'll replace the debugbar image with the one from your system?

**Comment by ddevsr** [comment]
You need screenshot fresh install, it just describes the application for the first time

**Comment by kenjis** [comment]
The screenshot should be taken with the fresh installation of CI4.
I'm fine with your screenshot if it is a fresh installation.

It seems Windows PHP needs more memory than macOS.
The time depends on systems. If you use more faster machine, it will be shorter.
Do you use HDD or SSD?

**Comment by sammyskills** [comment]
> You need screenshot fresh install, it just describes the application for the first time

The screenshot I used is for a fresh install

> Do you use HDD or SSD?

1TB SSD, 16GB RAM, Core i5

> It seems Windows PHP needs more memory than macOS.

I have `memory_limit = 512M` in my php.ini. Do I need to increase it?

**Comment by datamweb** [comment]
@sammyskills The output for me is as follows.

Just CI4.4.1:

Screenshot 2023-09-22 093852

CI4.4.1 + Shield(dev branch)

Screenshot 2023-09-22 094651


**Info :**

```console
P:\ci4\ci441>php -v
PHP 8.1.5 (cli) (built: Apr 12 2022 17:38:57) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.5, Copyright (c) Zend Technologies
    with Xdebug v3.1.4, Copyright (c) 2002-2022, by Derick Rethans
```

**Comment by sammyskills** [comment]
@datamweb, here's my php version output:

```
php -v
PHP 8.2.6 (cli) (built: May  9 2023 16:02:16) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.6, Copyright (c) Zend Technologies
    with Xdebug v3.2.2, Copyright (c) 2002-2023, by Derick Rethans
```

**Comment by kenjis** [comment]
> I have memory_limit = 512M in my php.ini. Do I need to increase it?

No. If your app runs well, the smaller memory limit is better.

**Comment by kenjis** [comment]
> 1TB SSD, 16GB RAM, Core i5

My MBA has 512GB SSD, 16GB RAM, Core i5.

**Comment by sammyskills** [comment]
I have updated the debugbar image with another fresh install, but the load time is still >70ms.

**Review by kenjis — APPROVED** [review]

**Comment by datamweb** [comment]
> but the load time is still >70ms.

@sammyskills I upgraded php to 8.2.6, the result is interesting!!

**Just CI4.4.1:**

ci441

**CI4.4.1+Shield:**

ci441shield

```console
P:\ci4\CI441>php -v
PHP 8.2.6 (cli) (built: May  9 2023 16:02:16) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.6, Copyright (c), by Zend Technologies

```

**Comment by kenjis** [comment]
@datamweb It is because you don't install/enable Xdebug.

**Comment by sammyskills** [comment]
@datamweb, interesting indeed!

Seeing that you also use a windows system, do you mind sharing your specific setup?

My PC is 1TB SSD, 16GB RAM, Core i5 and I use laragon to handle my development environment (php, mysql, etc).

**Comment by sammyskills** [comment]
> @datamweb It is because you don't install/enable Xdebug.

@kenjis you are right. I disabled Xdebug and the load time reduced to 66ms.

**Comment by datamweb** [comment]
> It is because you don't install/enable Xdebug.

Yes, it has an effect.
**Just CI441:**

ci441+xd

**CI441+shield :**

ci4+shield+xd

```console
P:\ci4\CI441>php -v
PHP 8.2.6 (cli) (built: May  9 2023 16:02:16) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.6, Copyright (c), by Zend Technologies
    with Xdebug v3.2.2, Copyright (c) 2002-2023, by Derick Rethans
```
```
Device name	Pooya
Processor	AMD Ryzen 9 3900X 12-Core Processor               3.80 GHz
Installed RAM	16.0 GB

Edition	Windows 11 Home
Version	21H2
Installed on	‎10/‎8/‎2021
OS build	22000.1219
Experience	Windows Feature Experience Pack 1000.22000.1219.0

Samsung SSD 980 PRO 250GB 

```

**Comment by sammyskills** [comment]
> I installed PHP directly. But my MySQL is installed by Xampp.

Installing PHP directly might be the game-changer.

**Review by neznaika0 — APPROVED** [review]

**Comment by kenjis** [comment]
@sammyskills Thank you!

**Pull request merged**
