### PR TITLE
refactor: replace time() with Time in `Session.php`

### PR DESCRIPTION
**Pull request by ping-yee**
**Description**
See #6815 

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by ping-yee** [comment]
> Error: CodeIgniter\Session\Session must not depend on CodeIgniter\I18n\Time (Session on I18n)

@kenjis I have no idea how to fix this, can you give some suggestions for me?

**Comment by kenjis** [comment]
```diff
--- a/deptrac.yaml
+++ b/deptrac.yaml
@@ -201,6 +201,7 @@ parameters:
       - Cookie
       - HTTP
       - Database
+      - I18n
     Throttle:
       - Cache
     Validation:
```
See https://qossmic.github.io/deptrac/

**Review by MGatner — COMMENTED** [review]
Looking good! I like that with these changes Deptrac will be able to report on our explicitly system clock usage.

**Comment by ping-yee** [comment]
Appricated that!
I've been added that.

**Review by datamweb — APPROVED** [review]

**Review by samsonasik — APPROVED** [review]

**Review by MGatner — APPROVED** [review]
Thanks!

**Pull request merged**
