### PR TITLE
Add counted() to Inflector Helper

### PR DESCRIPTION
**Pull request by MGatner**
**Description**
This adds another inflector function to make easy counted words (e.g. from database results):
```
$users = $userModel->findAll();
echo counted(count($users), 'users'); // "5 users" or "1 user"
```

**Checklist:**
- [X] Securely signed commits
- [X] Component(s) with PHPdocs
- [X] Unit testing, with >80% coverage
- [X] User guide updated
- [X] Conforms to style guide

### CODE REVIEW

**Comment by lonnieezell** [comment]
This is probably fine, but part of me says - what about non-Arabic numbers for other locales?

**Comment by MGatner** [comment]
No clue. :) How are they handled by `count()`?

**Comment by MGatner** [comment]
This is messy. I think since `counted()`'s dependent functions (`singular`, `plural`, `is_pluralizable`) are hard-coded to English its the best we can do for now. But maybe an international pass at the Inflector helper at some point...

**Comment by lonnieezell** [comment]
Agreed on that. I mean, technically for the numbers we could use the `intl` library, but doesn't help with pluralization, I don't think, so yeah. Stick with English for now on this.

**Pull request merged**
