### PR TITLE
test: use array_sort_by_multiple_keys() in AbstractGetFieldDataTest

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
- refactor test

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by datamweb — APPROVED** [review]

**Comment by kenjis** [comment]
@datamweb Thank you for reviews!

**Comment by kenjis** [comment]
```
Run vendor/bin/rector process system --dry-run --no-progress-bar

Error: ] Could not process                                                      
         "/home/runner/work/CodeIgniter4/CodeIgniter4/vendor/rector/rector/vendo
         r/symplify/easy-parallel/src/ValueObject/ParallelProcess.php" file, due
         to:                                                                    
         "Child process timed out after 120 seconds". On line: 108              

Error: ] Could not process some files, due to:                                  
         "Reached system errors count limit of 50, exiting...".                 

Error: Process completed with exit code 1.
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/7770165323/job/21189995850

**Comment by samsonasik** [comment]
Reduce the job size may be needed.

```diff
-    $rectorConfig->parallel(120, 8, 15);
+    $rectorConfig->parallel(120, 8, 10);
```

**Comment by samsonasik** [comment]
https://github.com/codeigniter4/CodeIgniter4/pull/8510

**Pull request merged**
