### PR TITLE
optimize FileLocator autoloader : use foreach instead of for with count when possible

### PR DESCRIPTION
**Pull request by samsonasik**
**Checklist:**
- [x] Securely signed commits

### CODE REVIEW

**Comment by michalsn** [comment]
Sorry for the silly question but is `foreach` faster than `for`? Or this is just for readability purposes?

**Comment by samsonasik** [comment]
previously, with `for`, it need to run `count()` first, while direct foreach is enough.

**Comment by michalsn** [comment]
Yes, I understand this part, but isn't `foreach` slower than `for`?

**Comment by samsonasik** [comment]
It faster. Example benchmark about `for` with `count` vs direct `foreach` : https://coderwall.com/p/il1tog/php-for-vs-foreach-benchmark

**Comment by samsonasik** [comment]
```
➜  ~ curl https://gist.githubusercontent.com/nodesocket/3909074/raw/80e1bd3612b2b1680d6d519c8fd53bb79435e9de/gistfile1.php -o benchmark-for-vs-foreach.php

➜  ~ php benchmark-for-vs-foreach.php 
For took: 2.862ms
For with count() took: 3.643ms
Foreach took: 1.489ms
```

**Comment by michalsn** [comment]
I get quite different results to be honest
```
For took: 0.128ms
For with count() took: 0.175ms
Foreach took: 0.162ms
```
Also checked it on sandbox: https://phpsandbox.io/n/red-king-pnbr

**Comment by samsonasik** [comment]
The code that I updated previosly uses count+for, so foreach still win

**Comment by michalsn** [comment]
Not really. "For with count()" is when we use `count()` inside `for()` loop, like:
```php
for($i = 0; $i < count($elements); $i++)
```
and it's not the case here.

**Comment by samsonasik** [comment]
The benchmark code need update to associative array and run the code inside loop, I updated the benchmark code at https://phpsandbox.io/n/super-fog-72g7 with place assign `count()` to variable first, but execute it. I got it:

```bash
For took: 0.066ms
For with count() took: 0.167ms
Foreach took: 0.099ms
```

foreach wins on this case.

**Comment by michalsn** [comment]
Okay, now it looks good. Thanks.

**Pull request merged**
