### PR TITLE
feat: WIP -  Support overriding common functions from modules

### PR DESCRIPTION
**Pull request by najdanovicivan**
**Description**
Currently we can only override Common.php from APPPATH this adds support to make such overrides from any module

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by najdanovicivan** [comment]
What do you think about this one. 

I just don't have idea how to make tests for this one

**Comment by kenjis** [comment]
What about Composer packages?

I'm not sure CI4 should have this feature.
But If #8558 is merged, you can extend the Boot class to add the loading of Common.php in modules.

**Comment by lonnieezell** [comment]
I was thinking it already loaded Common files in Modules but I'm probably mistaken. Even though I see use these files myself, I don't think they should override the main one, personally. I like the idea that whatever is put in app is what can override anything else to ensure the app has the final say and doesn't have someone override core functionality.

**Comment by najdanovicivan** [comment]
This looks into autoload config psr4 namespaces.  So if composer package is added there it will also load Common.php from that. 

The main goal I need Common.php in Module is to be able to override system behaviour

Maybe adding separate property in Autoload config eg. commonPaths will be better approach that way we'll have full control which files get loaded and in which order

**Comment by michalsn** [comment]
IMO we should not be able to override Common.php from within modules. This can cause problems with loading order or declaring different versions of the same function in each module.

For me, the correct way to handle this should include the Publisher class, which would copy the changed function to the Common.php file inside the APP folder. This would also give the ability to handle conflicts, etc.

**Comment by najdanovicivan** [comment]
There should be no conflict when functions are written with 
```
if (! function_exists('str_ends_with')) {
```

The approach of having separate parameter in autoload will just introduce possibility but it will still require the end user to load the override in the config.

**Comment by michalsn** [comment]
What if two different modules decide to override the same function?

In a scenario where we are building a module system similar to, say, Prestashop, this will be a huge problem. Only one function will be loaded, and we have no way to decide which one will be loaded first (except for naming conventions, I guess).

The last part - we have no way to recognize that we have any conflict between modules and resolve it.

**Comment by kenjis** [comment]
> I like the idea that whatever is put in app is what can override anything else to ensure the app has the final say and doesn't have someone override core functionality.

I agree. 

>What if two different modules decide to override the same function?

> The last part - we have no way to recognize that we have any conflict between modules and resolve it.

Yes, Services also have this issue.

**Pull request closed without merging**
