### PR TITLE
docs: fix wrong QueryBuilder sample code

### LINKED ISSUE #4464: Bug: UG QueryBuilder::from() wrong SQL example.
**Describe the bug**

Because the $builder variable contains an instance of the BaseBuilder class, which can only be accessed via db->table(). 
Then the SQL in the example will be like this: 

```sql
SELECT title, content, date FROM mytable, mytable
```

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #4464

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
Is this still a relevant fox despite the `builder(array)` conversation?

**Comment by kenjis** [comment]
What's *fox*?

This is just fix to the current docs.

**Comment by MGatner** [comment]
> fox

🤦‍♂️ A typo for "fix". There are a lot of discussions around Builder and the `table` property and methods... I was making sure you think this is still the correct documentation.

**Comment by kenjis** [comment]
Thanks. I think this is the correct documentation, with or without the discussion.

**Review by MGatner — APPROVED** [review]

**Pull request merged**
