### PR TITLE
Some Base Functional Changes

### PR DESCRIPTION
**Pull request by atishamte**
Some Base functional changes w.r.t.
- Doxygen comments
- Datatypes and return types
- Added exceptions in function comments

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by jim-parry** [comment]
Do you use doxygen? Have you run it against CI4? If so, do you have a config or other details you could share? Thanks.

**Comment by atishamte** [comment]
I am using phpStorm, which has a built in support to create function documentations. I am not using doxygen external tool to create entire project documentation.
So here I am referring doxygen to function documentation

**Comment by atishamte** [comment]
But surely I will give it a try for doxygen generator. If sucess, will share the configuration file.

**Comment by jim-parry** [comment]
I took a look at doxyfen examples, and am not overly fond of them.
phpdocumentor has version 2 now, which I plan to try. I didn't have much success with version 1.

**Comment by atishamte** [comment]
Not an issue. Will this affect this PR?

**Pull request merged**
