### PR TITLE
Fix fill() method in Entity class

### PR DESCRIPTION
**Pull request by michalsn**
**Description**
When we declare class properties for Entity class then `__set()` method won't be called.

> __set() is run when writing data to inaccessible (protected or private) or non-existing properties

See: #3368

**Checklist:**
- [x] Securely signed commits
- [x] Conforms to style guide

### CODE REVIEW

**Comment by natanfelles** [comment]
I confirm that this resolved issue #3368 . Thank you!

**Comment by MGatner** [comment]
This is a breaking change and IMO it is more of a philosophical change than a bug fix. There are legit reasons a developer may want to declare properties and have them filled but not included in `toArray`, etc. @natanfelles' issue seems to have been in misunderstanding how Entity properties are declared - you should add them as fields in `$attributes` rather than class properties.

**Comment by michalsn** [comment]
@MGatner I can't agree with you as we should take a look at how this method looked like before: https://github.com/codeigniter4/CodeIgniter4/pull/2968/files

From my perspective we simply forgot that parameters may be declared in the class and then `__set()` won't be triggered.

**Comment by MGatner** [comment]
I think you're right and that was an unintentional BC, but I don't know if it merits another BC to "fix" it. 

My personal opinion is I think this is a good change. As is, if someone had a field named "dates" and tried to fill it into an Entity it would really screw the class: `$entity = new Entity(['dates' => 2674862738])`. This would overwrite the date property, so maybe that constitutes a bug and is worth another BC? Let's keep this discussion going.

**Comment by MGatner** [comment]
Yeah the more I think about this the more I think you're right. We will need to note this as a minor breaking change - unlikely that many people will be affected but it could still mess something up. Can we start a `4.0.5` changelog with this PR and include a note on this interaction? Also I'd like to be sure @lonnieezell sees this.

**Comment by lonnieezell** [comment]
I agree this should be fixed. The original intent was that you do exactly what @natanfelles did in his example. so, yes, make a note of it in the the Upgrade Guide that we should start maintaining and I think it's good. :)

**Comment by lonnieezell** [comment]
After reading back through the original post, I need to clarify. You should be able to do this: 

```
$user = new User([
  'email' => 'joe@example.com',
  'name' => 'Joe Smith'
]);
$users = new UserModel();
$users->save($user);
```

Double-checking against the Model and the change is good.

**Comment by michalsn** [comment]
I've added info to the changelog.

**Pull request merged**
