### PR TITLE
docs: improve Tutorial v4.3

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
- Use `validateData()` instead of `validate()` because it is more secure.
   - If we use `validate()`, we cannot know which data is validated.  
- Use new `validation_list_errors()`.
- Use `set_value()` to show old input data.
- Update description for v4.3.
- Update screenshots.

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by MGatner — COMMENTED** [review]
You used `php:func:` for a number of internal functions. I thought that would create a link out to the PHP docs? Or am I thinking of another syntax?

**Comment by kenjis** [comment]
> I thought that would create a link out to the PHP docs?

No. It creates a link to the `.. php:function:: xxx()` page in the user guide.

**Review by MGatner — APPROVED** [review]
Looks good! I haven't walked through the tutorial, might be good to do before 4.3 goes live at some point.

**Comment by kenjis** [comment]
I pushed my working repository:
https://github.com/kenjis/ci4-news

**Review by paulbalandan — APPROVED** [review]

**Review by datamweb — APPROVED** [review]
Thanks!
Verry good.

**Comment by MGatner** [comment]
@kenjis Please proceed; I won't get to walk through this soon.

**Pull request merged**
