### PR TITLE
Module wise Typos changes

### PR DESCRIPTION
**Pull request by atishamte**
Typos changes module wise

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by atishamte** [comment]
@jim-parry & @lonnieezell, I didn't make any changes in the PHPUnit configs. Then too getting this error.

```
PHP Fatal error:  Uncaught SebastianBergmann\Timer\RuntimeException: Cannot determine time at which the request started in /home/travis/build/codeigniter4/CodeIgniter4/vendor/phpunit/php-timer/src/Timer.php:85
Stack trace:
#0 /home/travis/build/codeigniter4/CodeIgniter4/vendor/phpunit/php-timer/src/Timer.php(98): SebastianBergmann\Timer\Timer::timeSinceStartOfRequest()
#1 /home/travis/build/codeigniter4/CodeIgniter4/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php(410): SebastianBergmann\Timer\Timer::resourceUsage()
#2 /home/travis/build/codeigniter4/CodeIgniter4/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php(183): PHPUnit\TextUI\ResultPrinter->printHeader()
#3 /home/travis/build/codeigniter4/CodeIgniter4/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(652): PHPUnit\TextUI\ResultPrinter->printResult(Object(PHPUnit\Framework\TestResult))
#4 /home/travis/build/codeigniter4/CodeIgniter4/vendor/phpunit/phpunit/src/TextUI/Command.php(206): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
# in /home/travis/build/codeigniter4/CodeIgniter4/vendor/phpunit/php-timer/src/Timer.php on line 85
Fatal error: Uncaught SebastianBergmann\Timer\RuntimeException: Cannot determine time at which the request started in /home/travis/build/codeigniter4/CodeIgniter4/vendor/phpunit/php-timer/src/Timer.php on line 85
SebastianBergmann\Timer\RuntimeException: Cannot determine time at which the request started in /home/travis/build/codeigniter4/CodeIgniter4/vendor/phpunit/php-timer/src/Timer.php on line 85
Call Stack:
    0.0001     424032   1. {main}() /home/travis/build/codeigniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:0
    0.0043     937984   2. PHPUnit\TextUI\Command::main() /home/travis/build/codeigniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:61
    0.0043     938096   3. PHPUnit\TextUI\Command->run() /home/travis/build/codeigniter4/CodeIgniter4/vendor/phpunit/phpunit/src/TextUI/Command.php:162
    0.5041   20627472   4. PHPUnit\TextUI\TestRunner->doRun() /home/travis/build/codeigniter4/CodeIgniter4/vendor/phpunit/phpunit/src/TextUI/Command.php:206
  250.7060  207901256   5. PHPUnit\TextUI\ResultPrinter->printResult() /home/travis/build/codeigniter4/CodeIgniter4/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:652
  250.7060  207901256   6. PHPUnit\TextUI\ResultPrinter->printHeader() /home/travis/build/codeigniter4/CodeIgniter4/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:183
  250.7060  207901256   7. SebastianBergmann\Timer\Timer::resourceUsage() /home/travis/build/codeigniter4/CodeIgniter4/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:410
  250.7060  207901256   8. SebastianBergmann\Timer\Timer::timeSinceStartOfRequest() /home/travis/build/codeigniter4/CodeIgniter4/vendor/phpunit/php-timer/src/Timer.php:98
```

Please guide me, where I have made the changes, as everything is working fine in the local environment.

**Comment by jim-parry** [comment]
I haven't seen this error before!
Googling led to https://github.com/sebastianbergmann/phpunit/issues/3026
That suggests enabling backup & restore of $GLOBALS, but I don't see that you have changed that.
The only thing I can think of is to break the PR into smaller ones, eg one per commt in the history above.

**Comment by jim-parry** [comment]
The return type of color() fixed the travos-ci break? go figure!

**Comment by atishamte** [comment]
Nope. The getUserInfo() method of URI return type is given string in coment block. I have reverted the same.
But we need to figure it out the actual return types of methods.
There are many methods in Database module have incorrect return type documented.

**Comment by atishamte** [comment]
Typos changes completed. No more commits in this PR.

**Comment by atishamte** [comment]
Any update on this PR. Is any change required?

**Comment by lonnieezell** [comment]
Looks fine to me. Merging.

**Pull request merged**
