### PR TITLE
Update BaseBuilder.php

### PR DESCRIPTION
**Pull request by LorenzKeel**
**Description**
Just allow to increment or decrement float number with Base Builder Class, not only int

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by neznaika0** [comment]
This is a breaking change. Now you can't use integer.

Are there any good reasons for the change?

**Comment by neznaika0** [comment]
Union types added in php8, php7.4 not supported)

Wait @kenjis comnent

**Comment by LorenzKeel** [comment]
That you for your replies!
I've used the `$builder->where('id', $id)->set('field', 'field+' . $floatnumber, false)->update();` option to achieve the result i needed.
I'm sorry if I caused any inconvenience with my suggestion, which was a bit frivolous.
However, it seems to me that there is no reason why these functions should be restricted to using only numbers of type int.
I would appreciate it if you could find the most appropriate way to make this change in the future.

**Comment by kenjis** [comment]
Adding features through PR is not prohibited. 
However, in order to do so, there must first be a clear reason for adding the feature.

It must also conform to coding standards, and there must be test code.
Union types cannot be used until CI4 drops support PHP 7.4.

**Comment by kenjis** [comment]
As to why this method only allows `int`, perhaps there was no need for anything else. 
At least, it is sure that no one implemented an enhancement that supports `float`.

Certainly, I don't see a strong reason why `float` should be restricted. 
So this enhancement will likely be accepted if the appropriate PR is sent.

**Comment by kenjis** [comment]
Also, since this is an enhancement, not a bug fix, it needs to be sent to branch `4.5`, not `develop`.
See https://codeigniter4.github.io/CodeIgniter4/database/query_builder.html#CodeIgniter\Database\BaseBuilder::increment

**Pull request closed without merging**
