### PR TITLE
perf: replace $locator->getClassname() with findQualifiedNameFromPath()

### PR DESCRIPTION
**Pull request by kenjis**
~~Needs  #8010~~

**Description**
To be honest, I am not sure if the speed has increased, but memory consumption has definitely decreased.

Welcome page:
Before:
Screenshot 2023-10-06 12 59 17
After:
Screenshot 2023-10-06 13 00 15

macOS 12.7
```
$ php -v
PHP 8.1.24 (cli) (built: Sep 28 2023 22:29:09) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.24, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.24, Copyright (c), by Zend Technologies
```

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by neznaika0** [comment]
```console
MINGW64 /e/www/ci-demo (dev)
$ php -v
PHP 8.2.11 (cli) (built: Sep 26 2023 15:25:31) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.11, Copyright (c) Zend Technologies
```
Performance has not changed (my project)

**Comment by kenjis** [comment]
See my results. The change is only about 0.5MB.
In real projects, we use more memory. So it can't measure the change.
Try the default Welcome page or Hello World.

**Comment by neznaika0** [comment]
I tried my test project. Used mem ~7.5 - 7.6 with pagination, filters, events

**Review by MGatner — COMMENTED** [review]
Looks good; awaiting rebase.

**Comment by kenjis** [comment]
The difference is not as great as before.

```
4.5 branch: 1.830 MB
   This PR: 1.621 MB
```

**Review by MGatner — APPROVED** [review]
CodeIgniter's niche is being a full-featured monolith framework that is conservative on magic and very lightweight and easy to install. I think anything that keeps our performance impact down will only help the marketing.

**Pull request merged**
