### PR TITLE
SQLSRV Driver: Update getFullName function to add dynamic schema support

### PR DESCRIPTION
**Pull request by wradstok**
This commit allows one to set the schema for the table in the query builder. For example we can do:

`$this-db->table("myschema.users")->select("userid")`

to create

`SELECT "userid" FROM "myschema"."users"`
 rather than the default
`SELECT "userid" FROM "dbo"."users"`

Each pull request should address a single issue and have a meaningful title.

**Description**
Explain what you have changed, and why.

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

---------Remove from here down in your description----------

**Notes**
- Pull requests must be in English
- If the PR solves an issue, reference it with a suitable verb and the issue number
(e.g. fixes <hash>12345)
- Unsolicited pull requests will be considered, but there is no guarantee of acceptance
- Pull requests should be from a feature branch in the contributor's fork of the repository
  to the develop branch of the project repository

### CODE REVIEW

**Review by michalsn — CHANGES_REQUESTED** [review]
Sorry, but I cannot accept this if dynamic schema support is only implemented for one driver. We would also need some tests for this feature.

**Comment by wradstok** [comment]
That sounds fair enough. I can try taking a stab at the postgres drivers, but I don't have a local instance right now so it might take some time.

Is there documentation for how to run a specific test, or on how to debug tests? It would help me out a lot when writing them.

**Comment by paulbalandan** [comment]
> Is there documentation for how to run a specific test, or on how to debug tests? It would help me out a lot when writing them.

You can take a look at the Builder tests in `tests/system/Database/Builder/` folder and see which particular tests suit your proposed changes.

**Comment by kenjis** [comment]
It seems the base branch of this PR must be changed to `develop`.

**Comment by paulbalandan** [comment]
Hi, and thanks for your contribution! As this PR has been standing for a couple of months now and no effort has been seen to add the necessary unit testing to confirm the patch, we can conclude that there's no more interest in moving this forward.

We love to see and appreciate all contributions coming in from the community. However, please make it an effort to make it easy for maintainers to verify your code (that you want to be part of the framework core) through unit testing. You cannot (and we cannot, either) expect to write only source code and delegate the testing part to others. Unfortunately, that's not how OSS works.

Closing this for now. We'd still love to see you around contributing to the framework. Feel free to open a new PR once all necessary testing is in place. Thanks!

**Pull request closed without merging**
