### PR TITLE
Command cache info to show cache in current system

### PR DESCRIPTION
**Pull request by agungsugiarto**
**Description**
Command cache info to show cache in the current system.
Example: 
image

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by samsonasik** [comment]
phpstan notice handled at https://github.com/codeigniter4/CodeIgniter4/pull/3661

**Review by MGatner — APPROVED** [review]
Very nice addition! Thank you for a thorough PR.

**Comment by michalsn** [comment]
Actually, I have a little problem with this new command because it supports only the `file` handler. `getCacheInfo()` return different information for every handler so if we really want to have such a command we have to point out that it works with the `file` handler only.

Even if we fix it and it will work with other handlers the returned information won't be very useful compared to the `file` handler (and quite different). Just my 2 cents...

**Comment by MGatner** [comment]
Ah, sorry I should have waited for you to review it. I'm rather inexperienced with non-file cache handlers - would the extra info even be worth displaying?

I think the fix for now would be to note (or check) the handler for compatibility.

**Comment by michalsn** [comment]
Well, it might be usable for some people but nothing near the `file` handler (you won't get any list of keys or something like that). I'm concerned that the information for other handlers may frustrate users.

For now, I think we should allow usage of the `file` handler only with this command. And if someone tries to use different handles we should display a note about compatibility (as you proposed).

@agungsugiarto Would you be up for making that change?

**Comment by agungsugiarto** [comment]
@michalsn ahh.. forgive me, i dont see if any handler is the same output like file handler.
This bellow message is clear for display?
image

**Comment by michalsn** [comment]
@agungsugiarto No worries - nothing terrible happened :)

Maybe something like: `At the time, this command only supports the file cache handler.`?

**Comment by agungsugiarto** [comment]
Mr @samsonasik i got error phpstan on pre-commit.
```sh
Starting CodeIgniter precommit...
Linting PHP code...
No syntax errors detected in C:\laragon\www\CodeIgniter4/system/Commands/Cache/InfoCache.php
No syntax errors detected in C:\laragon\www\CodeIgniter4/tests/system/Commands/InfoCacheTest.php
Running PHPStan...
Note: Using configuration file C:\laragon\www\CodeIgniter4\phpstan.neon.dist.
   0/344 [>---------------------------]   0%
[2K 344/344 [============================] 100%

 ------ ------------------------------------------------------------------ 
  Line   system\CodeIgniter.php                                            
 ------ ------------------------------------------------------------------ 
  1118   Variable $_SESSION in isset() always exists and is not nullable.  
 ------ ------------------------------------------------------------------ 

 ------ ------------------------------------------------------------------ 
  Line   system\Log\Logger.php                                             
 ------ ------------------------------------------------------------------ 
  461    Variable $_SESSION in isset() always exists and is not nullable.  
 ------ ------------------------------------------------------------------ 

 ------ ------------------------------------------------------------------ 
  Line   system\Validation\Validation.php                                  
 ------ ------------------------------------------------------------------ 
  761    Variable $_SESSION in isset() always exists and is not nullable.  
 ------ ------------------------------------------------------------------ 

 [ERROR] Found 3 errors                                                                                                

Fix the phpstan error(s) before commit.
> git config --get-all user.name
> git config --get-all user.email
```

**Comment by samsonasik** [comment]
phpstan notice fixed in latest develop, you can checkout develop ( git checkout develop ), pull latest develop, and run composer update first, in case you have some changes to be commited already, you can disable temporary remove `.git/hooks/pre-commit` file.

For example, if your branch named `foo` (You should create new branch based on develop for next new PR for clean commits), you can do as follow:

```bash
# remove temporary .git/hooks/pre-commit file
rm -rf .git/hooks/pre-commit

# commit your change
git commit -m 'add note for cache command info that works only for file system cache' -a

# checkout to develop and pull latest develop
git remote add upstream git@github.com:codeigniter4/CodeIgniter4.git
git checkout develop && git pull upstream develop

# checkout again to your branch and rebase develop
git checkout foo
git rebase develop

# run composer update
composer update

# you can now can make change and add more commits as necessary, it will works as already uses latest phpstan
# the .git/hooks/pre-commit already re-copied during composer update
git commit -m 'more commit if necessary' -a

# push to your fork repository
git push origin foo
```

I wrote a blog post for how to do clean rebase https://samsonasik.wordpress.com/2015/09/16/practical-git-4-rebasing-conflicted-task-branch-against-primary-branch/

**Comment by agungsugiarto** [comment]
> 
> 
> phpstan notice fixed in latest develop, you can checkout develop ( git checkout develop ), pull latest develop, and run composer update first, in case you have some changes to be commited already, you can disable temporary by remove `.git/hooks/pre-commit` file.
> 
> For example, if your branch named `foo` (You should create new branch based on develop for next new PR for clean commits), you can do as follow:
> 
> ```shell
> # remove temporary .git/hooks/pre-commit file
> rm -rf .git/hooks/pre-commit
> 
> # commit your change
> git commit -m 'add note for cache command info that works only for file system cache' -a
> 
> # checkout to develop and pull latest develop
> git remote add upstream git@github.com:codeigniter4/CodeIgniter4.git
> git checkout develop && git pull upstream develop
> 
> # checkout again to your branch and rebase develop
> git checkout foo
> git rebase develop
> 
> # run composer update
> composer update
> 
> # you can now can make change and add more commits as necessary, it will works as already uses latest phpstan
> # the .git/hooks/pre-commit already re-copied during composer update
> git commit -m 'more commit if necessary' -a
> 
> # push to your fork repository
> git push origin foo
> ```
> 
> I wrote a blog post for how to do clean rebase https://samsonasik.wordpress.com/2015/09/16/practical-git-4-rebasing-conflicted-task-branch-against-primary-branch/

Thank u Mr @samsonasik, my pr is working smootly for now hehe

**Pull request merged**
