### PR TITLE
4.1.4 Ready code

### PR DESCRIPTION
**Pull request by MGatner**
**Note**: This is applied directly to `master` because `develop` has moved past the release point. Please review 0ae2594f9d7651e1fe442383a823e56fc29caeb4

### CODE REVIEW

**Review by paulbalandan — COMMENTED** [review]
Are the commits from Sep 4 to 6 intended not to be included?

**Comment by MGatner** [comment]
@paulbalandan Yes, I took those for content changes so was leaving them out. If I misunderstood then speak up.

**Comment by paulbalandan** [comment]
Okay, understood. Please include then the changelog additions for PHP 8.1 changes as those were included in this release. One in Sep 4, another in Sep 6.

**Comment by MGatner** [comment]
@paulbalandan Like that?

**Review by paulbalandan — APPROVED** [review]
Yes, thanks!

**Pull request merged**
