### PR TITLE
Run composer update after composer remove --dev on PHPUnit workflow

### PR DESCRIPTION
**Pull request by samsonasik**
Run composer update after composer remove --dev on PHPUnit workflow to make faster.

**Checklist:**
- [x] Securely signed commits

### CODE REVIEW

**Comment by samsonasik** [comment]
Running the `composer update` after `composer remove --dev` removing many unused packages :tada:

```bash
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 0 updates, 60 removals
  - Removing composer/ca-bundle (1.2.8)
  - Removing composer/composer (1.10.13)
  - Removing composer/package-versions-deprecated (1.11.99)
  - Removing composer/semver (1.7.1)
  - Removing composer/spdx-licenses (1.5.4)
  - Removing composer/xdebug-handler (1.4.3)
  - Removing doctrine/annotations (1.10.4)
  - Removing doctrine/inflector (2.0.3)
  - Removing doctrine/lexer (1.2.1)
  - Removing jean85/pretty-package-versions (1.5.1)
  - Removing justinrainbow/json-schema (5.2.10)
  - Removing migrify/migrify-kernel (0.3.48)
  - Removing migrify/php-config-printer (0.3.48)
  - Removing nette/finder (v2.5.2)
  - Removing nette/robot-loader (v3.3.1)
  - Removing nette/utils (v3.1.3)
  - Removing nikic/php-parser (v4.10.2)
  - Removing ondram/ci-detector (3.5.1)
  - Removing phpstan/phpdoc-parser (0.4.9)
  - Removing phpstan/phpstan (0.12.48)
  - Removing phpstan/phpstan-phpunit (0.12.16)
  - Removing psr/cache (1.0.1)
  - Removing psr/container (1.0.0)
  - Removing psr/event-dispatcher (1.0.0)
  - Removing psr/simple-cache (1.0.1)
  - Removing seld/jsonlint (1.8.2)
  - Removing seld/phar-utils (1.1.1)
  - Removing symfony/cache (v5.1.7)
  - Removing symfony/cache-contracts (v2.2.0)
  - Removing symfony/config (v5.1.7)
  - Removing symfony/console (v5.1.7)
  - Removing symfony/dependency-injection (v5.1.7)
  - Removing symfony/deprecation-contracts (v2.2.0)
  - Removing symfony/error-handler (v5.1.7)
  - Removing symfony/event-dispatcher (v5.1.7)
  - Removing symfony/event-dispatcher-contracts (v2.2.0)
  - Removing symfony/filesystem (v5.1.7)
  - Removing symfony/finder (v5.1.7)
  - Removing symfony/http-client-contracts (v2.2.0)
  - Removing symfony/http-foundation (v5.1.7)
  - Removing symfony/http-kernel (v5.1.7)
  - Removing symfony/polyfill-intl-grapheme (v1.18.1)
  - Removing symfony/polyfill-intl-normalizer (v1.18.1)
  - Removing symfony/polyfill-mbstring (v1.18.1)
  - Removing symfony/polyfill-php73 (v1.18.1)
  - Removing symfony/polyfill-php80 (v1.18.1)
  - Removing symfony/process (v5.1.7)
  - Removing symfony/service-contracts (v2.2.0)
  - Removing symfony/string (v5.1.7)
  - Removing symfony/var-dumper (v5.1.7)
  - Removing symfony/var-exporter (v5.1.7)
  - Removing symfony/yaml (v5.1.7)
  - Removing symplify/autowire-array-parameter (8.3.27)
  - Removing symplify/composer-json-manipulator (8.3.27)
  - Removing symplify/console-color-diff (8.3.27)
  - Removing symplify/easy-testing (8.3.27)
  - Removing symplify/package-builder (8.3.27)
  - Removing symplify/set-config-resolver (8.3.27)
  - Removing symplify/smart-file-system (8.3.27)
  - Removing symplify/symplify-kernel (8.3.27)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 0 updates, 60 removals
  - Removing symplify/symplify-kernel (8.3.27)
  - Removing symplify/smart-file-system (8.3.27)
  - Removing symplify/set-config-resolver (8.3.27)
  - Removing symplify/package-builder (8.3.27)
  - Removing symplify/easy-testing (8.3.27)
  - Removing symplify/console-color-diff (8.3.27)
  - Removing symplify/composer-json-manipulator (8.3.27)
  - Removing symplify/autowire-array-parameter (8.3.27)
  - Removing symfony/yaml (v5.1.7)
  - Removing symfony/var-exporter (v5.1.7)
  - Removing symfony/var-dumper (v5.1.7)
  - Removing symfony/string (v5.1.7)
  - Removing symfony/service-contracts (v2.2.0)
  - Removing symfony/process (v5.1.7)
  - Removing symfony/polyfill-php80 (v1.18.1)
  - Removing symfony/polyfill-php73 (v1.18.1)
  - Removing symfony/polyfill-mbstring (v1.18.1)
  - Removing symfony/polyfill-intl-normalizer (v1.18.1)
  - Removing symfony/polyfill-intl-grapheme (v1.18.1)
  - Removing symfony/http-kernel (v5.1.7)
  - Removing symfony/http-foundation (v5.1.7)
  - Removing symfony/http-client-contracts (v2.2.0)
  - Removing symfony/finder (v5.1.7)
  - Removing symfony/filesystem (v5.1.7)
  - Removing symfony/event-dispatcher-contracts (v2.2.0)
  - Removing symfony/event-dispatcher (v5.1.7)
  - Removing symfony/error-handler (v5.1.7)
  - Removing symfony/deprecation-contracts (v2.2.0)
  - Removing symfony/dependency-injection (v5.1.7)
  - Removing symfony/console (v5.1.7)
  - Removing symfony/config (v5.1.7)
  - Removing symfony/cache-contracts (v2.2.0)
  - Removing symfony/cache (v5.1.7)
  - Removing seld/phar-utils (1.1.1)
  - Removing seld/jsonlint (1.8.2)
  - Removing psr/simple-cache (1.0.1)
  - Removing psr/event-dispatcher (1.0.0)
  - Removing psr/container (1.0.0)
  - Removing psr/cache (1.0.1)
  - Removing phpstan/phpstan-phpunit (0.12.16)
  - Removing phpstan/phpstan (0.12.48)
  - Removing phpstan/phpdoc-parser (0.4.9)
  - Removing ondram/ci-detector (3.5.1)
  - Removing nikic/php-parser (v4.10.2)
  - Removing nette/utils (v3.1.3)
  - Removing nette/robot-loader (v3.3.1)
  - Removing nette/finder (v2.5.2)
  - Removing migrify/php-config-printer (0.3.48)
  - Removing migrify/migrify-kernel (0.3.48)
  - Removing justinrainbow/json-schema (5.2.10)
  - Removing jean85/pretty-package-versions (1.5.1)
  - Removing doctrine/lexer (1.2.1)
  - Removing doctrine/inflector (2.0.3)
  - Removing doctrine/annotations (1.10.4)
  - Removing composer/xdebug-handler (1.4.3)
  - Removing composer/spdx-licenses (1.5.4)
  - Removing composer/semver (1.7.1)
  - Removing composer/package-versions-deprecated (1.11.99)
  - Removing composer/composer (1.10.13)
  - Removing composer/ca-bundle (1.2.8)
```

**Comment by michalsn** [comment]
Sounds promising 👍

**Comment by samsonasik** [comment]
@michalsn faster with 22 minutes build 🎉

**Comment by samsonasik** [comment]
@michalsn All green 🎉

**Comment by MGatner** [comment]
Awesome work - so glad to see the times come down!

**Pull request merged**
