### PR TITLE
Relocate cookie exception

### PR DESCRIPTION
**Pull request by mostafakhudair**
Finish Relocate Cookie Class #4502

### CODE REVIEW

**Review by paulbalandan — CHANGES_REQUESTED** [review]
Remove the CookieException file in HTTP.

**Comment by mostafakhudair** [comment]
@MGatner this PR need to be merged before the next release
@paulbalandan please review

**Comment by mostafakhudair** [comment]
I deleted it, but forgot to save changes ^^

**Comment by paulbalandan** [comment]
Waiting for tests..

**Comment by mostafakhudair** [comment]
All green

**Review by paulbalandan — APPROVED** [review]

**Comment by mostafakhudair** [comment]
@paulbalandan Thank you

**Pull request merged**
