### PR TITLE
chore: add "Edit this page" to the userguide latest

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
- add "Edit this page" button to https://codeigniter4.github.io/CodeIgniter4/

Screenshot 2022-05-09 21 15 33

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [] User guide updated
- [] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
The HTML contents I generated locally and the https://codeigniter4.github.io/CodeIgniter4/ are different.
My local HTML has `<div role="navigation" aria-label="breadcrumbs navigation">`, but the deployed HTML does not have it. Why?

**Comment by MGatner** [comment]
By "deployed" you mean the latest dev version right?

The GitHub Action uses `ammaraskar/sphinx-action@0.4` - it's possible that is using a different version of Sphinx than you have installed. I don't know much about Sphinx unfortunately, but that's my best guess.

**Review by MGatner — APPROVED** [review]
I assume you've tested this.

**Comment by kenjis** [comment]
Yes, I tested on my repos.

**Pull request merged**
