### PR TITLE
chore: Add `minimum-stability` and `prefer-stable` properties to composer.json

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
To ease adding of dev packages (such as `rector/rector:dev-main`).
See:
- https://getcomposer.org/doc/04-schema.md#minimum-stability
- https://getcomposer.org/doc/04-schema.md#prefer-stable

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
How did you run composer normalize?
12de7ec810d9d54c5626d494d8dabd070e68d446

```
$ composer normalize
            
  Command "normalize" is not defined.  
```

**Comment by paulbalandan** [comment]
Run `composer global require ergebnis/composer-normalize`

**Comment by kenjis** [comment]
If we use a thrid-party plugin, it seems better to add our composer.json.
Otherwise, it could change to a non-normalized state soon.

**Comment by paulbalandan** [comment]
I limited the PR to the adding of the properties. I'll send another PR for the normalize plugin

**Comment by kenjis** [comment]
Why do we need these changes?
We can easily install dev package now:
```
$ composer require rector/rector:dev-main
```

**Comment by paulbalandan** [comment]
Not sure what happened in between releases but this is suggested by @samsonasik in https://github.com/rectorphp/rector/issues/7988#issuecomment-1589616717.

Anyway, if you'll require the in-development `codeigniter/phpstan-codeigniter` composer will error:
```console
$ composer require --dev codeigniter/phpstan-codeigniter

In PackageDiscoveryTrait.php line 331:
                                                                                                                                                          
  Could not find a version of package codeigniter/phpstan-codeigniter matching your minimum-stability (stable). Require it with an explicit version con   
  straint allowing its desired stability.                                                                                                                 
                                                                                                                                                          

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]   

```

**Comment by kenjis** [comment]
It is no wonder because it does not have any stable release.
I don't think we should set the minimum stability to `dev`.

If you want to install the package, you can specify it:
```
$ composer require --dev codeigniter/phpstan-codeigniter:1.x-dev
```

**Comment by paulbalandan** [comment]
This repo is for development, so I believe it should be able to add dev packages easily. Also, specifying the unstable version may not be feasible at all times. As far as I know, users require their packages only with the package name.

This approach is also used by the development repos `rector-src` and `phpstan-src`

**Comment by kenjis** [comment]
> As far as I know, users require their packages only with the package name.

They don't know what they do. So dev packages should not be installed easily.

I think only maintainers edit composer.json in this repository, and almost no packages will be added. 
What on earth do we need to add dev packages easily?
I do not understand the need for this PR.

I'm fine with adding `codeigniter/phpstan-codeigniter:1.x-dev` in this repo if we need.

**Comment by MGatner** [comment]
I'm not opposed to adding the flag since this is a dev repo that we have complete control over, but I'm also not clear what benefit it brings. It sounds like this was originally the Composer Normalize PR that got split apart, but we should be able to run Normalize without requiring a dependency at all.

**Comment by lonnieezell** [comment]
What's the consensus here? Should we close this?

**Comment by MGatner** [comment]
I'm ambivalent. Paul & Kenjis, any change in opinion or new thoughts to add?

**Comment by kenjis** [comment]
Are there any problems with the current stability?
I don't think we should reduce minimum stability easily.

**Comment by paulbalandan** [comment]
I'll be reiterating my comment here: https://github.com/codeigniter4/CodeIgniter4/pull/7724#issuecomment-1646538560
> This repo is for development, so I believe it should be able to add dev packages easily.

Adding the `minimum-stability` flag applies only to this `composer.json`. Anyone `require`-ing this on their own apps will not inherit the minimum-stability imposed here. Composer will still use the minimum stability in those apps.

**Comment by MGatner** [comment]
I don't have any concern about our changing these settings, as devs shouldn't be building projects out of this repo (and even if they are accidentally they will have much bigger issues than package stability).

**Comment by paulbalandan** [comment]
As the stance here is effectively neutral, I'm closing this.

**Pull request closed without merging**
