### PR TITLE
fix: Exception rework

### LINKED ISSUE #4358: Discussion: Exception Design
The current exception classes are not neatly categorized, and when creating a new exception class, it is difficult to determine which exceptions to inherit and implement.

Also, when throwing exceptions, it is sometimes difficult to determine which exceptions to throw.

Click and see the class diagram:
class dia
[source](http://www.plantuml.com/plantuml/uml/nLV1Rjim3BtdA_mBk-tOBMrG0zrQPCLElMWoumcLn82YaVhlvsge8ALJjHXoSZEVzVWUQL62hnmBui7erKfguLopnWxQtYe6UbeB-HkURbuax5cXTN-143Vmmc0xrsm7oyf4BvJPQp1WkP0lFBQMWNP2mhzi90OS7-ld5vDY9OM-8K8g94xMXiHPvlgkZTbJMEvAoG7QdUgNAGxnMS5_fzwGC710UlxG-hLWyKiuY9W12r3QoSo-2BJIrb1lZpFOkQBpZ5EAdZyJQSQPOt6D1wjHTBDjp52taaQ_BE46z8nMDag3YsWUkBJ-T-GD3hOxhmy6IfruwDX3-GogxGp924wCUUHipIcSRylBtwA5SOySCGDsySzp-_Zu4B5yNFcsQ3zzjX7BnxKbZEZJEVJ8V9Lw3Rx3FYPDOStQKyAt2TRBfNyG_GTds_t0zxklh-zSzIvwwNTUg7AfMnoEU5le587azqAd9V98TRy_G0waU8oO0QikvLnwtxz1bOL-2gqwmQbMGElBAJX4B1ylDq1VD11dVpFo8sA0Uh1op5AJwIjVRPwJmBdDtQok9kJr7_4F)

In addition, the following questions arise.
- What is the difference between `AlertError`, `CriticalError`, and `EmergencyError`?
- What is the difference between an exception that extends `Error` and an exception that extends `Exception`?
- What is the difference between exceptions placed in `CodeIgniter/Exceptions/` and exceptions placed in components such as `CodeIgniter/Filters/`?
- In what cases do we implement `ExceptionInterface`?
- What is the `FrameworkException`?
- Do we need `CodeIgniter\Cache\Exceptions\ExceptionInterface`?
- Shouldn't there be `LogicException`?

Another problem that has been found is that the exceptions thrown by database-related classes are disparate and not standardized. See #4331

It seems to me that we need to classify the exception classes in a way that is easy to understand, and also indicate what kind of exceptions we throw.

What are your thoughts?

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Supersedes #8470
Closes #4358

- add new Exception classes in `CodeIgniter\Exceptions`
  - `LogicException`
  - `RuntimeException`
  - `BadFunctionCallException`
  - `BadMethodCallException`
  - `InvalidArgumentException`
- add domain-level `ExceptionInterface` to catch all Exceptions in the domain
  - `Files`
  - `HTTP`
  - `Router`

exceptions-database-class-dia

- all Exception classes that the framework throws
  - implement `CodeIgniter\Exceptions\ExceptionInterface`
  - extend `\Exception` (not `\Error`)
  - extend `\LogicException` or `\RuntimeException`

exceptions-class-dia

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
Looks good to me.

**Comment by kenjis** [comment]
Updated code and added user guide.

**Review by MGatner — APPROVED** [review]

**Comment by MGatner** [comment]
UG changes look good, thanks for the thorough coverage.

**Comment by kenjis** [comment]
@MGatner Thanks for the review!

**Pull request merged**
