### PR TITLE
Module discover filter improved

### PR DESCRIPTION
**Pull request by ChibuezeAgwuDennis**
**Module discovering filter issue improved**

**Description**
I think is better to call the module filter just like the default filter in the Config directory to get all the filter features.

So I instantiate the module filter class on module ``discoverfilter()`` in ``system/filters/filters.php``.

```php
include($file);

$this->config = new $className;
```
This is working fine in my project the only problem here is that the default config filter is not loading again

**Checklist:**
- [ ] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
@ChibuezeAgwuDennis Thank you for sending a PR.
But it seems your base branch is very old. There are lots of conflicts.
And you missed the last two commits with GPG sign.

Please read the [Contributing to CodeIgniter](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/README.md), especially:
- https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#php-style
- https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#unit-testing

And this PR contains unrelated `str_contaions()`:
https://github.com/codeigniter4/CodeIgniter4/pull/5534/files#diff-a96878ab09ca70cda56a717ca46ea7d2e1761159d07b7eea0fad26b8472f33e4R868
Please remove unrelated commits.

Thank you.

**Comment by paulbalandan** [comment]
@ChibuezeAgwuDennis  would you be able to address @kenjis 's concerns? If not, we'll promptly close this in the next few days.

**Comment by ChibuezeAgwuDennis** [comment]
> @ChibuezeAgwuDennis would you be able to address @kenjis 's concerns? If not, we'll promptly close this in the next few days.

I am having issue updating my fork to the current version of codeigniter.  can you guide me on that newly to git

**Comment by kenjis** [comment]
@ChibuezeAgwuDennis Try: https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#pushing-your-branch

**Pull request closed without merging**
