### PR TITLE
[WIP] Implement escape defaults in the Model

### PR DESCRIPTION
**Pull request by reinaldorauch**
Currently, if you have in your model defined the $escape property, it will be ignored when doing a insert or update operation (see [this](https://github.com/codeigniter4/CodeIgniter4/issues/4339) issue).

I'm attempting to fix this by moving those statements inside the conditional above because they don't seem to make sense outsite thus ocasioning the issue.

**Checklist:**
- [X] Securely signed commits
- [X] Component(s) with PHPdocs (do not apply)
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [X] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
I don't totally understand how this fixes the issue you reported, but initially it makes sense to me that we only escape data within the conditional. Could you come up with a test case that would have failed prior to your PR but is now fixed? Probably one for both insert and update are in order.

**Comment by MGatner** [comment]
Actually looking at it again I think we need to add the escape regardless of temp data. Regardless I think the test cases will elucidate this for me.

**Comment by michalsn** [comment]
The `$escape` property in the Model is used only internally to determine if the value should be escaped or not. Please see the test example here: https://github.com/codeigniter4/CodeIgniter4/blob/develop/tests/system/Models/InsertModelTest.php#L264

To set this value you have to use `set()` method with your model. It works the same as in the Builder class.

**Comment by reinaldorauch** [comment]
Sorry,  I didn't updated this PR with my recent findings. Only after analyzing better the code that i realized what @michalsn pointed.

I opened an [issue](https://github.com/codeigniter4/CodeIgniter4/issues/4339) before to explain the issue but i've updated that to suggest a feature to pre-configure the escaped properties of the model.

I will update this PR to implement this feature

**Comment by paulbalandan** [comment]
2 months have passed and no updates to this PR. @reinaldorauch is this PR a WIP or are you still interested tackling this?

**Comment by reinaldorauch** [comment]
@paulbalandan Sorry, i have no more interest in pushing this forward. I will close it for now

**Pull request closed without merging**
