### PR TITLE
feat: AVIF Supported

### PR DESCRIPTION
**Pull request by ALTITUDE-DEV-FR**
**Description**
Here is an edition to support the .AVIF format on CodeIgniter 4.5.0, which is the successor to .webp in the years to come. Currently, only three browsers do not yet support AVIF (88.81% of browsers support this version).

https://caniuse.com/avif

The AVIF format is lighter than WEBP.

Here is an example of a comparison from my CodeIgniter CMS, for instance.
Capture d'écran 2024-02-19 132846

Warning, changing the format to a larger one than the original image increases its file size.
Exemple of use: 

` $image->withFile($pathfolder.$newName)->convert(IMAGETYPE_AVIF)->save($pathfolderLarge.mb_url_title($newNameC).'.avif');`

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
Thank you for sending PR!

But you created your PR branch from `develop`. It is wrong, and it runs incorrect GitHub Action checks, and some fails.
See "PHPUnit / Others (8.0)". Of course `4.5` does not support PHP 8.0.

Can you run `git rebase --onto`?
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#if-you-sent-to-the-wrong-branch

**Comment by kenjis** [comment]
Also, fix the coding style. If you run `composer cs-fix`, it fixes automatically.

```diff
   1) system/Images/Handlers/GDHandler.php (unary_operator_spaces, statement_indentation, not_operator_with_successor_space, no_extra_blank_lines, blank_line_before_statement, no_whitespace_in_blank_line)
      ---------- begin diff ----------
--- /home/runner/work/CodeIgniter4/CodeIgniter4/system/Images/Handlers/GDHandler.php
+++ /home/runner/work/CodeIgniter4/CodeIgniter4/system/Images/Handlers/GDHandler.php
@@ -274,7 +274,7 @@
                     throw ImageException::forSaveFailed();
                 }
                 break;
-            
+
             case IMAGETYPE_AVIF:
                 if (! function_exists('imageavif')) {
                     throw ImageException::forInvalidImageCreate(lang('Images.avifNotSupported'));
@@ -376,11 +376,11 @@
 
                 return imagecreatefromwebp($path);
 
-             case IMAGETYPE_AVIF:
+            case IMAGETYPE_AVIF:
                 if (! function_exists('imagecreatefromavif')) {
                     throw ImageException::forInvalidImageCreate(lang('Images.avifNotSupported'));
                 }
-            
+
                 return imagecreatefromavif($path);
 
             default:

      ----------- end diff -----------

   2) system/Images/Handlers/BaseHandler.php (trailing_comma_in_multiline, unary_operator_spaces, not_operator_with_successor_space, no_extra_blank_lines, blank_line_before_statement)
      ---------- begin diff ----------
--- /home/runner/work/CodeIgniter4/CodeIgniter4/system/Images/Handlers/BaseHandler.php
+++ /home/runner/work/CodeIgniter4/CodeIgniter4/system/Images/Handlers/BaseHandler.php
@@ -113,7 +113,7 @@
     protected $supportTransparency = [
         IMAGETYPE_PNG,
         IMAGETYPE_WEBP,
-        IMAGETYPE_AVIF
+        IMAGETYPE_AVIF,
     ];
 
     /**

      ----------- end diff -----------
```

**Comment by ALTITUDE-DEV-FR** [comment]
> Also, fix the coding style. If you run `composer cs-fix`, it fixes automatically.
> 
> ```diff
>    1) system/Images/Handlers/GDHandler.php (unary_operator_spaces, statement_indentation, not_operator_with_successor_space, no_extra_blank_lines, blank_line_before_statement, no_whitespace_in_blank_line)
>       ---------- begin diff ----------
> --- /home/runner/work/CodeIgniter4/CodeIgniter4/system/Images/Handlers/GDHandler.php
> +++ /home/runner/work/CodeIgniter4/CodeIgniter4/system/Images/Handlers/GDHandler.php
> @@ -274,7 +274,7 @@
>                      throw ImageException::forSaveFailed();
>                  }
>                  break;
> -            
> +
>              case IMAGETYPE_AVIF:
>                  if (! function_exists('imageavif')) {
>                      throw ImageException::forInvalidImageCreate(lang('Images.avifNotSupported'));
> @@ -376,11 +376,11 @@
>  
>                  return imagecreatefromwebp($path);
>  
> -             case IMAGETYPE_AVIF:
> +            case IMAGETYPE_AVIF:
>                  if (! function_exists('imagecreatefromavif')) {
>                      throw ImageException::forInvalidImageCreate(lang('Images.avifNotSupported'));
>                  }
> -            
> +
>                  return imagecreatefromavif($path);
>  
>              default:
> 
>       ----------- end diff -----------
> 
>    2) system/Images/Handlers/BaseHandler.php (trailing_comma_in_multiline, unary_operator_spaces, not_operator_with_successor_space, no_extra_blank_lines, blank_line_before_statement)
>       ---------- begin diff ----------
> --- /home/runner/work/CodeIgniter4/CodeIgniter4/system/Images/Handlers/BaseHandler.php
> +++ /home/runner/work/CodeIgniter4/CodeIgniter4/system/Images/Handlers/BaseHandler.php
> @@ -113,7 +113,7 @@
>      protected $supportTransparency = [
>          IMAGETYPE_PNG,
>          IMAGETYPE_WEBP,
> -        IMAGETYPE_AVIF
> +        IMAGETYPE_AVIF,
>      ];
>  
>      /**
> 
>       ----------- end diff -----------
> ```

Thanks for your help, i dont use composer for Github, i push directly from Github Website.

**Comment by ALTITUDE-DEV-FR** [comment]
oh no i have delete the repo.. do you have possibilitie to re-open ?

**Pull request closed without merging**
