### PR TITLE
Validation placeholders in Controller not replaced

### PR DESCRIPTION
**Pull request by erikkloeze**
This pull request should fix issues #2812 and #2817.

**Description**
Duplicated the `fillPlaceholders()` function from Model.php to Controller.php. Called the function before the validator runs.

**Checklist:**
TODO

### CODE REVIEW

**Comment by samsonasik** [comment]
seems requires 2 things:

1. cs check - fix, you can enable cs by run:

```
./admin/setup.sh
```

and try do some changes in the file, and commit. First commit should fail as it act to fix the cs. Retry commit will apply the commit.

2. New tests if possible.

**Comment by samsonasik** [comment]
also, I think placeholder replacement check rules should not in controller as validation may be in model.

**Comment by njsx** [comment]
This is not universal a solve! 

This fix will be work ONLY with data from REQUEST (GET or POST). What about if I want to check data from array in my Controllers's method?

```
$arr['id'] = $this->request->getVar('id');
$arr['login'] = $this->request->getVar('login');

if ($this->validation->run($arr, 'myRuleSet') ) { 
.....
```

In my app\Config\Validation.php:

```
public $myRuleSet = [
		'login' => "is_unique[admins.login,id,{id}]",
	];
```
For is_unique placeholder {id} will never be recognized!

**Comment by samsonasik** [comment]
can be closed in favor of https://github.com/codeigniter4/CodeIgniter4/pull/2897

**Pull request closed without merging**
