### PR TITLE
fix: [DBForge] addForeignKey() Table prefix issue while using with database

### PR DESCRIPTION
**Pull request by Kyoiory**
While adding a foreign key to any external table, it was getting miss formatted if we defined the DB prefix like `db2.table_name` is being formatted like `prefix_db2.tablename` and the query was ended up in malformed constraint error.

This fix will add prefix to the table name only.

**Description**
I have changed the logic of adding prefix for foreign tables and now prefix will only prepend with table name only (last index)

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
Thank you for sending this PR!

We expect the following in all Pull Requests (PRs).
- PRs must be sent to the [appropriate branch](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#branching)
- All git commits must be [GPG-signed](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#signing)
- Must follow our [style guide](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#php-style)
- Be [commented](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#comments) in the PHP source file
- Be documented in the [user guide](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#user-guide)
- Be [unit tested](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#unit-testing)
- Pass all checks in GitHub Actions

> [!IMPORTANT]
> We expect all code changes or bug-fixes to be accompanied by one or more tests added to our test suite to prove the code works.

If pull requests do not comply with the above, they will likely be closed. Since we are a team of volunteers, we don't have any more time to work on the framework than you do. Please make it as painless for your contributions to be included as possible.

See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md

**Comment by kenjis** [comment]
Why do you need to specify the table name like `db2.table_name`?
I don't think now CI4 supports such a name.

**Comment by Kyoiory** [comment]
People often use external table foreign relationships. Just like in my case where i wanted to add foreign key with of a **tablea** from **databasea** to **tableb** of **databaseb**, and was getting it format like  **"`prefix_databaseb`.`tableb`"**

**Comment by kenjis** [comment]
Okay, that makes sense.
But I'm not sure this is a bug or enhancement.

In any case, please fix all errors in GitHub Actions.

**Comment by kenjis** [comment]
We have a command to fix coding style.
```
composer cs-fix
```
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#php-style

**Comment by Kyoiory** [comment]
I am not working with compose until SDLC. Right now i am at pre planning phase and only able to structure my code.

**Comment by kenjis** [comment]
Sorry, I don't get what you mean by "until SDLC".

If you don't use Composer, you cannot run PHPUnit.
How could you write test code for this PR?

In any case, we do not accept PRs without test code.
Thank you.

**Comment by Kyoiory** [comment]
Actually i ran the fixer couple of times (on standalone installation) and only change the specific 3 lines.

**Comment by datamweb** [comment]
Please make sure to update the packages first with the following command.
```console
composer update
```

Then run command : 
```console
git switch patch-1
```
Then  run
```console
composer cs-fix
```
```console
git add system/Database/Forge.php system/Database/BaseConnection.php
git commit -m "style: fix code style"
git push origin patch-1
```

**Comment by kenjis** [comment]
By the way, can you write test code? 
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#unit-testing

We do not accept PRs without test code.

**Comment by kenjis** [comment]
> [!IMPORTANT]
> We expect all code changes or bug-fixes to be accompanied by one or more tests
> added to our test suite to prove the code works.

This PR does not have the necessary test code. If you want this PR to be reviewed, please add the test code.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#unit-testing

If the test is not added, this PR will be closed.

**Pull request closed without merging**
