### PR TITLE
Run tests in random to catch non-deterministic tests

### PR DESCRIPTION
**Pull request by paulbalandan**
**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
Since it was not originally intended to be executed randomly, there are probably too many to fix.

**Review by MGatner — COMMENTED** [review]
I would love to see this happen! Random test order is important for any test quality checks, like Infection.

**Comment by MGatner** [comment]
> Since it was not originally intended to be executed randomly, there are probably too many to fix.

I don't think it should be too hard. Rerun multiple times and isolate the tests that fail as a good starting point.

**Comment by lonnieezell** [comment]
Is anyone interested in tackling this? If not, we should close it.

**Comment by MGatner** [comment]
If tests depend on each other (unintentionally) then there is an inherent hidden point of failure for whatever is being tested. I think this is still worth implementing but I cannot commit to it right now.

**Comment by paulbalandan** [comment]
I'm still willing to finish this. As I am using Windows, I am encountering Windows-related errors which I need to finish first. I'll re-commit to this once I have free time.

**Comment by lonnieezell** [comment]
Ok thanks @paulbalandan. I had been 6 months since the last comment so wasn't sure. 

> If tests depend on each other (unintentionally) then there is an inherent hidden point of failure for whatever is being tested. I think this is still worth implementing but I cannot commit to it right now.

Never said it wasn't worth pursuing. But after 6 months if no one has found the time they either won't without prodding or the issue should just be closed for now until someone wants to bring it up again later. :)

**Comment by paulbalandan** [comment]
To be revived at some point in time.

**Pull request closed without merging**
