### PR TITLE
CURLRequest raise exception only when `http_errors` is true

### PR DESCRIPTION
**Pull request by abydahana**
Add the statement to returning the exception only when "http_errors" configuration isn't set to "false".

### CODE REVIEW

**Comment by paulbalandan** [comment]
As this is a change in behavior, please add tests demonstrating what will happen with and without the curl option supplied.

**Comment by lonnieezell** [comment]
@abydahana  Are you able to submit tests for this?

**Comment by abydahana** [comment]
Hello @lonnieezell, @paulbalandan. I'm trying to contribute but there are terms on the label that I don't fully understand. Like, where can i do a test?

**Comment by paulbalandan** [comment]
Hi, and thanks for your contribution! As this PR has been standing for a couple of months now and no effort has been seen to add the necessary unit testing to confirm the patch, we can conclude that there's no more interest in moving this forward.

We love to see and appreciate all contributions coming in from the community. However, please make it an effort to make it easy for maintainers to verify your code (that you want to be part of the framework core) through unit testing. You cannot (and we cannot, either) expect to write only source code and delegate the testing part to others. Unfortunately, that's not how OSS works.

Closing this for now. We'd still love to see you around contributing to the framework. Feel free to open a new PR once all necessary testing is in place. Thanks!

**Pull request closed without merging**
