### PR TITLE
Added app/Common.php

### PR DESCRIPTION
**Pull request by jason-napolitano**
A commit that will hopefully help with this topic: https://github.com/codeigniter4/CodeIgniter4/issues/2101

Signed-off-by: jason-napolitano <jnapolitanoit@gmail.com>

Each pull request should address a single issue, and have a meaningful title.

**Description**
Explain what you have changed, and why.

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

---------Remove from here down in your description----------

**Notes**
- Pull requests must be in English
- If the PR solves an issue, reference it with a suitable verb and the issue number
(e.g. fixes <hash>12345
- Unsolicited PRs will be considered, but there is no guarantee of acceptance
- Pull requests should be from a feature branch in the contributor's fork of the repository
  to the develop branch of the project repository

### CODE REVIEW

**Comment by xbotkaj** [comment]
Do you need help with this?

**Comment by jim-parry** [comment]
commits need to be gpg-signed, instead of having a PR "signed off", thanks

**Comment by jason-napolitano** [comment]
Yeah @jim-parry, my PHPStorm IDE had an issue with GPG signing (apparently it is still an issue with PHPStorm's Terminal not catching the correct flag upon push) Sorry about that. I'll update my IDE settings and submit a new PR later today.

Thanks.

**Comment by jim-parry** [comment]
I do my GPG-signing from the command line, rather than fight an IDE.

**Comment by MGatner** [comment]
@jason-napolitano I work occasionally in a setting where I cannot setup GPG, so if I have to commit I paste the code right into GitHub which will automatically verify. It isn’t ideal but handy to have as a backup.

**Comment by jason-napolitano** [comment]
@MGatner that is what I ended up doing for https://github.com/codeigniter4/CodeIgniter4/pull/2110 since it is a simple one. I'll get my ducks in order for any potential future PR's so I can rest assured that everything is setup right.

Thanks again!

**Pull request closed without merging**
