### PR TITLE
feat: cors filter

### PR DESCRIPTION
**Pull request by yasinpalizban**
Supersedes #7264

this is cors middleware for ci4 which can be use easily for developing rest ful api application.

go to App/Cors.php do change settings (i mean for most cases add new url without any space to validDomain or exceptionDomain ).
got to App/Filter.php uncomment cors
that's it.

there is some thing i have  to tell you  when deploy app to host (i'm sure you know it)
these are two path for actual  domain. https://www.example.com and https://example.com
it seem that  there are the same but they are different  so it must  insert both  url to validDomain array .

$validDomain[https://example.com,https://www.example.com ];

exceptionDomain[https://api.example.com ];

this is my httaccess for angular  at https://example.com 
 if refresh  page redirect to index.htm and  if come with HTTP turn to be HTTPS

`
<IfModule mod_rewrite.c>
  Options Indexes FollowSymLinks
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
  RewriteCond %{HTTPS} off
  RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</IfModule>

<IfModule mime_module>
  AddHandler application/x-httpd-ea-php72 .php .php7 .phtml
</IfModule>

`

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by samsonasik** [comment]
why you keep close re-open the PR? 

Just add more commit and git push to the branch in case there is more change, you can rebase later if you have too many commits.

**Comment by kenjis** [comment]
Why do you remove **Checklist**?

**Comment by kenjis** [comment]
You opened 6 PRs for this CORS.
https://github.com/codeigniter4/CodeIgniter4/pulls?q=is%3Apr+author%3Ayasinpalizban++cors

**Comment by yasinpalizban** [comment]
this is my httaccess for angular  at https://example.com 
 if refresh  page redirect to index.htm and  if come with HTTP turn to be https


<IfModule mod_rewrite.c>
  Options Indexes FollowSymLinks
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
  RewriteCond %{HTTPS} off
  RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</IfModule>

# php -- BEGIN cPanel-generated handler, do not edit
# Set the “ea-php72” package as the default “PHP” programming language.
<IfModule mime_module>
  AddHandler application/x-httpd-ea-php72 .php .php7 .phtml
</IfModule>
# php -- END cPanel-generated handler, do not edit

**Comment by yasinpalizban** [comment]
> You opened 6 PRs for this CORS. https://github.com/codeigniter4/CodeIgniter4/pulls?q=is%3Apr+author%3Ayasinpalizban++cors

my bad

**Comment by michalsn** [comment]
The idea is fine, but... there is already a very good addon that handles cors: https://github.com/agungsugiarto/codeigniter4-cors, and it's probably a bit more advanced. For this reason, I would personally hold off on this feature.

**Comment by kenjis** [comment]
The package seems good.
But it uses another vendors namespace:
https://github.com/agungsugiarto/codeigniter4-cors/blob/4b7ed2d0f6dfd6f84983b8e7f2afc99a34e54607/composer.json#L18-L21
https://packagist.org/packages/fluent/
So I can't recommend it.

And I think it is better to have official CORS filter even if it is simple.

**Comment by kenjis** [comment]
I found a past PR for CORS: #3706

**Pull request closed without merging**
