### PR TITLE
refactor: replace PHP_VERSION by PHP_VERSION_ID

### PR DESCRIPTION
**Pull request by justbyitself**
PHP_VERSION_ID is shorter and the most commonly used in this repository.

### CODE REVIEW

**Comment by samsonasik** [comment]
There is already `VersionCompareFuncCallToConstantRector` rector rule for that

https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#versioncomparefunccalltoconstantrector

Could you add the `rector.php` so it will be detected automatically in the future? Thank you.

**Comment by samsonasik** [comment]
It seems you commit in separate branch, you can commit new change here that the PR include rector.php + code change

**Comment by justbyitself** [comment]
@samsonasik  OK, done. Thank you.

**Comment by paulbalandan** [comment]
@justbyitself please run the following in your terminal:
```console
composer cs-fix
vendor/bin/rector process system
```

**Review by kenjis — APPROVED** [review]
LGTM!

**Comment by samsonasik** [comment]
Thank you @justbyitself

**Comment by justbyitself** [comment]
Thank you @samsonasik @paulbalandan @kenjis

**Pull request merged**
