### PR TITLE
Cache command info only for file cache handler

### PR DESCRIPTION
**Pull request by agungsugiarto**
**Description**
This command cache:info only supports the file cache handler.
Related discussion https://github.com/codeigniter4/CodeIgniter4/pull/3660#issuecomment-695786132

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Review by paulbalandan — COMMENTED** [review]
Can you show a simple test showing that using the command when the cache handler is not `file` will result in an error message?

**Comment by michalsn** [comment]
@agungsugiarto Please let us know if you will be able to make above changes. If no, I will merge this and we will handle it in the separate PR. Thanks.

**Comment by agungsugiarto** [comment]
Im sorry @paulbalandan and @michalsn this week i'm busy to interview for my new job. I can't for now, thanks.

**Comment by paulbalandan** [comment]
@michalsn I can do the changes in a separate PR. Thanks

**Comment by michalsn** [comment]
@agungsugiarto No worries. Thank you and good luck with your interview.

@paulbalandan It will be great. Thank you.

**Pull request merged**
