### PR TITLE
Minor fixes in Helpers

### PR DESCRIPTION
**Pull request by atishamte**
Each pull request should address a single issue, and have a meaningful title.

**Description**
Explain what you have changed, and why.

**Checklist:**
- [ ] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

---------Remove from here down in your description----------

**Notes**
- Pull requests must be in English
- If the PR solves an issue, reference it with a suitable verb and the issue number
(e.g. fixes <hash>12345
- Unsolicited PRs will be considered, but there is no guarantee of acceptance
- Pull requests should be from a feature branch in the contributor's fork of the repository
  to the develop branch of the project repository

### CODE REVIEW

**Comment by jim-parry** [comment]
You have checked the "securely signed" box, but your commits are not GPG-signed, blocking their merge.
The changes you made to the helpers are good, though :)

**Comment by atishamte** [comment]
Can these changes will get merged in master branch or I need to commit these securely again?

**Comment by jim-parry** [comment]
I can merge them, but they won't be attributed to you. Your call.

**Comment by atishamte** [comment]
If my latest commit is secure, then It will be attributed to me?
Or I need to make new pull request for the same?

**Comment by atishamte** [comment]
I want attribution as I want to make few more contribution

**Comment by jim-parry** [comment]
You might be able to do a "git amend -S" to GPG-sign it retroactively, though I am not sure of the details.
If not, then a new PR, with a signed commit, might be simplest, sorry!

**Comment by atishamte** [comment]
No worries, i will give it a try

**Pull request closed without merging**
