### PR TITLE
refactor: add `declare(strict_types=1)`

### PR DESCRIPTION
**Pull request by kenjis**
Needs ~~#8078, #8080, #8090, #8091, #8124, #8138, #8175, #8242, #8270~~

**Description**
- add `declare(strict_types=1)`

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
@samsonasik 
The following config does not work. 
`DeclareStrictTypesRector` does not skip files in `app/` or other folders.
Is there something wrong?

```diff
--- a/rector.php
+++ b/rector.php
@@ -44,6 +44,7 @@ use Rector\Privatization\Rector\Property\PrivatizeFinalClassPropertyRector;
 use Rector\Set\ValueObject\LevelSetList;
 use Rector\Set\ValueObject\SetList;
 use Rector\Strict\Rector\If_\BooleanInIfConditionRuleFixerRector;
+use Rector\TypeDeclaration\Rector\StmtsAwareInterface\DeclareStrictTypesRector;
 use Utils\Rector\PassStrictParameterToFunctionParameterRector;
 use Utils\Rector\RemoveErrorSuppressInTryCatchStmtsRector;
 use Utils\Rector\RemoveVarTagFromClassConstantRector;
@@ -107,6 +108,15 @@ return static function (RectorConfig $rectorConfig): void {
             __DIR__ . '/system/Session/Handlers',
         ],
 
+        DeclareStrictTypesRector::class => [
+            __DIR__ . '/app',
+            __DIR__ . '/system/Commands/Generators/Views',
+            __DIR__ . '/system/Pager/Views',
+            __DIR__ . '/system/Validation/Views',
+            __DIR__ . '/system/View/Parser.php',
+            __DIR__ . '/tests/system/View/Views',
+        ],
+
         // use mt_rand instead of random_int on purpose on non-cryptographically random
         RandomFunctionRector::class,
 
@@ -117,6 +127,7 @@ return static function (RectorConfig $rectorConfig): void {
     $rectorConfig->importNames();
     $rectorConfig->removeUnusedImports();
 
+    $rectorConfig->rule(DeclareStrictTypesRector::class);
     $rectorConfig->rule(UnderscoreToCamelCaseVariableNameRector::class);
     $rectorConfig->rule(SimplifyUselessVariableRector::class);
     $rectorConfig->rule(RemoveAlwaysElseRector::class);
```

**Comment by samsonasik** [comment]
I am on mobile, but that seems a bug due to `DeclareStrictTypesRector` run on `beforeTraverse()` while skipping check happen on `enterNode()` so that overlapped.

**Comment by samsonasik** [comment]
Reproduced at Rector side:

- https://github.com/rectorphp/rector-src/pull/5191

**Comment by MGatner** [comment]
What a long-standing conversation! I think this is the right time to do this. @lonnieezell What was our `strict_types` friend? John something... Should mention him here.

**Comment by MGatner** [comment]
@John-Betong

**Comment by neznaika0** [comment]
I like type control.

**Comment by kenjis** [comment]
All checks have passed! 🎉

**Review by samsonasik — APPROVED** [review]

**Comment by kenjis** [comment]
Now in `4.5` branch, most files have `declare(strict_types=1)`! 🎉

**Pull request merged**
