### PR TITLE
Patch Log code

### PR DESCRIPTION
**Pull request by MGatner**
**Description**
The `Psr\Log` code in **ThirdParty** is a few versions old. This PR updates to the latest code from the PSR repo.

**Checklist:**
- [X] Securely signed commits
- [X] Component(s) with PHPdocs
- [X] Unit testing, with >80% coverage
- n/a User guide updated
- [X] Conforms to style guide

### CODE REVIEW

**Comment by iRedds** [comment]
I have a question.
Why not move this in the composer dependency?

**Comment by MGatner** [comment]
It is already in the Composer dependency, and that version will be used by Composer installations. For download users though they will access this pre-injected version, which requires occasional updates.

**Review by paulbalandan — APPROVED** [review]

**Comment by paulbalandan** [comment]
I believe though this should be handled by `ComposerScripts`.

**Comment by MGatner** [comment]
I think those are only for Kint and Escaper. My guess is that Log has barely changed in many years so didn't seem to need updates. These changes are really just docblock tweaks.

**Pull request merged**
