### PR TITLE
Pager makeLinks param fix

### PR DESCRIPTION
**Pull request by TysiacSzescset**
**Description**
If $group=null then group name and query string param name is made of timestamp (change every call) making it useless. Setting default $group to "default" string literal solves the problem and generates default "page" query param name.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
Could you please add a test case to **tests/system/Pager/PagerTest.php** to demonstrate the issue that this fixes? See `testMakeLinks()` for likely examples.

**Comment by TysiacSzescset** [comment]
I'v modified makeLinks() a little more.
Timestamp assign is not needed anymore, either $group checks in $this->store() and $this->displayLinks() calls.
Now makeLinks() generates 2 types of results based on two possible types of groups:
- default group (no group or '' empty group) -> `page` query parameter
- custom group -> `page_groupName` query parameter.

Also addes some test and user guide update.

**Comment by TysiacSzescset** [comment]
Ok, after some struggle with git, i hope it's my final commit for this PR :)

**Comment by MGatner** [comment]
> i hope it's my final commit for this PR

I really hope those CI test errors are related to your PR or we have bigger issues!

**Comment by MGatner** [comment]
Actually it looks like a bunch of files had their mode changed. Sorry to do this to you, but let's back out the changes and reapply just what you need. Looks like that will fix the CI issues because your branch is missing a `.env` file. There's a lot of ways to do that, but you might try something like this:

1. Backup the following files outside your repo:
* system/Pager/Pager.php
* tests/system/Pager/PagerTest.php
* user_guide_src/source/libraries/pagination.rst
2. Reset your branch to before the issue: `git reset c307fec459eb6b70a0bab2dd77b1c82c5c8a2e28`
3. Your modified files should still all be in place, so re-apply them:
* `git add system/Pager/Pager.php`
* `git add tests/system/Pager/PagerTest.php`
* `git add user_guide_src/source/libraries/pagination.rst`
4. Make a new commit: `git commit -m "Pager fix, Pager test added, Guide update"`
5. Force origin to the new state: `git push -f`

I have a backup of your repo state local in case anything goes wrong. Good luck! :)

**Comment by MGatner** [comment]
Much better, thank you!

**Pull request merged**
