### PR TITLE
add MockEmail class

### PR DESCRIPTION
**Pull request by samsonasik**
Based on @MGatner comment at https://github.com/codeigniter4/CodeIgniter4/pull/2785#issuecomment-607180488

**Checklist:**
- [x] Securely signed commits
- [x] Unit testing, with >80% coverage

### CODE REVIEW

**Comment by samsonasik** [comment]
I've added unit test for `$autoClear` parameter in `send()` method.

**Comment by lonnieezell** [comment]
This looks good. We do need a way to incorporate testing failures, though, too. Not sure what the preferred way here would be, whether it's another method that specifies the result, or another parameter I'm not too concerned. 

@MGatner thoughts?

**Comment by MGatner** [comment]
Yes I think this is a great start. I was thinking of something like this:
```
	/**
	 * Record of mock emails sent.
	 * @var string
	 */
	public $archive;
...
	public function send($autoClear = true)
	{
...
		$this->archive[] = get_object_vars($this);

		return true;
	}
```

That way a test could check `$mockEmail->archive` to see the actual emails that were "sent". I don't think that code will work because of the scope but you get the idea.

**Comment by samsonasik** [comment]
@MGatner I've added `$archive` property for save properties on `send()` method called.

**Comment by samsonasik** [comment]
I realized that `clear()` methods clear the properties, so, I placed the `archive` saving after `autoClear` check.

**Comment by MGatner** [comment]
Thanks @samsonasik this is precisely what I'd hoped for! Glad to see it wasn't too complicated either.

**Comment by MGatner** [comment]
> I realized that `clear()` methods clear the properties, so, I placed the `archive` saving after `autoClear` check.

@samsonasik I'm working on some tweaks to Email testing... Isn't the precisely what we *don't* want? Setting `$this->archive = get_object_vars($this);` after `clear()` means the values will always be blank. Should be before like you originally had it, right?

**Pull request merged**
