### PR TITLE
fix: [Postgre] updateBatch() breaks `char` type data

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Follow-up #8439
From https://forum.codeigniter.com/showthread.php?tid=89336

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by sclubricants — APPROVED** [review]
This looks good.

One other option - though I don' t know that it would be any better would be to change CHARACTER into CHARACTER VARYING in the cast method. The only reason is that it would keep the getFieldType() method more 'pure' in a sense.  But I'm not sure this would be any better.

**Comment by sclubricants** [comment]
You could change to CHARACTER | CHAR TO VARCHAR in the cast() method. This should cover the other DBMS too.

**Comment by kenjis** [comment]
@sclubricants Thank you for the review!

If `character` (or `char`) lacks a specifier, it is equivalent to `character(1)`.
So on PostgreSQL, `character(n)` seems to be correct type.
And it does not seem to be *pure* to change CHAR to VARCHAR, too.

Anyway, the method is only for Postgre, and it will override even if the parent class has the method.
So I think there is no problem. Go with this for now.

**Comment by sclubricants** [comment]
CHAR = CHARACTER
VARCHAR = CHARACTER VARYING
VARCHAR = CHAR of unspecified length

Anyways, looks good

**Comment by sclubricants** [comment]
```SQL
SELECT CAST('STRING' AS VARCHAR) AS TEST;
```

This runs on postgre but not on mysql

**Pull request merged**
