### PR TITLE
fix. Parser allow other extension

### PR DESCRIPTION
**Pull request by Instrye**
**Description**
- Fix bug from #2086. reference `CodeIgniter/View/View::render ` 

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
The User Guide will need to be updated as well:

"These scripts have a .php extension, but can not contain any PHP." (https://codeigniter4.github.io/CodeIgniter4/outgoing/view_parser.html#what-it-does)

[user_guide_src/source/outgoing/view_parser.rst]

**Comment by Instrye** [comment]
In fact, I just saw that this problem needs to be decided in 4.0.0-rc.2, I don't know what is the reason for fixing this problem. Compatible with CI3? Or is it allowed for any extension? Is this part of the CI4 program?(translate from Google) 
@jim-parry

**Comment by jim-parry** [comment]
It's a defect that makes sense to fix now before the next RC, that's all.
We fix what we can, and defer what we must.

**Comment by jim-parry** [comment]
The view parser was supposed to allow other extensions, and not doing so is an oversight.
I hope to pull together rc.2 on thursday, and hope this can be part of it.

**Comment by Instrye** [comment]
I tried windows / linux / vagrant and there is no way to generate a user guide. Sorry I can't modify the content in the user guide. In fact, English is not my native language, and I don't think I can accurately modify the user guide.(translate from Google)

**Comment by jim-parry** [comment]
You don't have to actually generate the user guide - that is done as part of release building.
The more important thing is to update the appropriate .rst pages.
It is apparent that we need a better process for managing the user guide workflow, but that is something I plan to address in October.

**Comment by jim-parry** [comment]
Thank you :)

**Pull request merged**
