### PR TITLE
docs: restore goals.rst from 3.0 user guide

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
I don't know why this "Design and Architectural Goals" was removed in 4.0 user guide.
But I would like to restore it.

Basically, this goal is still valid today. If there are any changes that should be made, 
please comment.

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [x] User guide updated
- [] Conforms to style guide

### CODE REVIEW

**Review by datamweb — APPROVED** [review]

**Review by TimexPeachtree — APPROVED** [review]
Yess this looks back to good

**Review by ddevsr — APPROVED** [review]

**Comment by kenjis** [comment]
Related #8201

**Review by paulbalandan — APPROVED** [review]

**Review by neznaika0 — APPROVED** [review]
The change is not critical, but has been hanging in PR for a long time

**Comment by kenjis** [comment]
@MGatner @lonnieezell May I merge this?

**Review by MGatner — APPROVED** [review]
I'm okay with this. I came in for a critical read and found no real issues - which makes me think this document might be too abstract or general.

**Pull request merged**
