### PR TITLE
Tests setUp and tearDown: void

### PR DESCRIPTION
**Pull request by MGatner**
**Description**
`setUp()` and `tearDown()` already always return void, but as of PHPUnit 8 the interface requires this in the declaration. This updates the test cases and all tests to add the explicit reference.

**Checklist:**
- [X] Securely signed commits
- [X] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [X] Conforms to style guide

### CODE REVIEW

**Comment by jim-parry** [comment]
gmm - a couple of files changed here :-/

**Comment by MGatner** [comment]
Good old recursive `sed` doing work! We'll see how the tests look, but I think it's an innocuous change.

**Comment by MGatner** [comment]
I'm baffled what happened to the test view files. I didn't touch them - maybe some style enforcement injected the newline? It's causing the tests to fail. I'm trying a manual update via GitHub UI but failing that the test might need to be updated.

**Comment by jim-parry** [comment]
I find that the commit pre-hook can mangle the formatting. Maybe it needs to be made smarter or more context-sensitive.

**Comment by MGatner** [comment]
Yeah it's definitely breaking this - I think I will update the test for now because there is no way to commit those files without the newline.

**Comment by jim-parry** [comment]
I have seen this before ... running a group of tests will have \n added to output, whereas running the entire suite doesn't, or vice-versa (can't remember which way it goes).
Anytime I run into this, I make sure the tests work when the lot of them is run, and avoid running that one module's.
This could be a phpunit thing!?

**Comment by MGatner** [comment]
Not sure but I might redo this and exclude those files from the original commit to prevent them changing.

**Comment by MGatner** [comment]
It looks like that fixed it. @jim-parry Do you feel okay about the tests embracing the newlines?

**Comment by jim-parry** [comment]
I am ok with that - it is a different issue to track down at some point.

**Pull request merged**
