### PR TITLE
style: use `yield_from_array_to_yields` fixer

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
```console
$ vendor/bin/php-cs-fixer describe yield_from_array_to_yields
Description of yield_from_array_to_yields rule.
Yield from array must be unpacked to series of yields.
The conversion will make the array in `yield from` changed in arrays of 1 less dimension.

Fixing examples:
 * Example #1.
   ---------- begin diff ----------
   --- Original
   +++ New
   @@ -1,7 +1,7 @@
    <?php function generate() {
   -    yield from [
   -        1,
   -        2,
   -        3,
   -    ];
   +
   +        yield 1;
   +        yield 2;
   +        yield 3;
   +
    }

   ----------- end diff -----------
```

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
What is better?

**Comment by paulbalandan** [comment]
According to the PR author, it's a matter of preference. Unpacking to series of yields makes the code more readable especially when the array yielded is 3-dimension.

**Comment by kenjis** [comment]
> According to the PR author

Is this about you?

I don't have a strong opinion on which is easier to read.

**Comment by paulbalandan** [comment]
Not me, but a member of the php-cs-fixer team.

One argument is for consistency.

**Comment by MGatner** [comment]
I think the current version is easier to read. Look at `identifiersProvider()` where someone used brilliant white space to make logical divisions - when these get homogenized to separate `yield` statements it all becomes singly spaced. In other providers this also significantly increases the spacing since the arrays were previously on consecutive lines.

**Comment by kenjis** [comment]
Okay, I agree with MGatner.

**Pull request closed without merging**
