### PR TITLE
refactor: replace `global $app` with Services

### PR DESCRIPTION
**Pull request by ping-yee**
**Description**
Modified #6523.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by kenjis — APPROVED** [review]

**Comment by iRedds** [comment]
I understand the reason for this PR, but I don't think it's the right solution.

To begin with, the ``Services::codeigniter()`` service was actually introduced at the suggestion of a developer who wanted to change the request handler.
The reason for this was the unsuccessful design of the framework and the rejection of autowiring.
Therefore, I do not consider it necessary to implement this service, which is a crutch.

I also think that the design of the toolbar filter is bad. Instead of simply injecting a toolbar header or script into the response, data collection is additionally triggered.

I think the way the toolbar works should be changed instead of using ``Services::codeigniter()``.

- Codeigniter 
--- filter toolbar::after( Turn on the toolbar. Inject a header or script into the response. )
-- sending the response
- if the toolbar is enabled, we collect data, including timer data.

**Comment by ping-yee** [comment]
@iRedds Thanks for your advices, I understand what you mean and feel grateful.
Is there any alternative change can use?
If it isn't, I will close this PR.

**Comment by kenjis** [comment]
@iRedds It seems true what you say, but this PR fixes the bug in Long-living PHP like RoadRunner.
I think even if a PR is not perfect, if it improves CI4, it is better to merge.

**Comment by iRedds** [comment]
I just expressed my opinion.
So which way to choose is up to you, gentlemen.

**Comment by kenjis** [comment]
@ping-yee Can you remove this?
https://github.com/codeigniter4/CodeIgniter4/blob/e1dbce0b79e6de31a2e6eb72c86163f01e06f959/system/Debug/Toolbar.php#L354

**Comment by kenjis** [comment]
@iRedds Thank you for your opinion. You can send a PR to fix the bad design of the debugbar later.

**Comment by ping-yee** [comment]
@kenjis I have been taken out the comment out, Appreciated that!

**Review by kenjis — APPROVED** [review]

**Pull request merged**
