### PR TITLE
feat: support database name with dots

### LINKED ISSUE #8647: tableExists() cannot handle Database Name with dot
### PHP Version

8.1

### CodeIgniter4 Version

4.4.5

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL 8.0

### What happened?

Hello, I'm having a problem

My database name;
>com.sitedb.web

The operation I intend to perform is `tableExists('tableName')`.

When I run this code, I receive a Database Exception error. Upon detailed examination of the error, I found that CodeIgniter 4 (CI4) was sending the following MySQL command:
>SHOW TABLES FROM \`com\`.\`sitedb\`.\`web\`

### Steps to Reproduce

That should have been the right command;
>SHOW TABLES FROM \`com.sitedb.web\`

Due to the dots `.` in my database name, CI4 was treating it as \`.\`, thus causing the issue. However, since I'm using a hosting service, I cannot change the database name. Upon inspecting the source code, I found that in `system/Database/MySQLi/Connection.php`, line 391, the code was modified as follows:
>$sql = 'SHOW TABLES FROM ' . $this->escapeIdentifiers($this->database);

I identified that the problem stems from the `escapeIdentifiers` method. Instead of modifying this method, I updated the line as follows:
>"$sql = 'SHOW TABLES FROM \`' . $this->escapeLikeStringDirect($this->database).'\`';"

so that the mysql command was correctly as follows
>SHOW TABLES FROM \`com.sitedb.web\`

This solution temporarily resolved my issue. However, when I update to a new version of CI4, the old code will return, potentially causing the same error in the future. I would appreciate it if you could address this issue and provide a permanent solution.
Thank you.

### Expected Output

>SHOW TABLES FROM \`com.sitedb.web\`

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Closes #8647

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by michalsn — APPROVED** [review]
It seems to work well :thumb

**Review by ddevsr — COMMENTED** [review]
Add notes support dot in database since 4.5

**Review by datamweb — APPROVED** [review]
Codegniter is widely used in shared hosting, I'm glad you removed a limitation.

**Comment by kenjis** [comment]
> Add notes support dot in database since 4.5

Added.

**Review by ddevsr — APPROVED** [review]

**Comment by mbnl** [comment]
Thank you very much it worked for me. #8647

**Pull request merged**
