### PR TITLE
refactor: enable ClosureReturnTypeRector

### PR DESCRIPTION
**Pull request by samsonasik**
**Description**

Add closure return type should be safe, this PR adds it via  `ClosureReturnTypeRector`

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by samsonasik** [comment]
Ready to merge 👍

**Comment by kenjis** [comment]
Coding Standards check Failed.

**Review by MGatner — CHANGES_REQUESTED** [review]
The code all looks good, but once again Rector doesn't match up with our styles.

**Comment by samsonasik** [comment]
cs fixed 👍

**Comment by samsonasik** [comment]
All green 👍 let's merge, thank you @kenjis @MGatner for the review

**Pull request merged**
