### PR TITLE
chore: Enable rector cache

### PR DESCRIPTION
**Pull request by samsonasik**
**Description**

Let's try enable rector cache based on https://getrector.com/documentation/cache-in-ci 

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by samsonasik** [comment]
It seems working ok with merge multiple paths to single:

**Before**  Time: `2m 43s` 

ref https://github.com/codeigniter4/CodeIgniter4/actions/runs/8403997993/job/23015107946#step:11:1


**After** Time: `2s`

ref https://github.com/codeigniter4/CodeIgniter4/actions/runs/8404013987/job/23015144926?pr=8655#step:11:1

Ready to merge 👍

**Review by kenjis — APPROVED** [review]
LGTM!

**Comment by kenjis** [comment]
@samsonasik Can you update `.github` and `devkit` repositories?

**Comment by samsonasik** [comment]
@kenjis yes, I created PR:

- https://github.com/codeigniter4/devkit/pull/128

for it.

**Pull request merged**
