### PR TITLE
Added new interface FilterInterfaceWithArguments

### PR DESCRIPTION
**Pull request by tangix**
**Description**
Fixing #3216 by implementing a new interface to avoid breaking already implemented Filters.

**Checklist:**
- [X] Securely signed commits
- [X] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [X] Conforms to style guide

### CODE REVIEW

**Comment by tangix** [comment]
All tests pass locally, so I am not sure what I'm seeing...

**Comment by michalsn** [comment]
@tangix Can you pull the latest changes from the dev branch and add `Services::reset()` to the `FiltersWithArgumentsTest::setUp()` just after the call to the `parent::setUp()`?

**Comment by tangix** [comment]
Done.

**Comment by michalsn** [comment]
@lonnieezell @MGatner

We probably need to update the user guide for this, but besides that - are you good with these changes?

**Comment by tangix** [comment]
> @lonnieezell @MGatner
> 
> We probably need to update the user guide for this, but besides that - are you good with these changes?

Also, please consider if there is a better way to do this without break backward compatibility.

**Comment by lonnieezell** [comment]
So basically all we're doing is creating a new interface that accepts `$args`, correct? In my mind, this is a bug since it is expected to be working currently. So all we need to do is add the argument to the interface and method. And maybe add some better docs, right? 

While I realize this is technically a BC break, it won't break any existing code. And should be working actually since Myth:Auth uses those filters, though I haven't tried it in a while.

**Comment by tangix** [comment]
@lonnieezell 
Yeah, I was torn between changing the current interface (breaking code) or adding a new interface (possibly cluttering down the framework)...

**Comment by lonnieezell** [comment]
@tangix And I totally respect that you were trying to avoid the BC break here and really appreciate it! I just think this qualifies as a bug so we can fix it the right way.

**Comment by tangix** [comment]
> @tangix And I totally respect that you were trying to avoid the BC break here and really appreciate it! I just think this qualifies as a bug so we can fix it the right way.

I can live with that and I think that would be the correct way forward to avoid another interface and added complexity to CI4.

**Comment by tangix** [comment]
@lonnieezell 
I see 4.0.4 is around the corner but with no fix for this issue. Do you want me to create a new PR based on develop branch, change the FilterInterface (introduce a BC breaking fix) and also check over the docs?

**Comment by MGatner** [comment]
@tangix the goal for 4.0.4 is within the next 24 hours. If you can get this reworked and submitted today I think it would be a great addition given that developers using it will require manual intervention, and a point release is a great time for that.

**Comment by tangix** [comment]
OK, created #3316 fixing the actual bug instead of adding a new interface.

**Pull request closed without merging**
