### PR TITLE
fix: `spark migrate:status` shows incorrect filename when format is `Y_m_d_His_`

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
See https://github.com/codeigniter4/CodeIgniter4/pull/7033#discussion_r1058721974

```console
+-----------+-------------------+-------------------------+-------+-------------+-------+
| Namespace | Version           | Filename                | Group | Migrated On | Batch |
+-----------+-------------------+-------------------------+-------+-------------+-------+
| App       | 2022_12_29_050744 | 12_29_050744_KenjisTest | ---   | ---         | ---   |
| App       | 2022_12_29_050800 | 12_29_050800_PooyaTest  | ---   | ---         | ---   |
+-----------+-------------------+-------------------------+-------+-------------+-------+
```

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by michalsn — APPROVED** [review]

**Review by datamweb — COMMENTED** [review]
Well, it works fine now, **but see the steps below**.
```console
P:\Bug\project-root>php spark migrate:status

CodeIgniter v4.2.10 Command Line Tool - Server Time: 2022-12-29 02:33:16 UTC-06:00

+----------------------+-------------------+--------------------+-------+-------------+-------+
| Namespace            | Version           | Filename           | Group | Migrated On | Batch |
+----------------------+-------------------+--------------------+-------+-------------+-------+
| App                  | 2022_12_29_082842 | KenjisTest         | ---   | ---         | ---   |
| App                  | 2022_12_29_083112 | PooyaTest          | ---   | ---         | ---   |
| Datamweb\ShieldOAuth | 2022-10-20-182737 | ShieldOAuth        | ---   | ---         | ---   |
| CodeIgniter\Shield   | 2020-12-28-223112 | create_auth_tables | ---   | ---         | ---   |
+----------------------+-------------------+--------------------+-------+-------------+-------+
```
step1:
```console
php spark make:migration KenjisTest
```
step2:
```console
php spark make:migration KenjisTest
```
step3:
```console
php spark migrate:status
```
step4:
```console
php spark migrate
```
```console
P:\Bug\project-root>php spark migrate

CodeIgniter v4.2.10 Command Line Tool - Server Time: 2022-12-29 02:37:53 UTC-06:00

Running all new migrations...
PHP Fatal error:  Cannot declare class App\Database\Migrations\KenjisTest, because the name is already in use in P:\Bug\project-root\app\Database\Migrations\2022_12_29_083515_KenjisTest.php on line 7

[ErrorException]

Cannot declare class App\Database\Migrations\KenjisTest, because the name is already in use

at APPPATH\Database\Migrations\2022_12_29_083515_KenjisTest.php:7

Backtrace:
  1    [internal function]
       CodeIgniter\Debug\Exceptions()->shutdownHandler()


P:\Bug\project-root>
```

**Comment by kenjis** [comment]
It is the specification. 

> Since the migration class is a PHP class, the classname must be unique in every migration file.
https://codeigniter4.github.io/CodeIgniter4/dbmgmt/migration.html#create-a-migration

But it is better to report an error when creating the file.

**Comment by datamweb** [comment]
> But it is better to report an error when creating the file.

Before this PR, the output was as follows.
```console
P:\Bug\project-root>php spark migrate

CodeIgniter v4.2.10 Command Line Tool - Server Time: 2022-12-29 02:50:45 UTC-06:00

Running all new migrations...
        Running: (App) 2022_12_29_083515_App\Database\Migrations\KenjisTest
Migrations complete.

```
```console
P:\Bug\project-root>php spark migrate:status

CodeIgniter v4.2.10 Command Line Tool - Server Time: 2022-12-29 02:51:06 UTC-06:00

+----------------------+-------------------+-------------------------+---------+---------------------+-------+
| Namespace            | Version           | Filename                | Group   | Migrated On         | Batch |
+----------------------+-------------------+-------------------------+---------+---------------------+-------+
| App                  | 2022_12_29_082842 | 12_29_082842_KenjisTest | default | 2022-12-29 02:37:53 | 1     |
| App                  | 2022_12_29_083112 | 12_29_083112_PooyaTest  | default | 2022-12-29 02:37:53 | 1     |
| App                  | 2022_12_29_083515 | 2_29_083515_KenjisTest  | default | 2022-12-29 02:50:45 | 2     |
| Datamweb\ShieldOAuth | 2022-10-20-182737 | ShieldOAuth             | ---     | ---                 | ---   |
| CodeIgniter\Shield   | 2020-12-28-223112 | create_auth_tables      | ---     | ---                 | ---   |
+----------------------+-------------------+-------------------------+---------+---------------------+-------+
```
Therefore, in my opinion, it is necessary to display the error message when creating with command `php spark make:migration`, as well as display the error when using `php spark migrate` (perhaps it was created manually).

Thanks anyway.

**Comment by kenjis** [comment]
Do you mean the behavior has changed with this PR?

**Comment by datamweb** [comment]
> behavior has changed with this PR?

What I noticed, yes.

**Comment by kenjis** [comment]
Okay, that makes sense.

But the current behavior is not good.
If you run migrate refresh, `Cannot declare class` error would occur.
Or if a new dev comes to a team, and setup new dev environment, the error would occur.

**Review by datamweb — APPROVED** [review]

**Review by MGatner — APPROVED** [review]

**Pull request merged**
