### PR TITLE
[Rector] Apply Rector to tests directory as well

### PR DESCRIPTION
**Pull request by samsonasik**
Register `tests` directory to run rector as well.

**Checklist:**
- [x] Securely signed commits

### CODE REVIEW

**Review by MGatner — CHANGES_REQUESTED** [review]
That's a lot of test failures! Request a re-review when this is ready.

**Comment by samsonasik** [comment]
@MGatner I updated tests, it seems the test only errors on `MySQLi` and `Postgre` now:

```bash
There were 2 failures:
1) CodeIgniter\Database\Live\SelectTest::testSelectWithMultipleWheresOnSameColumn
Failed asserting that false is true.
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Database/Live/SelectTest.php:172

2) CodeIgniter\Database\Live\SelectTest::testSelectWithMultipleWheresOnSameColumnAgain
Failed asserting that false is true.
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Database/Live/SelectTest.php:191
```

It seems will need re-start the GH action in next few hours just in case it is a GH action issue.

**Comment by samsonasik** [comment]
@MGatner it seems its due to `in_array()` pass true strict check on `SelectTest` for `Mysqli` and `Postgre`.  I updated to skip `PassStrictParameterToFunctionParameterRector` for the `SelectTest`.

**Comment by samsonasik** [comment]
@MGatner All green 🎉

**Comment by samsonasik** [comment]
I also added new rector rule: RemoveUnusedForeachKeyRector to clean up unused key in foreach after moving for to foreach.

**Comment by samsonasik** [comment]
@MGatner All green 🎉

**Review by paulbalandan — APPROVED** [review]

**Comment by paulbalandan** [comment]
Why is `tests/system/Models` excluded?

**Comment by samsonasik** [comment]
@paulbalandan It was hanging there, need to check one by one, so skipping `tests/system/Models` for now.

**Comment by samsonasik** [comment]
I am merging it.

**Comment by MGatner** [comment]
I'm haven't looked through all of them but overall they look good and tests pass. Glad for your work on this!

**Pull request merged**
