### PR TITLE
Set CIDatabaseTestCase and CIUnitTestCase abstract

### LINKED ISSUE #3788: Bug: Warning no tests found in CodeIgiter\Tests\...
**Describe the bug**
I started to write tests in my app and CodeIgniter generate these warnings

```

1) Warning
No tests found in class "CodeIgniter\Test\CIDatabaseTestCase".

2) Warning
No tests found in class "CodeIgniter\Test\CIUnitTestCase".

```

I tried to manually configure my phpunit.xml but it didn't work. Easiest way to solve this according to internet is by set these class to `abstract`.

**CodeIgniter 4 version**
4.0.4

**Expected behavior, and steps to reproduce if appropriate**
Out of the box, should not generate these warning.

phpunit.xml that i tried:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit bootstrap="vendor/codeigniter4/framework/system/Test/bootstrap.php" ...>
	<testsuites>
		<testsuite name="app">
			<directory>./tests</directory>
			<exclude>
				./vendor/codeigniter4/framework/system/Test/CIDatabaseTestCase.php
			</exclude>
		</testsuite>
	</testsuites>

	<filter>
		<whitelist addUncoveredFilesFromWhitelist="false" processUncoveredFilesFromWhitelist="false">
			<directory suffix=".php">./app</directory>
			<exclude>
				<directory suffix=".php">./app/Views</directory>
				<file>./app/Config/Routes.php</file>
			</exclude>
		</whitelist>
	</filter>

	<logging>
		...
	</logging>

	<php>
		...
	</php>
</phpunit>
```

**Context**
 - OS: Windows 10
 - PHP version [e.g. 6.5.4]

### PR DESCRIPTION
**Pull request by willnode**
**Description**
This is PR I propose to fix #3788 (my own issue)

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by samsonasik** [comment]
Looking at your config at https://github.com/codeigniter4/CodeIgniter4/issues/3788, I think your `PHPUnit` config can use `addUncoveredFilesFromWhitelist="true"` instead: 

```xml
		<whitelist addUncoveredFilesFromWhitelist="true" processUncoveredFilesFromWhitelist="true">

                </whitelist>
```

**Comment by willnode** [comment]
I did try that, but I get error.

```
PHP Fatal error:  Cannot declare class App\Commands\FetchTemplate, because the name is already in use in /home/travis/build/domcloud/dom-portal/app/Commands/FetchTemplate.php on line 11
``` 

Because it's the first file in my app folder, I assumed somehow phpunit redefine App namespace again, but I have no idea what's causes nor how to solve it. Except turning off these settings.

[Full build log](https://travis-ci.com/github/domcloud/dom-portal/builds/191150515) or [the project](https://github.com/domcloud/dom-portal/blob/master/phpunit.xml.dist) if that's necessary.

**Comment by samsonasik** [comment]
The redeclare error seems already fixed in latest `dev-develop` at https://github.com/codeigniter4/CodeIgniter4/pull/3772 . Please try latest dev-develop with use `builds` script at like at https://github.com/codeigniter4/CodeIgniter4/blob/develop/admin/starter/builds and run:

```bash
php builds development && composer update
```

**Comment by willnode** [comment]
Thanks. I tried, but that didn't work for me. I don't know why. I think I will revisit that problem later. I'm happy with my setup.

By the way, I seen that a lot phpdoc references changed to Interface due to [this commit](https://github.com/codeigniter4/CodeIgniter4/commit/c480aedd3c9d58017a8840168a86fc7e10675a6f)? That breaks intelephense in VS code (all references goes red, because they don't support `@mixin` yet?). I'm reverting back to release builds.

**Comment by samsonasik** [comment]
Docblock check is part checked by PHPStan. The PHPStan configuration is at https://github.com/codeigniter4/CodeIgniter4/blob/develop/phpstan.neon.dist .Please create issue if you think there issue with that.

**Comment by samsonasik** [comment]
Lets wait other review from the team for it.

**Comment by samsonasik** [comment]
I tried your repo, and after run: `php builds development && composer update`, and update phpunit.xml.dist:

```xml
		<whitelist addUncoveredFilesFromWhitelist="true" processUncoveredFilesFromWhitelist="true">
			<directory suffix=".php">./app</directory>
			<exclude>
				<directory suffix=".php">./app/Views</directory>
				<directory suffix=".php">./app/Config</directory>
				<file>./app/Config/Routes.php</file>
			</exclude>
		</whitelist>
```

running tests is succeed:

```
➜  dom-portal git:(master) ✗ vendor/bin/phpunit tests                    
PHPUnit 8.5.8 by Sebastian Bergmann and contributors.

Error:         No code coverage driver is available

....                                                                4 / 4 (100%)

Time: 1.97 seconds, Memory: 10.00 MB
```

So It probably related with your local dev system.

**Review by MGatner — APPROVED** [review]
Current conversation aside, I think this is actually a fine change on its own.

**Review by michalsn — APPROVED** [review]

**Review by paulbalandan — APPROVED** [review]
Making the classes as `abstract` is not bad since these are not meant to be tested individually.

Project side, I think there is something wrong in your setup causing these to be tested. Here's a portion of my phpunit config.
```xml
    <testsuites>
        <testsuite name="default">
            <directory suffix="Test.php">tests/src</directory>
        </testsuite>
    </testsuites>

     <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">src</directory>
        </whitelist>
    </filter>
```

**Comment by samsonasik** [comment]
@willnode merged, thank you. 
@MGatner @michalsn @paulbalandan thank you for the review.

**Pull request merged**
