### PR TITLE
Fix Undefined property: Config\App::$cookieSameSite

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes the notice.
> Notice: Undefined property: Config\App::$cookieSameSite

See <https://forum.codeigniter.com/thread-78693.html>.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by WinterSilence — COMMENTED** [review]
need replace `$config` to `$this`, also you must use `property_exists()`
`if (! in_array(strtolower($this->cookieSameSite), Cookie::ALLOWED_SAMESITE_VALUES, true))`

**Comment by WinterSilence** [comment]
please add `const SAMESITE_NONE_SECURE = 'none; secure';` to fix all cases

**Comment by paulbalandan** [comment]
There is already a validation check in Cookie for Samesite None without Secure attribute.

**Review by paulbalandan — APPROVED** [review]

**Comment by kenjis** [comment]
> need replace $config to $this, also you must use property_exists()
if (! in_array(strtolower($this->cookieSameSite), Cookie::ALLOWED_SAMESITE_VALUES, true))

`$this->cookieSameSite` is deprecated.

> also you must use property_exists()

Sorry, what do you mean?

**Comment by WinterSilence** [comment]
@kenjis  
~~~php
$config->cookieSameSite = $config->cookieSameSite ?? Cookie::SAMESITE_LAX;
if (property_exists($this, 'cookieSameSite')) {
    $this->cookieSameSite = $config->cookieSameSite;
}
if (! in_array(strtolower($config->cookieSameSite), Cookie::ALLOWED_SAMESITE_VALUES, true))
~~~
property_exists vs isset:
~~~
$o = new  stdClass();
$o->isNull = null;
var_dump(property_exists($o, 'isNull'), isset($o->isNull)); // true, false
~~~

**Comment by WinterSilence** [comment]
@paulbalandan 
> SameSite=None requires Secure

I can't find it in [rfc6265](https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-05#section-5.3.7)
It's good fix but not required rule and other browsers may use none without Secure

**Comment by kenjis** [comment]
@WinterSilence Thanks.

`$this->cookieSameSite` surely exists and is deprecated.
So it seems the current PR code is okay.
https://github.com/codeigniter4/CodeIgniter4/blob/ebdbf0d3ff19667c71ebb909c0afdf0541b3d90c/system/HTTP/ResponseTrait.php#L102-L109

**Review by michalsn — APPROVED** [review]

**Pull request merged**
