### PR TITLE
docs: variable naming adjustments

### PR DESCRIPTION
**Pull request by andifahruddinakas**
**Description**
Explain what you have changed, and why.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Review by ddevsr — APPROVED** [review]

**Comment by paulbalandan** [comment]
Hi @andifahruddinakas, thanks for your PR. However, we're blocked from merging this because the commits are not GPG-signed. Can you sign them?

**Comment by andifahruddinakas** [comment]
> Hi @andifahruddinakas, thanks for your PR. However, we're blocked from merging this because the commits are not GPG-signed. Can you sign them?

Yes, of course

**Comment by paulbalandan** [comment]
Closing, reopening to trigger CI checks

**Review by michalsn — APPROVED** [review]

**Review by paulbalandan — APPROVED** [review]

**Comment by andifahruddinakas** [comment]
Thank You @paulbalandan

**Pull request merged**
