### PR TITLE
chore: update composer scripts

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Follow-up #5866
- update composer scripts

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [] User guide updated
- [] Conforms to style guide

### CODE REVIEW

**Review by paulbalandan — COMMENTED** [review]
This is more of a request than a review :) Can we add the `--ansi` flag to the composer scripts so that output will be colored rather than bland black and white.

**Comment by kenjis** [comment]
Added `--ansi`.
On macOS the output is colored, so I didn't know the need.

**Review by paulbalandan — APPROVED** [review]
Not sure why, but Composer running these scripts in Windows gives black and white output.

**Comment by sfadschm** [comment]
I am on mobile, but I only see one changed file (composer. json). Are the cs-fixer files renamed?

**Comment by sfadschm** [comment]
Nevermind, they already were before 😄

**Pull request merged**
