### PR TITLE
Fix $cookie['expires'] double calculation error

### PR DESCRIPTION
**Pull request by phpvod**
**Description**
```
$this->setCookie(
				$cookie['name'],
				$cookie['value'],
				$cookie['expires'], //The expiration time will be double-counted
				$cookie['domain'],
				$cookie['path'],
				'', // prefix
				$cookie['secure'],
				$cookie['httponly']
			);
```

### CODE REVIEW

**Comment by MGatner** [comment]
I don't understand what is happening and how this fixes it. Can you elaborate?

**Comment by phpvod** [comment]
Please run the following code to reproduce the error.

```
$this->response->setCookie('my_cookie', '123456', DAY);
$redirectResponse = Services::redirectResponse()->withCookies();

$responseCookie = $this->response->getCookie('my_cookie');
$redirectResponseCookie = $redirectResponse->getCookie('my_cookie');

echo $responseCookie['expires'] . '<br />' . $redirectResponseCookie['expires'];
if($responseCookie['expires'] != $redirectResponseCookie['expires']) {
	echo '<br />This is a bug.';
}
```

**Comment by phpvod** [comment]
Please run the following code in the controller to reproduce the error.

$this-&gt;response-&gt;setCookie('my_cookie', '123456', DAY);
$redirectResponse = Services::redirectResponse()-&gt;withCookies();


$responseCookie = $this-&gt;response-&gt;getCookie('my_cookie');
$redirectResponseCookie = $redirectResponse-&gt;getCookie('my_cookie');


echo $responseCookie['expires'] . '<br /&gt;' . $redirectResponseCookie['expires'];
if($responseCookie['expires'] != $redirectResponseCookie['expires']) {
&nbsp; &nbsp;echo '<br /&gt;This is a bug.';
}





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MGatner"<notifications@github.com&gt;; 
发送时间: 2020年7月29日(星期三) 晚上7:11
收件人: "codeigniter4/CodeIgniter4"<CodeIgniter4@noreply.github.com&gt;; 
抄送: "PHPVOD"<phpvod@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [codeigniter4/CodeIgniter4] Fix $cookie[&#39;expires&#39;] double calculation error (#3420)





 
I don't understand what is happening and how this fixes it. Can you elaborate?

**Comment by michalsn** [comment]
Good catch! Thank you.

**Pull request merged**
