### PR TITLE
Add JSON_NUMERIC_CHECK to JSON encoding

### PR DESCRIPTION
**Pull request by devorama**
This allows encoding to make numeric data more true to its type (not enclose them with "", making the receiving system identify
the types easier.

Note making the options variable configurable might be handy in the future depending on the needs of the users
people they interface with they might need additional options added here

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by samsonasik** [comment]
The git history is messing with other branch of PR, you need to back to develop, pull latest upstream,  backup branch, reset it, rebase develop, and cherry-pick the commit ee6accf57127e7dd2178a6bff2a1a0ed44eb50ae , and finally, `git push --force origin devorama-json_encoding` . The following steps should can do:

```bash
git remote add upstream git@github.com:codeigniter4/CodeIgniter4.git
git checkout develop
git pull upstream develop
git checkout devorama-json_encoding
git checkout -b devorama:devorama-json_encoding-backup
git checkout devorama-json_encoding
git reset --hard HEAD~9
git rebase develop
git cherry-pick ee6accf57127e7dd2178a6bff2a1a0ed44eb50ae
git push --force origin devorama-json_encoding
```

**Comment by devorama** [comment]
Good day. I have given up I cannot get 2 git accounts to work on the same machine for this repo
it just nightmare. I am going to delete my work and re-pull it and then redo all the work as I cannot continue like this just wasting time, all the google search help tutorials to get 2 to work just wont work., will delete fork now and start again

> The git history is messing with other branch of PR, you need to back to develop, pull latest upstream, backup branch, reset it, rebase develop, and cherry-pick the commit [ee6accf](https://github.com/codeigniter4/CodeIgniter4/commit/ee6accf57127e7dd2178a6bff2a1a0ed44eb50ae) , and finally, `git push --force origin devorama-json_encoding` . The following steps should can do:

**Comment by devorama** [comment]
@samsonasik Please close/reject this pull request, re-forked will redo it and resend a pull request from new fork

**Comment by devorama** [comment]
Added new pull request from new forked version
https://github.com/codeigniter4/CodeIgniter4/pull/3288

**Comment by samsonasik** [comment]
I am not a collaborator, so I can't close your PR. You can close your PR by yourself.

**Pull request closed without merging**
