### PR TITLE
fix: `spark migrate` `-g` option

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
See #7891

- fix description for `-g` in `spark migrate`, `migrate:refresh`, and `migrate:status`
- remove `-g` option in `spark migrate:rollback` because it does not work (and should not work)

### The current behavior

`migrage:rollback`:
```console
$ php spark migrate:status

CodeIgniter v4.4.0 Command Line Tool - Server Time: 2023-09-04 06:10:28 UTC+00:00

+-----------+-------------------+----------------+---------+---------------------+-------+
| Namespace | Version           | Filename       | Group   | Migrated On         | Batch |
+-----------+-------------------+----------------+---------+---------------------+-------+
| App       | 2023-09-04-013453 | DefaultAddBlog | default | 2023-09-04 06:10:26 | 1     |
| App       | 2023-09-04-013454 | Test1AddBlog   | test1   | 2023-09-04 06:10:26 | 1     |
| App       | 2023-09-04-013455 | Test2AddBlog   | test2   | 2023-09-04 06:10:26 | 1     |
+-----------+-------------------+----------------+---------+---------------------+-------+

$ php spark migrate:rollback -g default

CodeIgniter v4.4.0 Command Line Tool - Server Time: 2023-09-04 06:10:37 UTC+00:00

Rolling back migrations to batch:  0
        Rolling back: (App) 2023-09-04-013455_App\Database\Migrations\Test2AddBlog
        Rolling back: (App) 2023-09-04-013454_App\Database\Migrations\Test1AddBlog
        Rolling back: (App) 2023-09-04-013453_App\Database\Migrations\DefaultAddBlog
Done rolling back migrations.

$ php spark migrate:status

CodeIgniter v4.4.0 Command Line Tool - Server Time: 2023-09-04 06:10:39 UTC+00:00

+-----------+-------------------+----------------+-------+-------------+-------+
| Namespace | Version           | Filename       | Group | Migrated On | Batch |
+-----------+-------------------+----------------+-------+-------------+-------+
| App       | 2023-09-04-013453 | DefaultAddBlog | ---   | ---         | ---   |
| App       | 2023-09-04-013454 | Test1AddBlog   | ---   | ---         | ---   |
| App       | 2023-09-04-013455 | Test2AddBlog   | ---   | ---         | ---   |
+-----------+-------------------+----------------+-------+-------------+-------+
```

`migrate:status`:
```console
$ php spark migrate:status

CodeIgniter v4.4.0 Command Line Tool - Server Time: 2023-09-04 07:15:42 UTC+00:00

+-----------+-------------------+----------------+---------+---------------------+-------+
| Namespace | Version           | Filename       | Group   | Migrated On         | Batch |
+-----------+-------------------+----------------+---------+---------------------+-------+
| App       | 2023-09-04-013453 | DefaultAddBlog | default | 2023-09-04 06:22:19 | 1     |
| App       | 2023-09-04-013454 | Test1AddBlog   | test1   | 2023-09-04 06:22:19 | 1     |
| App       | 2023-09-04-013455 | Test2AddBlog   | test2   | 2023-09-04 06:22:19 | 1     |
+-----------+-------------------+----------------+---------+---------------------+-------+

$ php spark migrate:status -g default

CodeIgniter v4.4.0 Command Line Tool - Server Time: 2023-09-04 07:15:48 UTC+00:00

+-----------+-------------------+----------------+---------+---------------------+-------+
| Namespace | Version           | Filename       | Group   | Migrated On         | Batch |
+-----------+-------------------+----------------+---------+---------------------+-------+
| App       | 2023-09-04-013453 | DefaultAddBlog | default | 2023-09-04 06:22:19 | 1     |
| App       | 2023-09-04-013454 | Test1AddBlog   | ---     | ---                 | ---   |
| App       | 2023-09-04-013455 | Test2AddBlog   | ---     | ---                 | ---   |
+-----------+-------------------+----------------+---------+---------------------+-------+

$ php spark migrate:status -g test2

CodeIgniter v4.4.0 Command Line Tool - Server Time: 2023-09-04 07:15:52 UTC+00:00

+-----------+-------------------+----------------+-------+---------------------+-------+
| Namespace | Version           | Filename       | Group | Migrated On         | Batch |
+-----------+-------------------+----------------+-------+---------------------+-------+
| App       | 2023-09-04-013453 | DefaultAddBlog | ---   | ---                 | ---   |
| App       | 2023-09-04-013454 | Test1AddBlog   | ---   | ---                 | ---   |
| App       | 2023-09-04-013455 | Test2AddBlog   | test2 | 2023-09-04 06:22:19 | 1     |
+-----------+-------------------+----------------+-------+---------------------+-------+
```

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by MGatner — COMMENTED** [review]
Does this need a changelog note?

**Comment by kenjis** [comment]
@MGatner Rebased and added changelog.

**Review by MGatner — APPROVED** [review]
Thanks! Looks good.

**Comment by xonipatino** [comment]
Hello everyone, I have had the same recent problem with version 4.4.1 having the CI_ENVIRONMENT in "development", review the code of the file \system\Database\MigrationRunner.php and comment the following lines (849 - 855):

```
if (ENVIRONMENT !== 'testing' && $group === 'tests' && $this->groupFilter !== 'tests') {
    // @codeCoverageIgnoreStart
    $this->groupSkip = true;

    return true;
    // @codeCoverageIgnoreEnd
}
```

this solved my problem.

It should be allowed that regardless of whether your CI_ENVIRONMENT is "production", "testing" or "development" you can rollback without any problem.

**Comment by xonipatino** [comment]
> Hello everyone, I have had the same recent problem with version 4.4.1 having the CI_ENVIRONMENT in "development", review the code of the file \system\Database\MigrationRunner.php and comment the following lines (849 - 855):
> 
> ```
> if (ENVIRONMENT !== 'testing' && $group === 'tests' && $this->groupFilter !== 'tests') {
>     // @codeCoverageIgnoreStart
>     $this->groupSkip = true;
> 
>     return true;
>     // @codeCoverageIgnoreEnd
> }
> ```
> 
> this solved my problem.
> 
> It should be allowed that regardless of whether your CI_ENVIRONMENT is "production", "testing" or "development" you can rollback without any problem.

Hello, I found a better way to solve and modify these two files:

In **\system\Commands\Database\MigrateRollback.php**

lines 84-86 and 93:

```
/*if (is_string($group)) { xoni
    $runner->setGroup($group);
}*/
$group = is_string($group) ? $group : null;
...
...
...
if (! $runner->regress($batch, $group)) {  //added second parameter
```
In **\system\Database\MigrationRunner.php**

lines 236-240:

```
// Set database group if not null
if ($group !== null) {
    $this->groupFilter = $group; // add this lines
    $this->setGroup($group);
}
```

**Comment by kenjis** [comment]
Your customization is yours, no problem.

But the specifications of the CI4 migration are:
- https://github.com/codeigniter4/CodeIgniter4/issues/7891#issuecomment-1704523056 
- https://github.com/codeigniter4/CodeIgniter4/issues/8026#issuecomment-1756312761

**Pull request merged**
