### PR TITLE
refactor: enable FlipTypeControlToUseExclusiveTypeRector

### PR DESCRIPTION
**Pull request by samsonasik**
**Description**

enable FlipTypeControlToUseExclusiveTypeRector to flip type control from null compare to use exclusive instanceof object for more verbose check.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by samsonasik** [comment]
Ready to merge 👍

**Review by paulbalandan — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @paulbalandan for the review, let's merge ;)

**Comment by neznaika0** [comment]
Does the rule only apply to available classes? There is just a question when using helpers - `config('App') service('routes')` - they can accept not only built-in classes, but also custom

**Comment by samsonasik** [comment]
It check based on native type

**Pull request merged**
