### PR TITLE
fix: [ImageMagickHandler] early terminate processing of invalid library path

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
We should check if the `convert` program exists before doing any processing. Currently, it just checks for a non-empty string in the config file, which is insufficient.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by kenjis — APPROVED** [review]
Looks good.

**Comment by kenjis** [comment]
However, there is a lot of room for improvement in this class.
- #6149
- #6317
- It seems better that the constructor checks the command path.

**Comment by paulbalandan** [comment]
Actually, I'm already looking at those issues since yesterday and might open a PR soon. 🤞

**Comment by paulbalandan** [comment]
Moved checking of `convert` to constructor.

**Review by kenjis — APPROVED** [review]

**Pull request merged**
