### PR TITLE
Fix RendererInterface default params

### LINKED ISSUE #4086: Bug: classes overwrites parameter defaults, phpDoc's defined in interfaces
Please fix difference(phpDoc, parameter defaults) between classes and their interfaces.

For example:
in `system/View/RendererInterface.php` `$saveData = false`:
~~~php
interface RendererInterface {
public function render(string $view, array $options = null, bool $saveData = false): string;
public function renderString(string $view, array $options = null, bool $saveData = false): string;
}
~~~

in `system/View/View.php`  `$saveData = null`:
~~~php
class View implements RendererInterface {
public function render(string $view, array $options = null, bool $saveData = null): string
public function renderString(string $view, array $options = null, bool $saveData = null): string
}
~~~

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #4086

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
Let's discuss this at the linked issue first. I do think the discrepancy is a mistake so might merit this change, but altering the interface definitely counts as a breaking change.

**Comment by WinterSilence** [comment]
@kenjis @MGatner it's break backward compatibility

**Comment by kenjis** [comment]
@WaldemarStanislawski What's the difference between `@param bool|null` and `?bool`?

**Comment by WinterSilence** [comment]
@kenjis
You can pass NULL:
~~~php
/**
 * @param bool|null $value
 */
function f1(?bool $value = null)
{
}
~~~
You can't pass NULL:
~~~php
/**
 * @param bool $value
 */
function f2(bool $value = null)
{
}
~~~

**Pull request closed without merging**
