### PR TITLE
Validation: added $label for custom rule

### PR DESCRIPTION
**Pull request by enix90s**
**Description**

I just needed `$label` for my custom rule.
Because `$label` and `$field` are different.

Thanks.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
Why do you need $label?

And this is an enhancement, so you need to send this PR to `4.4` branch.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#if-you-sent-to-the-wrong-branch

**Comment by enix90s** [comment]
> Why do you need $label?
> 
> And this is an enhancement, so you need to send this PR to `4.4` branch. See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#if-you-sent-to-the-wrong-branch

My use cases, a process for translating eg. in Indonesian.

```php
<?php

return [
    'array_min_length' => 'Minimal {min, number} {label}.',
    // expected: 'Minimal 3 Kata Kunci.'
    // I don't need a `field`.
];
```

I don't know if the `{field}` can convert automatically to `label` when processing the custom error messsage in CodeIgniter4's validation.

Custom rules:

```php

<?php

class CustomRules {

    public function array_min_length($value, $params, array $data, string &$error = null, string $field, string $label): bool
    {
        $items = (array) $value;
        $min = (int) $params;

        if (count($items) < (int) $min) {
            $error = lang('Validation.array_min_length', ['label' => $label]);
            return false;
        }

        return true;
    }


}
```

My model:

```php

<?php

class MyModel extends Model {

    protected $validationRules = [
        'tags'     => [
            'label' => 'Kata Kunci',
            'rules'  => 'required|array_min_length[3]',
        ],
    ];
}
```

As it is known, the `field` identical to `column` in a table, which are commonly used are alphanumeric and underscore (`[A-Za-z0-9\_]`).

I think my English is not too bad.
Thank You.

**Comment by ddevsr** [comment]
I dont know you reading custom message on documentation, we already custom message

```php
protected $validationRules    = [];
protected $validationMessages = [];
```

https://codeigniter4.github.io/CodeIgniter4/libraries/validation.html#translation-of-messages-and-validation-labels

**Comment by enix90s** [comment]
> I dont know you reading custom message on documentation, we already custom message
> 
> ```
> protected $validationRules    = [];
> protected $validationMessages = [];
> ```
> 
> https://codeigniter4.github.io/CodeIgniter4/libraries/validation.html#translation-of-messages-and-validation-labels

Yeah, I know. But I created my own custom model. I'm not using CodeIgniter's Model.

**Comment by kenjis** [comment]
We have the way to translate the label:
https://codeigniter4.github.io/CodeIgniter4/libraries/validation.html#translation-of-messages-and-validation-labels
and `{field}` will be replaced with the translation:

**Comment by kenjis** [comment]
So, I don't think this PR is necessary.

**Comment by kenjis** [comment]
However, since custom rules have the ability to change error messages, there is the possibility of adding the extension of receiving labels.

But even then, it is an enhancement and a PR needs to be sent to the next minor version branch (now `4.4`). 
Also, test code and documentation are needed in order to be merged.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md

**Comment by enix90s** [comment]
I use this framework because it's not too strict. In the custom rule, you should add a label parameter to customize the error message.

Important note here, I'm not using the default CodeIgniter's model.

Maybe no one has done this case yet. For a while I will extend it.

**Comment by kenjis** [comment]
> Important note here, I'm not using the default CodeIgniter's model.

It is not important, because the Validation has the functionality to customize the error messages. The Model just uses the Validation inside.

Anyway, if you send a proper PR, we will consider it.
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md

**Pull request closed without merging**
