### PR TITLE
feat: Encryption CI3 compatibility

### LINKED ISSUE #5769: Bug: [Encryption] supported Message digest algorithm unknown
### PHP Version

8.0

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

cli

### Database

_No response_

### What happened?

Supported Message digest algorithm unknown.
https://codeigniter4.github.io/userguide/libraries/encryption.html#configuration

If I use `RIPEMD160`,
TypeError : Unsupported operand types: string / int

### Steps to Reproduce

```php
        $params         = new EncryptionConfig();
        $params->driver = 'OpenSSL';
        $params->digest = 'RIPEMD160';
        $params->key    = '\xd0\xc9\x08\xc4\xde\x52\x12\x6e\xf8\xcc\xdb\x03\xea\xa0\x3a\x5c';
        $encrypter = $this->encryption->initialize($params);

        $message1 = 'This is a plain-text message.';
        $this->assertSame($message1, $encrypter->decrypt($encrypter->encrypt($message1)));
```

### Expected Output

No TypeError.

### Anything else?

See https://github.com/codeigniter4/CodeIgniter4/pull/5764#pullrequestreview-898715209

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
See https://forum.codeigniter.com/showthread.php?tid=82494

- can decrypt encrypted data by CI3
- add *Supported HMAC Authentication Algorithms* from CI3

Related  #5769
Fixes #5769

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by MGatner — APPROVED** [review]
I'm not going to try to wrap my head around all this in the airport. The forum thread is legit, this solution looks good, and tests seem solid. If you feel confident in it please proceed.

**Comment by kenjis** [comment]
Added the docs.

**Review by MGatner — APPROVED** [review]
Docs look good! Thanks @kenjis 

Out of curiosity, did you have a lot of CI3 projects? Have you ported many of them to CI4?

**Comment by MGatner** [comment]
Predis failure seems unrelated.

**Comment by kenjis** [comment]
> Wouldn't this be breaking for plaintexts encrypted in previous CI4 versions, then decrypted using the new logic, because of the added authentication and encryption information?

No. Because the default value is `''`.
https://github.com/codeigniter4/CodeIgniter4/pull/6277/files#diff-df093e1bf8ea2f3c41b52b1051e5594ae032414e7f50999b97b05c8db3c81cd9R74

I added a test for it.

**Review by paulbalandan — APPROVED** [review]

**Comment by paulbalandan** [comment]
Thanks for the clarification!

**Comment by kenjis** [comment]
Resolved conflict.

**Pull request merged**
