### PR TITLE
refactor: [Redis Cache] fix phpstan baseline error

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
Fix the phpstan baseline error.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by iRedds** [comment]
If we define a type for a class property, then "instanceof" will cause an error if the property is not defined. "isset" will not cause such an error.
Since we periodically add types for class properties, won't this become a problem in the future?

```php
<?php

class A {}

$b= new class {
  protected A $a;
  
  public function __destruct()
  {
    if ($this->a instanceof A) {}
  }
};

unset($b);
// Fatal error: Uncaught Error: Typed property class@anonymous::$a must not be accessed before initialization in /home/user/scripts/code.php:10
```

**Comment by kenjis** [comment]
The following `@var` type is wrong. It is nullable.
https://github.com/codeigniter4/CodeIgniter4/blob/d692016d03b9122370d9faab9ffeec159ebeeb44/system/Cache/Handlers/RedisHandler.php#L41-L43

**Review by kenjis — APPROVED** [review]

**Review by MGatner — COMMENTED** [review]
What prevents someone from this initialization mistake?
```php
$cache = new RedisCache($config);
$value = $cache->get('foo');

**Comment by kenjis** [comment]
Most devs do not write that code.
https://codeigniter4.github.io/CodeIgniter4/libraries/caching.html#example-usage

If they write code like that, they should use `CacheFactory`.
Add comment "Use CacheFactory" in the constructor?

**Comment by MGatner** [comment]
> Add comment "Use CacheFactory" in the constructor?

Yes that would be good. Or make the class `@internal`.

**Review by MGatner — APPROVED** [review]
For the fix at hand: LGTM

**Pull request merged**
