### PR TITLE
[Static Analysis] Use Rector 0.9 for 4.1 branch with php version feature 7.3

### PR DESCRIPTION
**Pull request by samsonasik**
Update rector dependency to 0.9 for 4.1 branch with php version feature 7.3

**Checklist:**
- [x] Securely signed commits

### CODE REVIEW

**Review by paulbalandan — COMMENTED** [review]
I think you need to rebase this first to get the latest fix on Postgre testing. Other than that, this is good to go.

**Comment by samsonasik** [comment]
@paulbalandan if the  latest fix on Postgre testing currently still in develop, it can wait until `4.1` branch rebased against develop.

**Review by MGatner — APPROVED** [review]
Looks good! I will re-run this after next `4.1` rebase. Coming soon!

**Review by paulbalandan — APPROVED** [review]
Ah yes. I didn't mean that the Postgre failure to be a blocker for this PR.

**Comment by MGatner** [comment]
`4.1` is rebased to `develop` - @samsonasik looks like you will need to rebase as well, sorry about that. Might be easier to start over?

**Comment by samsonasik** [comment]
Yes, I will start over.

**Pull request closed without merging**
