### PR TITLE
fix: invalid INSERT/DELETE query when Query Builder uses table alias

### LINKED ISSUE #5365: Bug: [QueryBuilder] Invalid INSERT query when builder use table alias
### PHP Version

8.0

### CodeIgniter4 Version

4,1,5

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MariaDB  10.1.31

### What happened?

I get builder in my Model (I do not extend CodeIgniter Model) assigned to property like that:
`$this->builder = $this->dbConn->table($this->getTable() . ' as t');`
`getTable()` return set table name.
When I produce queries for in eg. select, they are produced nicely.
When I want to produce insert query, builder use table alias I provided and produce query like this:

```INSERT INTO `users` as `t` (fields) VALUES (values)```

### Steps to Reproduce

Create builder object with passed table alias and try to produce insert query.

### Expected Output

```INSERT INTO `users` (fields) VALUES (values)```

### Anything else?

I do not extend CodeIgniter Model.

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #5365
- remove alias from *FROM string* when INSERT/DELETE

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by iRedds** [comment]
I have nothing against the motive of this PR.
But it starts to smell like crutches.

**Comment by lonnieezell** [comment]
I agree. This feels like we're putting a bandaid on  an error instead of fixing a root cause.

**Comment by MGatner** [comment]
Checking back in on this... I'm all for deeper fixes but we have an open bug with a working solution which seems like a good merge to me. I assume the "do it right" approach would involve a fair amount of class refactoring around conditional aliasing, or something like that - and the trend has been to stay away from large changes to the database layer.

**Comment by kenjis** [comment]
I think if a PR makes CI4 better, we should merge it.
Of course, if the quality is too low or the technical debt is too great, it should be rejected.

If you have a better solution, you should send another PR.
I think it is not better to leave a bug unfixed for months.

**Review by MGatner — APPROVED** [review]
I agree. This doesn't lock us out from a refactor fix so even if it is a bandaid it will stop some of the bleeding 😅 Good by me.

**Review by michalsn — APPROVED** [review]

**Pull request merged**
