### PR TITLE
Update documentation code samples

### LINKED ISSUE #4816: Dev: Update documentation code examples to reflect new coding standards
As we're all aware of the latest developments in our coding styles in a bid to shift to PSR-12 plus some of our custom styling, we've started rolling out code style changes in our code base. However, our new coding style tool **cannot** automatically correct **also** our documentation, which needs manual intervention.

We will be appreciative of a helping hand to assist us in updating also the code examples used in our documentation. Please submit pull requests while you can! 😎

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
Closes #4816 

**Checklist:**
- [x] Securely signed commits
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by sfadschm** [comment]
Looks good! I hope you found a way to automate this somehow 😆

**Comment by paulbalandan** [comment]
Got no luck with that. 😅

**Review by MGatner — APPROVED** [review]
Holy cow man this is an unreal amount of work! Thank you so much. Going to ping @lonnieezell to make sure he notices :)

**Review by lonnieezell — APPROVED** [review]
Wow! Amazing job. Thanks so much for doing this. I would hit approve twice if I could :D

**Pull request merged**
