### PR TITLE
Negative feature assertions

### PR DESCRIPTION
**Pull request by MGatner**
**Description**
Adds a few inverses to feature test response assertions.

**Checklist:**
- [X] Securely signed commits
- [X] Component(s) with PHPdocs
- [X] Unit testing, with >80% coverage
- [X] User guide updated
- [X] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
Wow serious ImageMagick failure. I guess I will rerun in a bit. @paulbalandan, in case you have any ideas?

**Review by lonnieezell — APPROVED** [review]
Once you get whatever is going on with the ImageMagick failure fixed, I like these.

**Comment by MGatner** [comment]
I'm hoping if I just keep re-running them it will be magically fixed 😂

**Comment by MGatner** [comment]
It worked! All passing. Who knows why?

**Pull request merged**
