### PR TITLE
apply rector: RemoveAlwaysElseRector

### PR DESCRIPTION
**Pull request by samsonasik**
Use rector to detect no need else when there is already return, continue, throw early.

**Checklist:**
- [x] Securely signed commits

### CODE REVIEW

**Comment by michalsn** [comment]
Oops... we need a rebase to merge this :)

**Comment by samsonasik** [comment]
rebased ;)

**Comment by samsonasik** [comment]
close-reopen to restart build.

**Comment by samsonasik** [comment]
weird, phpunit got canceled: 

```bash

Run script -e -c "vendor/bin/phpunit -v"
Script started, file is typescript
PHPUnit 8.5.8 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.22-1+ubuntu18.04.1+deb.sury.org+1 with Xdebug 2.9.6
Configuration: /home/runner/work/CodeIgniter4/CodeIgniter4/phpunit.xml.dist

.............................................................   61 / 3550 (  1%)
.............................................................  122 / 3550 (  3%)
.............................................................  183 / 3550 (  5%)
.............................................................  244 / 3550 (  6%)
.............................................................  305 / 3550 (  8%)
Error: The operation was canceled.

```

**Comment by samsonasik** [comment]
re-trigger it

**Comment by samsonasik** [comment]
All green 🎉

**Pull request merged**
