### PR TITLE
Fix alignment on few buttons in debug toobar and change color

### PR DESCRIPTION
**Pull request by Nudasoft**
I don't know if this was a design choice or not. But it's looks bit broken with few alignment issues. So I have fixed that and made little cosmetic color changes to make those elements go align with CI4 color theme.

Before...

After...

Thanks.

### CODE REVIEW

**Comment by kenjis** [comment]
When viewed in Firefox 97.0.1, the entire page shifts slightly.

Without Debug Bar:
screenshot 2022-02-21 17 55 51

Before:
screenshot 2022-02-21 17 55 54

After:
screenshot 2022-02-21 17 55 57

**Comment by Nudasoft** [comment]
This layout shifting thing is not related to debug bar. its how firefox render things. no matter what webpage you compare between firefox and chorme you will see that shifting. It's completely unrelated.

**Comment by kenjis** [comment]
I compared in Firefox *Before* and *After*, and the layout shits slightly.
I compared in Chrome *Before* and *After*, and the layout are exactly the same.

**Comment by Nudasoft** [comment]
I cant really reproduce what you are saying. It's pretty much the same before and after.

Firefox 97.01 on Windows10
toolbar

And these are the only changes I've done that related to layout/typography to the toolbar.css file.

#debug-bar h1 {
    display: flex;
    font-weight: normal;
    margin: 0 0 0 auto;
}

#debug-bar #debug-bar-link {
    padding: 6px;
    display: flex;
}

As you can see I'm not targeting anything globally. Only two very specific elements. So it's pretty much impossible to have any unexpected layout issues.

Can you assign someone else to check this pr? 

Thanks.

**Comment by kenjis** [comment]
Thank you for confirmation.
It seems the output of Firefox are a bit different between macOS and Windows.

**Review by paulbalandan — CHANGES_REQUESTED** [review]
Please update also the CSS in **admin/css/debug-toolbar/**

**Comment by kenjis** [comment]
Ah! We use SASS.
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/css.md

**Comment by paulbalandan** [comment]
> Ah! We use SASS. https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/css.md

Yes, but sadly we don't have a workflow that updates the CSS from the SASS/SCSS.

**Comment by sfadschm** [comment]
> > Ah! We use SASS. https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/css.md
> 
> Yes, but sadly we don't have a workflow that updates the CSS from the SASS/SCSS.

Right, but changes should still be made to the SASS files and the compiled locally to produce the CSS.
Otherwise we will run into issues if the next contributer follows this way.

**Review by paulbalandan — APPROVED** [review]
I've compiled the changed SCSS files locally using Dart SASS and found some minor formatting issues. I think I'll tackle that in a separate PR together with a workflow. Anyway, this looks good. Checking also the final output seems fine to me.

**Comment by kenjis** [comment]
I've checked the layout in Firefox. 
I don't know why but the slight shift was gone. Both are exact same.

**Review by kenjis — APPROVED** [review]

**Comment by paulbalandan** [comment]
Thank you, @Nudasoft

**Pull request merged**
