### PR TITLE
4.1.5 Ready code

### PR DESCRIPTION
**Pull request by MGatner**

### CODE REVIEW

**Comment by totoprayogo1916** [comment]
Repo Framework & Appstarter still in v4.1.4

@MGatner @paulbalandan

**Comment by kenjis** [comment]
Deploy Framework failed.
https://github.com/codeigniter4/CodeIgniter4/actions/runs/1435363713

**Comment by MGatner** [comment]
Looks like this was broken with the update to version 5 of `github-script`: https://github.com/codeigniter4/CodeIgniter4/commit/72cd33009817a7db5941c63275e4e7face654f00#diff-02131a2dbc3b22f90f5a8c85b30d8ee770211489caed215e4e1284e318268f67

There were some breaking changes (https://github.com/actions/github-script#breaking-changes-in-v5) but it is not immediately apparent what needs to happen. I will do a manual release (in 1-2 hours) and then look into this when I get a chance.

**Comment by MGatner** [comment]
The scripts all ran, it was just the final workflow step of creating the release that fails. I've created the releases manually now - we will new to fix the action before next release.

**Comment by kenjis** [comment]
@MGatner I sent a PR: #5301
But I don't know how to test.

**Pull request merged**
