### PR TITLE
Update PagerRenderer.php

### PR DESCRIPTION
**Pull request by binhaiit**
Some time , somebody need 'total' and 'pageCount'

Each pull request should address a single issue and have a meaningful title.

**Description**
Explain what you have changed, and why.

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

---------Remove from here down in your description----------

**Notes**
- Pull requests must be in English
- If the PR solves an issue, reference it with a suitable verb and the issue number
(e.g. fixes <hash>12345)
- Unsolicited pull requests will be considered, but there is no guarantee of acceptance
- Pull requests should be from a feature branch in the contributor's fork of the repository
  to the develop branch of the project repository

### CODE REVIEW

**Comment by binhaiit** [comment]
Before ,like this:
`previous 1 ... 2 3 4 [5] 6 7 8 ...  100 Next`     or     `previous 1 ... 93 94 95 [96] 97 98 99 ... 100 Next`

Then:
`previous 1 2 3 4 [5] 6 7 8 ...  100 Next`     or     `previous 1 ... 93 94 95 [96] 97 98 99 100 Next`

**Review by michalsn — COMMENTED** [review]
Sorry, but we can't accept this because you're changing the public API of `PageRenderer` class. 

If you make it work without these changes then it's a different story. Also, there are some conflicts in your branch that should be resolved. Please keep in mind that we also need some tests if you change any functionality.

**Comment by binhaiit** [comment]
If I want to get

`total:100 previous 1 2 3 4 [5] 6 7 8 ... 100 Next`  or  `total:100 previous 1 ... 93 94 95 [96] 97 98 99 100 Next`

This kind of demand is more common

**Comment by binhaiit** [comment]
`total:100 previous 1 2 3 4 [5] 6 7 8 ... 100 Next page:5/100` or `total:100 previous 1 ... 93 94 95 [96] 97 98 99 100 Next page:96/100`

**Comment by michalsn** [comment]
I see the difference here in the output you're presenting but still... you have to find the way to accomplish it without changing parameters for public methods, like `makeLinks()` and `displayLinks()`. Making changes to the public methods will result in broken code for other users.

**Comment by paulbalandan** [comment]
This has been unattended for almost a month, a BC break, and has merge conflicts. Closing this.

**Pull request closed without merging**
