### PR TITLE
[4.3] style: update coding style

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
See #6678

- run `composer cs-fix`.

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
I got the following error, but the fixed code still can be fixed if I run php-cs-fixer again. 
Is this a bug?

```diff
   1) CodeIgniter4/system/Database/BaseBuilder.php (no_useless_concat_operator, concat_space, statement_indentation, unary_operator_spaces, not_operator_with_successor_space)
      ---------- begin diff ----------
--- /home/runner/work/CodeIgniter4/CodeIgniter4/system/Database/BaseBuilder.php
+++ /home/runner/work/CodeIgniter4/CodeIgniter4/system/Database/BaseBuilder.php
@@ -1938,17 +1938,16 @@
         if ($sql === '') {
             $updateFields = $this->QBOptions['updateFields'] ?? $this->updateFields($keys)->QBOptions['updateFields'] ?? [];
 
-            $sql = 'INSERT INTO ' . $table . ' (' . implode(', ', $keys) . ")\n" . '{:_table_:}'
-                . "ON DUPLICATE KEY UPDATE\n" . implode(
-                    ",\n",
-                    array_map(
-                        static fn ($key, $value) => $table . '.' . $key . ($value instanceof RawSql ?
-                            ' = ' . $value :
-                            ' = VALUES(' . $value . ')'),
-                        array_keys($updateFields),
-                        $updateFields
-                    )
-                );
+            $sql = 'INSERT INTO ' . $table . ' (' . implode(', ', $keys) . ")\n{:_table_:}" . "ON DUPLICATE KEY UPDATE\n" . implode(
+                ",\n",
+                array_map(
+                    static fn ($key, $value) => $table . '.' . $key . ($value instanceof RawSql ?
+                        ' = ' . $value :
+                        ' = VALUES(' . $value . ')'),
+                    array_keys($updateFields),
+                    $updateFields
+                )
+            );
 
             $this->QBOptions['sql'] = $sql;
         }

      ----------- end diff -----------
```

**Comment by kenjis** [comment]
```
There was 1 failure:

1) CodeIgniter\Database\Live\UpsertTest::testUpsertWithMultipleSet
Failed asserting that a row in the table [user] matches the attributes 
{
    "email": "jarvis@example.com",
    "name": "Jarvis",
    "country": "2022-10-14"
}

Found similar results: [
    {
        "id": "5",
        "name": "Jarvis",
        "email": "jarvis@example.com",
        "country": "2022-10-15",
        "created_at": null,
        "updated_at": null,
        "deleted_at": null
    }
] and 2 others.

/home/runner/work/CodeIgniter4/CodeIgniter4/system/Test/DatabaseTestTrait.php:280
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Database/Live/UpsertTest.php:641
phpvfscomposer:///home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:97

--
```

**Comment by sclubricants** [comment]
I don't think so. Its just rearranging things I think.

I updated CS fixer but its not giving me the results that it does on here.

**Comment by sclubricants** [comment]
I just got that bug.. let me check it out.

**Comment by sclubricants** [comment]
I think its because of the way I wrote the test. The database is on a different time than php.

**Comment by sclubricants** [comment]
```php
    public function testUpsertWithMultipleSet()
    {
        $builder = $this->db->table('user');

        $ts = 'DATE(CURRENT_TIMESTAMP)';
        if ($this->db->DBDriver === 'OCI8') {
            $ts = "to_char(CURRENT_TIMESTAMP, 'yyyy-mm-dd')";
        } elseif ($this->db->DBDriver === 'SQLSRV') {
            $ts = 'CAST( GETDATE() AS date )';
        }

        $builder->set('email', 'jarvis@example.com');
        $builder->set('name', 'Jarvis');
        $builder->set('country', $ts, false);
        $builder->upsert();

        $dt = date('Y-m-d');

        $this->seeInDatabase('user', ['email' => 'jarvis@example.com', 'name' => 'Jarvis', 'country' => $dt]);
```

Perhaps its not good to use php date() compared to SQLite's DATE(CURRENT_TIMESTAMP)

**Comment by sclubricants** [comment]
https://stackoverflow.com/questions/381371/sqlite-current-timestamp-is-in-gmt-not-the-timezone-of-the-machine

Looks like its using GMT instead of local timezone.

**Comment by sclubricants** [comment]
Merge!

**Review by paulbalandan — APPROVED** [review]

**Review by sclubricants — APPROVED** [review]

**Comment by sclubricants** [comment]
How can we avoid all these warnings?

```
Took 1.37s from 0.50s limit to run CodeIgniter\\Models\\SaveModelTest::testSaveNewEntityWithDate
```

Is there some way to set a time limit on a test?

**Comment by kenjis** [comment]
> How can we avoid all these warnings?

Make the test faster.

> Is there some way to set a time limit on a test?

See https://github.com/NexusPHP/tachycardia/blob/1.x/docs/custom_time_limits.md

**Comment by sclubricants** [comment]
I'd rather set a reasonable time limit and have less of these warnings. It would be nice to see warnings that really need to take a look at and not hundreds of nothing.

**Pull request merged**
