### PR TITLE
New Year 2023

### PR DESCRIPTION
**Pull request by mostafakhudair**
New Year 2023

### CODE REVIEW

**Review by datamweb — COMMENTED** [review]
see https://github.com/codeigniter4/CodeIgniter4/pull/5520

**Review by datamweb — APPROVED** [review]

**Review by kenjis — CHANGES_REQUESTED** [review]
Please update:
https://github.com/codeigniter4/CodeIgniter4/blob/e035451da3eb295446e538e7a1a4366560415420/user_guide_src/source/conf.py#L140

**Comment by ddevsr** [comment]
I think in file `user_guide_src/source/conf.py` using latest year date.

```
yearNow = datetime.date.today().year
```

**Review by MGatner — APPROVED** [review]
Thanks!

**Comment by samsonasik** [comment]
Thank you @mostafakhudair

**Comment by kenjis** [comment]
I sent a PR #7056
But where is the epub copyright year printed?

**Comment by datamweb** [comment]
Screenshot 2023-01-07 131337

**Comment by kenjis** [comment]
It is the HTML version.

I didn't find the copyright year in EPUB version.
We use the same variable to EPUB, so it is probably no problem, though.

**Pull request merged**
