### PR TITLE
[4.5] fix: merge mistake

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Follow-up: https://github.com/codeigniter4/CodeIgniter4/commit/ed4fce13abb12cf37950e53230729b42081dfafe

- fix merge mistake in FeatureTestTrait
- docs: update `@param` in FileLocatorInterface

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
PHPStan cannot detect this simple bug, but Psalm detected.

> Error: system/Test/FeatureTestTrait.php:373:55: UndefinedVariable: Cannot find referenced variable $method (see https://psalm.dev/024)
https://github.com/codeigniter4/CodeIgniter4/actions/runs/7293752587/job/19877405238?pr=8359

**Comment by paulbalandan** [comment]
Not sure what happened but phpstan detects the errors as usual: https://phpstan.org/r/72b876e6-46da-4451-91ad-d1dee59a6829

**Comment by kenjis** [comment]
Indeed it does.
It may be a bug in PHPStan due to some other complex condition.

**Review by michalsn — APPROVED** [review]
The tests passed, so I will assume this is good and ready.

**Pull request merged**
