### PR TITLE
Extension Pager::makeLinks (optional grup name)

### PR DESCRIPTION
**Pull request by nowackipawel**
Allows to specify a group name in a makeLinks method - implicated i.e. allowance to set custom path for pagination.

### CODE REVIEW

**Comment by lonnieezell** [comment]
From looking at the code I'm not 100% sure what the usefullness of this is. If I were to include it, though, the docs would need to be updated to describe its use.

**Comment by nowackipawel** [comment]
on of use cases - you want to show a couple of custom paginations on one page (like in on the dashboard page)..

i.e. simplefast code:
```
		if($user_alerts['count'] > \UserAlertModel::per_page)
		{
			$pager = service('pager');
			$pager->setPath(route_to('user_alerts', self::P_A), 'user-alerts');
			$pager_links_alerts = $pager->makeLinks($page ?? 1, \UserAlertModel::per_page, $user_alerts['count'], 'navigation_full_justify', 3, 'user-alerts');
		}



		$user_history = (new \TransactionModel())->getByUsrIdStageAndOperationIdentifier(\UserModel::isLogged(), 1, \TransactionModel::per_page);

		if($user_history['count'] > \TransactionModel::per_page)
		{
			$pager = service('pager');
			$pager->setPath(route_to('user_history',  self::P_A, self::P_A, 0, 1), 'user-history');
			$pager_links_history = $pager->makeLinks($page ?? 1, \TransactionModel::per_page, $user_history['count'], 'navigation_full_justify', 5, 'user-history');
		}
```

in case there is no way to specify group in make links there is no way to get many different URL prefixes of URLs.

**Comment by nowackipawel** [comment]
@lonnieezell : docs added.

**Comment by lonnieezell** [comment]
Wouldn't these typically be associated with a model already? That's how it's primarily designed to be used....

**Comment by nowackipawel** [comment]
makeLinks as far as I know designed to create custom pagination links ;-)
so IMHO not necessarily

czw., 20 cze 2019 o 06:39 Lonnie Ezell <notifications@github.com>
napisał(a):

**Pull request merged**
