### PR TITLE
URL Functions

### PR DESCRIPTION
**Pull request by MGatner**
**Description**
The next stage of reworking URI handling, this PR refactors the URL Helper's `*_url()` functions to use a new internal helper, `_get_uri()`. This should a) make clearer what each function does, and b) fix a few bugs, including the "big one" #4116.

Due to #4116 I expect there to be failures from dependent components. This will give some idea of the impact this could have on developers who have been expecting `current_url()` to leave off `indexPage`, even though that creates invalid project URLs. In anticipation of this upset we will need some loud screaming in the changelog and release notes.

Note: This relies on #4672 and will need to be rebased after that is merged.

**Checklist:**
- [X] Securely signed commits
- [X] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [X] Conforms to style guide

### CODE REVIEW

**Review by lonnieezell — APPROVED** [review]
I agree we need to shout about this one, but it fixes what needs to be fixed. Thanks. 

I don't see any issues with it.

**Comment by MGatner** [comment]
@lonnieezell See if you think these User Guide changes are appropriate and sufficient.

**Review by lonnieezell — APPROVED** [review]
Yes, I think those changes are sufficient. Will want to include info about that in our release notice, too.

**Review by paulbalandan — APPROVED** [review]
We should also document the changes in the function signatures.

**Comment by MGatner** [comment]
@paulbalandan I already updated the function comments to match what it now does a bit more accurately. Did you mean something like, "Note: this function has changed to..."?

**Comment by paulbalandan** [comment]
I meant the documentation in url_helper.rst

**Comment by MGatner** [comment]
@paulbalandan Something like [this](https://github.com/codeigniter4/CodeIgniter4/pull/4675/files#diff-a6b91e000bc8c7ae5e9527419d54e736e76b1e801ac7ce8da76f75fb3873690aR98)?

**Comment by paulbalandan** [comment]
> @paulbalandan Something like [this](https://github.com/codeigniter4/CodeIgniter4/pull/4675/files#diff-a6b91e000bc8c7ae5e9527419d54e736e76b1e801ac7ce8da76f75fb3873690aR98)?

Ah I see it now. The insertion of the _get_uri function complicated the diff views. I thought the signatures changed. 

Oh, the current_url function has now a nullable second param. We should update that in the docs.

**Comment by MGatner** [comment]
Good catch! Added.

**Review by paulbalandan — APPROVED** [review]

**Pull request merged**
