### PR TITLE
[Rector] Apply FuncGetArgsToVariadicParamRector

### PR DESCRIPTION
**Pull request by samsonasik**
Refactor `func_get_args()` in to a variadic param with `FuncGetArgsToVariadicParamRector` rector rule.

**Checklist:**
- [x] Securely signed commits

### CODE REVIEW

**Review by paulbalandan — APPROVED** [review]

**Review by MGatner — APPROVED** [review]

**Review by MGatner — CHANGES_REQUESTED** [review]
I think the docblock on alternator() needs to be updated.

**Review by MGatner — APPROVED** [review]

**Comment by samsonasik** [comment]
@MGatner updated https://github.com/codeigniter4/CodeIgniter4/pull/4963/commits/cb7458f424481c0683ccd830f51d016edd749d97 

@paulbalandan the git hook somehow changing tabs on return, need manually run : 

```bash
vendor/bin/php-cs-fixer fix system/Helpers/text_helper.php
```

**Comment by paulbalandan** [comment]
> @paulbalandan the git hook somehow changing tabs on return, need manually run :
> 
> ```shell
> vendor/bin/php-cs-fixer fix system/Helpers/text_helper.php
> ```

Not on me, though. Maybe your IDE has indentation set to tabs?

**Comment by samsonasik** [comment]
It is 4 space : 

Screen Shot 2021-07-24 at 19 52 21

Actually, I run the manual command in IDE terminal, so if the IDE is the issue, it should be rolled back to invalid state. Let's see if this will happen again in the future.

**Pull request merged**
