### PR TITLE
fix: validation custom error with asterisk field

### LINKED ISSUE #6245: Bug: Custom validation error for a field with an asterisk.
### CodeIgniter4 Version

dev

### What happened?

If you specify a custom error message for a field with an asterisk, the default error text will be used.
This is due to the fact that a field without an asterisk is passed to generate an error (it contains the full path of the key)

### Steps to Reproduce

```php
$data = [
    'user' => [
        ['name' => null],
        ['name' => null],
    ]
];

$validator = Services::validation();

$validator->setRules(['user.*.name' => 'required'], ['user.*.name' => ['required' => 'Required']]);

$validator->run($data);

dd($validator->getErrors());
// array (2) [
//     'user.0.name' => 'The user.*.name field is required.'
//     'user.1.name' => 'The user.*.name field is required.'
// ]
```

### Expected Output

```php
array (2) [
    'user.0.name' => 'Required'
    'user.1.name' => 'Required'
]
```

### PR DESCRIPTION
**Pull request by ping-yee**
**Description**
Fixes #6245 

- increase judgment if user set up custom validation error with asterisk field.
- increase **testRunWithCustomErrorsAndAsteriskField** for testing

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
Thank you for contribution!

I would like to ask for these three things:
- https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#signing
- https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#php-style
- https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#static-analysis-on-php-code

**Comment by MGatner** [comment]
Thanks for the submission @ping-yee! Please address Kenjis' concerns above. 
Also let's get @iRedds in here to check the actual solution.

**Comment by ping-yee** [comment]
Thanks for your recommend and I will change my code to follow the contributing rules!
I will close this PR then open new one that has securely signed commits.

**Comment by iRedds** [comment]
@ping-yee Doesn't work if a label is specified.

**Comment by ping-yee** [comment]
@iRedds Like what data set?
Because I run the all of validation test and don't get the problem...

**Comment by iRedds** [comment]
['foo.*.bar' => ['label' => 'foo bar', 'rules' => 'required'],

**Comment by ping-yee** [comment]
@iRedds Ok, I got it.
I'll fix this problem when I sent the new PR with securely signed commits.

**Pull request closed without merging**
