### PR TITLE
docs: improve Localization

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
- some improvements
- add tests for the current behavior
- refactor test

See #7960

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [x] User guide updated
- [] Conforms to style guide

### CODE REVIEW

**Comment by neznaika0** [comment]
I would add a note about the keys. Something like this:
> If you want to use whole phrases instead of short keys, be careful - each dot is considered an array separator. You will not be able to get the correct translation.
```php
return [
    'Done. The email has been sent successfully.' => 'Done. The email has been sent successfully.'
];
```

**Review by datamweb — APPROVED** [review]

**Comment by kenjis** [comment]
@neznaika0 Added a note.

**Review by neznaika0 — APPROVED** [review]

**Comment by kenjis** [comment]
Added about missing `Language`  locale: https://github.com/codeigniter4/CodeIgniter4/pull/9109/commits/3cb3839a538e87d8a3e61ca09fdb36eef4365098

**Comment by neznaika0** [comment]
Good. I changing the language in the request (in Filters). It's the same solution.
`$request->setLocale($settings->get('language'));`

**Review by michalsn — APPROVED** [review]

**Pull request merged**
