### PR TITLE
Fix Cookie Prefix

### LINKED ISSUE #6009: Bug: `get_cookie()` cookie prefix behavior
### PHP Version

7.3

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

macOS, Linux

### Which server did you use?

apache

### Database

MySQL 8

### What happened?

The cookie prefixing to prevent collisions doesn't exactly work as expected. There is an issue with at least the get_cookie() helper function. The cookie prefix is specifically toted as a way to prevent collisions, however this function doesn't solve for collisions.

```php
    function get_cookie($index, bool $xssClean = false)
    {
        $prefix  = isset($_COOKIE[$index]) ? '' : config(App::class)->cookiePrefix;
        $request = Services::request();
        $filter  = $xssClean ? FILTER_SANITIZE_FULL_SPECIAL_CHARS : FILTER_DEFAULT;

        return $request->getCookie($prefix . $index, $filter);
    }
```
This function looks to see if the base cookie without the prefix exists, and if it does not exist then it looks for the prefixed cookie. It should look for the prefixed cookie and reject the un-prefixed cookie entirely, otherwise it creates collisions.

### Steps to Reproduce

If you take the following example:

Config/App.php
`
public $cookiePrefix   = 'prefix_';
`

Theoretical array of cookies:
```php
$_COOKIES = [
    'prefix_test' => 'Right Value',
    'text'        => 'Wrong Value',
];
```

`
get_cookie('test');
`

returns 'Wrong Value' by default, ideally it should return 'Right Value' and even if 'prefix_text' is not set, it should return null and never 'Wrong Value'

### Expected Output

returns 'Wrong Value' by default, ideally it should return 'Right Value' and even if 'prefix_text' is not set, it should return null and never 'Wrong Value'

### Anything else?

This could be fairly easily fixed by just enforcing the prefix:
`
$prefix  = config(App::class)->cookiePrefix ?? '';
`

However, I'm not sure if this should be enforced at a deeper stage of getting the cookie, and/or the function should be extended to allow for a prefix to be set independently if desired like:

```php
    function get_cookie($index, bool $xssClean = false, string $prefix = null)
    {
        $prefix  = $prefix !== null ? $prefix : config(App::class)->cookiePrefix;
        $request = Services::request();
        $filter  = $xssClean ? FILTER_SANITIZE_FULL_SPECIAL_CHARS : FILTER_DEFAULT;

        return $request->getCookie($prefix . $index, $filter);
    }
```

### PR DESCRIPTION
**Pull request by colethorsen**
Fixes #6009

This allows the cookie_helper to enforce the default prefix if one exists, and also allows the user to set their own prefix including none at all to overwrite the prefix if necessary. This way there is no longer a collision issue if there are cookies that are prefixed and un-prefixed.

There is also an issue with the session setup where it would inconsistently set the name of the session cookie with and without the cookie prefix leading to multiple session cookies and also effectively creating the same prefixed vs un-prefixed issue.

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
Thank you for sending a PR.

> There is also an issue with the session setup where it would inconsistently set the name of the session cookie with and without the cookie prefix leading to multiple session cookies and also effectively creating the same prefixed vs un-prefixed issue.

I don't know this issue. Could you make it  another PR?
We don't change the Session cookie name.
See https://github.com/codeigniter4/CodeIgniter4/pull/5951#issuecomment-1124407187

**Comment by kenjis** [comment]
This is my simple question.

> We expect all contributions to conform to our [style guide](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/styleguide.md), be commented (inside the PHP source files), be documented (in the [user guide](https://codeigniter4.github.io/userguide/)), and unit tested (in the [test folder](https://github.com/codeigniter4/CodeIgniter4/tree/develop/tests)).
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#contributions

It is clearly stated that we need unit tests.
But almost (especially new) contributors don't write test code.
Do you know why?

**Comment by datamweb** [comment]
> Do you know why?

I understand why! 🥇

**Comment by colethorsen** [comment]
Well if it’s not supposed to set the prefix on the session cookie with the header then it’s broken occasionally in the opposite way.

**Comment by kenjis** [comment]
@colethorsen I don't know why the session is broken occasionally, and why this PR fixes it.

Anyway, the session cookie name is another issue.
Would you please remove it from this PR?
Otherwise this PR won't go ahead.

**Pull request closed without merging**
