### PR TITLE
Renew: add or remove 'stale' label

### PR DESCRIPTION
**Pull request by totoprayogo1916**
**Description**
Returning #7950 unexpectedly `$mergeable` not only results in MERGEABLE or CONFLICTING but also UNKNOWN

**Checklist:**
- [x] Securely signed commits

### CODE REVIEW

**Review by ddevsr — APPROVED** [review]

**Review by kenjis — APPROVED** [review]

**Comment by kenjis** [comment]
It seems no problem!

**Comment by ddevsr** [comment]
I forgot for comment.

We have labelling manual `stale`, and bot will added label and comment only not have label with conflict branch.

Can refactor with this? We remind PR older stale manually. After this if we cant see trigger bot, we can still added manually first and waiting next trigger?

```bash
            # CONFLICTING
            if [ "$mergeable" == "CONFLICTING" ]; then
              # No have 'stale` label
              if [[ ! "$labels" == *"stale"* ]]; then
                    # Add "stale" label
                    gh pr edit $url --add-label "stale"
              fi

              # Add a comment
              gh pr comment $url --body ":wave: Hi, @$author!<br><br>We detected conflicts in your PR against the base branch :speak_no_evil:<br>You may want to sync :arrows_counterclockwise: your branch with upstream!<br><br>Ref: [Syncing Your Branch](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#pushing-your-branch)"
            fi
```

**Comment by kenjis** [comment]
@ddevsr Doesn't that make the comment again and again?

**Comment by ddevsr** [comment]
```bash
gh api \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  /repos/OWNER/REPO/pulls/PULL_NUMBER/comments
```

Can we get contains each per each comment on PR from bot using github cli?

**Comment by kenjis** [comment]
@ddevsr What do you mean?
If this workflow works perfectly, we will not label `stale` manually. It will be added/removed automatically.

**Comment by kenjis** [comment]
@totoprayogo1916 I've found the documentation.
> The value of the mergeable attribute can be true, false, or null. If the value is null, then GitHub has started a background job to compute the mergeability. After giving the job time to complete, resubmit the request. When the job finishes, you will see a non-null value for the mergeable attribute in the response. If mergeable is true, then merge_commit_sha will be the SHA of the test merge commit.
https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request

**Pull request merged**
