### PR TITLE
docs: change comment style in sample code

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
See #5765

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Review by paulbalandan — COMMENTED** [review]
I was thinking using the multiline comment style:
```php
/*
 * This is a comment
 * spanning multiple
 * lines.
 */
```
Notice the beginning `/*` as compared to PHPDoc `/**`

**Comment by kenjis** [comment]
The current:
Screenshot 2022-03-04 13 52 37

With `*`:
Screenshot 2022-03-04 13 54 38

**Comment by kenjis** [comment]
I don't like the following. Too many `*`:
```
$builder->update($data);
/*
 * Produces:
 * UPDATE mytable
 * SET title = '{$title}', name = '{$name}', date = '{$date}'
 * WHERE id = $id
 */
```

The following is better?:
```
$builder->update($data);
/*
Produces:
    UPDATE mytable
    SET title = '{$title}', name = '{$name}', date = '{$date}'
    WHERE id = $id
*/
```

**Comment by sfadschm** [comment]
I do not really have a preference here. If any I would give a slight vote for the asteriks solution by Paul.

While I don't think they are pretty it helps readong the content as ist guides the eye with the indentation.

**Comment by kenjis** [comment]
Okay, I changed comment style.

**Review by paulbalandan — APPROVED** [review]

**Pull request merged**
