### PR TITLE
Add .env example for SQLite3

### PR DESCRIPTION
**Pull request by FrancoisCapon**
**Description**
* Add .env example for SQLite
* I used http://rst.ninjs.org/ to check the result of my modification, hope that render will be ok.

Thanks for CodeIgniter4

**Checklist:**
- [X] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [X] User guide updated
- [X] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
Please drop the firest commit. It is not related to this PR.

**Comment by kenjis** [comment]
Please remove the tabs.

```
Run php utils/check_tabs_in_rst.php
Tabs in RST files were detected:

* in user_guide_src/source/database/configuration.rst
 225 |           etc.) not all values will be needed.  ............

Error: Process completed with exit code 1.
```
https://github.com/codeigniter4/CodeIgniter4/runs/4686745794?check_suite_focus=true

**Comment by kenjis** [comment]
I recommend you setup Sphinx.
See https://github.com/codeigniter4/CodeIgniter4/tree/develop/user_guide_src#setup-instructions

**Review by kenjis — CHANGES_REQUESTED** [review]
Please fix the GitHub Actions check errors.

**Comment by paulbalandan** [comment]
@FrancoisCapon  please use your `fc/pull/001` branch to PR for this change.

**Comment by paulbalandan** [comment]
Closing. Please open a new PR using the correct branch of your fork.

**Pull request closed without merging**
