### PR TITLE
Porting FTP Library from CI3

### PR DESCRIPTION
**Pull request by coderste**
This PR completes the FTP Library port over (#506) from CI3.

I have also added a `ftp()` function within the Checks Controller and made a successfully connection to one of my private servers where I was also making new directory using the library.

All that needs to be done now is for the library to be added to the User Guide - I will try and get round to doing this tomorrow at some point.

### CODE REVIEW

**Comment by jim-parry** [comment]
Er, Checks is mistakenly leftover from one of Lonnie's experiments - it is *not* the testing that would be appropriate ... that would go inside tests/FTP/FTPTest.php, for instance. It doesn't look as though there was any unit testing in CI# -> this is our opportunity to ascertain that it behaves as expected in CI4 :)

**Comment by byazrail** [comment]
@coderste 
hey, language file fix key;
key change to ftpUnableToDelete -> ftpUnableToMove.

this fix commit changed key;
https://github.com/bcit-ci/CodeIgniter4/pull/510/commits/a99700a7e30617a278bafe6f0971a6ce03cf7b8b

perfect job :)
take it easy.

**Comment by coderste** [comment]
So hopefully by the end of the day I will have the Unit Tests for this

**Comment by lonnieezell** [comment]
@coderste Any luck getting this wrapped up? No hurry, but I am out on vacation next week and had a moment after wrapping up a rough deadline and thought I'd check in. :)

**Comment by lonnieezell** [comment]
@coderste Are you going to be able to wrap work on this more?

**Comment by coderste** [comment]
@lonnieezell - yea sure thing, should have some time next weekend to complete the Unit Tests

**Comment by lonnieezell** [comment]
@coderste Excellent. Just trying to figure out which PRs are abandoned that I need to finish up. :)

**Pull request closed without merging**
