### PR TITLE
Fix missing extensions in CI/CD

### PR DESCRIPTION
**Pull request by paulbalandan**
**Checklist:**
- [x] Securely signed commits

### CODE REVIEW

**Comment by kenjis** [comment]
It seems there are still some fonts missing.

> convert: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1338.

**Comment by paulbalandan** [comment]
I've reinstalled `ghostscript` but still imagick's `convert` still fails.

**Comment by kenjis** [comment]
I'm not sure, but how about installing `gsfonts`?

**Comment by paulbalandan** [comment]
> I'm not sure, but how about installing `gsfonts`?

Thanks!

**Pull request merged**
