### PR TITLE
[ci skip] user guide title fix: remove "-rc-4" suffix in title, update with next release version

### PR DESCRIPTION
**Pull request by samsonasik**
The current userguide still using "4.0.0-rc.4" in title. This update it with next version in the title.

**Checklist:**
- [x] Securely signed commits

### CODE REVIEW

**Comment by MGatner** [comment]
Good catch! @jreklund @littlej Does this conflict with the work either of you are doing?

**Comment by LittleJ** [comment]
Thanks for the heads up ! 😉 It has no conflict with my work, but @jreklund might have already fixed it in his branch (big up-coming PR I believe). Let's wait for his answer.

**Comment by jreklund** [comment]
I have personally changed it into `4.0.2` in my PR. As what I can dig out of admin/version(?) script it should bump it up to the latest automatically (but failed?). So I stayed on the one we have right now.

And develop branch lacks the changelog files (for 4.0.1 and 4.0.2), but the codeigniter4/userguide project have them. So it's a little mystery why we have this inconsistency.

**Comment by samsonasik** [comment]
@jreklund for no more changelog files, there is a note in `./user_guide_src/source/changelogs/v4.0.0.rst` :

```
We now have an automated changelog generated in the CHANGELOG.md file in the main repo. See it for more details.
```

**Comment by jreklund** [comment]
Thanks, but that dosen't describe how the codeigniter4/userguide repo got the files (4.0.1 and 4.0.2), but empty ones:. Can't find them in any other repo. https://github.com/codeigniter4/userguide/tree/master/docs/changelogs

If it have been removed from the userguide and moved to github. It should be referenced in the userguide.

**Comment by MGatner** [comment]
This is not intended to be set manually, but rather updated by the admin release scripts. See for example **admin/release** line 51. If someone wants to explore why those failed to update that would be helpful, but I'm also hopeful that our upcoming User Guide GitHub Action will be taking this over.

**Comment by samsonasik** [comment]
ok, closing it

**Pull request closed without merging**
