### PR TITLE
fix: debug toolbar vars response headers includes request headers

### PR DESCRIPTION
**Pull request by zl59503020**
update debug toolbar vars response header

**Description**
update debug toolbar vars response header no repeat request header

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
@zl59503020 Can you fix the coding style?

**Comment by kenjis** [comment]
Before:
Screenshot 2022-02-17 10 03 28

After:
Screenshot 2022-02-17 10 03 37

**Comment by zl59503020** [comment]
> @zl59503020你能修复编码风格吗？

ok

**Comment by kenjis** [comment]
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#php-style

**Review by kenjis — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @zl59503020

**Pull request merged**
