### PR TITLE
add app and app/Config to autoload composer.json for app starter

### PR DESCRIPTION
**Pull request by samsonasik**
The starter app is mostly installed via composer create-project. I think it is better to use composer autoload for it.

**Checklist:**
- [x] Securely signed commits

### CODE REVIEW

**Comment by paulbalandan** [comment]
I think we should exclude `App\` from here as we support custom namespace via `APP_NAMESPACE`.

**Comment by samsonasik** [comment]
That change may less happen, also, composer autoload doesn't break codeigniter 4 autoloader, that will be a fallback namespace.

**Comment by kenjis** [comment]
We cannot change `app` folder name. Because the composer's path overwrite the config in `Config\Autoload`.
https://forum.codeigniter.com/thread-81153.html

@samsonasik What's the benefit to use composer autoload?

**Comment by samsonasik** [comment]
As far as i remember, with prioritize composer autoload when possible, it will got benefit for composer itself (eg: classmap on `dump-autoload -o`).

Probably in case of changing `app` directory, documentation need to be updated to change `composer.json` as well.

**Comment by iRedds** [comment]
It's time to abandon the internal autoloader and use only the composer.

**Comment by kenjis** [comment]
@samsonasik Thank you. I'm not sure that composer's autoloader has priority. I'll check.

**Comment by kenjis** [comment]
@iRedds Do you mean the zip installation will be discontinued?

**Comment by lonnieezell** [comment]
One core tenet of CI  has always been the ability to download a zip and not worry about anything. From my experience on the forums since v4 has been released this is still the case for a large chunk of users.

We must always remember the broader user-base and CodeIgniter's history. While we don't want to be completely beholden to old ways, we do need to pay attention to the users, and not alienate a broad group of them for no discernible gain.

**Comment by paulbalandan** [comment]
This could have been avoided if we did not have the `autoload.psr4` section. I tried with `codeigniter4/codeigniter4` renaming **app/** to **myapp/**, and the only thing I need to change is the FCPATH in **spark** and **public/index.php**.

**Comment by iRedds** [comment]
@kenjis Do you need a zip installation?
@lonnieezell The CI history says use an array for configuration files.
Do you have zip download data to say that this is the majority?
For example, Composer generated 37,735 installs in the last 30 days, of which 1,311 were made today alone.
https://packagist.org/packages/codeigniter4/framework/stats#major/4

**Comment by kenjis** [comment]
@iRedds Personally I never use zip installation, but I don't say drop it soon.
CI is the last major framework that can be installed without Composer.
I think drop of the Zip installation should be carefully considered.

I see users using Zip who report GitHub issues sometime.

**Comment by iRedds** [comment]
@kenjis Composer.phar and the installed framework can be added to the zip.

**Comment by kenjis** [comment]
The path is from Composer, but 
it seems CI's autoloader loads `App\Controllers\Home`. CI 4.1.8 appstarter.

Screenshot 2022-01-29 18 33 58

**Comment by kenjis** [comment]
No, @samsonasik is correct.
If I run `composer dump-autoload -o`, `'App\\Controllers\\Home'` is included in Composer classmap file,
and CI4 autoloader use it.

**Comment by kenjis** [comment]
@iRedds 
> Composer.phar and the installed framework can be added to the zip.

I don't think it is good idea.
It forces users to use Composer without permission.

**Pull request merged**
