### PR TITLE
fix: Response::download() causes TypeError

### LINKED ISSUE #6358: Bug: Force File Download error in the latest version (4.2.3)
### PHP Version

7.4

### CodeIgniter4 Version

4.2.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

_No response_

### What happened?

when I executed `return $this->response->download('some.txt', 'some text', true)`
it return an error below.
```
TypeError

Argument 1 passed to CodeIgniter\CodeIgniter::displayPerformanceMetrics() must be of the type string, null given, 
called in D:\laragon\www\iprisinsi\vendor\codeigniter4\framework\system\CodeIgniter.php on line 500 
```

**SYSTEMPATH\CodeIgniter.php at line 740**
```
733 
734         return md5($name);
735     }
736 
737     /**
738      * Replaces the elapsed_time tag.
739      */
740     public function displayPerformanceMetrics(string $output): string
741     {
742         return str_replace('{elapsed_time}', (string) $this->totalTime, $output);
743     }
744 
745     /**
746      * Try to Route It - As it sounds like, works with the router to
747      * match a route against the current URI. If the route is a
```

actually I found this when 4.2.2 released 

### Steps to Reproduce

just run this code on home Controller
`return $this->response->download('some.txt', 'some text', true)`

### Expected Output

file `some.txt` downloaded

### Anything else?

since I m new to this I couldn't point what file to fix

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes  #6358

- never cache DownloadResponse/RedirectResponse
- add null check for $this->response->getBody()

**How to Test**
```php
<?php

namespace App\Controllers;

class Home extends BaseController
{
    public function index()
    {
        return $this->response->download('some.txt', 'some text', true);
    }
}
```

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by MGatner — APPROVED** [review]

**Comment by MGatner** [comment]
Should `RedirectResponse` be checked? Also, I think `null` is an acceptable body for some API responses - we might need to check or cast that.

**Review by MGatner — CHANGES_REQUESTED** [review]
_See previous comments._

**Comment by nicojmb** [comment]
Hi, same problem here, just tested[kenjis](https://github.com/kenjis) fix and works fine.

**Comment by kenjis** [comment]
Changed the implementation.

**Review by MGatner — APPROVED** [review]
Thank you!

**Comment by MGatner** [comment]
Any ideas how this made it through tests to release?

**Pull request merged**
