### PR TITLE
some optimization of CodeIgniter class

### PR DESCRIPTION
**Pull request by samsonasik**
- Add `\Config\App` type hint in constructor config parameter
- add `|null` to docblock to parameter function that allow null
- add `Cache` parameter to cache parameter in `gatherOutput()` and `handleRequest()` function
- remove unnecessary `$routes instanceof RouteCollectionInterface` check in `tryToRouteIt()` function as already has `RouteCollectionInterface` type hinted parameter. Null check is enough.
- apply unset `$override` variable after close if in `display404errors()` function.

**Checklist:**
- [x] Securely signed commits

### CODE REVIEW

**Comment by samsonasik** [comment]
travis build in php 7.3:postgres seems unrelated.

**Comment by samsonasik** [comment]
close-reopen to restart build.

**Comment by samsonasik** [comment]
travis build green 🎉

**Comment by samsonasik** [comment]
@MGatner merge-able? thank you

**Comment by MGatner** [comment]
Yes, looks good! Thank you for the mention - I'm overly busy right now and haven't been doing many reviews. 

Also thanks for the optimizations! I can tell you're focusing on "frequently used" components. There's a lot of refining to do overall but these will help collective performance and code cleanliness by a lot.

**Pull request merged**
