### PR TITLE
Fixes #2520 : ensure service(router)->controllername() returns fqcn

### LINKED ISSUE #2520: Bug: router service adds backslash to controllername if route is configured
**Describe the bug**
When a route isn't defined, the controllerName() function in service('router') returns an expected string like 'App\Controllers\{controllername}'. But when a route is defined in the routes.php it also returns an extra \ like '\App\Controllers\{controllername}'.

**CodeIgniter 4 version**
CodeIgniter 4 RC 3 zip version
CodeIgniter 4 Dev starter composer
CodeIgniter 4 App starter composer

**Affected module(s)**
Probably the router service

**Expected behavior, and steps to reproduce if appropriate**
Let the namespace define the route, and return the controller name using
`$router = service("router");
echo $router->controllerName();`
It should return the namespace of the controller with the name.

Now define the route in routes.php, and the same code will return an \ with the namespace of the controller with the controllername.

I expected them to be the same.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #2520 : ensure service(router)->controllername() returns fqcn

**Checklist:**
- [x] Securely signed commits
- [x] Unit testing, with >80% coverage

### CODE REVIEW

**Comment by samsonasik** [comment]
I've added unit test for it.

**Comment by samsonasik** [comment]
I've added `ltrim` check first to ensure clearance `\\` prefix before prepend with the `\\` prefix. I've added data provider in the unit test to test it.

**Comment by samsonasik** [comment]
I've added test for both autoroute and not autoroute to returns always fqcn.

**Comment by MGatner** [comment]
Awesome, I was going to ask about tests when I looked at it earlier! Looks great

**Comment by MGatner** [comment]
I can’t see tests results for this one - maybe an issue with the new GitHub mobile app? I’ll check it out on desktop in a bit.

**Comment by samsonasik** [comment]
rebased

**Comment by samsonasik** [comment]
@MGatner travis build green :tada:

**Pull request merged**
