### PR TITLE
[4.5] config: update env

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
- delete items that are not expected to change with the environment

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [] User guide updated
- [] Conforms to style guide

### CODE REVIEW

**Review by MGatner — APPROVED** [review]
This is great! Our **.env** files have gotten huge and I barely touch any of it - mostly add my own values at the bottom. 

Please acquire one other review on this one for a sanity check on what is actually likely to change. I personally have never set any of these deleted value.

**Review by neznaika0 — APPROVED** [review]
Yes. There seems to be too much information. I try to use ENV instead of editing Config. And I also add my own parameters

**Review by TimexPeachtree — APPROVED** [review]
Awesome 😎 making the file leaner is better

**Review by paulbalandan — APPROVED** [review]

**Comment by kenjis** [comment]
For some reason, this PR is incredibly popular!

**Pull request merged**
