### PR TITLE
Fix email & migrations docs; update changelog

### PR DESCRIPTION
**Pull request by jim-parry**
Correct user guide errors on migration & email pages.
Update changelog, getting ready for RC.1

### CODE REVIEW

**Comment by fefo-p** [comment]
Hello Jim,
I spotted this wrong assumption based on the comment above the variable

/*
	|--------------------------------------------------------------------------
	| Enable/Disable Migrations
	|--------------------------------------------------------------------------
	|
	| Migrations are **disabled** by default for security reasons.
	| You should enable migrations whenever you intend to do a schema migration
	| and disable it back when you're done.
	|
	*/
	public $enabled = **true**;

**Comment by jim-parry** [comment]
@lonnieezell @MGatner Contradictory user guide text pointed out. Which is correct - the text or the setting?

**Comment by MGatner** [comment]
Text is wrong - migrations are *enabled* by default. That was a change with lonnie's refactor and we probably just missed the comment, good catch by fefo-p

**Comment by jim-parry** [comment]
Fixed this with #2157

**Pull request merged**
