### PR TITLE
Use view files for generator commands

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
Use view stubs for the templates required by generator commands for future maintainability.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by michalsn** [comment]
I like this. 

What do you think about adding an array variable to the configuration file that would define the used views? This way making "small" changes to the generated files would become very simple. We would just "tell" the generator to use our view file.

**Comment by paulbalandan** [comment]
Okay, but in what config file will that be put.?

**Comment by michalsn** [comment]
I guess `Config/Migrations.php` would be the right place. But we would also have to hard-code the view names in our generator classes - for an easy upgrade path (fallback).

**Comment by paulbalandan** [comment]
OK. So I guess you mean that the user-configurable views are for the migrations and seeders only.

**Comment by michalsn** [comment]
Yeah... I just realized we don't have any config files related to commands. Maybe @MGatner will have an idea of how to handle this regarding an easy upgrade path? And maybe he will validate if this is a good idea in the first place :)

**Comment by MGatner** [comment]
I think this is great! Just to be clear on the Config file... something like the `$views` to property we use in Myth:Auth Config? https://github.com/lonnieezell/myth-auth/blob/develop/src/Config/Auth.php

`Generators` have grown a lot since their inception - I think it would be fine to make a new Config file for them, just so long as we have a fallback for when it is missing from **app/**.

**Comment by michalsn** [comment]
Yes, I was thinking exactly about the way Myth:Auth is doing it 😄

And yes, we need a fallback for the view name for every generator.

**Comment by MGatner** [comment]
My beef with the way Myth:Auth does it (with the disclaimer that I'm pretty sure I wrote that) is that there is no way to overwrite one view without supplying the whole array. Likewise, if a view were added down the road any existing extensions in **app/** would have to add that. I wonder if we can come up with a "smart" Config file that does some merging, kind of like Routes?

**Comment by paulbalandan** [comment]
My question is... should ALL the generators be given a configuration? My concern is the other generators have complicated code and have in-set text replacements in the templates.

**Comment by MGatner** [comment]
> should ALL the generators be given a configuration

Do you mean a configuration, or a view? I don't see a problem with treating Generators like a Controller: most of the time they will have a view, maybe a view with some variables passed in. But occasionally there is output to display that still makes sense to handle in the Controller.

**Comment by paulbalandan** [comment]
> > should ALL the generators be given a configuration
> 
> Do you mean a configuration, or a view? I don't see a problem with treating Generators like a Controller: most of the time they will have a view, maybe a view with some variables passed in. But occasionally there is output to display that still makes sense to handle in the Controller.

Yes, yes. I'm referring to views.

**Comment by MGatner** [comment]
This is looking good. Can we get an alias of `make:migration` to `migrate:create`? I guess just a new class that calls the other. 

Also is `{@inheritDoc}` a legit PHPDocs block?

**Review by MGatner — CHANGES_REQUESTED** [review]
*See comment*

**Comment by paulbalandan** [comment]
> This is looking good. Can we get an alias of `make:migration` to `migrate:create`? I guess just a new class that calls the other.

Are we leaning to deprecating use of `migrate:create` in favor of `make:migration`??

> Also is `{@inheritDoc}` a legit PHPDocs block?

Yes, it signals PHPDoc to copy the parent method's doc block into the inherited method.

**Comment by MGatner** [comment]
Nothing we've discussed officially but I think it makes sense for consistency to move toward the other. Maybe it would make sense to move the code and leave `migrate:create` as a deprecated alias. What do you think?

**Comment by paulbalandan** [comment]
Yes, thinking the same.

**Comment by michalsn** [comment]
As for `{@inheritDoc}` I believe that docblock is automatically inherited.
> Currently some applications have DocBlocks containing just the {@inheritDoc} inline tag to indicate that their complete contents should be inherited. This usage breaks with the PHPDoc Standard as summaries cannot contain inline tags and inheritance is automatic; you do not need to define a special tag for it.
However, it does make clear that an element has been explicitly documented (and thus not forgotten). As such we are working to include a new (normal) tag in the PHPDoc Standard @inheritDoc that will serve that purpose.

**Comment by paulbalandan** [comment]
> As for `{@inheritDoc}` I believe that docblock is automatically inherited.
> 
> > Currently some applications have DocBlocks containing just the {@inheritdoc} inline tag to indicate that their complete contents should be inherited. This usage breaks with the PHPDoc Standard as summaries cannot contain inline tags and inheritance is automatic; you do not need to define a special tag for it.
> > However, it does make clear that an element has been explicitly documented (and thus not forgotten). As such we are working to include a new (normal) tag in the PHPDoc Standard @inheritdoc that will serve that purpose.

However, our API generator complains.
> 
**Commands/Generators/CreateModel.php**
Type | Line | Description
-- | -- | --
error | 45 | No summary for class \CodeIgniter\Commands\Generators\CreateModel
error | 88 | No summary for method getClassName()
error | 100 | Argument $rootNamespace is missing from the Docblock of getNamespacedClass
error | 100 | Argument $class is missing from the Docblock of getNamespacedClass
error | 100 | No summary for method getNamespacedClass()
error | 105 | No summary for method getTemplate()
error | 119 | Argument $template is missing from the Docblock of setReplacements
error | 119 | Argument $class is missing from the Docblock of setReplacements
error | 119 | No summary for method setReplacements()

**Comment by michalsn** [comment]
Oh... okay - I didn't check to be honest. In that case, all is good.

This is documented very strangely in their website though.

**Review by MGatner — APPROVED** [review]
Very nice deprecation. Is this all set? Looks good to me.

**Comment by paulbalandan** [comment]
> Very nice deprecation. Is this all set? Looks good to me.

Feel free. 😁

**Pull request merged**
