### PR TITLE
Revert Actions minor versioning

### PR DESCRIPTION
**Pull request by MGatner**
Reverts codeigniter4/CodeIgniter4#4678

### CODE REVIEW

**Comment by paulbalandan** [comment]
Why was the two reverted?

**Comment by MGatner** [comment]
> Why was the two reverted?

What two?

**Comment by paulbalandan** [comment]
> > Why was the two reverted?
> 
> What two?

Nevermind. I saw your comment in the tagged PR.

**Review by paulbalandan — APPROVED** [review]

**Comment by MGatner** [comment]
FYI https://github.community/t/increase-if-necessary-for-github-actions-in-dependabot/179581

**Pull request merged**
