### PR TITLE
Use baseURL to calculate in fillRouteParams() and parseRequestURI()

### PR DESCRIPTION
**Pull request by eakkew**
**Description**
If we deploy ci4 into subfolder,, route function will be broker because path create and parse from relative path which is `/`

### CODE REVIEW

**Comment by MGatner** [comment]
You will need to namespace the App Config class. Preferable do this with a `use` statement at the top of the file, and the same for `URI` (instead of using the full namespace in the method).

**Comment by eakkew** [comment]
> You will need to namespace the App Config class. Preferable do this with a `use` statement at the top of the file, and the same for `URI` (instead of using the full namespace in the method).

fixed it at 683e18be1d6f8f39c1db8bd50c487e71daafa4b9

**Comment by MGatner** [comment]
You did not. You are using `App:class` from the Router namespace but that class does not exist. You need to add below line 18, so it looks like this:
```
use CodeIgniter\Router\Exceptions\RouterException;
use Config\App;
```

**Comment by paulbalandan** [comment]
With the import use statement fixed, it seems proposed changes will not work. Please open another PR if you can look into other options.

**Pull request closed without merging**
