### PR TITLE
fix: handle namespaced helper found on Common helper

### PR DESCRIPTION
**Pull request by samsonasik**
**Description**

Closes https://github.com/codeigniter4/CodeIgniter4/pull/9350

@yllumi this should handle https://github.com/codeigniter4/CodeIgniter4/pull/9350

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by samsonasik** [comment]
Ready to merge 👍 /cc @neznaika0

**Review by michalsn — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @michalsn for the review, let's merge 👍

**Comment by michalsn** [comment]
@samsonasik Oh... I forgot - we need a changelog entry 😅

**Comment by samsonasik** [comment]
@michalsn sure, here the PR for changelog:

- https://github.com/codeigniter4/CodeIgniter4/pull/9356

**Pull request merged**
