### PR TITLE
Connect function to throw correct Exception type

### PR DESCRIPTION
**Pull request by devorama**
**Description**
Connect function to throw correct exception type DatabaseException based on
function comment and design

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by devorama** [comment]
Litte confused how my code change could affect this test area PredisHandlerTest::testGetMetaData

prent

**Comment by michalsn** [comment]
@devorama Don't worry about `PredisHandlerTest`. It fails randomly sometimes (we probably need to take a look at this in near future).

**Comment by MGatner** [comment]
Test failure is unrelated. This looks good to me - I'd like to give it one more glance when I'm on desktop, unless somebody else beats me to it.

**Comment by devorama** [comment]
@MGatner and @michalsn  Thanks for the info and help

**Comment by samsonasik** [comment]
@devorama it seems the 1st commit always brought on your new pull request (`Merge pull request #1 from codeigniter4/develop` ), please always rebase by back to develop first before create new branch on new pull request to make show only commit related to the pull request.

**Comment by MGatner** [comment]
+1 for the rebase. `git pull --rebase`

**Comment by devorama** [comment]
> @devorama it seems the 1st commit always brought on your new pull request (`Merge pull request #1 from codeigniter4/develop` ), please always rebase by back to develop first before create new branch on new pull request to make show only commit related to the pull request.

@samsonasik  Hi there sorry I was trying previously via the browser to sync the fork as I could not get the client to work with 2 accounts, but I have it working now but only after I made 2 branches from it. I will from now on with the client do a rebase, sorry for that

**Comment by devorama** [comment]
Have rebased now for future branches
prent

**Comment by samsonasik** [comment]
I already wrote the step in other previous PR https://github.com/codeigniter4/CodeIgniter4/pull/3286#issuecomment-657182575 you just need to modify branch name and commit hash

**Comment by devorama** [comment]
Created a new for again.
The made sure it correct
prent

prent

prent


Will create new branch from this now

**Pull request closed without merging**
