### PR TITLE
 Fix broken caching system when array of allowed parameters used

### PR DESCRIPTION
**Pull request by JavaDeveloperKiev**
New clean PR of #6410 after rebase

Discussion available here:
https://github.com/codeigniter4/CodeIgniter4/pull/6410

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by JavaDeveloperKiev** [comment]
@kenjis can you please explain details or share link where I can read about _coveralls_, and why the test is failing. Did I do something wrong? 

Thanks!

**Comment by JavaDeveloperKiev** [comment]
> > Did I do something wrong?
> 
> No. I don't know why but coveralls reports _Coverage decreased_ often.

Okay, then I believe thats it :)

Let me know if I have to do some other fixes/changes

**Comment by ddevsr** [comment]
@JavaDeveloperKiev In report website, your PR increase coverage

https://coveralls.io/builds/52168240/source?filename=system%2FCodeIgniter.php

**Review by MGatner — APPROVED** [review]
Very nice PR! I'm sure we could clear the cache directly, but the use of stream filters and `command()` is very creative 😊

**Review by kenjis — APPROVED** [review]

**Comment by kenjis** [comment]
Thank you!

**Pull request merged**
