### PR TITLE
fix: `IncomingRequest::getJsonVar()` may cause TypeError

### LINKED ISSUE #5391: Bug: public function getJsonVar error in the code
### PHP Version

8.0

### CodeIgniter4 Version

4.1.2

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

_No response_

### What happened?

If "null" is sent to the server and when trying to get data through "Services :: request () -> getVar('myKey')", the error "Argument 2 passed to dot_array_search () must be of the type array..."

### Steps to Reproduce

I am sending a POST request without data

### Expected Output

Services :: request () -> getVar ('myKey') function should return "null"

### Anything else?

File: 
system/HTTP/IncomingRequest.php

`public function getJsonVar()`

 Line 540: `$data = dot_array_search($index, $this->getJSON(true));`

if `$this->getJSON(true)` returns null then an error appears

Solution:

```
$getJson = $this->getJSON(true) ?: [];
$data = dot_array_search($index, $getJson);
```

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #5391

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by iRedds** [comment]
JSON can contain null as a value. Therefore, I do not know if this way of solving the problem is correct.

**Comment by kenjis** [comment]
If the user input is `'null'`, `json_decode()` returns `null`.
`null` is not an array, so there is no value for a key.

**Comment by iRedds** [comment]
i mean
```php
// body: {"var" : null}
$request->getVar('var'); // null

// body: {}
$request->getVar('var'); // null

// body: null
$request->getVar('var'); // null
```
If we assume that the value "var" can be null, then the last two examples are incorrect behavior.
And it seems to me you need to throw an exception.

If we compare it with working with an array, then:

```php
$a = [];
$a['test'];
// Warning:  Undefined array key "test"

$a = null;
$a['test'];
// Warning:  Trying to access array offset on value of type null
```

**Comment by kenjis** [comment]
It depends on `getJsonVar()`'s specification.
It throws an exception or not.

If it should throw an exception, #5391 is not a bug.

**Review by MGatner — APPROVED** [review]

**Comment by samsonasik** [comment]
@kenjis could you verify PHPUnit error on develop branch?

**Comment by kenjis** [comment]
@samsonasik Do you mean this?
> PHP Fatal error:  Declaration of PhpCoveralls\Bundle\CoverallsBundle\Console\Application::getDefinition() must be compatible with Symfony\Component\Console\Application::getDefinition(): Symfony\Component\Console\Input\InputDefinition in /home/runner/.composer/vendor/php-coveralls/php-coveralls/src/Bundle/CoverallsBundle/Console/Application.php on line 44
https://github.com/codeigniter4/CodeIgniter4/runs/4376649089?check_suite_focus=true

It is an error of PhpCoveralls: https://github.com/php-coveralls/php-coveralls/issues/327

**Comment by samsonasik** [comment]
Yes, is there a way to pin to specific coveralls version that is working?

**Comment by kenjis** [comment]
Adding this to composer.json?
```
"symfony/console": "< 6.0",
```

**Comment by samsonasik** [comment]
Yes, that's probably the temporary fix 👍

**Comment by kenjis** [comment]
@samsonasik Okay, I will do it.

**Pull request merged**
