### PR TITLE
When running update return "true" not primary key of data

### PR DESCRIPTION
**Pull request by titounnes**
Each pull request should address a single issue, and have a meaningful title.

**Description**
Explain what you have changed, and why.

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

---------Remove from here down in your description----------

**Notes**
- Pull requests must be in English
- If the PR solves an issue, reference it with a suitable verb and the issue number
(e.g. fixes <hash>12345
- Unsolicited PRs will be considered, but there is no guarantee of acceptance
- Pull requests should be from a feature branch in the contributor's fork of the repository
  to the develop branch of the project repository

### CODE REVIEW

**Comment by nowackipawel** [comment]
Won't be cleaner to change:
`return $data->$this->primaryKey;`
to
`return $data->{$this->primaryKey}` in line 471?

Because you didn't give any details instead of PR title :) could you please write more details what this is about? How this will improve CI?

**Comment by titounnes** [comment]
thanks for the correction. you are right.

**Comment by lonnieezell** [comment]
Can you explain why you think this is needed? 

If you're doing an update you already know the primary key since you have to pass it in, so the only thing you're really interested in is whether it worked or not, right?

**Comment by titounnes** [comment]
the resulting feedback is more informative regarding the data involved. And it can be used to simplify when we need to change data in a table that has a relationship if needed.

**Comment by lonnieezell** [comment]
Sorry - I don't see how it simplifies anything since you've already got the data it returns. I'll pass on this one. Thanks. Look forward to other contributions, though!

**Pull request closed without merging**
