### PR TITLE
Fix view caching with directory separators

### LINKED ISSUE #3711: Bug: view caching not work on windows
The cache file does not creating when i don't set cache_name option 

i have see issue #2821 and i think it is the same issue

on windows and with CI 4.0.4

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
Fixes #3711 .

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by paulbalandan** [comment]
@paul45 can you verify if this fixes your issue?

**Comment by paul45** [comment]
Yes thx 
it works


in Cell.php the cache name is 
`$cacheName = ! empty($cacheName)
			? $cacheName
			: str_replace(['\\', '/'], '', $class) . $method . md5(serialize($params));`


maybe the dot will be removein view.php or add in Cell.php to standardize

**Comment by paulbalandan** [comment]
I replaced it with a dot so that cache name will still show the directory. Putting it in Cell.php is nice.

**Comment by michalsn** [comment]
Yes, we should keep the same convention everywhere.

**Review by MGatner — APPROVED** [review]

**Review by michalsn — APPROVED** [review]

**Pull request merged**
