### PR TITLE
Strive for stricter assertions

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
Since we're advocating for identity checks with `===` , we should do the same with testing.

Expecting this to be breaking the builds. 😂

**Checklist:**
- [x] Securely signed commits

### CODE REVIEW

**Comment by sfadschm** [comment]
This looks fun to debug 😆

**Comment by lonnieezell** [comment]
The fun part of this is that almost everything that comes from the database is a string, unless there is an associated entity that is casting it to something different. Which I'm pretty sure none of the database tests would do since PHP is a loosely typed language by default.

**Comment by sfadschm** [comment]
Sounds right, at least half of the failures I scrolled over where `string` vs `notString` stuff ^.^

**Comment by John-Betong** [comment]
> The fun part of this is that almost everything that comes from the database is a string, unless there is an associated entity that is casting it to something different. Which I'm pretty sure none of the database tests would do since PHP is a loosely typed language by default.

I believe PHP is trying to move away from the loose default setting and introduced **declare strict_types** which picks up these warnings and makes then into errors.

I have a function which adds the strict_type setting to every PHP System file and there are very few problems: Perhaps start adding the declaration to files which does no harm if everything is Hunky-Dory :)

https://ci4-strict.tk/

**Comment by MGatner** [comment]
@John-Betong thanks to static analysis we are mostly strict in the framework itself these days. The test cases are another matter. I think this PR is a worthy goal but unless someone wants it as a personal journey (maybe in need of some self-flagellation repentance? ☺️) I don't know that it is worth the time. 

@paulbalandan is there such a thing as differentiating rule sets for PRs versus the current code? It would be good to enforce this moving forward but that would let us leave things as they are (unless someone really wants to spend this time).

**Comment by paulbalandan** [comment]
I felt obligated to check on those errors as the PR opener, and I must say that while other errors are string checks the other errors are 🤦 - worthy.

**Comment by sfadschm** [comment]
Well that looks much better already 👏 


> 🤦 - worthy

was that the wrongly ordered array elements? 😆

**Comment by paulbalandan** [comment]
Nice to see green builds again. 🎉

**Comment by John-Betong** [comment]
> @John-Betong thanks to static analysis we are mostly strict in the framework itself these days. The test cases are another matter. I think this PR is a worthy goal but unless someone wants it as a personal journey (maybe in need of some self-flagellation repentance? ) I don't know that it is worth the time.
> 
I just downloaded the latest CI4 Github Build: 2025-06-27 - b856a65

Inserting declare(strict_types); into every system file and the following errors were encountered and fixed:

```
<dl>
<dt>#001 	<br>
	strlen(): Argument #1 ($str) must be of type string, int given 
</dt>
<dd>
	SYSTEMPATH/ThirdParty/Kint/Parser/TimestampPlugin.php at line 60
	<br><br>
	line #60 ==> $len = \strlen($var);
	<br><br>
	FIXED ==>  $len = \strlen( (string) $var);
</dd><dd> &nbsp; </dd>

<dt>#002<br>
	strlen(): Argument #1 ($str) must be of type string, null given 
</dt>
<dd>
	SYSTEMPATH/ThirdParty/Kint/Renderer/RichRenderer.php at line 330
	<br><br>
	line #330 ==> if (\strlen($result)) {
	<br><br>
	FIXED  ==> if (\strlen( (string) $result)) {
</dd><dd> &nbsp; </dd>

<dt>#003 <br>
	strlen(): Argument #1 ($str) must be of type string, null given 
</dt>
<dd>
	line #135 ==> if (\strlen($out)) {
	<br><br>
	FIXED ==> if (\strlen( (string) $out)) {
</dd><dd> &nbsp; </dd>

<dt>#004 <br>
	preg_replace(): Argument #3 ($subject) must be of type array|string, int given 
</dt>
<dd>
	SYSTEMPATH/ThirdParty/Kint/Renderer/RichRenderer.php at line 311
	<br><br>
	line #311 ==>  $s = \preg_replace('/\\s+/', ' ', $s);
	<br><br>
	FIXED ==> 
	</dd><dd> &nbsp; </dd>

	<dt>#005 <br>
		mb_detect_encoding(): Argument #1 ($string) must be of type string, int given 
	</dt>
	<dd>
		SYSTEMPATH/ThirdParty/Kint/Object/BlobObject.php at line 151
		<br><br>
		line #151 ==> if ($ret = \mb_detect_encoding( $string, self::$char_encodings, true)) {
		<br><br>
		FIXED ==> if ($ret = \mb_detect_encoding( ()string  $string, self::$char_encodings, true)) {
  </dd><dd> &nbsp; </dd>		

  <dt>#006 <br>
  	htmlspecialchars(): Argument #1 ($string) must be of type string, int given 
  </dt>
  <dd>
  	SYSTEMPATH/ThirdParty/Kint/Renderer/RichRenderer.php at line 502
  	<br><br>
  	line #502: ==> $string = \htmlspecialchars($string, ENT_NOQUOTES, $encoding);
  	<br><br>
  	FIXED ==> $string = \htmlspecialchars( (string) $string, ENT_NOQUOTES, $encoding);
  </dd><dd> &nbsp; </dd>

  <dt>#007 <br>
  	str_replace(): Argument #3 ($subject) must be of type array|string, bool given 
 	</dt> 	
 	<dd>
 		SYSTEMPATH/ThirdParty/Kint/Kint.php at line 680
 		<br><br>
 		line # 680 ==> return \str_replace(
 			array('%f', '%l'), 
 			array($file, $line), 
 			self::$file_link_format
 		);
 		<br><br>
 		FIXED ==> return \str_replace(
 			array('%f', '%l'), 
 			array($file, $line), 
 			(string) self::$file_link_format
 		);
 	</dd><dd> &nbsp; </dd>

 	<dt>#008 <br>
 		Uncaught TypeError: strtolower(): Argument #1 ($string) must be of type string, null given  
 	</dt>
 	<dd>
 		in /var/www/ci4-strict.tk/system/Validation/FormatRules.php:313
 		<br><br>
 		line # 313 ==> switch (strtolower($which)) {
 		<br><br>
 		FIXED ==> switch (strtolower( (string) $which)) {
 	</dd><dd> &nbsp; </dd>

 	<dt>#009 <br>
 		Uncaught TypeError: filter_var(): Argument #3 ($options) must be of type array|int, null given 
 	</dt>
 	<dd>
 		in /var/www/ci4-strict.tk/system/Validation/FormatRules.php:327 
 		<br><br>
 		line #327 ==> switch (strtolower( $which)) {
 		<br><br>
 		Fixed ==> switch (strtolower( (string) $which)) {
	</dd><dd> &nbsp; </dd> 		

	<dt>
		Uncaught TypeError: filter_var(): Argument #3 ($options) must be of type array|int, null given   
	</dt>
	<dd>	
		in /var/www/ci4-strict.tk/system/Validation/FormatRules.php:327
		<br><br>
    line #327 ==> return (bool) filter_var(
    	$ip, 
    	FILTER_VALIDATE_IP, 
    	$which
    ) 
    	|| 
    (
    	! ctype_print($ip) && (bool) filter_var(inet_ntop($ip), FILTER_VALIDATE_IP, 
    	$which
    ));
	<br><br>
 		FIXED ==> return (bool) filter_var(
    	$ip, 
    	FILTER_VALIDATE_IP, 
    	(array) $which
    ) 
    	|| 
    (
    	! ctype_print($ip) && (bool) filter_var(inet_ntop($ip), FILTER_VALIDATE_IP, 
    	$which
    ));
		</dd><dd> &nbsp; </dd> 		
</dl>

```

I did notice that Kint uses a declare strict but only on about four files.


  [**Uploaded changes:**](https://ci4-strict.tk)

**Comment by MGatner** [comment]
Most of that is in **ThirdParty** which is *not* part of the framework; it is code from other libraries we supply, unmodified, for non-Composer users. Your formatting is unreadable on mobile but it looks like a couple of issues in Validation. As I believe you've been told dozens of times: if you would propose your changes in Pull Requests the team would gladly review them, though CodeIgniter 4 is still not intending to be `strict`. 

This conversation has derailed - please start a new Issue or PR if you would like to discuss more so we can get back to the test assertions.

**Comment by paulbalandan** [comment]
@MGatner is this good for merge or I need to do something more?

**Review by MGatner — APPROVED** [review]
Good!

**Comment by paulbalandan** [comment]
Thanks!

**Pull request merged**
