### PR TITLE
refactor: `command()` in Common function

### PR DESCRIPTION
**Pull request by ddevsr**
**Description**
Improvement.

***Benchmark***
```bash
Test 		Time 	Memory
command_new() 	11.8162 	2 MB
command() 	12.5120 	0 Bytes
```
```php
<?php

namespace App\Controllers;

use CodeIgniter\Debug\Iterator;

class Home extends BaseController
{
    public function index(): string
    {
        $iterator = new Iterator();

        $iterator->add('command_new()', static function () {
            for ($i = 0; $i <= 10; $i++) {
                command_new('env');
            }
        });

        $iterator->add('command()', static function () {
            for ($i=0; $i <= 10; $i++) {
                command('env');
            }
        });


        return $iterator->run(40000);
    }
}
```

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by ddevsr** [comment]
Latest in 427f2a6a

**Comment by kenjis** [comment]
Benchmarking on macOS shows things are getting very slow.
Why?

```
Test 		Time 	Memory
command_new() 	0.0203 	0 Bytes
command() 	0.0004 	0 Bytes
```

```php
<?php

namespace App\Controllers;

use CodeIgniter\Debug\Iterator;

class Home extends BaseController
{
    public function index(): string
    {
        $iterator = new Iterator();

        $iterator->add('command_new()', static function () {
            command_new('env');
        });

        $iterator->add('command()', static function () {
            command('env');
        });

        return $iterator->run(10);
    }
}
```

**Comment by ddevsr** [comment]
I have already benchmark on 2 PC windows, new better then old.

@kenjis What a result when run more iterator?

**Comment by paulbalandan** [comment]
Running on macOS with M2, shows similar results with @kenjis 

```php
<?php

namespace App\Controllers;

use CodeIgniter\Debug\Iterator;

class Home extends BaseController
{
    public function index(): string
    {
        $iterator = new Iterator();

        $iterator->add('command_new()', static function () {
            command_new('env');
        });

        $iterator->add('command()', static function () {
            command('env');
        });


        return $iterator->run(40000);
    }
}
```

1. On 10 runs:
```
Test	        Time	Memory
command_new()	0.0059	0 Bytes
command()	0.0002	0 Bytes
```

2. On 1,000 runs:
```
Test       	Time	Memory
command_new()	0.0275	0 Bytes
command()	0.0169	0 Bytes
```

4. On 2,000 runs:
```
Test	        Time	Memory
command_new()	0.0432	0 Bytes
command()	0.0331	0 Bytes
```

5. On 4,000 runs:
```
Test	        Time	Memory
command_new()	0.0750	0 Bytes
command()	0.0666	0 Bytes
```

7. On 40,000 runs:
```
Test        	Time	Memory
command_new()	0.6287	0 Bytes
command()	0.6578	0 Bytes
```

I removed the for loop inside the closure as the iterator itself loops the closure already.

**Comment by paulbalandan** [comment]
Running with the loop inside the closure:
```php
<?php

namespace App\Controllers;

use CodeIgniter\Debug\Iterator;

class Home extends BaseController
{
    public function index(): string
    {
        $outputs = [];
        $template = 'On %s runs:<br/>';

        foreach ([10, 1000, 2000, 4000, 40000] as $run) {
            $outputs[] = sprintf($template, number_format($run));

            $iterator = new Iterator();
            $iterator->add('command_new()', static function () {
                for ($i = 0; $i <= 10; $i++) {
                    command_new('env');
                }
            });
            $iterator->add('command()', static function () {
                for ($i = 0; $i <= 10; $i++) {
                    command('env');
                }
            });

            $outputs[] = $iterator->run($run);
            $outputs[] = '<br/>';
        }

        return implode("\n", $outputs);
    }
}
```

On 10 runs:
<table>
    <thead>
        <tr>
            <td>Test</td>
            <td>Time</td>
            <td>Memory</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>command_new()</td>
            <td>0.0176</td>
            <td>0 Bytes</td>
        </tr>
        <tr>
            <td>command()</td>
            <td>0.0020</td>
            <td>0 Bytes</td>
        </tr>
    </tbody>
</table>
<br/>
<br/>

On 1,000 runs:
<table>
    <thead>
        <tr>
            <td>Test</td>
            <td>Time</td>
            <td>Memory</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>command_new()</td>
            <td>0.1605</td>
            <td>0 Bytes</td>
        </tr>
        <tr>
            <td>command()</td>
            <td>0.1714</td>
            <td>0 Bytes</td>
        </tr>
    </tbody>
</table>
<br/>
<br/>

On 2,000 runs:
<table>
    <thead>
        <tr>
            <td>Test</td>
            <td>Time</td>
            <td>Memory</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>command_new()</td>
            <td>0.3197</td>
            <td>0 Bytes</td>
        </tr>
        <tr>
            <td>command()</td>
            <td>0.3409</td>
            <td>0 Bytes</td>
        </tr>
    </tbody>
</table>
<br/>
<br/>

On 4,000 runs:
<table>
    <thead>
        <tr>
            <td>Test</td>
            <td>Time</td>
            <td>Memory</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>command_new()</td>
            <td>0.6282</td>
            <td>0 Bytes</td>
        </tr>
        <tr>
            <td>command()</td>
            <td>0.6774</td>
            <td>0 Bytes</td>
        </tr>
    </tbody>
</table>
<br/>
<br/>

On 40,000 runs:
<table>
    <thead>
        <tr>
            <td>Test</td>
            <td>Time</td>
            <td>Memory</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>command_new()</td>
            <td>6.2965</td>
            <td>0 Bytes</td>
        </tr>
        <tr>
            <td>command()</td>
            <td>6.7474</td>
            <td>0 Bytes</td>
        </tr>
    </tbody>
</table>
<br/>

**Comment by kenjis** [comment]
When the iteration is very small, command() is much, much faster. Why?

**Comment by kenjis** [comment]
If I quit almost all applications except terminal, and disables Xdebug.

<table>
			<thead>
				<tr>
					<td>Test</td>
					<td>Time</td>
					<td>Memory</td>
				</tr>
			</thead>
			<tbody>
				<tr>
				<td>command_new()</td>
				<td>0.0045</td>
				<td>0 Bytes</td>
			</tr><tr>
				<td>command()</td>
				<td>0.0040</td>
				<td>0 Bytes</td>
			</tr>
			</tbody>
		</table>

But if I am running Firefox and PhpStrom, the values sometime differ a lot like:
<table>
			<thead>
				<tr>
					<td>Test</td>
					<td>Time</td>
					<td>Memory</td>
				</tr>
			</thead>
			<tbody>
				<tr>
				<td>command_new()</td>
				<td>0.0059</td>
				<td>0 Bytes</td>
			</tr><tr>
				<td>command()</td>
				<td>0.0293</td>
				<td>0 Bytes</td>
			</tr>
			</tbody>
		</table>

```php
<?php

namespace App\Controllers;

use CodeIgniter\Debug\Iterator;

class Home extends BaseController
{
    public function index(): string
    {
        $iterator = new Iterator();

        $iterator->add('command_new()', static function () {
        });

        $iterator->add('command()', static function () {
        });

        return $iterator->run(40000);
    }
}
```

**Comment by kenjis** [comment]
However, such micro-optimization would have little or no effect on performance improvement in the real world.

I cannot assume that command() will be executed many times in a request.

**Comment by kenjis** [comment]
> [!IMPORTANT]
> We expect all code changes or bug-fixes to be accompanied by one or more tests
> added to our test suite to prove the code works.

This PR does not have the necessary test code. If you want this PR to be reviewed, please add the test code.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#unit-testing

If the test is not added, this PR will be closed.

**Pull request closed without merging**
