### PR TITLE
fix: workaround for Faker deprecation errors in PHP 8.2

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
See #6170 

Suppress the following error in PHP 8.2.
This error prevents our app and library developments to support 8.2. See https://github.com/codeigniter4/CodeIgniter4/pull/6172#issuecomment-1288302674

```
1) CodeIgniter\Test\FabricatorTest::testMakeArrayReturnsArray
ErrorException: Use of "static" in callables is deprecated

/Users/kenji/work/codeigniter/official/CodeIgniter4/vendor/fakerphp/faker/src/Faker/Provider/Base.php:374
/Users/kenji/work/codeigniter/official/CodeIgniter4/vendor/fakerphp/faker/src/Faker/Provider/Base.php:432
/Users/kenji/work/codeigniter/official/CodeIgniter4/vendor/fakerphp/faker/src/Faker/Provider/Base.php:449
/Users/kenji/work/codeigniter/official/CodeIgniter4/vendor/fakerphp/faker/src/Faker/Provider/Internet.php:118
/Users/kenji/work/codeigniter/official/CodeIgniter4/vendor/fakerphp/faker/src/Faker/Generator.php:696
/Users/kenji/work/codeigniter/official/CodeIgniter4/vendor/fakerphp/faker/src/Faker/Generator.php:744
/Users/kenji/work/codeigniter/official/CodeIgniter4/vendor/fakerphp/faker/src/Faker/Generator.php:747
/Users/kenji/work/codeigniter/official/CodeIgniter4/vendor/fakerphp/faker/src/Faker/Provider/Internet.php:51
/Users/kenji/work/codeigniter/official/CodeIgniter4/vendor/fakerphp/faker/src/Faker/Generator.php:696
/Users/kenji/work/codeigniter/official/CodeIgniter4/vendor/fakerphp/faker/src/Faker/Generator.php:952
/Users/kenji/work/codeigniter/official/CodeIgniter4/system/Test/Fabricator.php:377
/Users/kenji/work/codeigniter/official/CodeIgniter4/tests/system/Test/FabricatorTest.php:254
```

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
The Faker deprecated magic property access error never shows in CI4 testing.
Because  the `trigger_error()` is using `@`:
```php
    function trigger_deprecation(string $package, string $version, string $message, ...$args): void
    {
        @trigger_error(($package || $version ? "Since $package $version: " : '').($args ? vsprintf($message, $args) : $message), \E_USER_DEPRECATED);
    }
```

`@` makes the `error_reporting()` 0 in PHP 7.4:
https://github.com/codeigniter4/CodeIgniter4/blob/e0779d7fb4da487c98c3dcbbf5344c917dca5311/system/Debug/Exceptions.php#L152-L159

In PHP 8, the `error_reporting()` will be 4437. See https://bugs.php.net/bug.php?id=80548
So `E_USER_DEPRECATED` error is also not shown.

**Comment by kenjis** [comment]
```diff
--- a/system/Debug/Exceptions.php
+++ b/system/Debug/Exceptions.php
@@ -151,7 +151,7 @@ class Exceptions
      */
     public function errorHandler(int $severity, string $message, ?string $file = null, ?int $line = null)
     {
-        if (error_reporting() & $severity) {
+        if (E_ALL & $severity) {
             throw new ErrorException($message, 0, $severity, $file, $line);
         }
 
```
```console
$ ./phpunit tests/system/Test/FabricatorTest.php
PHPUnit 9.5.25 #StandWithUkraine

Runtime:       PHP 8.1.11
Configuration: /Users/kenji/work/codeigniter/official/CodeIgniter4/phpunit.xml

.........E...........EEEEEEEEEEEEEEEE..........                   47 / 47 (100%)

Time: 00:00.625, Memory: 18.00 MB

There were 17 errors:

1) CodeIgniter\Test\FabricatorTest::testGetFakerReturnsUsableGenerator
ErrorException: Since fakerphp/faker 1.14: Accessing property "randomDigit" is deprecated, use "randomDigit()" instead.

/Users/kenji/work/codeigniter/official/CodeIgniter4/vendor/symfony/deprecation-contracts/function.php:25
/Users/kenji/work/codeigniter/official/CodeIgniter4/vendor/fakerphp/faker/src/Faker/Generator.php:950
/Users/kenji/work/codeigniter/official/CodeIgniter4/tests/system/Test/FabricatorTest.php:123

...

ERRORS!
Tests: 47, Assertions: 32, Errors: 17.
```

**Comment by kenjis** [comment]
> Another case against this: it might hide errors that people would actually like to see. This is, after all, what deprecations are for.

I changed to limit only the error `Use of "static" in callables is deprecated`.
Also, the error is now output to the log.

**Review by MGatner — APPROVED** [review]
Thanks for making it specific. I'm okay with this under the banner of "workaround to support 8.2", since it is actually just a deprecation upstream. Let's be sure to pull this whenever Faker updates.

**Review by samsonasik — APPROVED** [review]

**Pull request merged**
