### PR TITLE
Fix for current_url() global method not returning index.php part.

### PR DESCRIPTION
**Pull request by npwsamarasinghe**
This PR address this issue: #4116

### CODE REVIEW

**Review by MGatner — COMMENTED** [review]
If `current_url()` is supposed to be equivalent to `site_url(uri_string())` wouldn't it be easier and more consistent to reflect that in the code? I already see a fair amount of duplicate between `site_url()` and your new version of `current_url()`.

**Comment by MGatner** [comment]
Actually looking at your test failures it appears this was the intended behavior. I'm not saying I agree with it, but if the tests and the User Guide both agree that `current_url()` should *not* include the index page it is going to be harder to justify changing.

**Comment by npwsamarasinghe** [comment]
Actually `site_url(uri_string())` is _not_ 100% identical. `current_url()` is support for _full_ version of _current url_. For example, we can pass `boolean true` to this method and it will return _current url_ with the _query string_. Also with this method we can easily access the URI object if we need. So this method is very flexible than `site_url(uri_string())`. And I agree docs should be more descriptive about this.

I think this should not be the default behaviour. This method should respect the `indexPage` configuration. This change should not introduce any issues and Its just only adding `indexPage` to the urls.

CI3 also has this method and its returning urls with the `index.php` part.
[https://codeigniter.com/userguide3/helpers/url_helper.html#current_url](https://codeigniter.com/userguide3/helpers/url_helper.html#current_url)

I highly appreciate if someone can explain how this should not be the default behaviour of this method?

Thanks.

**Comment by michalsn** [comment]
This is definitely a BC. The best we can do now is to add a separate method that will do what you want.

The reason behind this is simple - we can't be sure how users were using this helper. And this was working this way (along with documentation) from the initial release. In the worst-case scenario adding `index.php` to the result string will break someone's code. I can imagine people using this function to dynamically link images for example.

**Comment by MGatner** [comment]
> I highly appreciate if someone can explain how this should not be the default behaviour of this method?

It isn't a matter of "should" but of what is already in place. See @michalsn 's comment above. IMO just make a new function (I proposed `this_url()` but anything appropriate) and build it off `site_url()` to reduce code repetition.

**Pull request closed without merging**
