### PR TITLE
2373 Update kint-php version to 3.3

### PR DESCRIPTION
**Pull request by musmanikram**
Update kint version to 3.3 #2373

**Description**
Update package dependency version for kint-php/kint from 2.1 to 3.3

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by lonnieezell** [comment]
Unfortunately, there's much more to it than this. While your fix works fine for composer-based installs, it will fail completely for those that want to simply download a release and not use composer. 

For those, the post-install script has to be modified to copy the files into the appropriate place, and then everything has to work smoothly. I had attempted this at one point and ran into issues there, as described in the issue you referenced. Haven't had an opportunity to get back to it just yet.

**Comment by musmanikram** [comment]
> Unfortunately, there's much more to it than this. While your fix works fine for composer-based installs, it will fail completely for those that want to simply download a release and not use composer.
> 
> For those, the post-install script has to be modified to copy the files into the appropriate place, and then everything has to work smoothly. I had attempted this at one point and ran into issues there, as described in the issue you referenced. Haven't had an opportunity to get back to it just yet.

I will try to fix zip issue. But is it very important to give support for zip download? I mean we can enforce to use only composer. Otherwise, we have to support both and will face these issues in future,

**Comment by lonnieezell** [comment]
> But is it very important to give support for zip download?

Yes. That is the CodeIgniter legacy. And, at least with v4, we are keeping the ability to download and go, just like we're keeping the ability to auto-route based on the URL. These are things that helped make CI what it is, and we are trying to make an improved version of an existing framework, not creating a brand new framework, so we do have to keep the feel where possible, and the things many many have loved about it, whether or not we all want to use that style of programming.

**Comment by musmanikram** [comment]
> > But is it very important to give support for zip download?
> 
> Yes. That is the CodeIgniter legacy. And, at least with v4, we are keeping the ability to download and go, just like we're keeping the ability to auto-route based on the URL. These are things that helped make CI what it is, and we are trying to make an improved version of an existing framework, not creating a brand new framework, so we do have to keep the feel where possible, and the things many many have loved about it, whether or not we all want to use that style of programming.

ahh that make sense. I will try to spend some time it.

**Comment by musmanikram** [comment]
I noticed it's a bit tricky now. I am closing this PR and we can see this issue in future

**Pull request closed without merging**
