### PR TITLE
test: add tests for required_without

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
To confirm the current behavior.

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by MGatner — APPROVED** [review]
I'm not saying yet whether I agree or not with the other PR but it is good to have tests for existing behavior.

**Comment by kenjis** [comment]
> required_without
The field is required when all of the other fields are present in the data but not required.
https://codeigniter4.github.io/CodeIgniter4/libraries/validation.html#available-rules

It seems the explanation in the user guide is not correct, or I can't get it.
Is it correct?

How about this?
> The field is required when any of the other fields do not pass `required` checks.

**Review by michalsn — APPROVED** [review]
> The field is required when any of the other fields do not pass required checks.

Sounds correct. The user guide description is very unfortunate.

**Comment by MGatner** [comment]
Yes yours is much better.

**Pull request merged**
