### PR TITLE
Add PHP 8.2 to Unit Tests GHA

### PR DESCRIPTION
**Pull request by paulbalandan**
See #6170

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
There are too many dynamic properties!

> There were 889 errors:
https://github.com/codeigniter4/CodeIgniter4/runs/6996511004?check_suite_focus=true

**Comment by samsonasik** [comment]
Rector can be used to transform  AllowDynamicProperties if needed

https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#addallowdynamicpropertiesattributerector

**Comment by kenjis** [comment]
I think `#[AllowDynamicProperties]` should be used as little as possible.

**Comment by paulbalandan** [comment]
Or maybe this is better: https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#completedynamicpropertiesrector

**Comment by kenjis** [comment]
Yes, probably `CompleteDynamicPropertiesRector` can fix most of the errors.

**Review by MGatner — APPROVED** [review]
Wow we passed! Very nice. How about adding to the PHPStan Action as well so we can catch deprecations?

**Comment by MGatner** [comment]
Oh haha we didn't pass at all 🤦‍♂️ Result was ignored. Digging through these now...

**Comment by MGatner** [comment]
Okay this isn't so bad. Lots of the same culprits over and over. Some specifics...

1. I think we need to allow dynamics on `BaseConfig` (I assume that will extend t child classes?) to keep Registrars working. Maybe there is an alternative where we create some special `__set()` method and mark it private/internal for Registrars only or something? But I don't see a way around Config needing dynamic properties. 
2. Anything in **tests/** I'm happy to have Rector allow or add, since they are pretty much all just mocks. 
3. Predis looks like it isn't our handler that is the issue, but maybe I'm reading that wrong?
4. Image handlers need some digging but I think that's a pretty easy fix
5. Everything else should be considered for Rector adding, but I don't like the idea of generating a ton of public properties throughout the code, so they are probably worth examining case by case. 

This is a good opportunity to improve code quality/smells - I wish we already had some dynamic property rules in place beforehand!

**Comment by kenjis** [comment]
> I think we need to allow dynamics on BaseConfig (I assume that will extend t child classes?) to keep Registrars working. Maybe there is an alternative where we create some special __set() method and mark it private/internal for Registrars only or something? But I don't see a way around Config needing dynamic properties.

I don't know why Configs (or Registrars) need dynamic properties.
What is wrong with just overriding existing properties?
When properties are added dynamically, it is not possible to see all the properties by looking at the class definition.

**Comment by MGatner** [comment]
Maybe `BaseConfig` is overkill but there might be some (like our `Validation` discussion, or `Database`) that merit dynamic properties. Any Config that a module a) needs to expand but b) needs to allow `App` to override.

**Comment by kenjis** [comment]
> Maybe BaseConfig is overkill but there might be some (like our Validation discussion, or Database) that merit dynamic properties. Any Config that a module a) needs to expand but b) needs to allow App to override.

I'm not convinced. In the Shield validation case, it seems property overriding is enough.
I don't know why a user needs to use Registrar. It seems good just to add the validation rules in `\Config\Validation` class.

**Comment by MGatner** [comment]
I just went through all the Config files and I think the two I mentioned (`Database` and `Validation`) are the only ones that function in a way that I think would benefit from dynamic properties. The classes that drive these use properties dynamically (e.g. a database connection is formed from the properties that match a database group) so the only way a module can add additional functionality to those classes is to define a corresponding property. The alternative is to specify that the developer add them manually during setup, which isn't the worst, but it adds a layer to module integration that tends to deter people.

**Comment by kenjis** [comment]
I don't understand the need to add dynamic properties to Database config.
Third party module adds another database connection config? For what?

Like Validation config, I don't understand the need for it at all.
Does anyone else use the feature? Any use case?

**Comment by MGatner** [comment]
I'm fine skipping it and then revisiting if the need arises. I certainly have never needed it before. My opinion was based on how these Config files work, which is different than other files.

**Comment by kenjis** [comment]
About 200 errors were reduced.

> There were 660 errors:
https://github.com/codeigniter4/CodeIgniter4/runs/7096495359?check_suite_focus=true

**Comment by MGatner** [comment]
The vfsStream issue has been fixed but not released (https://github.com/bovigo/vfsStream/commit/49283282eba373c14552d57c8b17247f48acf543). I'm not sure about Predis, that one still surprises me.

**Comment by MGatner** [comment]
Predis constructor straight up sets it's own property that doesn't exist 🤦‍♂️

https://github.com/predis/predis/blob/main/src/Connection/Parameters.php

**Comment by paulbalandan** [comment]
> Predis constructor straight up sets it's own property that doesn't exist 🤦‍♂️
> 
> https://github.com/predis/predis/blob/main/src/Connection/Parameters.php

Patched in `main`.

**Comment by MGatner** [comment]
By our very own @paulbalandan! https://github.com/predis/predis/pull/781

Thanks Paul; glad to see their quick response too.

**Comment by MGatner** [comment]
Since the 8.2 tests are exempt should we go ahead and merge this? It would make tracking the errors easier instead of rebasing this branch over and over.

**Review by MGatner — APPROVED** [review]

**Comment by kenjis** [comment]
But there are still 133 errors.

**Comment by MGatner** [comment]
> But there are still 133 errors.

Right but because of this line:
```yaml
        continue-on-error: ${{ matrix.php-versions == '8.2' }} # remove when PHP 8.2 is generally available
```
The errors won't cause the pipeline to fail, so they are only there as information if you open up the job logs. Merging this PR will let us keep an eye on those errors, since many of them are issues upstream that we cannot control. It will also let us send PRs to fix those errors that will actually run the GitHub Actions (beneficial for me since I don't have an 8.2 environment yet).

**Comment by kenjis** [comment]
> Merging this PR will let us keep an eye on those errors

I doubt it. 
If I make an error in my PR, I probably can't find the error out of more than 100 errors.
I hope less errors, ideally 0, at least less than 10.

**Comment by MGatner** [comment]
But those errors will only show on the PHPUnit 8.2 Action logs. You should be able to look at all the regular pipeline checks to discern your code impact, then the 8.2 run will be optionally available for future information. 

Unless I misunderstood something you were saying?

**Comment by kenjis** [comment]
I don't want to increase GA resource consumption by adding checks that almost no one sees. 
It will also make the checks take even longer.

**Review by MGatner — APPROVED** [review]
Yay, we passed! Thanks for sticking with this @paulbalandan

**Comment by kenjis** [comment]
Wow, greatly improved! 

> Tests: 5251, Assertions: 8657, Errors: 70, Failures: 28, Skipped: 14.

**Comment by MGatner** [comment]
Predis just posted a release! https://github.com/predis/predis/compare/v2.0.0...v2.0.1

It includes Paul's fix for the dynamic property warning. Closing and reopening to run again...

**Comment by kenjis** [comment]
> Tests: 5286, Assertions: 8699, Errors: 70, Failures: 28, Skipped: 14.

No changes?

```
1) CodeIgniter\Cache\Handlers\PredisHandlerTest::testNew
ErrorException: Use of "static" in callables is deprecated

/home/runner/work/CodeIgniter4/CodeIgniter4/vendor/predis/predis/src/Command/Processor/KeyPrefixProcessor.php:200
/home/runner/work/CodeIgniter4/CodeIgniter4/vendor/predis/predis/src/Command/Factory.php:76
/home/runner/work/CodeIgniter4/CodeIgniter4/vendor/predis/predis/src/Client.php:308
/home/runner/work/CodeIgniter4/CodeIgniter4/vendor/predis/predis/src/Client.php:299
/home/runner/work/CodeIgniter4/CodeIgniter4/system/Cache/Handlers/PredisHandler.php:144
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Cache/Handlers/PredisHandlerTest.php:49
```

**Comment by MGatner** [comment]
The error has changed, even though the count hasn't 🤦‍♂️ Looks like Predis is failing to deal with 8.2 properly.

**Comment by MGatner** [comment]
Some Predis movement:
* https://github.com/predis/predis/pull/796
* https://github.com/predis/predis/pull/797

Looking good.

**Comment by MGatner** [comment]
Predis 2.0.2 released to fix the "static in callables" issue! Rerunning...

**Comment by kenjis** [comment]
>  Tests: 5296, Assertions: 8749, Errors: 56, Failures: 28, Skipped: 14.

The number of errors has decreased.

**Comment by MGatner** [comment]
```console
CodeIgniter\Validation\StrictRules\FormatRulesTest::testValidDate with data set #27 ('Monday 8th of August 2005 03:12:46 PM', 'l jS \of F Y h:i:s A', true)
731
Failed asserting that false is identical to true.
```
The failures are all in format validation. 🤨 Unexpected! It's hard to dig on mobile: could this be related to the `!` style changes?

**Comment by paulbalandan** [comment]
The `!` changes are not yet in, and it's PHP 8.2 specific. Maybe a bug in PHP?

**Comment by MGatner** [comment]
Good point! Maybe try again next RC, before digging into it?

**Comment by MGatner** [comment]
Now it's Faker issues 🤦‍♂️
> Use of "static" in callables is deprecated

**Comment by MGatner** [comment]
> Creation of dynamic property CodeIgniter\HTTP\IncomingRequest::$csp is deprecated

I did t see these before but we now have a few errors for tests creating dynamic properties. Faker still an issue.

**Comment by kenjis** [comment]
> I did t see these before but we now have a few errors for tests creating dynamic properties.

I sent PRs to fix  creating dynamic properties.

**Comment by kenjis** [comment]
It seems `DateTime::getLastErrors()` returns `false` since PHP 8.2.
https://3v4l.org/eACZZ

**Comment by MGatner** [comment]
Wow, that's a big change to slip in. Especially it appears to be unannounced: https://php.watch/versions/8.2

**Comment by kenjis** [comment]
It seems Faker will not fix the deprecation soon:
https://github.com/FakerPHP/Faker/issues/479

**Comment by MGatner** [comment]
It seems that the deprecations a caused by an older structure of Faker factories; we may be able to identify those and replace them with different faked content (if you look at Chris' linked PR s/he did the same).

**Comment by paulbalandan** [comment]
I used a temporary patch for Faker's troubled file. https://github.com/codeigniter4/CodeIgniter4/pull/6172/commits/7976a073bfc500cb7464a3d2d15512150d86cafe

**Comment by kenjis** [comment]
> Tests: 5368, Assertions: 8917, Errors: 14, Skipped: 14.

The last error is `mb_convert_encoding()`. #6672

> 1) CodeIgniter\HTTP\ContentSecurityPolicyTest::testBodyScriptNonceDisableAutoNonce
ErrorException: mb_convert_encoding(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead

**Comment by kenjis** [comment]
@paulbalandan Applying patch on GA is not enough.
All users tests would still fail.
Why don't you send a PR to Faker?

**Comment by paulbalandan** [comment]
I have never used Faker so I'm not confident my patch will cover all edge cases for faker tests.

I'm not sure what you mean by "all users tests". If that would mean all consumers of Faker aside from us, then that is the least of my concern. Faker itself should provide the official patch. As I said, this addition is just a temporary hack.

**Comment by kenjis** [comment]
I mean all CI4 devs that use Faker.

**Comment by MGatner** [comment]
I'm fine with this to pass the framework. We don't actually offer any deprecated Faker usage directly: the Generator is available to users and may or may not be called. I am fine with this workaround (also: very cool use of `git apply`!) and maybe some notes in the User Guide if this is still an issue when 8.2 comes out.

**Comment by kenjis** [comment]
This is the test result of Shield. Most of the errors caused by Faker.

```console
bash-3.2$ composer test
> phpunit
PHPUnit 9.5.25 #StandWithUkraine

Runtime:       PHP 8.2.0-dev
Configuration: /Users/kenji/work/codeigniter/official/codeigniter-shield/phpunit.xml
Random Seed:   1666576446

.................................................E....E.E......  63 / 251 ( 25%)
E.E.EE...E.........EE...EEE..............EE.............E.E...E 126 / 251 ( 50%)
...EE.E..E......E.E......................E.E.....E.....EE.E...E 189 / 251 ( 75%)
...........EE..........EE.E....................E..EEE.E.EEE...  251 / 251 (100%)

Time: 00:10.122, Memory: 38.00 MB

There were 44 errors:
```

**Comment by kenjis** [comment]
```
7) CodeIgniter\Database\Live\GetTest::testGetRowWithCustomReturnType
ErrorException: Creation of dynamic property class@anonymous::$id is deprecated

/Users/kenji/work/codeigniter/official/CodeIgniter4/system/Database/SQLite3/Result.php:143
/Users/kenji/work/codeigniter/official/CodeIgniter4/system/Database/SQLite3/Result.php:147
/Users/kenji/work/codeigniter/official/CodeIgniter4/system/Database/BaseResult.php:149
/Users/kenji/work/codeigniter/official/CodeIgniter4/system/Database/BaseResult.php:286
/Users/kenji/work/codeigniter/official/CodeIgniter4/system/Database/BaseResult.php:273
/Users/kenji/work/codeigniter/official/CodeIgniter4/tests/system/Database/Live/GetTest.php:234
```

**Comment by kenjis** [comment]
I merged #6757
So all error should be gone.

**Comment by MGatner** [comment]
Looks like one more dynamic property issue in each of the driver-specific Result classes. E.g.: /home/runner/work/CodeIgniter4/CodeIgniter4/system/Database/OCI8/Result.php:109

**Comment by martinemily3** [comment]
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

https://uphold_lginuiil.godaddysites.com/
--
https://upholddxy_login.godaddysites.com/
https://uphold-usa_login3.godaddysites.com/
https://bloc-fe-logg-in1.godaddysites.com/
https://blckkfe_loginnu3.godaddysites.com/
https://blokifiloginn35.godaddysites.com/
https://ronin-loginn2.godaddysites.com/
https://roninsignino1.knorish.com/
https://rooninloginu.bravesites.com/
https://kucoin-logii_n.godaddysites.com/
https://kucoin_loggin1.godaddysites.com/
https://robuikhook_loginx.godaddysites.com/
https://robnhood_loginx.godaddysites.com/
https://rabiuhoadlogin1.godaddysites.com/
https://robinihood_loginn.godaddysites.com/
https://rooninohood-logg_in3.godaddysites.com/
https://roobin-hudlog-in.godaddysites.com/
https://kukoinnlogg-in1.godaddysites.com/
https://phantom_login6.godaddysites.com/
https://lunologinn.godaddysites.com/
https://upholdsign.knorish.com/
https://exodus_login3.godaddysites.com/
https://luno_login48.godaddysites.com/
https://krakenlogin6.godaddysites.com
https://geminlogin5.godaddysites.com
https://phantom.bravesites.com/
https://lunologinn20.godaddysites.com
https://krakensign.knorish.com/
https://exoduswalletlogin83.godaddysites.com
https://lunosignin.knorish.com/
https://phantomwallet3.godaddysites.com/
https://krakenwalletsignin.godaddysites.com
https://exoduslogin0.godaddysites.com/
https://phantomlogin.godaddysites.com
https://lunowalletlogin5.godaddysites.com
https://krakenloginn46.godaddysites.com
https://geminloginn.godaddysites.com/
https://phantomwallet39.godaddysites.com

**Review by MGatner — APPROVED** [review]
Yay! We did it!

**Comment by MGatner** [comment]
Side note: scrolling through these test results over and over with all the "skips"... maybe we should tag database-specific tests as their own suites and run them per driver?

**Review by kenjis — APPROVED** [review]

**Comment by paulbalandan** [comment]
🚀

**Comment by kenjis** [comment]
I didn't know but it seems `@runInSeparateProcess` (or `@preserveGlobalState`?) tests need XDebug.

```
There were 52 skipped tests:

...

2) CodeIgniter\CommonFunctionsSendTest::testRedirectResponseCookiesSent
XDebug not found.

/home/runner/work/CodeIgniter4/CodeIgniter4/system/Test/CIUnitTestCase.php:407
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/CommonFunctionsSendTest.php:60

3) CodeIgniter\HTTP\ContentSecurityPolicyTest::testExistence
XDebug not found.

/home/runner/work/CodeIgniter4/CodeIgniter4/system/Test/CIUnitTestCase.php:407
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/HTTP/ContentSecurityPolicyTest.php:71

4) CodeIgniter\HTTP\ContentSecurityPolicyTest::testReportOnly
XDebug not found.

/home/runner/work/CodeIgniter4/CodeIgniter4/system/Test/CIUnitTestCase.php:407
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/HTTP/ContentSecurityPolicyTest.php:84

5) CodeIgniter\HTTP\ContentSecurityPolicyTest::testDefaults
XDebug not found.

/home/runner/work/CodeIgniter4/CodeIgniter4/system/Test/CIUnitTestCase.php:531

...

OK, but incomplete, skipped, or risky tests!
Tests: 5372, Assertions: 8876, Skipped: 52.
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/3368104698/jobs/5586268619

**Comment by MGatner** [comment]
That's odd. Also: why don't we have Xdebug available? I thought setup-php added it

**Pull request merged**
