### PR TITLE
Add multi column primary key in model

### PR DESCRIPTION
**Pull request by rakoitde**
**Description**
Codeigniter4 currently only supports one column of primary keys. In some cases, however, it is helpful to be able to use a primary key with several columns.
Known issue "Compound primary-key not supported" #1991

**Usage**
`class myModel extends Model`
`{`
`	protected $table      = 'myTable';`
`	protected $primaryKey = [ 'first_id' , 'second_id' ];`
...

`$mymodel->find(['1','1']);`
`$mymodel->delete(['first_id' => '1', 'second_id' => '1']);`

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
We cannot change the type on `$primaryKey` without introducing breaking changes. What you could probably do is introduce an alternate model (like "CompoundKeyModel") which was an extension of `Model` with these changes. I'm not sure if proliferating Models is something we would want core to the framework or not, but since you've written the code might as well.

**Comment by nowackipawel** [comment]
I added some code to #1991  I am using it and there are no BC.

**Comment by MGatner** [comment]
@nowackipawel `Model` has since split out `BaseModel` so your code will need some adjustments.

The bigger issue around breaking changes is not whether the modified code works, but whether it will break existing use of the class. For example, I develop `Tatter\Relations` which automates table joins based off Models. Pretend I knew nothing about this PR, now this line in my code becomes a syntax error (https://github.com/tattersoftware/codeigniter4-relations/blob/d033806af70e3eade9baf89ac4ea5c5995b92d59/src/Traits/ModelTrait.php#L276):
```
$ids = array_column($rows, $this->primaryKey);
```

In order to make breaking changes like this we either need to make a major release (version 5), deprecate the current behavior and "phase in" the new (version 4.1+), or find a way to work around it (like my `CompoundModel` example).

**Comment by nowackipawel** [comment]
@MGatner  please check #4120. It seams that it is working in every test case ;-) this could be a good starting point.

**Comment by MGatner** [comment]
I replied to the PR, but basically: it is a good implementation but it is still a breaking change. You will either need to find a way to make a separate class or some way to work with `$primaryKey` as a string (like explode a special character or something).

**Comment by rakoitde** [comment]
Thanks for the evaluation of the PR and suggested solutions.

**Comment by MGatner** [comment]
Yes I think that is a solution. I wonder if we should have some bigger picture conversations about Model in general? I already get confused frequently between BaseModel and Model - maybe there is a way we can do this better in a dedicated namespace?

**Comment by lonnieezell** [comment]
Yes, I think we need to be careful here. The database layer is already complex enough, maybe even more complex than needed currently.

**Comment by najdanovicivan** [comment]
I'm not sure what you mean by model being very complex. The BaseModel is very important for me as I relay on it to use Models/Entities with custom DB drivers for ElasticSearch and MongoDB. The Class naming may not be optimal but so far I only see the benefits having DB layer separated form everything else in the model.

I'll start working on putting up the CompositeModel class. We can decide on actual class naming later on. It should be very similar with the Model class. I'll make this one extend the BaseModel directly so it's completely independent  from the current Model class.  Will work on it today and submit a PR.

**Pull request closed without merging**
