### PR TITLE
fix: Session cookies are sent twice with Ajax

### LINKED ISSUE #6166: Bug: Session cookies are sent twice with Ajax
v4.2.0

- Session cookies are sent twice when regenerating session
- The old session cookie is sent after new session cookie

See https://github.com/codeigniter4/CodeIgniter4/pull/5656#issuecomment-1159801065

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #6166

**How to Test**
See https://github.com/codeigniter4/CodeIgniter4/issues/6166#issuecomment-1161381092

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by samsonasik — APPROVED** [review]

**Review by MGatner — APPROVED** [review]
Very odd that we have a mix of mutability and immutability within the same class. This fix looks good though!

**Comment by skuadron45** [comment]
i already tested this PR, see comment at #6166

**Comment by skuadron45** [comment]
> Special thanks also to @skuadron45 for the extensive testing and reporting!

your welcome @MGatner

**Comment by kenjis** [comment]
> Very odd that we have a mix of mutability and immutability within the same class. 

Yes, and it is difficult to remove a cookie in Response.

**Pull request merged**
