### PR TITLE
fix: table name is double prefixed when LIKE clause

### LINKED ISSUE #5775: Bug: table has double prefix when LIKE clause
### PHP Version

7.3

### CodeIgniter4 Version

4.1.9 + dev

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli

### Database

_No response_

### What happened?

see https://forum.codeigniter.com/thread-81454.html

### Steps to Reproduce

```php
// database.default.DBPrefix = db_

db_connect()->table('test')->like('test.field', 'string')->getCompiledSelect();

// SELECT * FROM `db_test` WHERE `db_``db_test`.`field` LIKE '%string%' ESCAPE '!' 

```

### Expected Output

```
SELECT * FROM `db_test` WHERE `db_test`.`field` LIKE '%string%' ESCAPE '!' 
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #5775

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by iRedds** [comment]
Double escaping when using the LIKE clause.
https://github.com/codeigniter4/CodeIgniter4/blob/f969513ddedf14409bede320a1ff2f34434b9dc0/system/Database/BaseBuilder.php#L1054

https://github.com/codeigniter4/CodeIgniter4/blob/f969513ddedf14409bede320a1ff2f34434b9dc0/system/Database/BaseBuilder.php#L2452

Does it make sense?

**Comment by kenjis** [comment]
It is from #5170.
We might have made a mistake.
We need to reconsider.

**Comment by kenjis** [comment]
Removed double escape.

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @kenjis

**Pull request merged**
