### PR TITLE
This is to allow changing SQLSRV schema from dbo to any other.

### PR DESCRIPTION
**Pull request by hdrodriguez**
Each pull request should address a single issue and have a meaningful title.

**Description**
Explain what you have changed, and why.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

This change in getFullName function allows defining different schemas in the table parameter of the models, example "adm.tablename" or sales.users etc.

### CODE REVIEW

**Comment by paulbalandan** [comment]
Please add some tests to this.

**Comment by hdrodriguez** [comment]
Added test

**Comment by MGatner** [comment]
This also needs to be pointed at `4.2` branch.

**Comment by lonnieezell** [comment]
> @lonnieezell it looks like you pointed this to 4.2 then back?

@MGatner yes, was hoping I could just change the branch and merge, but it needs a rebase as dozens of other commits showed up when pointed to that branch.

**Review by michalsn — CHANGES_REQUESTED** [review]
Sorry, but I personally can't give the green light. We've already had at least one attempt on this topic (#4955) and it was "blocked" simply because this type of functionality should be implemented in all database drivers that can support it.

**Comment by MGatner** [comment]
Is there some special reason SQLSRV needs this and other drivers do not? I defer to @michalsn on these matters, so unless there is some counter-justification we will close this.

**Comment by qury** [comment]
I guess this is just for convenience to be able to create cross-schema queries using the query builder instead of using raw SQL.
Other than this i do not see any reason for this.

**Comment by michalsn** [comment]
@MGatner This is just a feature that makes changing schema more convenient (dynamic). We always can change the schema, but we need to use more code. 

This can probably be useful in some cases, but again - this must be implemented for all drivers that support schemas: SQLSRV and Postgre. The code in the database layer is not perfect and I don't want to create more mess. At some point, we will have to think about rewriting the code and that is one more reason why we should keep the features we offer in some "shape".

**Comment by hdrodriguez** [comment]
I honestly do not understand why you do not accept the request, I am sure that this can help thousands of people to solve their problems when working with the SQLSRV driver, I do not know if you have seen that the getFullName method only exists in the SQLSRV builder it does not exist an interface that commits the BaseBuilder to implement the getFullName method, I understand that there must be an order to do things, but many of us take the time to contribute and help improve the framework, as it was proposed in #4955

**Comment by michalsn** [comment]
> I honestly do not understand why you do not accept the request, I am sure that this can help thousands of people to solve their problems when working with the SQLSRV driver, 

I don't know if there are thousands or just ten people waiting for this. It doesn't really matter. The point is that this new functionality should be implemented for all drivers that may support it. Nothing less, nothing more.

> I do not know if you have seen that the getFullName method only exists in the SQLSRV builder it does not exist an interface that commits the BaseBuilder to implement the getFullName method

Yes, I am aware of that. However, this is not a reason to not implement this functionality for other drivers.

> I understand that there must be an order to do things, but many of us take the time to contribute and help improve the framework

We always appreciate every developer who takes his time to contribute to the framework. However it doesn't mean we will accept every pull request. I say it from the beginning, in other PR too - this functionality has to be supported for all database drivers that can handle it.

**Comment by paulbalandan** [comment]
Thanks for the PR! Since there has been no activity since the requested changes, I believe there's no more interest here. Closing.

**Pull request closed without merging**
