### PR TITLE
Create database command

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
Supersedes and closes #3695 . 

Added special handling for SQLite3 connections.

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by paulbalandan** [comment]
I don't know why it went wrong for postgres.

**Comment by michalsn** [comment]
Seem like a general issue with `createDatabase()`. The produced query should be like: `CREATE DATABASE "user"`. The escape character should be applied around the database name.

**Comment by michalsn** [comment]
You know what... forget my last comment. It doesn't work because `user` is a restricted word in PostgreSQL. Change the database name for something else and we should be good.

**Comment by paulbalandan** [comment]
> You know what... forget my last comment. It doesn't work because `user` is a restricted word in PostgreSQL. Change the database name for something else and we should be good.

Okay. Didn't know that. Changing. Thanks.

**Comment by paulbalandan** [comment]
Off-topic to this PR but related to database creation.

It took me a long time pondering why SQLite's Forge didn't create databases using `createDatabase` without going throughout the code. Why was it set to return `true` instead of throwing a `DatabaseException`?

I mean in the parent `Forge` there's a check if the db creation is disabled for the driver by setting the `createDatabaseStr` to `false`. So sqlite's createDatabase can be something like:
```php
	public function createDatabase(string $dbName, bool $ifNotExists = false): bool
	{
		$this->createDatabaseStr = false;

		return parent::createDatabase($dbName, $ifNotExists);
	}
```

**Comment by michalsn** [comment]
Regarding SQLite, I can't tell really. Your idea seems good to me though.

**Review by michalsn — APPROVED** [review]

**Pull request merged**
