### PR TITLE
refactor: Apply code quality level 31 for rector

### PR DESCRIPTION
**Pull request by samsonasik**
**Description**

Applied `ThrowWithPreviousExceptionRector` so when throwing into a catch block, checks that the previous exception is passed to the new throw clause

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by samsonasik** [comment]
Ready to merge 👍

**Review by paulbalandan — COMMENTED** [review]
What is the issue with `compact()` that this change brings?

**Comment by samsonasik** [comment]
That's easier to verify that the variable exists and used after defined.

**Comment by neznaika0** [comment]
I purposely used compact() to compress the string...

**Review by neznaika0 — APPROVED** [review]

**Comment by paulbalandan** [comment]
It seems both approach emits a warning when the variable is defined. Difference only is that `compact` does not give the array key of the undefined variable while the array approach includes the key but with `null` value instead: https://3v4l.org/pHACp#v8.4.1

I'm not sure which way we want to go, but personally I use `compact` for its conciseness.

**Comment by michalsn** [comment]
Personally, I have nothing against using `compact()`. It is easy to understand when reviewing the code.

**Comment by samsonasik** [comment]
Ok, I will skip it. We can continue increase level with skip this rule.

**Comment by samsonasik** [comment]
I skipped `CompactToVariablesRector` https://github.com/codeigniter4/CodeIgniter4/pull/9303/commits/37e63299f5c39d99f990c3ad984d3aaab59f17d2 , then apply level 31 that apply change with `ThrowWithPreviousExceptionRector` https://github.com/codeigniter4/CodeIgniter4/pull/9303/commits/608b869a20c1848c51e2325ad82fa4a96391336e

**Comment by samsonasik** [comment]
Ready to merge 👍

**Review by neznaika0 — APPROVED** [review]
Go next level)

**Review by paulbalandan — APPROVED** [review]

**Comment by samsonasik** [comment]
Thanks all for the review, let's merge 👍

**Pull request merged**
