### PR TITLE
Entity exception for non existed props.

### PR DESCRIPTION
**Pull request by nowackipawel**
As for now if code calls non existed property of entity causing ErrorException with no info at all.
This PR is changing ErrorException to EntityException with translated information like this:
"Trying to access non existent property fle_amount_fromss of App\Entities\Fee\FeeLevel"

### CODE REVIEW

**Comment by lonnieezell** [comment]
You're right it's better than current, but that doesn't mean it's the right long-term solution. :)

Still waiting to hear @jim-parry thoughts.

**Comment by jim-parry** [comment]
I favor the idea of declaring entity properties explicitly, and thus support this PR.

**Comment by lonnieezell** [comment]
The part I'm concerned about is when you have a join, and select some fields from the other table. That property was not explicitly set on the object, but was implicitly defined through the query result, though I suppose it would still pass muster as existing at the time someone tried to get a property? It's late and I'm not honestly sure of that answer. Will have to investigate later.

**Comment by jim-parry** [comment]
Hmmm. If you are planning that an entity be the result of a join, would you not then be able to "predict" that it should have a specific property? I haven't used the Entity class, and don't have a good feel for what would work best :-/

**Comment by nowackipawel** [comment]
If entity is a result of joint it will contain all the own properties + new
ones from join. Properties from join are public and should not produce that
exception.

**Comment by lonnieezell** [comment]
@nowackipawel Now that my brain is a little clearer and less tired - you're right. I'm good with this then. 

> If you are planning that an entity be the result of a join, would you not then be able to "predict" that it should have a specific property?

sometimes, but not always since the entity will be used in different situations that might require different sets of data joined in, sometimes only for a single call.

**Pull request merged**
