### PR TITLE
docs: allow boolean values in the model for PHPStan

### PR DESCRIPTION
**Pull request by ping-yee**
**Description**
See #9197 

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by neznaika0** [comment]
> Ignored error pattern ...
requires removal from **phpstan-baseline.php**

**Review by michalsn — APPROVED** [review]

**Comment by michalsn** [comment]
@datamweb Will this solve the whole issue, or not?

**Comment by datamweb** [comment]
@michalsn In my opinion, it’s better to write a unit test for this, as I can’t practically verify the issue for all drivers. However, this can be handled through GitHub Actions to ensure proper verification.

**Comment by michalsn** [comment]
@datamweb I was under the impression that it was just a problem of setting allowed data types for PHPStan, which now treated booleans as an error.

We already have tests for boolean values: https://github.com/codeigniter4/CodeIgniter4/blob/develop/tests/system/Database/Live/UpdateTest.php#L363

**Review by datamweb — APPROVED** [review]
@michalsn, thank you so much for sharing the tests. 🙏 Also, the tests for PR #6348 are available as well.

@ping-yee , please edit the PR description and change **See #9197** to **fix #9197**. Thanks! 😊

**Pull request merged**
