### PR TITLE
test - replace only last operator in field name.

### PR DESCRIPTION
**Pull request by nowackipawel**
want to know what tests this will break.

If all tests will pass I will write what is better in this approach.

### CODE REVIEW

**Comment by lonnieezell** [comment]
You know - `composer install` is all it takes to get PHPUnit up and running on your local machine, right?

**Comment by nowackipawel** [comment]
Thank you for letting me know :).

**Comment by nowackipawel** [comment]
So my PR allows us to make sth like:
`(new \ExampleModel)->where('(SELECT COUNT(*) FROM t1 WHERE t1_exa_id = ex_id)',10);`
or its variants like:
`(new \ExampleModel)->where('(SELECT COUNT(*) FROM t1 WHERE t1_exa_id = ex_id) >= ',10);`
`(new \ExampleModel)->where('(SELECT COUNT(*) FROM t1 WHERE t1_exa_id = ex_id)',10);`

what was impossible before.

**Comment by nowackipawel** [comment]
will update code when my solution will work on sth like this:
```
(new \ExampleModel)
->startGroup()
->where('(SELECT COUNT(*) FROM t1 WHERE t1_exa_id = ex_id)','')
->orWhere('(SELECT COUNT(*) FROM t1 WHERE t1_exa_id = ex_id) IS NULL', NULL, false)
->endGroup()

->startGroup()
->where('field_1','')
->orWhere('field_1 IS NULL', NULL, false)
->endGroup()
;
```

**Pull request merged**
