### PR TITLE
chore: use phpstan-codeigniter

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
Add phpstan-codeigniter

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by paulbalandan** [comment]
@samsonasik is there a way to tell rector to read the `GeneratedConfig` of `phpstan/extension-installer`? Or do I need to write all extensions' configs in `$rectorConfig->phpstanConfigs()`?

**Comment by samsonasik** [comment]
@paulbalandan we had it automatically, but removed due to possible magic use cases on auto include, the :

```php
$rectorConfig->phpstanConfigs(...);
```

seems the way to go.

**Review by kenjis — APPROVED** [review]
Looks good!

**Comment by kenjis** [comment]
@paulbalandan Thank you!

**Pull request merged**
