### PR TITLE
fix: revert method name changed accidentally

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
From https://forum.codeigniter.com/showthread.php?tid=86096&pid=405141#pid405141

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by sclubricants** [comment]
This must of got mixed up with new method setQueryAsData(). Not sure how it got changed.

**Review by michalsn — APPROVED** [review]

**Comment by sclubricants** [comment]
Perhaps we need a test for this method? It must not have any coverage..

**Comment by kenjis** [comment]
Added a test.

**Review by sclubricants — APPROVED** [review]

**Comment by kenjis** [comment]
PHPStan error is not related to this PR.

```
Error: Ignored error pattern #^Variable \$data might not be defined\.$# in path /home/runner/work/CodeIgniter4/CodeIgniter4/system/Cache/Handlers/MemcachedHandler.php was not matched in reported errors.
 ------ ----------------------------------------------------------------------- 
  Line   system/Cache/Handlers/MemcachedHandler.php                             
 ------ ----------------------------------------------------------------------- 
         Ignored error pattern #^Variable \$data might not be defined\.$# in    
         path                                                                   
         /home/runner/work/CodeIgniter4/CodeIgniter4/system/Cache/Handlers/Mem  
         cachedHandler.php was not matched in reported errors.                  
 ------ ----------------------------------------------------------------------- 
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/3897874756/jobs/6656007175

**Pull request merged**
