### PR TITLE
Fix variable variable `$$id` in RedisHandler

### PR DESCRIPTION
**Pull request by Terrorboy**
**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by paulbalandan** [comment]
@Terrorboy I know what the fix is about, but can you tell us what is the problem you encountered because of this?

**Comment by Terrorboy** [comment]
I'm going out, so I'm attaching a screenshot I'm keeping.

**Review by paulbalandan — APPROVED** [review]
Looking at git blame, it seems I accidentally used variable variables when making the handlers compatible with SessionHandlerInterface.

**Comment by paulbalandan** [comment]
Thank you, @Terrorboy

**Comment by Terrorboy** [comment]
@paulbalandan When does `codeigniter4codeigniter4/framework` apply?

**Comment by paulbalandan** [comment]
Not sure when it can be released. For the meantime you can use the development version, or manually update the fix in your installation while waiting for next release.

**Comment by Terrorboy** [comment]
All right.

**Pull request merged**
