### PR TITLE
style: run php-cs-fixer v3.13.1

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
- run php-cs-fixer

See https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6590

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by michalsn** [comment]
I'm not a big fan 
* it makes the code less readable in many cases 
* it's not very natural for me to write code this way (it will probably be popping up frequently)

However, I'm not sure what others think. If the majority is on board, then let it be.

Also not sure there is an easy alternative to avoid this.

**Comment by kenjis** [comment]
To be honest, I'm also not a fan of this.

But the change is a bug fix of php-cs-fixer.
I don't know we can avoid this easily.

**Comment by kenjis** [comment]
I created an issue: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6716

**Comment by MGatner** [comment]
I think we hold off on this until we see what comes of kenjis' request.

**Pull request closed without merging**
