### PR TITLE
docs: change TOC depth 2 or more

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
- change TOC depth 2 or more

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [x] User guide updated
- [] Conforms to style guide

### CODE REVIEW

**Review by MGatner — COMMENTED** [review]
What is the end result of this? Standardizing the amount and type of content shown in the table of contents for each doc?

**Comment by kenjis** [comment]
> Standardizing the amount and type of content shown in the table of contents for each doc?

Yes.

I think 2 is appropriate as the standard depth.

**Review by MGatner — APPROVED** [review]
I'm good with this! Maybe check for one more review since this is more of an opinion preference.

**Comment by paulbalandan** [comment]
Can you give a visual tree of what this look like after merge? Just a screenshot of the TOC would be enough.

**Comment by kenjis** [comment]
@paulbalandan If the page has 2nd level header, it will be added in the TOC.
If not, nothing will change.

Before:
Screenshot 2021-12-23 8 55 04

After:
Screenshot 2021-12-23 8 55 00

**Review by paulbalandan — APPROVED** [review]

**Comment by MGatner** [comment]
Looks great.

**Pull request merged**
