### PR TITLE
Modified Model::doUpdate allowing arrays in $this->primaryKey for composite table keys

### PR DESCRIPTION
**Pull request by jbrahy**
I have tables with composite keys and needed the CI Model to work with it so I modified the Model to allow for values similar to this `$this-primaryKey = array('column1','column2').` 

I'm also pushing a separate update for doInsert.

### CODE REVIEW

**Comment by jbrahy** [comment]
adding the code for doInsert.

**Comment by jbrahy** [comment]
I'll change the code if anyone reviews this and lets me know the CI4 way to handle it.

**Comment by kenjis** [comment]
Thank you for sending PR.

First of all, please read the guide:
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/README.md
especially:
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md

> We expect all contributions to conform to our [style guide](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/styleguide.md), be commented (inside the PHP source files), be documented (in the [user guide](https://codeigniter4.github.io/userguide/)), and unit tested (in the [test folder](https://github.com/codeigniter4/CodeIgniter4/tree/develop/tests)).

> Note, we expect all code changes or bug-fixes to be accompanied by one or more tests added to our test suite to prove the code works. If pull requests are not accompanied by relevant tests, they will likely be closed. Since we are a team of volunteers, we don't have any more time to work on the framework than you do. Please make it as painless for your contributions to be included as possible. If you need help with getting tests running on your local machines, ask for help on the forums. We would be happy to help out.

Please fix the coding style:
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#php-style
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#static-analysis-on-php-code
And please add unit testing:
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#unit-testing

And you forgot the signing:
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/signing.md

**Comment by sfadschm** [comment]
There were multiple approaches for composite keys, e. g. :
#4120
#4115

Please see why they failed and make sure your approach tackles the issues that occured.

**Comment by jbrahy** [comment]
Thanks for the feedback, I'll check these out and get back to you.

**Comment by paulbalandan** [comment]
Closing for no activity in months.

**Pull request closed without merging**
