### PR TITLE
passing $primaryKey to entity toRawArray() + save() improvements

### PR DESCRIPTION
**Pull request by nowackipawel**
Fixing: #1770 
save() will try to insert() instead of update() in some cases [$data is instance of Entity].
i think this is fixing another issue with inserting entities with non-autoincrement primaryKeys - then save() tried to produce update()
we will see what kind of test this will break :D

### CODE REVIEW

**Comment by nowackipawel** [comment]
tests
```
UPDATE_TEST getting tes_id primaryKey - 144 -> 1
{"tes_id":"144","tes_txt":null,"tes_json":null,"tes_created_at":null,"tes_updated_at":null}
YES UPDATE `t_test` SET `tes_id` = 1
WHERE `t_test`.`tes_id` = '144'
VALIDATION ERRORS: 
UPDATE_TEST getting tes_id, tes_json - CHANGE json_col - X -> random one element long array
{"tes_id":"1","tes_txt":null,"tes_json":"[343]","tes_created_at":null,"tes_updated_at":null}
YES UPDATE `t_test` SET `tes_json` = '[343]', `tes_id` = 1
WHERE `t_test`.`tes_id` = '1'
VALIDATION ERRORS: 
UPDATE_TEST getting tes_id, tes_json - CHANGE json_col - X -> random one element long array, tes_txt -> random text
{"tes_id":"1","tes_txt":"ABC1551430367.506","tes_json":"[80]","tes_created_at":null,"tes_updated_at":null}
YES UPDATE `t_test` SET `tes_txt` = 'ABC1551430367.506', `tes_json` = '[80]', `tes_id` = 1
WHERE `t_test`.`tes_id` = '1'
VALIDATION ERRORS: 
UPDATE_TEST getting tes_id primaryKey - 1 -> 144, tes_txt -> random text
{"tes_id":144,"tes_txt":"ABC1551430367.527","tes_json":null,"tes_created_at":null,"tes_updated_at":null}
YES UPDATE `t_test` SET `tes_id` = 144, `tes_txt` = 'ABC1551430367.527'
WHERE `t_test`.`tes_id` = '1'
VALIDATION ERRORS: 
INSERT_TEST tes_id + tes_txt
{"tes_id":53,"tes_txt":"1110.54658200 1551430367","tes_json":null,"tes_created_at":null,"tes_updated_at":null}
53 INSERT INTO `t_test` (`tes_id`, `tes_txt`) VALUES (53, '1110.54658200 1551430367')
VALIDATION ERRORS: 
INSERT_TEST tes_id + tes_txt
{"tes_id":141,"tes_txt":null,"tes_json":null,"tes_created_at":null,"tes_updated_at":null}
141 INSERT INTO `t_test` (`tes_id`) VALUES (141)
VALIDATION ERRORS: 
```

**Comment by nowackipawel** [comment]
@lonnieezell , @jim-parry :
Could you please tell my why my PRs breaking the tests for sqlite?

- testSelectAndEntitiesSaveOnlyChangedValues ErrorException: SQLite3::exec(): NOT NULL /home/travis/build/codeigniter4/CodeIgniter4/tests/system/Database/Live/ModelTest.php:919

- testCanCreateAndSaveEntityClasses /home/travis/build/codeigniter4/CodeIgniter4/tests/system/Database/Live/ModelTest.php:643

I tried to replicate (without PHPUnit) on my local machine and I cannot replicate it :/


I don't want to bother you, but I think this approach to save() method is better as it was before changes.

**Comment by jim-parry** [comment]
The error messages for the SQLite3 tests seem straightforward.
I would guess that the Model changes you made have had side effects.
There is now a conflict with your Entity changes, and there have been some other Model changes -- I will restart the build, and see if other changes have alleviated some of the errors reported here.

**Comment by atishamte** [comment]
I guess, this is already fixed by @lonnieezell in #1829. So there is no need to pass primary key to methods

**Pull request closed without merging**
