### PR TITLE
Model's set method should accept not only string

### PR DESCRIPTION
**Pull request by nowackipawel**
I think someone adds casting here by mistake

### CODE REVIEW

**Comment by MGatner** [comment]
`Model::set()` should share the same signature with `Builder::set()`, which also only takes string values for input. The handling of the value type happens in a few different places, but ultimately the value is concatenated so safer to remain a string. Actually though, it should be of type `?string` since you can pass an array of values for `$key` and leave `$value` out altogether.

**Comment by nowackipawel** [comment]
@MGatner  ;-) thank you for pointing this out. updated. and yes you are right about the rest.

**Comment by MGatner** [comment]
You still have `string|int` for the docs. I don't know if inline docs care about things like `"4"` but this will always need to take a `string` for input.

**Comment by MGatner** [comment]
Looks correct, thank you!

**Pull request merged**
