### PR TITLE
Router Changes w.r.t #1541

### PR DESCRIPTION
**Pull request by atishamte**
Router Changes w.r.t #1541

**Checklist:**
- [x] Securely signed commits
- [x] Unit testing, with >80% coverage
- [x] Conforms to style guide

### CODE REVIEW

**Comment by atishamte** [comment]
Do not merge this. Few changes are remaining

**Comment by jim-parry** [comment]
If a PR isn't ready to merge, change its title to include "WIP".

**Comment by atishamte** [comment]
I have made the final changes. Now it is ready for review and merge

**Comment by atishamte** [comment]
@jim-parry and @lonnieezell, any changes required in this PR?

**Pull request merged**
