### PR TITLE
New command: 'debugbar:clear'

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
Adds the `debugbar:clear` command to help devs wanting to keep their `debugbar` directory tidy.
https://forum.codeigniter.com/thread-75733.html

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by truelineinfotech** [comment]
@paulbalandan  Awesome work. thanks for this PR.

**Comment by MGatner** [comment]
This looks great! One of my goals coming up is to get commands into some more-or-less official groups. I like "housekeeping" (I've been calling it maintenance) but let's make sure @lonnieezell signs off since this will set a precedent for this command group.

**Comment by paulbalandan** [comment]
Thanks, @MGatner . Thinking for "Housekeeping" took me more time than the code itself. Moreover, I am aiming for a similar command `logs:clear` under the same group, but I'm waiting first for the fate of this command. :)

**Comment by MGatner** [comment]
I forget who the quote is from and the exact wording but it’s something like: “Programming is spending 50% of your time figuring out what to name things and the other 50% writing code.”

**Comment by MGatner** [comment]
We didn't land Lonnie. I'm making the call, Housekeeping it is! Thanks for this PR

**Pull request merged**
