### PR TITLE
Refactor CommandRunnerTest to make it a little faster

### PR DESCRIPTION
**Pull request by paulbalandan**
~This is the best refactor that I can do. Time went down to at most 5 seconds faster.~
~Apparently, nothing changed running in Ubuntu.~
Verdict: The test itself is really sluggish.

**Checklist:**
- [x] Securely signed commits

### CODE REVIEW

**Comment by paulbalandan** [comment]
Why is the ListCommand an expensive command?? 🤔

**Comment by MGatner** [comment]
Are you certain `Expeditable` is functioning correctly? It's fishy that `testGoodCommand()` is marked slow but its almost-duplicate `testDefaultCommand` is not.

**Comment by paulbalandan** [comment]
> Are you certain `Expeditable` is functioning correctly? It's fishy that `testGoodCommand()` is marked slow but its almost-duplicate `testDefaultCommand` is not.

I have thought of that too. So I've run the test with Xdebug listening on the background. I've ascertained the bare times are being recorded in the $GLOBALS array and used in the output. So it means the actual test is taking long.

**Comment by paulbalandan** [comment]
What's interesting though is when I switched the two tests' places running testDefaultCommand first then testGoodCommand, the slow time gets attached to testDefaultCommand. I've also added breakpoints and noted that the CommandRunner keeps on compiling all available commands **per test run** instead of once only during constructor initialization.

**Comment by MGatner** [comment]
> the slow time gets attached to testDefaultCommand

That's baffling, because all that amounts to in the code is:
```
		$command = array_shift($params);

		if (is_null($command))
		{
			$command = 'list';
		}
```
... which should be a fraction of a nano-second 😳

**Comment by paulbalandan** [comment]
I think the culprit is in the Commands::discoverCommands when running $this->commands->run

**Comment by MGatner** [comment]
This brings up the question: is there any reason not to use `Expeditable` for the entire test suite? IMO it is the desired reporting behavior.

**Comment by paulbalandan** [comment]
IMO I would preempt first usage of `Expeditable` until we can track down all slow tests and optimize what we can do to make them faster. After exhausting all code refactors available and are still slow, then I would add the trait into the test suite.

**Pull request closed without merging**
