### PR TITLE
fix: [DebugBar] timeline annoying line on `Debug`

### PR DESCRIPTION
**Pull request by ddevsr**
**Description**
Before:
image

After:
image

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by ddevsr** [comment]
Another bug after switch to light and back again dark will change `timeline-parent-open` to dark

image

Expected after switch light
image

**Comment by michalsn** [comment]
For now, I'm a bit confused...
I can't recreate the error from the first comment and the error from the second one is not fixed.

**Comment by kenjis** [comment]
I also cannot reproduce the `Before:` annoying line.
Screenshot 2023-10-21 20 22 02

**Comment by kenjis** [comment]
v4.4.1 seems to be good.
Screenshot 2023-10-21 20 40 20

**Comment by MGatner** [comment]
@ddevsr What browser/OS/framework version?

**Comment by ddevsr** [comment]
Windows 10 with chrome latest `118`

**Comment by kenjis** [comment]
macOS/Chrome 118.0.5993.117
Screenshot 2023-10-26 21 05 10

**Comment by michalsn** [comment]
@ddevsr Does your screenshot come from the default welcome page, or is it an in-app page, with extra CSS styles?

**Comment by ddevsr** [comment]
Sorry, i think conflict with my adminlte or custom css. I will close this

**Comment by kenjis** [comment]
Okay, but we still have the issue #8064 that we cannot see "Controller" in the dark mode.

**Pull request closed without merging**
