### PR TITLE
perf: Improve call as `service()`

### PR DESCRIPTION
**Pull request by neznaika0**
**Description**
Replace the use of `Services::some()` with `service('some')`. In theory, for large queries (> 100,000), the difference in execution will be noticeable.
https://github.com/codeigniter4/CodeIgniter4/pull/8607 https://github.com/codeigniter4/CodeIgniter4/pull/8623
All texts are executed, there should be no problems.

I left it unchanged **tests/system/Config/ServicesTest.php**
The examples in the documentation have not been changed.

It is not possible to call `Services::createRequest()`as a `service ('createRequest`)', **rector** says:
```console
 ------ --------------------------------------------------------------------------------------------------------------- 
  Line   tests/system/Helpers/URLHelper/MiscUrlTest.php                                                                 
 ------ --------------------------------------------------------------------------------------------------------------- 
  :937   The method 'createRequest' is reserved for service location internals and cannot be used as a service method.  
         🪪  codeigniter.reservedServiceName                                                                            
 ------ --------------------------------------------------------------------------------------------------------------- 
 ```

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by paulbalandan — APPROVED** [review]

**Review by michalsn — APPROVED** [review]
Looks good.

Although using the `Service` class was nice from an IDE perspective - easy access to the method source. But performance is more important.

**Comment by neznaika0** [comment]
Someday there will be a person who will create an IDE extension for CI 4. And we will improve the experience

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
this needs rebase once more :)

**Comment by samsonasik** [comment]
Thank you @neznaika0

**Pull request merged**
