### PR TITLE
Prevented .env variables from exposing on the exception screen

### PR DESCRIPTION
**Pull request by DhPandya**
**Description**
See #7704

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by paulbalandan** [comment]
I would like to see this configurable. For example, I only want to hide certain keys in `$_ENV`. Or I would like to hide also certain keys in `$_SERVER`.

**Comment by DhPandya** [comment]
> I would like to see this configurable. For example, I only want to hide certain keys in `$_ENV`. Or I would like to hide also certain keys in `$_SERVER`.

As a developer, everyone is aware of the configuration variables added in the .env files. If an individual wants to include it they can, but as a default should avoid exposing .env variables.

**Comment by neznaika0** [comment]
> 

Good.  With this behavior, I can add parameters to replace in $_SERVER, for example

```
# .env
HTTP_USER_AGENT = 'Opera/10'
```

and it will not be added when merging, and will only be available from $_ENV.
So merging can cause conflicts if someone wants to use the env variable from $_SERVER

**Comment by kenjis** [comment]
This seems like it should be individually customized by developers.

The behavior of excluding items in `$_ENV` from `$_SERVER` is unpredictable, and we do not favor such behavior as the default.

**Comment by DhPandya** [comment]
> This seems like it should be individually customized by developers.
> 
> The behavior of excluding items in `$_ENV` from `$_SERVER` is unpredictable, and we do not favor such behavior as the default.

I really don't find any reason for exposing the ENV variables on the error screen. Exposing a sensitive information publicly may lead application to potential threads. If developer wants their variables on the screen then that may be their individual choice.

**Comment by kenjis** [comment]
> I really don't find any reason for exposing the ENV variables on the error screen.

The error page shows only $_SERVER and $_SESSION.

**Comment by DhPandya** [comment]
> > I really don't find any reason for exposing the ENV variables on the error screen.
> 
> The error page shows only $_SERVER and $_SESSION.

Yes. But $_SERVER is also contains the .env variables.

**Comment by kenjis** [comment]
It is because of `DotEnv`.

**Comment by DhPandya** [comment]
> It is because of `DotEnv`.

What is the reason for merging .env with $_SERVER ?

**Comment by kenjis** [comment]
> What is the reason for merging .env with $_SERVER ?

I'm not sure, but phpdotenv does so.

> All of the defined variables are now available in the $_ENV and $_SERVER super-globals.
https://github.com/vlucas/phpdotenv#usage

**Comment by neznaika0** [comment]
Are similar issues in the repository phpdotenv, they solve it by custom object creation
https://github.com/vlucas/phpdotenv/issues/556

**Comment by DhPandya** [comment]
@kenjis D

> > What is the reason for merging .env with $_SERVER ?
> 
> I'm not sure, but phpdotenv does so.
> 
> > All of the defined variables are now available in the $_ENV and $_SERVER super-globals.
> > https://github.com/vlucas/phpdotenv#usage
> 
> Also,
> 
> > In both the CGI and FastCGI SAPIs, [$_SERVER](https://www.php.net/manual/en/reserved.variables.server.php) is also populated by values from the environment
> > https://www.php.net/manual/en/ini.core.php#ini.variables-order

I see. But why we're not preventing it, although we have a control in our hand? Not every developer are aware of this kind of .env behaviours.

**Comment by kenjis** [comment]
Yes, we have a control. 

> Not every developer are aware of this kind of .env behaviours.

So we will add the Warning: https://codeigniter4.github.io/CodeIgniter4/general/errors.html#error-reporting

By the way, why do you need to hide the environment values?
Your `development` server is open to the world?
If so, you should have access control.

**Comment by DhPandya** [comment]
> Yes, we have a control.
> 
> > Not every developer are aware of this kind of .env behaviours.
> 
> So we will add the Warning: https://codeigniter4.github.io/CodeIgniter4/general/errors.html#error-reporting
> 
> By the way, why do you need to hide the environment values? Your `development` server is open to the world? If so, you should have access control.

I've full control for mine server.
By the way, why you don't want to hide it.?

**Comment by kenjis** [comment]
> By the way, why you don't want to hide it.?

I assume that the `development` server is used by one developer on his/her own computer for development.
Therefore, there is no problem to display the secret password.

**Comment by ddevsr** [comment]
I have dev server too, when will demo to client using dev server. There's no way I want to show an error to client, so I use `production` mode. I think of my dev server as `staging` to use to demo an app to clients. For my computer, i am using development.

For my self, its no problem

**Comment by ddevsr** [comment]
Will be better have a choice on `config` for expose this or not

**Comment by kenjis** [comment]
If you want to see all _SERVER variables, use `development`.
If you don't want, use `production` or create a custom environment like `staging` and customize the output as you like.

**Pull request closed without merging**
