### PR TITLE
Fix default value for page in Model::paginate()

### PR DESCRIPTION
**Pull request by michalsn**
**Description**
This PR fixes the default value for the `$page` parameter in Model::paginate().

Ref: #3188

**Checklist:**
- [x] Securely signed commits
- [x] Conforms to style guide

### CODE REVIEW

**Comment by mmrtonmoybd** [comment]
@michalsn pagination not working now.
It shows same data on every page , data isn't change. 
I have 16 rows. I want to show 4 data per page. But it shows same data every page. Maybe it's not fixed yet.

**Comment by michalsn** [comment]
Apparently there is another bug with `segment` support. I will look into it tomorrow.

**Comment by mmrtonmoybd** [comment]
Thank you @michalsn .
I am making a magazine on codeigniter. So I need pagination to display per page posts by category. I already doing pagination with page query parameter, but my boss rejected it because it is not seo friendly url. 
Almost all works are done in this project. I already two times rejected for not seo friendly pagination link.

Pagination links() method also have a problem. 
If I didn't need to use pagination group, but I need to use my own pagination template. 
So I basically do like 
```
<?= $pager->links(null, 'moshiur') ?>
```
It gives me a error, because links first Argument must be a string null given. 

Is it possible to give null value on links method both Arguments ?

**Comment by michalsn** [comment]
@mmrtonmoybd  instead of `null` you should use `default` for group name.

**Comment by mmrtonmoybd** [comment]
@michalsn do you fixed paginate show results with segment bug ?

**Comment by michalsn** [comment]
@mmrtonmoybd Yes, I hope it's fixed. The tests fail because of a random test failure.

**Comment by mmrtonmoybd** [comment]
Well done @michalsn
I am seeing that you fixed many issue in codeigniter like Super Man. You are the coding hero. Thank you 😊❤️❤️
Now it is working. But codeigniter ignore your pull request.

**Comment by michalsn** [comment]
@mmrtonmoybd I was only waiting for you to confirm that it's working fine. Thanks for your feedback!

**Comment by mmrtonmoybd** [comment]
@michalsn 
Codeigniter $pager->links() array contain the active boolean not working.
It return false for every page.
My current page is 5, but it return active=false for the page 5.


array(3) { [0]=> array(3) { ["uri"]=> string(42) "http://localhost:8080/category/exclusive/3" ["title"]=> int(3) ["active"]=> bool(false) } [1]=> array(3) { ["uri"]=> string(42) "http://localhost:8080/category/exclusive/4" ["title"]=> int(4) ["active"]=> bool(false) } [2]=> array(3) { ["uri"]=> string(42) "http://localhost:8080/category/exclusive/5" ["title"]=> int(5) ["active"]=> bool(false) } }

**Pull request merged**
