### PR TITLE
[Rector] Enable AddDefaultValueForUndefinedVariableRector

### PR DESCRIPTION
**Pull request by samsonasik**
**Description**

`AddDefaultValueForUndefinedVariableRector` now already cover isset variable check, so I think it can be enabled.

**Checklist:**
- [x] Securely signed commits

### CODE REVIEW

**Comment by samsonasik** [comment]
All green :tada:

**Comment by kenjis** [comment]
Sorry, phpstan-baseline.neon.dist was conflicted.
Can you rebase?

**Comment by samsonasik** [comment]
@kenjis rebased 👍

**Review by kenjis — APPROVED** [review]

**Comment by MGatner** [comment]
Oooh this is handy!!

**Pull request merged**
