### PR TITLE
Clean buffers after feature test

### PR DESCRIPTION
**Pull request by MGatner**
**Description**
This might be a long shot at #3063 but I can't run feature tests locally so I'm giving it a try here.

**Checklist:**
- [X] Securely signed commits
- [X] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [X] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
I think this is the correct implementation now. This could sometimes "hide" issues with views but explicit testing should uncover those, I don't believe that's the job of the `FeatureTestCase`.

@samsonasik would you review please, since you took the last pass at this?

**Comment by samsonasik** [comment]
@MGatner can you remove ob_start() in the tests at:

1. https://github.com/codeigniter4/CodeIgniter4/blob/develop/tests/system/Test/FeatureTestCaseTest.php#L230 

2. https://github.com/codeigniter4/CodeIgniter4/blob/develop/tests/system/Test/FeatureTestCaseTest.php#L244

to ensure it works?

**Comment by samsonasik** [comment]
that still make risky tests

**Comment by MGatner** [comment]
@samsonasik I don't totally understand it but I *think* cases that echo directly from an empty buffer needs to recreate the original buffer. I just added a commit so that the buffer is returned to its pre-test value regardless of state (up or down). It's kind of weird but it will prevent risky tests. If there is some deeper issue with buffering in the framework itself then it alludes me.

**Comment by MGatner** [comment]
Travis build green, no risky tests!

**Pull request merged**
