### PR TITLE
Model setValidationMessage functions introduced

### PR DESCRIPTION
**Pull request by atishamte**
W.r.t #1657, I have added functionality in Model,
- Added functions for setValidationMessage & setValidationMessages
- Added respective test scenarios
- Added user guide documentation

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by atishamte** [comment]
Test cases failed due to some other functionality committed earlier in Model.
What has to be done now, as the current PR is not relevant to the failed test case scenario

**Comment by jim-parry** [comment]
It looks like your PR 1804 missed changing the return type for Model::insert, and that the Model testing didn't catch it. That need to be fixed here or in a separate PR. 
This points out the need to finish the Model unit testing sooner than later :-/

**Comment by jim-parry** [comment]
You earlier changed the return type of save/updatge etc to boolean, BUT insert returns a boolean or an int, and that is passed into save, which then breaks.
We need to figure how to solve this, or else revert 1804 :(

**Comment by jim-parry** [comment]
I have fixed the cause of the problems. You need to synch your branch with the main repo's develop branch, and then repush your branch. The travis-ci build will restart automatically.

**Comment by jim-parry** [comment]
ps - I have checked out phpDocumentor2, and it is very usable. I will be incorporating the generated API as part of the project docs :)

**Comment by atishamte** [comment]
That's great. So the documentation will get generated automatically based on class and function documentation directly :)

**Pull request closed without merging**
