### PR TITLE
docs: remove useless @return BaseConnection|ConnectionInterface on BaseBuilder::db()

### PR DESCRIPTION
**Pull request by samsonasik**
**Description**

`BaseConnection` is implements `ConnectionInterface` so it can be removed from `@return` doc. Detected by run latest `"rector/rector": "dev-main"`

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by samsonasik** [comment]
Ready to merge 👍

**Comment by kenjis** [comment]
> `BaseConnection` is implements `ConnectionInterface` so it can be removed from `@return` doc.

Why? `BaseConnection` has more method than `ConnectionInterface`.

In fact, the `db()` returns `BaseConnection`.
Or the return type `ConnectionInterface` is incorrect.

Or `ConnectionInterface` is broken.
Or we don't know how to use interface correctly.
See #4356

**Comment by samsonasik** [comment]
The problem with including the interface itself in the union make all other type already valid as child of it.

The current usage is incorrect imo, if union type to be used, both should be a class that implement the interface, eg, for param which valid:

```php
/** @param SomeClass|SomeClass2 $param */
public function run(SomeInterface $param)
{
   echo $param->prop;
}
``` 

which both `SomeClass` and `SomeClass2` child of `SomeInterface` and has `prop` property, so that "more" data is valid.

**Comment by samsonasik** [comment]
The another solution is mark as BaseConnection instead:

```php
/** @return BaseConnection */
public function db(): ConnectionInterface
```

**Comment by samsonasik** [comment]
@kenjis I updated to `@return BaseConnection`

**Comment by kenjis** [comment]
@samsonasik Yes, after all, our code is incorrect. 
But I think this is better. 

```php
/** @return BaseConnection */
public function db(): ConnectionInterface
```
Because devs expect BaseConnection instead of ConnectionInterface.

**Comment by samsonasik** [comment]
done 👍

**Review by kenjis — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @kenjis for the review.

**Pull request merged**
