### PR TITLE
fix: module filters are not discovered when using route filters

### LINKED ISSUE #4720: Bug: Module route filters not loading
**Describe the bug**
If the module route has a filter, then the filter is checked in App\Config\Filters.
If the filter is not found, then an error is thrown. 
If a module filter must be registered in App\Config\Filters, then trying to load the module filters extension is meaningless. 

Example
```php
//Module/Namespace/Config/Routes
$routes->add('route', 'Controller::method', ['filter' => 'module_filter']);
//Module/Namespace/Config/Filters
$filters->aliases['module_filter'] = Module\Namespace\Filters\SomeFilter::class;
```

**CodeIgniter 4 version**
4.1.2

**Affected module(s)**
CodeIgniter, Filters

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #4720

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by iRedds** [comment]
Yes, this solution works.
But what if we move the search for filters to the class constructor?

**Comment by kenjis** [comment]
@iRedds I moved it. Does it work?

**Comment by iRedds** [comment]
@kenjis You asks me? How about tests? =)

**Comment by kenjis** [comment]
@iRedds Yes, of course. You are the only one user for this functionality in this planet.
Most important. :-)

**Comment by kenjis** [comment]
@michalsn https://github.com/codeigniter4/CodeIgniter4/pull/3459#discussion_r474690853

Is there something wrong with moving`$this->discoverFilters()` back to the constructor?

I think the Filters files in the namespace are determined at the time of the instance creation, 
so it seems better to execute it once in the constructor.

**Comment by michalsn** [comment]
I think this is a good fix. 

Can we add a test for this to make sure it won't be moved around anymore?

**Comment by kenjis** [comment]
@michalsn Thanks! I added a test.

**Review by michalsn — APPROVED** [review]
Looks good to me.

**Pull request merged**
