### PR TITLE
fixes #2049 - debug option 

### PR DESCRIPTION
**Pull request by michalsn**
**Description**
CURLRequest class with the default `debug` value reports an error:
```
curl_setopt_array(): supplied argument is not a valid File-Handle resource
```
This pull request fixes this issue and ensures to create resource if we specify a path to the log file. I believe that tests for this are already started in #2168.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
I think @xbotkaj was right and `$config[‘debug’]` will always be set so we should check `if ($config...` instead of `isset`. 

Also can you merge my tests from https://github.com/codeigniter4/CodeIgniter4/pull/2168? Let me know if you want help with a cross-user-fork merge.

**Comment by michalsn** [comment]
Yes, I removed the `isset` option. I also merged your tests - thanks.

Crap... seems like merge portion wasn't signed 😞 oh well...

**Comment by MGatner** [comment]
This is looking good. If there is any way you can setup signing on the device you did the merge from then GitHub will verify it retroactively. Unless @lonnieezell wants to override the merge block.

**Comment by michalsn** [comment]
Well... I made this (not signed) merge on the same device. I tried to fix it somehow yesterday but from what I can see I failed. So, idk... if you can't merge this just close this pull request, copy my code (it's just 3 lines actually) and add it to your branch with tests @MGatner - I don't mind.

**Comment by MGatner** [comment]
:D thanks! I can probably merge your commits and keep you as the author and just do a verified merge myself. I’ll take a look later tonight - we already got another CURL debug report so I’m eager to get this in.

**Comment by MGatner** [comment]
@michalsn I added your commits to https://github.com/codeigniter4/CodeIgniter4/pull/2168 and assuming it passes we should be all set. Feel free to close this PR if you are satisfied.

**Comment by michalsn** [comment]
Ok, thanks @MGatner.

**Pull request closed without merging**
