### PR TITLE
Add webp support to Image Manipulation Class

### PR DESCRIPTION
**Pull request by nicojmb**
Each pull request should address a single issue and have a meaningful title.

**Description**
Support webp image in Image Manipulation Class

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x ] Conforms to style guide

---------Remove from here down in your description----------

**Notes**
- Pull requests must be in English
- If the PR solves an issue, reference it with a suitable verb and the issue number
(e.g. fixes <hash>12345)
- Unsolicited pull requests will be considered, but there is no guarantee of acceptance
- Pull requests should be from a feature branch in the contributor's fork of the repository
  to the develop branch of the project repository

### CODE REVIEW

**Comment by michalsn** [comment]
@nicojmb we have two things to fix here: 

* The first - tests. If you look at Travis, we have 3 tests that are failing now, we have to change constant from `IMAGETYPE_PNG` to `IMG_PNG` since this is the correct one returned by `getimagesize()` function.
* The second thing that I didn't notice earlier is that your commits are not signed and we can't merge your code. Please check this page to learn more about code signing: https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/signing.rst

@MGatner is there a way to sign the code right now, to make it mergeable? I think you showed me once some instructions but I didn't succeed make them work for me (it was probably my fault). So, I'm just wondering is there a way to "fix" this PR in this state.

**Comment by MGatner** [comment]
@michalsn you can add credentials to GitHub post-push and it will verify precious commits, but if the commits weren’t signed already that won’t work. Anyone could pull the fork, `git reset develop`, then re-add and re-commit a signed version and make a new PR. Or Lonnie could just override the verification requirement 😇

**Comment by MichalPB1** [comment]
Can it be merged? This is something that is useful to me :)

**Comment by michalsn** [comment]
Right now we can't merge it since it's not signed and tests are failing. If nothing will change, I will probably wait till the weekend and try to fork this branch and re-commit.

**Comment by lonnieezell** [comment]
Yeah, the biggest problem is the tests. I am happy to override. And am thinking about removing that requirement, anyway, actually.

**Comment by michalsn** [comment]
Yes, removing the code signing requirement would probably be a good idea.

**Pull request merged**
