### PR TITLE
Update debug toolbar

### PR DESCRIPTION
**Pull request by totoprayogo1916**
**Description**
Improves the appearance of the Debug Toolbar.
The previous toolbar.css file is more up-to-date than toolbar.scss, (since #3070)
and fixes a cluttered menu (align not centered), compresses the Codeigniter logo.

**Checklist:**
- [x] Securely signed commits
- [x] Unit testing, with >80% coverage
- [x] Conforms to style guide
- [ ] Component(s) with PHPdocs
- [ ] User guide updated

### CODE REVIEW

**Review by paulbalandan — COMMENTED** [review]
Can you show a visual representation of the changes here? I tried pulling your PR locally but I did not see noticeable changes. If you can guide me visually on what you changed I would appreciate it.

**Review by MGatner — APPROVED** [review]
I approve the code, but please address @paulbalandan 's request. Also curious if @LittleJ is around to take a look?

**Comment by LittleJ** [comment]
@MGatner Thanks for the heads up. All has been done respecting the rules. Just wondering why to supply uncompressed CSS. I think the more we gain weight (and speed) for the final user (which will probably not tweak this toolbar), the best it is. But it is only a (my) point of view :-)

**Comment by totoprayogo1916** [comment]
The one above is the old version.
while the bottom is the current change.

In the old version the menu icon appears to point more upwards.

comparison
cc: @paulbalandan

**Comment by paulbalandan** [comment]
> @MGatner Thanks for the heads up. All has been done respecting the rules. Just wondering why to supply uncompressed CSS. I think the more we gain weight (and speed) for the final user (which will probably not tweak this toolbar), the best it is. But it is only a (my) point of view :-)

I'm in favor of distributing a minified version of the CSS, and probably the JS too, in the next releases. But this might be for another PR. :)

**Comment by paulbalandan** [comment]
> The one above is the old version.
> while the bottom is the current change.
> 
> In the old version the menu icon appears to point more upwards.
> 
> comparison
> cc: @paulbalandan

Ah I see. The changes are subtle but I like it!

**Review by paulbalandan — APPROVED** [review]

**Comment by paulbalandan** [comment]
@totoprayogo1916 thank you.

**Comment by MGatner** [comment]
Thanks all! The icon alignment has always bothered me. This is a good change.

**Pull request merged**
