### PR TITLE
feat: add new setter/getter for Entity

### PR DESCRIPTION
**Pull request by kenjis**
~~Needs  #7208~~

**Description**
Add special getter/setter to Entity to avoid method name conflicts.
- add new special setter method "`_set` + key" for a attribute
- add new special getter method "`_get` + key" for a attribute

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
I'm not sure what this is needed for? `bar:foo`

**Comment by kenjis** [comment]
For method name collision. https://github.com/codeigniter4/CodeIgniter4/issues/5762#issuecomment-1179520069

**Comment by MGatner** [comment]
I meant the colons in the value, but now I see those are an artifact of the test fixture, not part of the code! My mistake.

**Comment by kenjis** [comment]
Added docs.

**Comment by kenjis** [comment]
@mostafakhudair @najdanovicivan @iRedds @the-gt99 @lonnieezell 
Any comments?

**Comment by najdanovicivan** [comment]
I think this adds a lot of unnecessary complexity to have multiple ways of defining setters. So far the only problem we have is when we need to override setAttributes method. Since now we have setAttributes as deprecated and we're going forward with injectRawData() method. I'd rather use https://www.php.net/manual/en/reflectionmethod.getdeclaringclass.php to check if setAttributes is not from CodeIgniter\Entity or  CodeIgniter\Entity\Entity class. So if method is not from base CI4 classes it can be handled as regular setter for $this->attributes['attributes'].  The only problem with this one is BC in Entity classes which override the setAttributes method.

**Comment by kenjis** [comment]
@najdanovicivan Thank you for your opinion.

The main reason of this PR is to avoid setter/getter method name conflicts,
not only for `setAttributes()`.
See https://github.com/codeigniter4/CodeIgniter4/pull/7230/files#diff-b43fcc536c7ffa370ea5d043988d111223780b2dade0198d7b91818f9bd7ab62

**Review by MGatner — APPROVED** [review]
Docs look good.

**Comment by iRedds** [comment]
As far as I remember, PSR does not recommend using the underscore character as a prefix for method names.
I have already expressed my opinion about the names of methods for accessing attributes more than once.
get\<name>Attribute

**Comment by kenjis** [comment]
We don't remove `get<name>()` getter.
So `get<name>Attribute()` may conflict to another column.

If there are columns `parent` and `parent_attribute` and
`getParent()` and `getParentAttribute()`, 
`getParentAttribute()` is used when getting `parent`.
This is a breaking change.

**Comment by iRedds** [comment]
I just expressed my opinion.
The fact that some genius came up with the idea of using class property getter/setter method names for attributes, which gave rise to this garbage, is not my problem.
It seems that they were trying to combine the Doctrine and Eloquent.

I see two options.
1. We admit the problem, apologize and change the entity class with normal method names.
2. We add an alternative Entity that will be maintained further, and mark the existing one as deprecated.

**Pull request merged**
