### PR TITLE
Remove unused cast on RedisHandler

### PR DESCRIPTION
**Pull request by samsonasik**
**Description**

`\Config\Session` and `\Config\App` is typed `int`, so no need re-cast:

https://github.com/codeigniter4/CodeIgniter4/blob/46a1e5ef5cfd5bc23cade33215734dc8fdd20a6b/app/Config/Session.php#L43

https://github.com/codeigniter4/CodeIgniter4/blob/46a1e5ef5cfd5bc23cade33215734dc8fdd20a6b/app/Config/App.php#L175

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Review by kenjis — APPROVED** [review]

**Review by paulbalandan — APPROVED** [review]

**Comment by paulbalandan** [comment]
Why does PHPStan not catch this?

**Comment by kenjis** [comment]
PhpStorm screenshot

**Comment by samsonasik** [comment]
@paulbalandan it depends on what type we try to check: docblock base or native type based. 

This change is applied by rector/rector:dev-main, we are moving from docblock var type to native type detection in various rules location if make sense.

**Comment by samsonasik** [comment]
@paulbalandan @kenjis thank you for the review, I am merging it 👍

**Comment by paulbalandan** [comment]
The useless cast rule is in `phpstan/phpstan-strict-rules`

**Comment by samsonasik** [comment]
@paulbalandan I see, should we add `phpstan/phpstan-strict-rules` to dev dependency?

**Comment by kenjis** [comment]
When I tried to add phpstan-strict-rules in before, I got a huge number of errors. However, we might as well add it and update the baseline.

**Comment by paulbalandan** [comment]
We can add phpstan-strict-rules and enable rules one-by-one.

**Pull request merged**
