### PR TITLE
Fixes #3125 : add ability to override existing translation en in system language from App

### LINKED ISSUE #3125: Bug:  Can't override Translations Package Files / Keys
**Describe the bug**
When using the translations package, you can't override the validation messages, for example.

**CodeIgniter 4 version**
`4.0.3`

**Affected module(s)**
`CodeIgniter\Language`

**Expected behavior, and steps to reproduce if appropriate**
require `codeigniter4/translations`, try override any key in `App/Translations/[lang]/Validation.php`.

### PR DESCRIPTION
**Pull request by samsonasik**
Alternative of #3126 to allow override existing translation validation.

**Checklist:**
- [x] Securely signed commits
- [x] Unit testing, with >80% coverage

### CODE REVIEW

**Comment by samsonasik** [comment]
I've added unit test for it.

**Comment by samsonasik** [comment]
Previously, I change the `FileLocator::search()` autoloader. After some thinking, I think the change need to be in the `Language::requireFile()` to avoid BC break.

**Comment by samsonasik** [comment]
I think there is a better way, add a 3rd argument in `FileLocator` autoloader, eg: `bool $prioritizeSystem = true` so it can be tested properly, and re-usable.

**Comment by samsonasik** [comment]
I've added 3rd parameter `bool $prioritizeApp = true` in `Autoloader\FileLocator::search()` with set to false in `Language\Language::requireFile()`. Added unit test for it.

**Comment by MGatner** [comment]
I like the $prioritizeApp option. Does this still weight the remaining files by their alphabetical order? This should follow the approved priority hierarchy, see https://github.com/codeigniter4/CodeIgniter4/pull/2507. But basically: App, Config, modules, System. E.g. developers should be able to include a third-party language pack and have it override system defaults automatically.

**Comment by samsonasik** [comment]
Yes. And the 3rd parameter is default to true which uses existing functionality. Only in usage in `Language\Language::requireFile()` it uses false to make `App` language loaded in the last entry.

**Comment by samsonasik** [comment]
travis build green :tada:

**Comment by samsonasik** [comment]
updated to run `array_unique` once after array merged only.

**Comment by samsonasik** [comment]
travis build green 🎉

**Pull request merged**
