### PR TITLE
Remove PHPStan ignoreErrors: Unsafe usage of new static()

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Removes PHPStan ignoreErrors: `Unsafe usage of new static()`.

See <https://phpstan.org/blog/solving-phpstan-error-unsafe-usage-of-new-static>.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by paulbalandan — COMMENTED** [review]
Although this is technically breaking changes, I do not actually imagine anyone's app breaking. I'll wait for other's opinions first.

**Comment by kenjis** [comment]
I thought this is okay, but PHP 7.3 complains:
> Fatal error: Declaration of Error::__construct($message = NULL, $code = NULL, $previous = NULL) must be compatible with CodeIgniter\Exceptions\ExceptionInterface::__construct(string $message = '', int $code = 0, ?Throwable $previous = NULL) in /home/runner/work/CodeIgniter4/CodeIgniter4/system/Database/Exceptions/DatabaseException.php on line 16
S
https://github.com/codeigniter4/CodeIgniter4/pull/4357/checks?check_run_id=1992185571

**Comment by kenjis** [comment]
```sh-session
$ /usr/local/opt/php@7.3/bin/php vendor/bin/phpstan analyse
Note: Using configuration file /Users/kenji/work/codeigniter/CodeIgniter4/phpstan.neon.dist.
 372/372 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 -- -------------------------------------------------------------------------------------------------------------- 
     Error                                                                                                         
 -- -------------------------------------------------------------------------------------------------------------- 
     Child process error (exit code 255):                                                                          
     Fatal error: Declaration of Error::__construct($message = NULL, $code = NULL, $previous = NULL) must be       
     compatible with CodeIgniter\Exceptions\ExceptionInterface::__construct(string $message = '', int $code = 0,   
     ?Throwable $previous = NULL) in                                                                               
     /Users/kenji/work/codeigniter/CodeIgniter4/system/Database/Exceptions/DatabaseException.php on line 16        
     PHP Fatal error:  Declaration of Error::__construct($message = NULL, $code = NULL, $previous = NULL) must be  
     compatible with CodeIgniter\Exceptions\ExceptionInterface::__construct(string $message = '', int $code = 0,   
     ?Throwable $previous = NULL) in                                                                               
     /Users/kenji/work/codeigniter/CodeIgniter4/system/Database/Exceptions/DatabaseException.php on line 16        
                                                                                                                   
     Child process error (exit code 255):                                                                          
     Fatal error: Declaration of Error::__construct($message = NULL, $code = NULL, $previous = NULL) must be       
     compatible with CodeIgniter\Exceptions\ExceptionInterface::__construct(string $message = '', int $code = 0,   
     ?Throwable $previous = NULL) in                                                                               
     /Users/kenji/work/codeigniter/CodeIgniter4/system/Database/Exceptions/DatabaseException.php on line 16        
     PHP Fatal error:  Declaration of Error::__construct($message = NULL, $code = NULL, $previous = NULL) must be  
     compatible with CodeIgniter\Exceptions\ExceptionInterface::__construct(string $message = '', int $code = 0,   
     ?Throwable $previous = NULL) in                                                                               
     /Users/kenji/work/codeigniter/CodeIgniter4/system/Database/Exceptions/DatabaseException.php on line 16        
                                                                                                                   
     Child process error (exit code 255):                                                                          
     Fatal error: Declaration of Error::__construct($message = NULL, $code = NULL, $previous = NULL) must be       
     compatible with CodeIgniter\Exceptions\ExceptionInterface::__construct(string $message = '', int $code = 0,   
     ?Throwable $previous = NULL) in                                                                               
     /Users/kenji/work/codeigniter/CodeIgniter4/system/Database/Exceptions/DatabaseException.php on line 16        
     PHP Fatal error:  Declaration of Error::__construct($message = NULL, $code = NULL, $previous = NULL) must be  
     compatible with CodeIgniter\Exceptions\ExceptionInterface::__construct(string $message = '', int $code = 0,   
     ?Throwable $previous = NULL) in                                                                               
     /Users/kenji/work/codeigniter/CodeIgniter4/system/Database/Exceptions/DatabaseException.php on line 16        
                                                                                                                   
     Child process error (exit code 255):                                                                          
     Fatal error: Declaration of Error::__construct($message = NULL, $code = NULL, $previous = NULL) must be       
     compatible with CodeIgniter\Exceptions\ExceptionInterface::__construct(string $message = '', int $code = 0,   
     ?Throwable $previous = NULL) in                                                                               
     /Users/kenji/work/codeigniter/CodeIgniter4/system/Database/Exceptions/DatabaseException.php on line 16        
     PHP Fatal error:  Declaration of Error::__construct($message = NULL, $code = NULL, $previous = NULL) must be  
     compatible with CodeIgniter\Exceptions\ExceptionInterface::__construct(string $message = '', int $code = 0,   
     ?Throwable $previous = NULL) in                                                                               
     /Users/kenji/work/codeigniter/CodeIgniter4/system/Database/Exceptions/DatabaseException.php on line 16        
                                                                                                                   
 -- -------------------------------------------------------------------------------------------------------------- 

                                                                                                                       
 [ERROR] Found 4 errors                                    
```

**Comment by paulbalandan** [comment]
This is breaking LSP?? Maybe we can set the defaults to null instead to be LSP-compliant in php 7.3

**Comment by kenjis** [comment]
If I change the `ExceptionInterface`:
```diff
--- a/system/Exceptions/ExceptionInterface.php
+++ b/system/Exceptions/ExceptionInterface.php
@@ -22,5 +22,5 @@ use Throwable;
 
 interface ExceptionInterface
 {
-   public function __construct(string $message = '', int $code = 0, Throwable $previous = null);
+   public function __construct($message = null, $code = null, $previous = null);
 }
```

```sh-session
$ /usr/local/opt/php@7.3/bin/php vendor/bin/phpstan analyse
Note: Using configuration file /Users/kenji/work/codeigniter/CodeIgniter4/phpstan.neon.dist.
 -- ------------------------------------------------------------------------------------------------------------------ 
     Error                                                                                                             
 -- ------------------------------------------------------------------------------------------------------------------ 
     Child process error (exit code 255):                                                                              
     Fatal error: Declaration of CodeIgniter\Encryption\Exceptions\EncryptionException::__construct(string $message =  
     '', int $code = 0, ?Throwable $previous = NULL) must be compatible with                                           
     CodeIgniter\Exceptions\ExceptionInterface::__construct($message = NULL, $code = NULL, $previous = NULL) in        
     /Users/kenji/work/codeigniter/CodeIgniter4/system/Encryption/Exceptions/EncryptionException.php on line 21        
     PHP Fatal error:  Declaration of CodeIgniter\Encryption\Exceptions\EncryptionException::__construct(string        
     $message = '', int $code = 0, ?Throwable $previous = NULL) must be compatible with                                
     CodeIgniter\Exceptions\ExceptionInterface::__construct($message = NULL, $code = NULL, $previous = NULL) in        
     /Users/kenji/work/codeigniter/CodeIgniter4/system/Encryption/Exceptions/EncryptionException.php on line 21        
                                                                                                                       
     Child process error (exit code 255):                                                                              
     Fatal error: Declaration of CodeIgniter\Exceptions\FrameworkException::__construct(string $message = '', int      
     $code = 0, ?Throwable $previous = NULL) must be compatible with                                                   
     CodeIgniter\Exceptions\ExceptionInterface::__construct($message = NULL, $code = NULL, $previous = NULL) in        
     /Users/kenji/work/codeigniter/CodeIgniter4/system/Exceptions/FrameworkException.php on line 22                    
     PHP Fatal error:  Declaration of CodeIgniter\Exceptions\FrameworkException::__construct(string $message = '',     
     int $code = 0, ?Throwable $previous = NULL) must be compatible with                                               
     CodeIgniter\Exceptions\ExceptionInterface::__construct($message = NULL, $code = NULL, $previous = NULL) in        
     /Users/kenji/work/codeigniter/CodeIgniter4/system/Exceptions/FrameworkException.php on line 22                    
                                                                                                                       
     Child process error (exit code 255):                                                                              
     Fatal error: Declaration of CodeIgniter\Encryption\Exceptions\EncryptionException::__construct(string $message =  
     '', int $code = 0, ?Throwable $previous = NULL) must be compatible with                                           
     CodeIgniter\Exceptions\ExceptionInterface::__construct($message = NULL, $code = NULL, $previous = NULL) in        
     /Users/kenji/work/codeigniter/CodeIgniter4/system/Encryption/Exceptions/EncryptionException.php on line 21        
     PHP Fatal error:  Declaration of CodeIgniter\Encryption\Exceptions\EncryptionException::__construct(string        
     $message = '', int $code = 0, ?Throwable $previous = NULL) must be compatible with                                
     CodeIgniter\Exceptions\ExceptionInterface::__construct($message = NULL, $code = NULL, $previous = NULL) in        
     /Users/kenji/work/codeigniter/CodeIgniter4/system/Encryption/Exceptions/EncryptionException.php on line 21        
                                                                                                                       
     Child process error (exit code 255):                                                                              
     Fatal error: Declaration of CodeIgniter\Database\Exceptions\DataException::__construct(string $message = '', int  
     $code = 0, ?Throwable $previous = NULL) must be compatible with                                                   
     CodeIgniter\Exceptions\ExceptionInterface::__construct($message = NULL, $code = NULL, $previous = NULL) in        
     /Users/kenji/work/codeigniter/CodeIgniter4/system/Database/Exceptions/DataException.php on line 17                
     PHP Fatal error:  Declaration of CodeIgniter\Database\Exceptions\DataException::__construct(string $message =     
     '', int $code = 0, ?Throwable $previous = NULL) must be compatible with                                           
     CodeIgniter\Exceptions\ExceptionInterface::__construct($message = NULL, $code = NULL, $previous = NULL) in        
     /Users/kenji/work/codeigniter/CodeIgniter4/system/Database/Exceptions/DataException.php on line 17                
                                                                                                                       
 -- ------------------------------------------------------------------------------------------------------------------ 

                                                                                                                       
 [ERROR] Found 4 errors                                                                                                
```

```sh-session
$ /usr/local/opt/php@7.4/bin/php vendor/bin/phpstan analyse
Note: Using configuration file /Users/kenji/work/codeigniter/CodeIgniter4/phpstan.neon.dist.
 -- ------------------------------------------------------------------------------------------------------------------ 
     Error                                                                                                             
 -- ------------------------------------------------------------------------------------------------------------------ 
     Child process error (exit code 255):                                                                              
     Fatal error: Declaration of CodeIgniter\Exceptions\FrameworkException::__construct(string $message = '', int      
     $code = 0, ?Throwable $previous = NULL) must be compatible with                                                   
     CodeIgniter\Exceptions\ExceptionInterface::__construct($message = NULL, $code = NULL, $previous = NULL) in        
     /Users/kenji/work/codeigniter/CodeIgniter4/system/Exceptions/FrameworkException.php on line 23                    
     PHP Fatal error:  Declaration of CodeIgniter\Exceptions\FrameworkException::__construct(string $message = '',     
     int $code = 0, ?Throwable $previous = NULL) must be compatible with                                               
     CodeIgniter\Exceptions\ExceptionInterface::__construct($message = NULL, $code = NULL, $previous = NULL) in        
     /Users/kenji/work/codeigniter/CodeIgniter4/system/Exceptions/FrameworkException.php on line 23                    
                                                                                                                       
     Child process error (exit code 255):                                                                              
     Fatal error: Declaration of CodeIgniter\Database\Exceptions\DataException::__construct(string $message = '', int  
     $code = 0, ?Throwable $previous = NULL) must be compatible with                                                   
     CodeIgniter\Exceptions\ExceptionInterface::__construct($message = NULL, $code = NULL, $previous = NULL) in        
     /Users/kenji/work/codeigniter/CodeIgniter4/system/Database/Exceptions/DataException.php on line 23                
     PHP Fatal error:  Declaration of CodeIgniter\Database\Exceptions\DataException::__construct(string $message =     
     '', int $code = 0, ?Throwable $previous = NULL) must be compatible with                                           
     CodeIgniter\Exceptions\ExceptionInterface::__construct($message = NULL, $code = NULL, $previous = NULL) in        
     /Users/kenji/work/codeigniter/CodeIgniter4/system/Database/Exceptions/DataException.php on line 23                
                                                                                                                       
     Child process error (exit code 255):                                                                              
     Fatal error: Declaration of CodeIgniter\Database\Exceptions\DataException::__construct(string $message = '', int  
     $code = 0, ?Throwable $previous = NULL) must be compatible with                                                   
     CodeIgniter\Exceptions\ExceptionInterface::__construct($message = NULL, $code = NULL, $previous = NULL) in        
     /Users/kenji/work/codeigniter/CodeIgniter4/system/Database/Exceptions/DataException.php on line 23                
     PHP Fatal error:  Declaration of CodeIgniter\Database\Exceptions\DataException::__construct(string $message =     
     '', int $code = 0, ?Throwable $previous = NULL) must be compatible with                                           
     CodeIgniter\Exceptions\ExceptionInterface::__construct($message = NULL, $code = NULL, $previous = NULL) in        
     /Users/kenji/work/codeigniter/CodeIgniter4/system/Database/Exceptions/DataException.php on line 23                
                                                                                                                       
 -- ------------------------------------------------------------------------------------------------------------------ 

                                                                                                                       
 [ERROR] Found 3 errors
```

**Comment by paulbalandan** [comment]
Why not just change the constructor to final, in DebugTraceableTrait. As far as I know, exceptions here are only extended to add new methods for late static binding.

**Comment by kenjis** [comment]
> Why not just change the constructor to final, in DebugTraceableTrait.

I thought if I do so, we will not be able to change the constructor when we inherit from it.
But I changed it, because I was not able to solve the compatibility puzzle.

I deleted `system/Cache/Exceptions/ExceptionInterface.php`, because I didn't see the need for it.
But it is technically BC break. Should I revert?

**Comment by paulbalandan** [comment]
> I deleted `system/Cache/Exceptions/ExceptionInterface.php`, because I didn't see the need for it.
> But it is also technically BC break. Should I revert?

Yes please. Just deprecate it instead.

**Comment by paulbalandan** [comment]
With the interface being deprecated, I think `Cache` should now be implementing the framework's generic `ExceptionInterface` instead. I have seen you made that in one of your commits but now it's gone?

**Comment by kenjis** [comment]
> With the interface being deprecated, I think Cache should now be implementing the framework's generic ExceptionInterface instead. I have seen you made that in one of your commits but now it's gone?

Yes, I deleted the commit.

> I think Cache should now be implementing the framework's generic ExceptionInterface

Okay, I will do it again.

**Review by paulbalandan — APPROVED** [review]

**Comment by kenjis** [comment]
Changed interface to implement:
- CacheException

Made the constructor final:
- Cookie
- CookieStore
- CacheException
- CastException
- CLIException
- ConfigException
- DataException
- DownloadException
- EncryptionException
- FileException
- FileNotFoundException
- FormatException
- FrameworkException
- PageNotFoundException

Depreacted:
- CodeIgniter\Cache\Exceptions\ExceptionInterface

**Comment by MGatner** [comment]
Why the `final` on `Cookie` and `CookieStore`? This seems unnecessarily limiting.

**Comment by kenjis** [comment]
@MGatner Because they have `new static()`.
https://github.com/codeigniter4/CodeIgniter4/blob/7b9a7b25072066eccd0c497a1acb3fe63b05712c/system/HTTP/Cookie/Cookie.php#L225-L236

**Comment by MGatner** [comment]
🤦‍♂️

**Comment by paulbalandan** [comment]
As a cookie has predefined attributes, except for the `raw` option here, which we pass to the constructor of `Cookie`, I don't think it is necessary for users to add additional arguments in their own implementations.

**Comment by MGatner** [comment]
It think this is ready? @paulbalandan if you're good with it please proceed.

**Pull request merged**
