### PR TITLE
ext-json in composer.json

### PR DESCRIPTION
**Pull request by nowackipawel**
**Description**
ext-json in composer

### CODE REVIEW

**Comment by nowackipawel** [comment]
Possibly it is but there are many IDEs which shows warning when there is no ext-json specified in composer (ie phpstorm)

**Comment by lonnieezell** [comment]
I believe the ext-json package refers to the old one from PECL, which we definitely do not require. Where does PHP Storm show an error related to that? That's what I use daily and haven't noticed it.

**Comment by nowackipawel** [comment]
Here it is:
screenshot_2018-11-26_22-42-48

**Comment by lonnieezell** [comment]
Ah, just found more information about this error, also: https://medium.com/@luis.barros.nobrega/ext-json-is-missing-in-composer-json-what-is-this-700a1fcad966

In that case - good catch. :) Merging.

**Pull request merged**
