### PR TITLE
JSON Cast exception test cases

### PR DESCRIPTION
**Pull request by atishamte**
W.r.t #512 Adding test scenarios to increase the coverage of Cast Exception
WIP JSON Cast exception test cases.

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [x] Conforms to style guide

### CODE REVIEW

**Comment by atishamte** [comment]
@lonnieezell @jim-parry, I am trying to write the test case for the private method castAsJson() of Entity Class.
Below is my code for the test scenario.
```
public function testCastAsJSONSyntaxError()
{
	$entity = new Entity();
	$method = $this->getPrivateMethodInvoker($entity,'castAsJson');
		
	$this->expectException(CastException::class);
	$this->expectExceptionMessage('Syntax error, malformed JSON');

	$method("'{ bar: \"baz\" }'", true);
}
```
At the time of build, I am getting error like,
```
1) CodeIgniter\EntityTest::testCastAsJSONSyntaxError
Failed asserting that exception of type "CodeIgniter\Exceptions\CastException" is thrown.
```

Could you please help me out with this. So I will be able to generate test scenarios.

**Comment by jim-parry** [comment]
It looks like you are trying to json_decode a JSON string and expecting that to trigger an exception. That doesn't sound right.
Wouldn't you want to give the method something that can't be json_decoded? eg "( this is bad"

**Comment by atishamte** [comment]
What I am asking, Is this the correct way to implement the test scenarios?

**Comment by jim-parry** [comment]
Yes, it is reasonable.
Normally, however, you would thoroughly test on your system before pushing (and ending up with a bunch of commits), rather than using travis-ci to see if they work. Do you have the unit tests running on your system?

**Comment by atishamte** [comment]
I have tried but the system is not able to configure XDebug. I have tried many times but no success.
Also, I do not have Postgre, so all the test scenarios of it give an error.

**Pull request merged**
