### PR TITLE
chore: fix Upload coverage results to Coveralls / coveralls

### LINKED ISSUE #7941: Dev: Coveralls Uncaught Error: Class "Config\Autoload" not found
> PHP Fatal error:  Uncaught Error: Class "Config\Autoload" not found in /home/runner/work/CodeIgniter4/CodeIgniter4/system/Test/Mock/MockAutoload.php:16

See https://github.com/codeigniter4/CodeIgniter4/pull/7924#issuecomment-1717491085

Ref https://github.com/sebastianbergmann/phpcov/issues/101

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #7941

Fixes the following error:
> PHP Fatal error: Uncaught Error: Class "Config\Autoload" not found in /home/runner/work/CodeIgniter4/CodeIgniter4/system/Test/Mock/MockAutoload.php:16

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [] User guide updated
- [] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
Coverage report generated!

```
Run jq '.autoload."psr-4" += {"Config\\": "app/Config/"}' composer.json > temp.json && mv temp.json composer.json
  jq '.autoload."psr-4" += {"Config\\": "app/Config/"}' composer.json > temp.json && mv temp.json composer.json
  composer dump-autoload
  vendor/bin/phpcov merge --clover build/logs/clover.xml build/cov
  shell: /usr/bin/bash -e {0}
  env:
    COMPOSER_PROCESS_TIMEOUT: 0
    COMPOSER_NO_INTERACTION: 1
    COMPOSER_NO_AUDIT: 1
    COMPOSER_CACHE_FILES_DIR: /home/runner/.cache/composer/files
Generating optimized autoload files
Generated optimized autoload files containing 5608 classes
phpcov 8.2.1 by Sebastian Bergmann.

Generating code coverage report in Clover XML format ... done
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/6254242090/job/16981942317

**Comment by kenjis** [comment]
This PR fixes the current GitHub Action check failure.
Please approve.

**Comment by paulbalandan** [comment]
I think I forgot the reason why. Why do we not add `Config\\` psr4 mapping to composer.json in the first place?

**Comment by kenjis** [comment]
We removed it in #5824

**Review by paulbalandan — APPROVED** [review]

**Pull request merged**
