### PR TITLE
In method find returns uniform data

### PR DESCRIPTION
**Pull request by Sosko**
If find is used like: `$model->where("column", "5")->find()`, the ci4 returned array like [0->["id"=>1, "column"=>5]]. But mine opinion is, that it will be better to return only the first row

Each pull request should address a single issue and have a meaningful title.

**Description**
Explain what you have changed, and why.

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

---------Remove from here down in your description----------

**Notes**
- Pull requests must be in English
- If the PR solves an issue, reference it with a suitable verb and the issue number
(e.g. fixes <hash>12345)
- Unsolicited pull requests will be considered, but there is no guarantee of acceptance
- Pull requests should be from a feature branch in the contributor's fork of the repository
  to the develop branch of the project repository

### CODE REVIEW

**Comment by MGatner** [comment]
I like the concept but this is not something we can do in the framework. It would make a good addition to your `BaseModel`, where you detect certain kinds of singleton results based on database keys and flatten the array.

**Comment by Sosko** [comment]
I don't get it
In your documentation:

> find()
> Returns a single row where the primary key matches the value passed in as the first parameter:

So why not returns directly first row?

**Comment by michalsn** [comment]
@Sosko Because it's designed to work this way. Please read also other lines of the user guide regarding the `find()` method.
> If no parameters are passed in, will return all rows in that model’s table, effectively acting like findAll(), though less explicit.

You're not passing any parameters. The proposed change would break functionality of the Model for many people.

In general, we're always open for improvements to the Model class (and CodeIgniter) but sadly this particular change cannot be accepted - sorry.

**Comment by Sosko** [comment]
I'm really apologise to you, I'm mist that line.
But my opinion, that the `find` method, should always return only one row.
Thank you for your time

**Pull request closed without merging**
