### PR TITLE
Enable `ensure_single_space` option of `whitespace_after_comma_in_array`

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
```console
$ vendor/bin/php-cs-fixer describe whitespace_after_comma_in_array
Description of whitespace_after_comma_in_array rule.
In array declaration, there MUST be a whitespace after each comma.

Fixer is configurable using following option:
* ensure_single_space (bool): if there are only horizontal whitespaces after the comma then ensure it is a single space; defaults to false 

Fixing examples:
 * Example #1. Fixing with the default configuration.
   ---------- begin diff ----------
   --- Original
   +++ New
   @@ -1,2 +1,2 @@
    <?php
   -$sample = array(1,'a',$b,);
   +$sample = array(1, 'a', $b, );

   ----------- end diff -----------

 * Example #2. Fixing with configuration: ['ensure_single_space' => true].
   ---------- begin diff ----------
   --- Original
   +++ New
   @@ -1,2 +1,2 @@
    <?php
   -$sample = [1,2, 3,  4,    5];
   +$sample = [1, 2, 3, 4, 5];

   ----------- end diff -----------
```

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by kenjis — APPROVED** [review]

**Review by MGatner — APPROVED** [review]
Someone tried so hard to align the multidimensional arrays 😉 I'm good with this.

**Comment by MGatner** [comment]
@paulbalandan What's the plan for getting these updated in the coding standards repo?

**Comment by paulbalandan** [comment]
I just made a release hours ago. 😊

**Comment by MGatner** [comment]
🤦‍♂️ I just scrolled up and saw that. Thank you!!

**Pull request merged**
