### PR TITLE
add ability for nested language definition

### PR DESCRIPTION
**Pull request by samsonasik**
So, the language file can have something like:

```php
<?php
// Nested.php
return [
   'a' => [
	   'b' => [
		   'c' => [
			   'd' => 'e',
		   ],
	   ],
   ],
];
```

and can be called with `lang('Nested.a.b.c.d');`

**Checklist:**
- [x] Securely signed commits
- [x] Unit testing, with >80% coverage
- [x] User guide updated

### CODE REVIEW

**Comment by samsonasik** [comment]
travis build green 🎉

**Comment by lonnieezell** [comment]
This needs a mention in the docs and then it's good to go.

**Comment by samsonasik** [comment]
@lonnieezell  I've updated documentation for support nested language definition addition.

**Comment by lonnieezell** [comment]
Looks good. Thanks.

**Pull request merged**
