### PR TITLE
remove useless "raw html"

### PR DESCRIPTION
**Pull request by totoprayogo1916**
**Description**
I think it's useless,
```
.. raw:: html	

  <div class="custom-index container"></div>
```

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
I don't think these have any purpose. @paulbalandan do you know?

**Comment by paulbalandan** [comment]
The `raw:: html` actually embeds the following HTML into the generated HTML file instead of displaying it. I'm not sure if the div classes are actually used or defined in the user guide's CSS.

**Comment by paulbalandan** [comment]
@totoprayogo1916 can you show a before and after render of the user guide from this PR?

**Comment by totoprayogo1916** [comment]
@paulbalandan : its found at [contributing/documentation](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/documentation.rst)

but when render is not effect ,
after render,  it just create empty div tag like:
image

**Comment by paulbalandan** [comment]
@totoprayogo1916 yes it will just be put there. Can you show me what the page looks like with this div and after removing it. I am thinking maybe this div is controlling the `clear: both` css property. But if there's no noticeable change, I am fine removing those blocks.

**Comment by totoprayogo1916** [comment]
Sample from https://github.com/codeigniter4/CodeIgniter4/pull/4131/files#diff-438c1b41228e87925336e3c0af80780be95bf8bea65ee11efa4ec91fbc89c930

before: 
image

after: 
image

**Comment by totoprayogo1916** [comment]
and no specific CSS here
image

**Comment by paulbalandan** [comment]
Then, it is really useless. 😂

**Review by paulbalandan — APPROVED** [review]

**Pull request merged**
