### PR TITLE
id attribute support added for csrf_field

### PR DESCRIPTION
**Pull request by nowackipawel**
i.e. useful in autocomplete forms (it is faster to reach this field by id than by name or its position in form)

Each pull request should address a single issue, and have a meaningful title.

### CODE REVIEW

**Comment by nowackipawel** [comment]
@lonnieezell : 
hi there, there is one functionality missing. it is gr8 that we could specify id attribute using this function but .... there is still issue if we want to specify it via "form_open" function. 

What do you think to specify it like this?:

```
function form_open('',  ['csrf_id' => 'new-id'])
```

Honestly I don't like this idea cuz this attribute does not like naturally ... do you have any ideas to achieve it? It will be great to have possibility to define csrf field attribute in form_open as well.

**Comment by lonnieezell** [comment]
There's not an elegant way that I can really think of for that. The bigger question is - how important is it to be able to customize the id for this?

**Comment by nowackipawel** [comment]
Using forms which can be sent by regular post or by javascript call is good to be able to get value of csrf value easily. Additionally getting this value by elements id is the most efficient way .
Thx.

**Comment by nowackipawel** [comment]
PR#1633

**Comment by nowackipawel** [comment]
#1633

**Pull request merged**
