### PR TITLE
docs: add note for case-sensitive file systems

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
- add note for case-sensitive file systems

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [x] User guide updated
- [] Conforms to style guide

### CODE REVIEW

**Comment by ddevsr** [comment]
How about note this for installation & troubleshooting?

**Comment by kenjis** [comment]
Thanks! Adding in troubleshooting seems good.

installation? in where?

**Comment by ddevsr** [comment]
In here https://codeigniter4.github.io/CodeIgniter4/installation/running.html?

**Comment by cijagani** [comment]
This is actually depending on OS. ex. windows file system is case insensitive, and Linux file system is fully case sensitive.

**Review by MGatner — APPROVED** [review]

**Comment by kenjis** [comment]
Added in installation/troubleshooting.rst and installation/running.rst.

**Comment by kenjis** [comment]
> This is actually depending on OS. ex. windows file system is case insensitive, and Linux file system is fully case sensitive.

It depends on Filesystem.
On macOS, HFS+ and APFS can be configured as case sensitive when you format a filesystem.
On Windows, there are Case sensitivity options for mounting a drive in WSL.
See https://learn.microsoft.com/en-us/windows/wsl/case-sensitivity

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @kenjis

**Pull request merged**
