### PR TITLE
Feat add events for insertBatch()/updateBatch()

### PR DESCRIPTION
**Pull request by pjsde**
Add before and after events for ``BaseModel::insertBatch()`` and ``BaseModel::updateBatch()`` methods as 
[mentioned in the forum](https://forum.codeigniter.com/showthread.php?tid=80989)

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
Thank you for sending this PR!

Can you add about this in the changelog?
See https://github.com/codeigniter4/CodeIgniter4/blob/4.3/user_guide_src/source/changelogs/v4.3.0.rst#enhancements

**Review by MGatner — APPROVED** [review]
Very nice PR, and enhancement! We will probably be expanding Model events soon to include the original method input but these can be expanded when the other callbacks are as well. 

Awaiting the changelog request, but otherwise good by me.

**Comment by pjsde** [comment]
@kenjis

> Can you add about this in the changelog?

Done.

By the way, can you tell me what is the criteria for knowing when to update the changelog?

**Review by kenjis — APPROVED** [review]

**Comment by kenjis** [comment]
> By the way, can you tell me what is the criteria for knowing when to update the changelog?

- all security bug fixes
- all breaking changes
- all enhancements
- other behavior changes
- deprecations
- major bug fixes

Ref, https://codeigniter4.github.io/CodeIgniter4/changelogs/v4.2.0.html

**Comment by pjsde** [comment]
@kenjis Thanks for your inform

**Pull request merged**
