### PR TITLE
refactor: replace $e->getMessage() with $e in log_message()

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Depending on exception classes, but generally `(string) $e` has more info than `$e->getMessage()`.

<s>If this is not BC, then I would change the base branch to `develop`. </s>

`$e->getMessage()`:
```
ERROR - 2022-06-23 19:09:15 --> Cookie object with name "unknown" and prefix "" was not found in the collection.
```
`$e`:
```
ERROR - 2022-06-23 19:09:31 --> CodeIgniter\Cookie\Exceptions\CookieException: Cookie object with name "unknown" and prefix "" was not found in the collection. in /Users/kenji/work/codeigniter/CodeIgniter4/system/Cookie/CookieStore.php:114
Stack trace:
#0 /Users/kenji/work/codeigniter/CodeIgniter4/system/Cookie/CookieStore.php(114): CodeIgniter\Cookie\Exceptions\CookieException::forUnknownCookieInstance(Array)
#1 /Users/kenji/work/codeigniter/CodeIgniter4/system/HTTP/ResponseTrait.php(635): CodeIgniter\Cookie\CookieStore->get('unknown', '')
#2 /Users/kenji/work/codeigniter/CodeIgniter4/app/Controllers/Home.php(14): CodeIgniter\HTTP\Response->getCookie('unknown')
#3 /Users/kenji/work/codeigniter/CodeIgniter4/system/CodeIgniter.php(862): App\Controllers\Home->index()
#4 /Users/kenji/work/codeigniter/CodeIgniter4/system/CodeIgniter.php(452): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 /Users/kenji/work/codeigniter/CodeIgniter4/system/CodeIgniter.php(346): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /Users/kenji/work/codeigniter/CodeIgniter4/public/index.php(55): CodeIgniter\CodeIgniter->run()
#7 /Users/kenji/work/codeigniter/CodeIgniter4/system/Commands/Server/rewrite.php(43): require_once('/Users/kenji/wo...')
#8 {main}
```

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by MGatner — APPROVED** [review]
Nice touch. Modifying log entries does not affect our API, I would not consider this a breaking change at all - fine by me to switch branches.

**Review by paulbalandan — CHANGES_REQUESTED** [review]
We have a user who is an advocate of `declare(strict_types=1);`. Can you cast to string the `$e` so that string is still passed to `$message`? I don't want to read another forum post or issue regarding this, please.

**Comment by MGatner** [comment]
Exceptions are already Stringable: https://www.php.net/manual/en/exception.tostring.php

... so are allowed without casting.

**Comment by MGatner** [comment]
Nope, you were right @paulbalandan:

> If strict typing is enforced (with declare(strict_types=1) at the top of the file), an explicit string cast is required

I didn't realize that difference in behavior - unfortunate.

**Review by MGatner — APPROVED** [review]

**Review by paulbalandan — APPROVED** [review]

**Pull request merged**
