### PR TITLE
Double // in url in URI Routing example (Using Named Routes) 

### PR DESCRIPTION
**Pull request by gremirarunico**
This is a very stupid edit, just a typo in the url of example.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Review by datamweb — APPROVED** [review]

**Comment by datamweb** [comment]
@gremirarunico thank you!

Please sign  the all commits:

https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#gpg-signing-old-commits

**Comment by gremirarunico** [comment]
Done. I am sorry. This is the first time I sign a commit, I didn't think it was necessary.

**Comment by kenjis** [comment]
Please don't remove the checklist.

**Comment by kenjis** [comment]
If you learn to use git, you can easily remove the commit for another issue.
But that is a minor fix on the docs, so I will merge this PR.

Please send one PR for one issue next time.

**Review by kenjis — APPROVED** [review]

**Comment by gremirarunico** [comment]
> If you learn to use git, you can easily remove the commit for another issue. But that is a minor fix on the docs, so I will merge this PR.

Thank you for your understanding. Programming is a hobby for me, so there are still some significant gaps in my knowledge of Git that I need to address. I promise to be more attentive next time. Have a great day!

**Pull request merged**
