### PR TITLE
refactor: replace `time()` with Time into `Cache`, `Database` and `Test` class.

### PR DESCRIPTION
**Pull request by ping-yee**
**Description**
See #6815 

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
Please remove *Ignored error pattern* in `phpstan-baseline.neon.dist`.
```
Run vendor/bin/phpstan analyse
Note: Using configuration file /home/runner/work/CodeIgniter4/CodeIgniter4/phpstan.neon.dist.
   0/434 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
 220/434 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░]  50%
 434/434 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

Error: Ignored error pattern #^Comparison operation "\>" between int\<1, max\> and \(array\|float\|int\) results in an error\.$# in path /home/runner/work/CodeIgniter4/CodeIgniter4/system/Cache/Handlers/FileHandler.php was not matched in reported errors.
Error: Comparison operation ">" between int and (array|float|int) results in an error.
 ------ ----------------------------------------------------------------------- 
  Line   system/Cache/Handlers/FileHandler.php                                  
 ------ ----------------------------------------------------------------------- 
         Ignored error pattern #^Comparison operation ">" between int<1,        
         max> and \(array\|float\|int\) results in an error\.$# in path         
         /home/runner/work/CodeIgniter4/CodeIgniter4/system/Cache/Handlers/Fil  
         eHandler.php was not matched in reported errors.                       
  245    Comparison operation ">" between int and (array|float|int) results in  
         an error.                                                              
 ------ ----------------------------------------------------------------------- 
```

**Comment by ping-yee** [comment]
I personally agree that the class provided by CI4 are also used in the underlying development of CI4, so that it will be more convenient for expansion and maintenance in the future.
What's more, `time::now` is a static method. Although it is not as simple and fast as the built-in method, it will not use too many resources.

**Comment by kenjis** [comment]
The main purpose for this change is improving testability.
We cannot change the `time()` return value, so we cannot write proper test code.
Currently we have some fragile test codes that depend on real time.
These rarely fail due to test execution time.

> Creating a standard way of accessing the clock would allow interoperability during testing, when testing behavior that has timing-based side effects. Common ways to get the current time include calling \time() or new \DateTimeImmutable('now'). However, this makes mocking the current time impossible in some situations.
https://www.php-fig.org/psr/psr-20/

**Comment by kenjis** [comment]
> CodeIgniter4's time class is based on PHP's built-in DateTimeZone, which provides many convenient methods. If we could also use CodeIgniter4's own libraries in CodeIgniter4's core classes, we might be able to achieve greater consistency and maintainability in CodeIgniter4 source code.

Yes, we should use `Time` in all the framework code.

**Review by kenjis — APPROVED** [review]

**Comment by kenjis** [comment]
I'm going to merge this for consistency. If there is performance issues, we should take care of all the places.

**Comment by kenjis** [comment]
Thank you! @ping-yee

**Pull request merged**
