### PR TITLE
Better debug routes

### PR DESCRIPTION
**Pull request by enix-app**
**Description**
See the title above.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by enix-app** [comment]
Screen capture:

Screenshot 2020-02-18 03:47:54

**Comment by lonnieezell** [comment]
@enix-app Are you able to address @MGatner 's requests in the next couple of days? We're shooting for a release next Monday and would love to include this.

**Comment by MGatner** [comment]
Handled via #2587

**Comment by enix-app** [comment]
Sorry, but thank you.

**Pull request closed without merging**
