### PR TITLE
test for CodeIgniter\Config\Services::email()

### PR DESCRIPTION
**Pull request by samsonasik**
Test for `CodeIgniter\Config\Services::email()`. Make `CodeIgniter\Config\Services` class 100% tested.

**Checklist:**
- [x] Securely signed commits
- [x] Unit testing, with >80% coverage

### CODE REVIEW

**Comment by MGatner** [comment]
You probably thought this would be a quick PR, but I have a request for you to consider. It’s been on my list for a while to write a `MockEmail` class. It would essentially be an extension of the Email class but instead of sending it would store an array of the parameters that could be retrieved. Or something along those lines. Would you be interested in taking this on? Could make this part of a larger update to Email before the class gets rewritten.

**Comment by samsonasik** [comment]
Do you think the class will be `CodeIgniter\Test\Mock\MockEmail` ? mock 28 public methods ? or do you have list of methods that needs to be mocked?

**Comment by MGatner** [comment]
Yes that’s the class. I haven’t looked through the methods but my guess is only the actual send would need to be mocked. I can look when I’m not on mobile and specify, but I also trust your judgement.

**Comment by samsonasik** [comment]
I created separate PR #2788 for new MockEmail cass.

**Pull request merged**
