### PR TITLE
fix: `spark routes` shows 404 error when using regex

### LINKED ISSUE #6276: Bug: `spark routes` show error when using custom placeholder (regex)
### PHP Version

7.4

### CodeIgniter4 Version

4.2.1

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

MariaDB

### What happened?

when run `php spark routes`
show 404 error like:
image

### Steps to Reproduce

add route
```php
// app/Config/Routes.php
$routes->get('detail/([a-z0-9]{40})', 'User::detail/$1');
// or add using custom placeholder

$routes->addPlaceholder('uid', '[a-z0-9]{40}');
$routes->get('detail/(:uid)', 'User::detail/$1');
```
then run 
```bash
php spark routes
```

### Expected Output

show route lists as expected

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #6276

**How to Test**
```php
$routes->get('detail/([a-z0-9]{40})', 'User::detail/$1');
```

Before:
```console
ERROR: 404
Can't find a route for 'get: detail/([a-z0-9]{40})'.
```

After:
```console
+--------+-----------------------+------------------------------------------+----------------+---------------+
| Method | Route                 | Handler                                  | Before Filters | After Filters |
+--------+-----------------------+------------------------------------------+----------------+---------------+
| GET    | /                     | \App\Controllers\Home::index             |                | toolbar       |
| GET    | detail/([a-z0-9]{40}) | \App\Controllers\User::detail/$1         | <unknown>      | <unknown>     |
| CLI    | ci(.*)                | \CodeIgniter\CLI\CommandRunner::index/$1 |                |               |
+--------+-----------------------+------------------------------------------+----------------+---------------+
```

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by iRedds** [comment]
I think it would make more sense to catch the exception in FilterFilder::find()

**Comment by kenjis** [comment]
@iRedds Thanks. I was confusing `FilterFinder` with `Filters`.

**Review by totoprayogo1916 — APPROVED** [review]

**Review by MGatner — APPROVED** [review]
I'm not sure how this fixes the issue but if it does then I'm good with it.

**Comment by kenjis** [comment]
This error is because of the current limitation of the functionality.
We need a real route (without regex) to find its filters, but we can't get a real route from the regex route.
So it tries to find filters for the route `detail/([a-z0-9]{40})`, but there is no such a route.

**Pull request merged**
