### PR TITLE
Add apidocs action

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
Adds the action to update API docs. ~~I have made this barely working up to `Make the new API docs` step. The deploy step fails for the username. Perhaps it is because I don't have credentials to push to `codeigniter4/api` in my testing.~~

~~Another is the use of the phar file. I'm more inclined to download the phar file per run rather than maintain the phar in the codebase so as to save disk space. But, I cannot make the download through curl successful. But if you think otherwise, it's fine.~~

After a series of runs, had finally made this turn green.
[Workflow run](https://github.com/paulbalandan/CodeIgniter4/actions/runs/157498787)
[API push](https://github.com/paulbalandan/api)

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
@paulbalandan when I was creating the deployment action I forked all the affected repos and modified the organization section of the action so I can test it local to my GitHub account first. Might be a solution if you think there is a permissions issue.

**Comment by paulbalandan** [comment]
Wow. Thanks! I'll try this later this evening.

**Comment by paulbalandan** [comment]
I think this is ready. Requesting review from @lonnieezell or @MGatner .

**Comment by MGatner** [comment]
Were you able to test it local to your org? If so could you link action results please?

**Comment by paulbalandan** [comment]
Kindly see the link above.

**Comment by MGatner** [comment]
“Process exited with code 23”

https://github.com/codeigniter4/CodeIgniter4/actions/runs/157699136

**Comment by paulbalandan** [comment]
Didn't see that coming. I'll check later in the morning what is missing still.

**Comment by MGatner** [comment]
It could be an issue for @lonnieezell, like ensuring the secret token has access to the API repo.

**Comment by paulbalandan** [comment]
Visually inspecting this action's syntax against the green built run in mine, I think the problem is the missing `cd ./source` before the curl call. Might have overlooked that while copying. I'll send a PR for that later.

**Pull request merged**
