### PR TITLE
Cookie final touch

### PR DESCRIPTION
**Pull request by mostafakhudair**

### CODE REVIEW

**Review by paulbalandan — COMMENTED** [review]
I'm sorry but I do not agree to consolidating the expires methods. The current implementation wants to achieve  a "fluent" interface in interacting with the Cookie and the proposed changes makes this "less fluent". On "strict" static analysis, (i.e. using phpstan-strict-rules), this change will fail because it cannot determine whether the result is string or int based on implementation alone. Another is on the 3 withExpire** methods. While the two is much more of an addon, it is much more user friendly to use "withExpired" to quickly get an expired cookie. We're doing our users a good UX with this.

**Comment by samsonasik** [comment]
Your commit seems mixed with develop branch which make harder to review. Please rebase.

**Comment by paulbalandan** [comment]
I'm sorry but still I cannot accept this one. Thanks for your time, though.

**Comment by mostafakhudair** [comment]
isn't Cookie::withExpiresAt() gives the same result of Cookie::withExpired()?

**Pull request closed without merging**
