### PR TITLE
[Rector] Apply Full PHP 7.3 Rector Set List (Skip JsonThrowOnErrorRector & StringifyStrNeedlesRector)

### PR DESCRIPTION
**Pull request by samsonasik**
Alternative of https://github.com/codeigniter4/CodeIgniter4/pull/4600 with skip JsonThrowOnError & StringifyStrNeedlesRector.

**Checklist:**
- [x] Securely signed commits

### CODE REVIEW

**Review by paulbalandan — COMMENTED** [review]
I don't understand why the string cast is needed here.

**Comment by samsonasik** [comment]
That's based on the following https://wiki.php.net/rfc/deprecations_php_7_3#string_search_functions_with_integer_needle 

For function that return string from helper, eg, `singular()`, the helpers directory seems need to be registered to `Option::BOOTSTRAP_FILES`   to make skip function that already return string to no need re-cast.

**Comment by samsonasik** [comment]
We can skip `StringifyStrNeedlesRector` if it is unneeded check.

**Comment by paulbalandan** [comment]
Looking at the previous lines where the string casted variables arise, it seems these are already string so casting is unnecessary.

**Comment by samsonasik** [comment]
Ok, I skipped the `StringifyStrNeedlesRector` as well.

**Review by paulbalandan — APPROVED** [review]
Seems this is the better choice for now.

Just wondering, what are in the Set List for 7.3?

**Comment by samsonasik** [comment]
That's collection of rector rules for php 7.3, you can check at:
https://github.com/rectorphp/rector/blob/main/config/set/php73.php

**Comment by samsonasik** [comment]
I am merging it then, thank you @paulbalandan @MGatner for the review.

**Pull request merged**
