### PR TITLE
docs: update Model validation

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
From https://forum.codeigniter.com/showthread.php?tid=82814

- add note to Model Validation
- some tweaks

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
Please review this. This adds a note about the current behavior of in-model validation.

**Comment by tomatlscomm** [comment]
Hi.

Only the functions :
Model->validate
Model->update
Model->save (in the update process)

will ignore *required* unseted fields.

The functions :
Model->insert
Model->save (in the insert process)

will raise errors if *required* fields are unseted

**Comment by kenjis** [comment]
@tomatlscomm Thank you!
I didn't read the code carefully.
I've checked, and update the docs.

**Review by paulbalandan — APPROVED** [review]

**Comment by kenjis** [comment]
@paulbalandan Thanks!

**Pull request merged**
