### PR TITLE
[Rector] Apply MakeInheritedMethodVisibilitySameAsParentRector

### PR DESCRIPTION
**Pull request by samsonasik**
Make method visibility same as parent one with `MakeInheritedMethodVisibilitySameAsParentRector` rector rule.

**Checklist:**
- [x] Securely signed commits

### CODE REVIEW

**Review by paulbalandan — APPROVED** [review]

**Comment by MGatner** [comment]
These are all changes from `public` to `protected`, which technically is a breaking change. All the database classes have magic callers so should be fine; the Image handlers are "underscore protected" so should probably be protected and `@internal` anyway; the rest are all part of the Test namespace and seem appropriate for how those classes are intended to be used. 

If we want to proceed with these I would still like these documented appropriately.

**Comment by samsonasik** [comment]
@MGatner do you think it needs to be in the changelog https://github.com/codeigniter4/CodeIgniter4/blob/df419297c5f85c28e1cb27ac0dac66c408e6d0ea/user_guide_src/source/changelogs/v4.1.4.rst ?

**Comment by MGatner** [comment]
@samsonasik Yes, sorry to be unclear - that is precisely what I want. I think it is fine jus to list them out. 

```
Breaking Changes

The following methods were changed from "public" to "protected" to match their parent class methods and better align with their uses:
* Alpha\Beta::foo()
* Gamma\Delta::bar()

**Comment by samsonasik** [comment]
@MGatner changelog updated.

**Review by MGatner — APPROVED** [review]
Thanks!

**Pull request merged**
