### PR TITLE
fix: Route placeholder `(:any)` does not pass the whole value to controller

### LINKED ISSUE #6947: Bug: Route placeholder `(:any)` does not pass the whole value to controller
### PHP Version

8.1

### CodeIgniter4 Version

`develop` (ab55fe1994210b873d49246ed24a2141ea8a55fa)

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

n/a

### What happened?

`(:any)` does not pass the matched value, but passes the first segment only.

### Steps to Reproduce

```php
$routes->get('(:any)', 'Home::index/$1');
```

```php
<?php

namespace App\Controllers;

class Home extends BaseController
{
    public function index($any = '')
    {
        dd($any);
    }
}
```

Navigate to http://localhost:8080/abc/def ,
you will see `$any string (3) "abc"`.

### Expected Output

`$any string (3) "abc/def"`

### Anything else?

```php
<?php

namespace App\Controllers;

class Home extends BaseController
{
    public function index($any = '', $next = '')
    {
        dd($any, $next);
    }
}
```

Navigate to http://localhost:8080/abc/def ,
you will see:
```
$any string (3) "abc"
$next string (3) "def"
```

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #6947

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by samsonasik — APPROVED** [review]

**Review by michalsn — APPROVED** [review]

**Review by MGatner — APPROVED** [review]
Curious, I wonder if it has always been like this? I hope this isn't a surprise break for anyone!

**Comment by michalsn** [comment]
From what I see, the docs are just fine. Nothing has changed.

**Comment by kenjis** [comment]
This is a bug, but a breaking change. So I would like to move this to `4.3`.
I don't think there is any need to urgently fix this in 4.2, since it has been this way all along.

**Comment by kenjis** [comment]
Added the docs.

**Comment by kenjis** [comment]
> At least this is what I am used to from the CI3 times.

CI3 does not have `(:any)` in CI4. Do you mean you did that in CI3 with auto-routing?

> I understand the reason for this change from the perspective of the example provided in the tests, but maybe we should leave the current behavior of (:any) as it is and add another one which will behave as described in this PR? Something like (:any-segment) or something? I just think that the current behavior of the (:any) placeholder may be useful in many cases and changing it may break a lot of things.

This may be useful, but it seems we cannot implement it easily.

But I found the documentation that the behavior is not a bug.
> Note that a single (:any) will match multiple segments in the URL if present. For example the route:

```php
<?php
$routes->get('product/(:any)', 'Catalog::productLookup/$1');
```

> will match product/123, product/123/456, product/123/456/789 and so on. The implementation in the Controller should take into account the maximum parameters:

https://codeigniter4.github.io/CodeIgniter4/incoming/routing.html#examples

**Comment by michalsn** [comment]
> CI3 does not have (:any) in CI4. Do you mean you did that in CI3 with auto-routing?

Oh, there is `(:any)` in CI3 [https://codeigniter.com/userguide3/general/routing.html#examples](https://codeigniter.com/userguide3/general/routing.html#examples)

> But I found the documentation that the behavior is not a bug.

Okay, thanks for digging into it.

**Comment by kenjis** [comment]
@michalsn Do you mean `(:any)` in CI3 works like CI4's `(:any)`?
I think `(:any)` in CI3 is `(:segment)` in CI4. See #6957
Am I wrong?

**Comment by michalsn** [comment]
Yes, you might be right, and I confused it with auto-routing in CI3.

**Comment by kenjis** [comment]
My conclusion for now is that this behavior is a specification and cannot be changed. 

However, you should not add any placeholder after `(:any)`, and `(:any)` should be used only once in a route.

**Comment by mackxpall** [comment]
Telling me you are just - getting here.

**Comment by michalsn** [comment]
> However, you should not add any placeholder after (:any), and (:any) should be used only once in a route.

Sounds about right to me.

**Comment by kenjis** [comment]
Closed by #6960

**Pull request closed without merging**
