### PR TITLE
replaced language setting in APPPATH."Language"

### PR DESCRIPTION
**Pull request by SunilEver**
Fix issue #2354 

**Description**
Updated `CodeIgniter\Language\Language::requireFile()` to prefer APPPATH."Language" Directory

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
I like the idea but this is causing `testPrioritizedLocator()` to fail, which makes me believe that the priority load order still isn't working as expected.

**Comment by jim-parry** [comment]
Some problems with this PR:
- commits not GPG-signed
- unit testing not updated
- user guide not updated

**Comment by jim-parry** [comment]
@MGatner @lonnieezell Neither the user guide or code suggest anything about prioritizing one namespace over another, which appears to be the goal of the bug report / PR. Should App be prioritized?

**Comment by MGatner** [comment]
I think file locating needs to have an explicit hierarchy, which might vary depending on the component. `FileLocator` already uses the generic ordering: `System`, `Config`, `App`, `Modules`. The issue here is that `Language->requireFile()` essentially reverses the order, which could be misleading to anyone familiar with the regular hierarchy:
```
		$files   = Services::locator()->search($path);
...
		$strings = array_replace_recursive(...$strings);
```

As a regular module writer, I do think it is important for developers to be able to supply their own phrasing without modifying the module - so in this case I'm in favor of prioritizing `App` but maybe by pushing this to `FileLocator` instead of the override method here.

**Comment by MGatner** [comment]
I do think what this is addressing constitutes an issue, but I don't think this is the solution. `lang()` is a very high priority function as international-supported projects may call it hundreds of times in a single load, and this solution adds an additional filesystem search to every call:

`Services::locator()->locateFile($path)`

Any language files in `APPPATH` will already be included in `Services::locator()->search($path)`, it might just need to handle prioritizing a bit differently.

Additionally, this is causing tests to fail and the commit is not signed. Closing the PR, but I will open a corresponding issue so it doesn't get lost.

**Comment by erikkloeze** [comment]
> but I will open a corresponding issue so it doesn't get lost

Just had a look at the open issues, and no corresponding issue found. Just a reminder to prevent this issue being unresolved.

**Comment by MGatner** [comment]
The issue is linked directly above yours and has already been addressed. If you’re having a similar issue you could open a support thread on the forums.

**Comment by erikkloeze** [comment]
Noted issue [#2354](https://github.com/codeigniter4/CodeIgniter4/issues/2354) and the accompanying fix in [#2507](https://github.com/codeigniter4/CodeIgniter4/pull/2507). Doesn't the `array_replace_recursive` in **Language:319** (still) overwrite language adjustments made in `App` with the defaults in `vendor` - hence thereby not being able to adjust these?

**Pull request closed without merging**
