### PR TITLE
[4.4] refactor: moving RedirectException.

### PR DESCRIPTION
**Pull request by iRedds**
**Description**
Currently the ``RedirectException`` class is in the ``CodeIgniter\Router\Exceptions`` namespace.
I believe this exception is not related to routes but to the HTTP layer. Therefore, I propose to move it to the appropriate namespace.
The old class is marked as deprecated.

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
If there is code that throws `CodeIgniter\Router\Exceptions\RedirectException` in apps,
it will break.

Why don't you catch the deprecated class in the framework code for backward compatibility?

**Review by kenjis — APPROVED** [review]
LGTM!

**Review by michalsn — APPROVED** [review]
Nice.

**Comment by kenjis** [comment]
@iRedds Thank you!

**Pull request merged**
