### PR TITLE
Expressly forbid CLIRequest from running in non-CLI env

### PR DESCRIPTION
**Pull request by paulbalandan**
**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by sfadschm — APPROVED** [review]

**Comment by MGatner** [comment]
Should this throw system/CLI/Exceptions/CLIException.php ?

**Comment by sfadschm** [comment]
I would think that the CLIExceptions should rather be used when a user executes a CLI command in a wrong manner.
In the case here, a user tries to call a CLI-only service from browser (or not-CLI). Thats a different situation if you ask me.
However, I'm not sure if this distinction is a little picky...

Maybe this would make sense in the ConfigException, as services are located in Config?

**Comment by paulbalandan** [comment]
IMO `CLIException` should be thrown when it is running already in CLI and something went wrong. But here it is attempting to run in a non-CLI. I opted for the more generic `RuntimeException` as it is the safest. If I were to use a framework specific exception, then I would choose one under the HTTP namespace but I don't like creating a new static method just for that.

**Review by MGatner — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @paulbalandan

**Pull request merged**
