### PR TITLE
[Rector] Apply Rector : ListToArrayDestructRector

### PR DESCRIPTION
**Pull request by samsonasik**
Change `list()` to array destruct with `ListToArrayDestructRector` rector rule.

**Checklist:**
- [x] Securely signed commits

### CODE REVIEW

**Review by paulbalandan — COMMENTED** [review]
I have no questions for this except that can we make the array destructuring in a single line?

The current sniff for this makes the list call as multiline and it looks ugly when combined with aligned `=`.

**Comment by samsonasik** [comment]
Yes, that seems part of CodeIgniter Coding Standard that make it on before commit, run rector just use one line for it:

Screen Shot 2021-05-26 at 13 25 57

**Comment by samsonasik** [comment]
@paulbalandan implemented, I updated to use single line.

**Review by paulbalandan — APPROVED** [review]
Yes, the multilining should be reported in the `coding-standards` repo.

**Review by MGatner — APPROVED** [review]
I haven't looked at every change but I like this conceptually.

**Comment by MGatner** [comment]
We really need to address the code sniffing. I find myself using `--no-verify` on most of my commits because it screws up spacing, or insists `int` should be `integer`. We have another discussion going on whether to switch vendors - can we resurrect that thread and get this solved?

**Comment by paulbalandan** [comment]
> We really need to address the code sniffing. I find myself using `--no-verify` on most of my commits because it screws up spacing, or insists `int` should be `integer`. We have another discussion going on whether to switch vendors - can we resurrect that thread and get this solved?

We have this thread #4382 .

There's a suggestion to use ecs there, but I find it not easy to use IMO. For the `translations` repo, I have already switched that to php-cs-fixer.

**Comment by samsonasik** [comment]
is this merge-able for now or need to wait for the coding-standard to detect it ?

**Comment by paulbalandan** [comment]
I think we can merge this for now. Let us tackle the cs separately.

**Comment by samsonasik** [comment]
@paulbalandan @MGatner thank you for the review.

**Pull request merged**
