### PR TITLE
make Model::paginate() use default perPage from Config\Pager->perPage if $perPage parameter not passed

### PR DESCRIPTION
**Pull request by samsonasik**
Currently, the `$perPage` is default to `20` in `Model::paginate()` function. I think it should read from `config('Pager')->perPage` instead. I apply make default to null, and check if it is not passed, it will use the default `config('Pager')->perPage`

**Checklist:**
- [x] Securely signed commits
- [x] Unit testing, with >80% coverage

### CODE REVIEW

**Comment by samsonasik** [comment]
I've added unit test for use case change config('Pager')->perPage

**Comment by samsonasik** [comment]
travis build green 🎉

**Comment by samsonasik** [comment]
I've added check in `Pager` class to read `$perPage` from `Config('Pager')->perPage` to handle it when used in outside Model/Db related pagination.

**Comment by samsonasik** [comment]
I moved the handle per page null check to Pager class, use `$this->pager->getPerPage()` pulled from Pager instance to get final perPage value that will be used to make a limit query in the `Model::paginate()`

**Comment by samsonasik** [comment]
I updated `CodeIgniter\Config\Services::pager()` to use `config('Pager')` as well if no $config passed (null), instead of manual "new Config\Pager()" like in other services which uses `config()` function. It also make it testable in paginate in model test.

**Comment by samsonasik** [comment]
travis build green 🎉

**Comment by MGatner** [comment]
Definitely a good change, and a solid PR. Thanks as always @samsonasik

**Pull request merged**
