### PR TITLE
mysql connection throw correct  Exception type as per function comments

### PR DESCRIPTION
**Pull request by devorama**
**Description**
Throw correct exceptin type as per function comments
Was linked to this pull request
https://github.com/codeigniter4/CodeIgniter4/pull/3364
but had a fork/git version issue and redid fork and made sure develop branch is now in line

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by samsonasik** [comment]
actually, you don't need to re-create PR, `--force push` will work, but this is ok. Next time you create a new PR, you need to back to develop and pull latest develop first before create new branch.

**Comment by paulbalandan** [comment]
@devorama it seems your GPG signature was lost?

**Comment by devorama** [comment]
@paulbalandan  had to recreate all as I could not get git to work locally on my machine thus had todo everything via browser till now but sat last night till late recreating everything etc to get it to work locally on my machine, this I hope it all are all right I have the old signature and the new one still loaded on my profile and I can book in the code via git on my machine with the new one, I really hope it not a issue as git is really frustrating me running 2 seperate accounts on it is not as simple as setting up the config file in .ssh folder it just wont work, even making sure hte host in the .git/config is the same all just wont work thus I am really at a loss if it stil a issue for I really hoped and believed all is okay now

**Comment by michalsn** [comment]
Looks good to me, thanks!

**Pull request merged**
