### PR TITLE
Add XML tags normaliser

### LINKED ISSUE #3588: Bug pars xml
https://github.com/codeigniter4/CodeIgniter4/blob/f7dfb404fdd7bf7360fb4cab7f661527149dd157/system/Format/XMLFormatter.php#L94

1. arrayToXML(['BBB096630BD' => 'data...'], ...) - Its ok
2. arrayToXML(['096630FR' => 'data...'], ...)         - No ok

The problem with the second example is that it starts with a digit, and passes the check for! is_numeric, and when parsing back into an object, this xml gives an error.

The solution I think is to add a check for the first character not a digit and if a digit then add 'item'

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
Fixes #3588 

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by demortx** [comment]
This fix does not work on nested arrays, I will now present a variant of what it does, only a little later I can give the original array and it deleted some of the data from it



`{
  "data": {
    "itemmaster_account": {
      "email": "demo@gmail.com",
      "phone": {},
      "shield": "0",
      "affiliate": {},
      "data_create": "2020-06-26 14:17:51",
      "itemlast_login": "2020-09-03 12:17:04",
      "itemlast_ip": "*.*.*.*",
      "email_valid": "1",
      "itemlang": "ru",
      "telegram": "demo",
      "status": "0",
      "select_sid": "12",
      "platform": "web"
    },
    "vote": {
      "itemlist": {}
    },
    "user_data": {
      "account": {
        "KMWdemo": {
          "info": {
            "is_banned": "true",
            "itemlast_logout": {},
            "itemlast_ip": {},
            "email": "demo@gmail.com"
          },
          "char_list": {},
          "status": "1"
        },
        "itemMQFdemo": {
          "info": {
            "is_banned": "false",
            "itemlast_logout": "2020-07-08 10:56:12",
            "itemlast_ip": "*.*.*.*",
            "email": "demo@gmail.com"
          },
          "char_list": {},
          "status": "1"
        }
      },
      "itemmanager": {
        "item0": {
          "itemmid": "29739",
          "email": "demo@mail.ru",
          "phone": {},
          "status": "0",
          "itemlast_login": "2020-08-16 17:33:40",
          "itemlast_ip": "*.*.*.*",
          "itemmn_status": "1"
        }
      },
      "itemlogs": {
        "item0": {
          "id": "0",
          "description": "Успешная авторизация на мастер аккаунт.",
          "ip": "*.*.*.*",
          "date": "2020-09-03 11:17:04"
        },
        "item1": {
          "id": "1",
          "description": "Успешная авторизация на мастер аккаунт.",
          "ip": "*.*.*.*",
          "date": "2020-09-03 11:14:13"
        },
        
      },
      "balance": "151.80",
      "discount": "0",
      "social": {},
      "warehouse": {},
      "support": {
        "count_answer": "0"
      }
    },
    "session_data": {
      "session_end": "2020-09-03 13:46:49",
      "session_id": "m_5f50bb89365886.92480181",
      "ip": "*.*.*.*"
    }
  },
  "success": "Вы успешно авторизовались в мастер аккаунт!"
}`


this example shows that this fix adds the prefix item to the normal key.  item...master_account

**Comment by paulbalandan** [comment]
I think I know where the fault is. @demortx can you try changing this line?
```diff
$key = preg_replace('/^[xml]+/iu', 'item$0', $key);
$key = preg_replace('/^(xml)+/iu', 'item$0', $key);
```

**Comment by MGatner** [comment]
This is looking good. Thanks @paulbalandan

**Comment by michalsn** [comment]
If this will fix it, I would like to see some test to cover this case with nested array.

**Review by MGatner — APPROVED** [review]

**Comment by MGatner** [comment]
@demortx Can you confirm this latest version fixes your issue?

**Comment by demortx** [comment]
Yes its ok 👌

**Pull request merged**
