### PR TITLE
failValidationError can take an array of errors

### PR DESCRIPTION
**Pull request by caswell-wc**
**Description**
Adjusted the ResponseTrait::failValidationError so it can take an array of validation errors

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by MGatner — CHANGES_REQUESTED** [review]
Unfortunately we cannot change the function signature like this because it will break any developer classes extending this. I do see how this functionality could be appealing though - how about adding a new method `failValidationErrors` with this functionality? We could even deprecate the old one so it could be removed down the road. See what the rest of the team thinks too...

**Review by paulbalandan — COMMENTED** [review]
Aside from the point of @MGatner , the method's name itself implies using a single error so allowing an array of errors here seems unnatural. `failValidationErrors` is not a bad idea though. Maybe we can go that route?

**Comment by caswell-wc** [comment]
@MGatner @paulbalandan Yeah, I was debating between the same approaches. I went the way I did because the body of both functions are exactly the same but I agree with both of your points so I pushed an update.

**Review by paulbalandan — APPROVED** [review]

**Comment by MGatner** [comment]
I would like both of your opinions on whether we should deprecate the `string` version.

**Comment by paulbalandan** [comment]
> I would like both of your opinions on whether we should deprecate the `string` version.

I don't have a strong opinion against deprecating it. Seems to me that having one authoritative version will be one less of a maintenance issue, so I'm good with deprecating the old one if you think so.

**Comment by caswell-wc** [comment]
I could be swayed either way. I agree with @paulbalandan about having one less function means less to maintain. If we are going to do that, I would think we would want to change the signature for failValidationErrors() so it can accept an array or a string.

**Comment by paulbalandan** [comment]
> I could be swayed either way. I agree with @paulbalandan about having one less function means less to maintain. If we are going to do that, I would think we would want to change the signature for failValidationErrors() so it can accept an array or a string.

Hmm okay. I think that's our way to go. Please do what's necessary.

**Comment by MGatner** [comment]
@caswell-wc please also add this to **user_guide_src/source/changelogs/v4.1.2.rst**

**Review by paulbalandan — APPROVED** [review]

**Review by MGatner — APPROVED** [review]

**Comment by MGatner** [comment]
Thanks @caswell-wc !

**Pull request merged**
