### PR TITLE
Fixed table alias is not working with softDeletes

### PR DESCRIPTION
**Pull request by jahmedk**
Created property (tableAlias) for handling alias in model

### CODE REVIEW

**Comment by WinterSilence** [comment]
table name can contain whitespaces: 
~~~sql
CREATE TABLE `to do` (`id` INT(11) NULL DEFAULT NULL) COLLATE='utf8_general_ci' ENGINE=InnoDB;
~~~

**Comment by WinterSilence** [comment]
@jahmedk I told you in issue - you must check by `Connection::tableExists($table)`. It's can be work as in other cases: `to as do` or `to do`.  do you try add only `$this->db->addTableAlias($table);`? why not fix it in `setTable($table)`?

**Comment by jahmedk** [comment]
Yes @WinterSilence you're right we should handle all possible cases

**Comment by jahmedk** [comment]
@paulbalandan according to @WinterSilence test case we must check Connection::tableExists($table) before creating alias in BaseBuilder and BaseModel

**Comment by WinterSilence** [comment]
@jahmedk what's about 2 last questions?

**Comment by jahmedk** [comment]
> table name can contain whitespaces:
> 
> ```sql
> CREATE TABLE `to do` (`id` INT(11) NULL DEFAULT NULL) COLLATE='utf8_general_ci' ENGINE=InnoDB;
> ```
?

**Comment by jahmedk** [comment]
@WinterSilence ??

**Comment by WinterSilence** [comment]
@jahmedk 
> do you try add only $this->db->addTableAlias($table);? why not fix it in setTable($table)?

**Comment by jahmedk** [comment]
> @jahmedk
> 
> > do you try add only $this->db->addTableAlias($table);? why not fix it in setTable($table)?

Because setTable is just setting the table property of CodeIgniter\Model and in the CodeIgniter\Database\BaseBuilder they are checking alias with whitespace i am thinking alias should be handle in CodeIgniter\Database\BaseBuilder.

**Comment by jahmedk** [comment]
> > @jahmedk
> > > do you try add only $this->db->addTableAlias($table);? why not fix it in setTable($table)?
> 
> Because setTable is just setting the table property of CodeIgniter\Model and in the CodeIgniter\Database\BaseBuilder they are checking alias with whitespace i am thinking alias should be handle in CodeIgniter\Database\BaseBuilder.

Your suggestion is good https://github.com/codeigniter4/CodeIgniter4/issues/4527#issuecomment-816260255

**Comment by WinterSilence** [comment]
@jahmedk don't understand you:

>  i am thinking alias should be handle in CodeIgniter\Database\BaseBuilder.

but your PR changed `Model`

**Comment by jahmedk** [comment]
> @jahmedk don't understand you:
> 
> > i am thinking alias should be handle in CodeIgniter\Database\BaseBuilder.
> 
> but your PR changed `Model`

Yes i did
But it is not complete

**Pull request closed without merging**
