### PR TITLE
[Rector] Re-run InlineIfToExplicitIfRector on Latest Rector 0.11.36

### PR DESCRIPTION
**Pull request by samsonasik**
With improved `InlineIfToExplicitIfRector` to allow any expr in right expr. 

Skipped for constant definition on `app/Config` and `system/Test/bootstrap.php` like:

```php
defined('SHOW_DEBUG_BACKTRACE') || define('SHOW_DEBUG_BACKTRACE', true);
```

**Checklist:**
- [x] Securely signed commits

### CODE REVIEW

**Comment by samsonasik** [comment]
tests error seems unrelated.

**Comment by samsonasik** [comment]
It is strange, test somewhat only error on this branch: 

```bash
➜  CodeIgniter4 git:(update-rector-inline-if) git clean -xfd app/ && vendor/bin/phpunit tests/system/Commands/ConfigurableSortImportsTest.php
PHPUnit 9.5.6 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.0.8 with Xdebug 3.0.4
Configuration: /Users/samsonasik/www/CodeIgniter4/phpunit.xml.dist

FF.                                                                 3 / 3 (100%)

Time: 00:01.010, Memory: 38.00 MB

There were 2 failures:

1) CodeIgniter\Commands\ConfigurableSortImportsTest::testPublishLanguageWithoutOptions
Failed asserting that two strings are not identical.

/Users/samsonasik/www/CodeIgniter4/tests/system/Commands/ConfigurableSortImportsTest.php:37

2) CodeIgniter\Commands\ConfigurableSortImportsTest::testEnabledSortImportsWillDisruptLanguageFilePublish
Failed asserting that two strings are not identical.

/Users/samsonasik/www/CodeIgniter4/tests/system/Commands/ConfigurableSortImportsTest.php:50

FAILURES!
Tests: 3, Assertions: 9, Failures: 2.

Generating code coverage report in Clover XML format ... done [00:01.898]
```

**Comment by samsonasik** [comment]
oh, cs fixed seems cause it.

**Comment by samsonasik** [comment]
All green 🎉

**Review by paulbalandan — APPROVED** [review]

**Review by MGatner — APPROVED** [review]

**Pull request merged**
