### PR TITLE
Use getMimeType instead of getClientMimeType.

### LINKED ISSUE #3979: Bug: RAR file detected as CSV
I've tried to upload an rar file, and use validation ext_in[rar]

It always fail. 

When i tried to check, the system always detect to csv (application/octet-stream) not as a rar file.

### PR DESCRIPTION
**Pull request by sfadschm**
Possibly fixes #3979 and #4084.

As stated in the PHPDoc, `getClientMimeType` is not trustable. As `File->getMimeType()` defaults to the same value that `getClientMimeType` instantly returns if `fileinfo` is not available, we can use this method to more reliably guess extensions.

I feel that this is also related to most of the `octet-stream` related issues that keep popping up recently, as the mime type provided by the client (browser) often defaults to that (e.g. #3921).

**Checklist:**
- [x] Securely signed commits
- [x] Conforms to style guide

### CODE REVIEW

**Comment by sfadschm** [comment]
Tests are passing locally. Not really sure why `fileA.txt` gets guessed as `csv`.

**Comment by michalsn** [comment]
Are the tests are really passing locally for you? From what I see calling `$file->getExtension()` is the same as calling `$file->guessExtension()`.

**Comment by sfadschm** [comment]
:-D I will go through the test steps and see where this happens. I feel the guessing enters the reverse search loop for some reason and thus returns `csv` as it always does.
Is `fileinfo` enabled in the Github tests?

**Comment by michalsn** [comment]
I just sat down at my computer to check it and tests are failing for me also. The mime type returned by the OS for this file is `application/octet-stream`. But... when I added some content to this file, it started to be recognized correctly.

**Comment by sfadschm** [comment]
Interesting, but would match the failing test upstream. What OS are you on? I'm on Win10.

**Comment by michalsn** [comment]
macOS and a virtual machine with Ubuntu, so the environment is similar to GitHub actions.
I got the same results on both.

**Comment by sfadschm** [comment]
Okay. I will try to add some content to it. 
Originally, `fileA` and `fileB` only contain a single line break. I found that in Windows if I remove the line break, they are detected as `application/empty`.
So maybe this is some issues with special character only files or such?

**Comment by michalsn** [comment]
> Originally, fileA and fileB only contain a single line break. I found that in Windows if I remove the line break, they are detected as application/empty.

Yes, here it acts similar, I get `inode/x-empty`. But I'm not gonna pretend I have an idea why it is happening 😅 I guess empty files just fallback to the default mime type automatically?

**Comment by sfadschm** [comment]
Seems like that. O would think the same for the original files. Maybe on Mac/Ubuntu a file with only line break is not detected as `text` because it does not consider special characters as text characters. If we aplly the other MIME type PR (or similar), these would return `null` as guessed extension, which I feel to be the most right, as no content type can be deduced from empty/special char only files.
How do you feel about this?

**Comment by michalsn** [comment]
Yes, I think it's correct and the `null` value would be desired in that case. Following what OS returns is the best thing we can do here.

**Comment by michalsn** [comment]
Oh.. and as for this PR I think we should modify those files (add content to them), so they can be recognized correctly.

**Comment by sfadschm** [comment]
Alright.
Can I add a `rar` file to the files also or is this considered unsafe?
Would be nice to also text with `non-text` mime types.

**Comment by michalsn** [comment]
I don't see a problem. Just keep the size really small, and the number of files you want to test sane 😄

**Comment by sfadschm** [comment]
Seems to work. Thanks @michalsn!

**Review by michalsn — APPROVED** [review]
It looks good. Seems like a big improvement to mime checking and also for testing it.

I have one thing I would change but maybe it's better to address this in a different PR (maybe this one which is in draft right now).

**Comment by sfadschm** [comment]
Alright, feel free to add to the draft or redraft :-)

**Review by paulbalandan — APPROVED** [review]

**Comment by michalsn** [comment]
Thank you @sfadschm!

**Pull request merged**
