### PR TITLE
Original email port

### PR DESCRIPTION
**Pull request by jim-parry**
This is the original Email port from CodeIgniter 3.
It is inelegant and tested by assumption only (it worked it CI3, right?).

It is, however, available "now", as a "better-than-nothing" provision for CodeIgniter 4's initial release.

I will continue to work on a more elegant and tested Email package, targeting 4.1.

### CODE REVIEW

**Comment by jim-parry** [comment]
Bit of a hit on code coverage :(

**Comment by MGatner** [comment]
Closed? Could this mean... Email 4.0?

**Comment by lonnieezell** [comment]
I'm cool with this if it was closed by mistake. Feel free to merge if that's the case.

**Comment by jim-parry** [comment]
Dropped by mistake, sorry.

**Pull request merged**
