### PR TITLE
Added ability to get clean phrase from time->humanize()

### PR DESCRIPTION
**Pull request by haugli92**
**Description**
Added parameter to humanize($rawPhrase = false) to get clean phrase.

rawPhrase = false : 20 hours ago | in 20 hours
rawPhrase = true  : 20 hours

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
This is an enhancement, and should go to `4.3` branch, not `develop`.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#if-you-sent-to-the-wrong-branch

**Comment by MGatner** [comment]
This is how Carbon does it. Chronos doesn't seem to have a "raw value" option. Normally I'd prefer a new method rather than a flag that changes behavior, like `humanInterval()` but I could go either way on this. If we do stick with the parameter I'd prefer to see it as an additive description:
* rawPhrase = false = takes away content

Versus:
* useQualifier = true = adds content

**Comment by kenjis** [comment]
There is no test code. Please write test code.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#unit-testing

And please add to changelog:
https://github.com/codeigniter4/CodeIgniter4/blob/4.3/user_guide_src/source/changelogs/v4.3.0.rst#libraries

**Comment by kenjis** [comment]
I also prefer a new method rather than a flag that changes behavior.

**Comment by kenjis** [comment]
No feedback. Closing.

If you still find this change useful, please submit another PR following the guidelines.
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md

Thank you.

**Pull request closed without merging**
