### PR TITLE
Fix Query Builder limit for SQL Server 2008

### PR DESCRIPTION
**Pull request by abydahana**
The Query Builder will throw an error on  SQL Server 2008 (Version 10.x) when using limit since it doesn't yet support offset. This commit is part of worked limitation from CodeIgniter 3 and has been tested on SQL Server 2008.

### CODE REVIEW

**Comment by samsonasik** [comment]
please run:

```bash
vendor/bin/rector process
```
and commit to fix rector notice.

**Comment by abydahana** [comment]
> please run:
> 
> ```shell
> vendor/bin/rector process
> ```
> 
> and commit to fix rector notice.

Any updates or another suggestion of this commit?

**Comment by samsonasik** [comment]
could you provide unit test for it? Thank you.

**Comment by abydahana** [comment]
Sure. How could i present the unit testing since it require the 3rd party DBMS such SQL Server? Please give me advice.

**Review by michalsn — CHANGES_REQUESTED** [review]
We can't use Live tests, but we can test it using Builder tests.

Please take a look here to see how we use `SQLSRVBuilder` to make test exclusively run with SQLSRV: https://github.com/codeigniter4/CodeIgniter4/blob/develop/tests/system/Database/Builder/JoinTest.php#L88

Based on this example it should be easy to do - you will be able to set desired DB version via `MockConnection`, I think.

**Comment by paulbalandan** [comment]
This may be useful for users of sql server but no activity has been made for testing this change. The last 2 commits are out of scope of the PR. Closing this for now. Please open a new PR if you can add tests for this.

**Pull request closed without merging**
