### PR TITLE
fix: View::renderSection() return type

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
From https://forum.codeigniter.com/showthread.php?tid=91082

The method should not use `echo`, because it has side effects.

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by neznaika0 — COMMENTED** [review]
The bug is old. I came across this a long time ago, not a serious mistake and I agreed with it.
Do you need a return test? For example,
`$section = $this->renderSection(”content") ?? ”Not content";`

**Comment by kenjis** [comment]
Added a test.

**Review by neznaika0 — APPROVED** [review]
Good

**Review by datamweb — APPROVED** [review]

**Review by michalsn — APPROVED** [review]

**Comment by ricctram** [comment]
ok thank you @kenjis .. do you think Is better to wait the 4.6.0 then?

**Comment by kenjis** [comment]
If you want this soon, patch `system/View/View.php` by yourself.
https://github.com/codeigniter4/CodeIgniter4/pull/8965/files#diff-4a0d588299e7596abc008b8c30cfbbdd51be730d1a8ddf945704a5efcbb68cec
As you see, the change is only in it.

**Pull request merged**
