### PR TITLE
Add boolean field conversion

### PR DESCRIPTION
**Pull request by krangadurai**
**Description**

Purpose: This commit integrates the conversion of specific fields to boolean values in the find method to ensure consistent data representation when returning API data.

MySQL Boolean Representation: In MySQL, boolean fields are typically stored as integers, with 1 representing true and 0 representing false. However, for many API responses, it is preferable to return these fields as actual boolean values (true/false).

Automatic Conversion: The convertBooleanFields method is called after data retrieval and the afterFind event, ensuring that any specified fields are converted from 1/0 to true/false before the data is returned.

API Consistency: This conversion helps maintain consistency in API responses, aligning the data format with common expectations for boolean values in JSON and other data formats, where true and false are native boolean types.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
Thank you for sending this PR!

We expect the following in all Pull Requests (PRs).
- PRs must be sent to the [appropriate branch](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#branching)
- All git commits must be [GPG-signed](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#signing)
- Must follow our [style guide](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#php-style)
- Be [commented](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#comments) in the PHP source file
- Be documented in the [user guide](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#user-guide)
- Be [unit tested](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#unit-testing)
- Pass all checks in GitHub Actions

> [!IMPORTANT]
> We expect all code changes or bug-fixes to be accompanied by one or more tests added to our test suite to prove the code works.

If pull requests do not comply with the above, they will likely be closed. Since we are a team of volunteers, we don't have any more time to work on the framework than you do. Please make it as painless for your contributions to be included as possible.

See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md

**Comment by kenjis** [comment]
Why don't you use [Model Field Casting](https://codeigniter4.github.io/CodeIgniter4/models/model.html#model-field-casting) `int-bool` ?
Is something wrong?

**Comment by krangadurai** [comment]
I want to sincerely apologize for any inconvenience I may have caused. I value your time and appreciate your help. I'll do my best to ensure this doesn't happen again.

**Comment by kenjis** [comment]
@krangadurai No problem, but we recommend you read the in-progress User Guide:
https://codeigniter4.github.io/CodeIgniter4/

**Pull request closed without merging**
