### PR TITLE
spark: validate the PHP version

### PR DESCRIPTION
**Pull request by enix-app**
**Description**

As ``index.php`` have this, ``spark`` must have it too. I just copied and pasted it.

### CODE REVIEW

**Review by paulbalandan — COMMENTED** [review]
This check is already done in `ServeCommand`.

Maybe what we can do is remove the check in ServeCommand and have the check here instead.

**Comment by enix-app** [comment]
It's better to put it in front, not in command.
Spark will not show a list of commands if the PHP version does not match, 

```bash
$ php8 spark
```

**Comment by paulbalandan** [comment]
I agree an early terminating call to unsupported PHP version check is more preferable.

**Comment by MGatner** [comment]
@enix-app Can you remove the check from ServeCommand?

**Comment by enix-app** [comment]
Sorry there was an accident. My memory is short term :)

I opened a new PR. I'll close this.

**Pull request closed without merging**
