### PR TITLE
Convert PHPUnit tests to use reusable workflows

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
Ref:
- https://docs.github.com/en/actions/using-workflows/reusing-workflows
- https://docs.github.com/en/actions/learn-github-actions/expressions

Noted limitations:
- Service containers cannot be extracted to caller workflows
- Environment variables (`env` context) cannot be propagated from caller workflow to callee workflow
- `env` context is not available as part of inputs in `with:`

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
The test failures look promising! This is a very cool feature.

**Comment by kenjis** [comment]
Is this no problem?

```
Run vendor/bin/phpcov merge --clover build/logs/clover.xml build/cov
  vendor/bin/phpcov merge --clover build/logs/clover.xml build/cov
  shell: /usr/bin/bash -e {0}
  env:
    COMPOSER_PROCESS_TIMEOUT: 0
    COMPOSER_NO_INTERACTION: 1
    COMPOSER_NO_AUDIT: 1
    COMPOSER_CACHE_FILES_DIR: /home/runner/.cache/composer/files
phpcov 8.2.1 by Sebastian Bergmann.

PHP Warning:  file_put_contents(/home/runner/work/CodeIgniter4/CodeIgniter4/build/.phpunit.cache/code-coverage/0868cde789d9bbbd5291809ba3ac05eb): Failed to open stream: No such file or directory in /home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/php-code-coverage/src/StaticAnalysis/CachingFileAnalyser.php on line 157
PHP Warning:  file_put_contents(/home/runner/work/CodeIgniter4/CodeIgniter4/build/.phpunit.cache/code-coverage/572eb84dfb33d742634410dabaa7dd20): Failed to open stream: No such file or directory in /home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/php-code-coverage/src/StaticAnalysis/CachingFileAnalyser.php on line 157
PHP Warning:  file_put_contents(/home/runner/work/CodeIgniter4/CodeIgniter4/build/.phpunit.cache/code-coverage/0163c493712f5f3d146895a79f0399ea): Failed to open stream: No such file or directory in /home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/php-code-coverage/src/StaticAnalysis/CachingFileAnalyser.php on line 157
PHP Warning:  file_put_contents(/home/runner/work/CodeIgniter4/CodeIgniter4/build/.phpunit.cache/code-coverage/a9d6a0fd171ab95a4be00e3c2bc44e49): Failed to open stream: No such file or directory in /home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/php-code-coverage/src/StaticAnalysis/CachingFileAnalyser.php on line 157
PHP Warning:  file_put_contents(/home/runner/work/CodeIgniter4/CodeIgniter4/build/.phpunit.cache/code-coverage/435c2df1bed92ebf1a4371e97d990f06): Failed to open stream: No such file or directory in /home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/php-code-coverage/src/StaticAnalysis/CachingFileAnalyser.php on line 157
PHP Warning:  file_put_contents(/home/runner/work/CodeIgniter4/CodeIgniter4/build/.phpunit.cache/code-coverage/2639aaa66a9e5fc925ef8d0333ac89bd): Failed to open stream: No such file or directory in /home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/php-code-coverage/src/StaticAnalysis/CachingFileAnalyser.php on line 157
PHP Warning:  file_put_contents(/home/runner/work/CodeIgniter4/CodeIgniter4/build/.phpunit.cache/code-coverage/cd008375d308c903514526e9fbff1b02): Failed to open stream: No such file or directory in /home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/php-code-coverage/src/StaticAnalysis/CachingFileAnalyser.php on line 157
PHP Warning:  file_put_contents(/home/runner/work/CodeIgniter4/CodeIgniter4/build/.phpunit.cache/code-coverage/5b12acd09361cac9896a07a0099155a6): Failed to open stream: No such file or directory in /home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/php-code-coverage/src/StaticAnalysis/CachingFileAnalyser.php on line 157
PHP Warning:  file_put_contents(/home/runner/work/CodeIgniter4/CodeIgniter4/build/.phpunit.cache/code-coverage/a31934d95b42a28da4b0a1d8c295e4bd): Failed to open stream: No such file or directory in /home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/php-code-coverage/src/StaticAnalysis/CachingFileAnalyser.php on line 157
Generating code coverage report in Clover XML format ... done
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/3493686579/jobs/5848933314

**Comment by paulbalandan** [comment]
It seems I introduced this warning in #6891 by adding `cacheDirectory="build/.phpunit.cache/code-coverage"` in phpunit.xml.dist. I'll check if it poses a problem.

**Review by kenjis — APPROVED** [review]
LGTM!

**Review by MGatner — APPROVED** [review]
Awesome! Excited to play with this feature.

**Comment by paulbalandan** [comment]
I forgot to add the caching in the coverage merge. 😅

**Review by kenjis — APPROVED** [review]

**Comment by kenjis** [comment]
🎉

**Pull request merged**
