### PR TITLE
refactor: remove unused non-empty array in RequestTrait

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
Brought by `RemoveUnusedNonEmptyArrayBeforeForeachRector` but manually made as I cannot use rector on Windows.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
The `$proxyIPs` value may be an empty string if `Config\App` is not updated.
https://github.com/codeigniter4/CodeIgniter4/blob/9d952480df1059081ddccabd7ae1b38d45c659b0/app/Config/App.php#L341-L346

In this case, this change causes:
```
ErrorException
foreach() argument must be of type array|object, string given
SYSTEMPATH/HTTP/RequestTrait.php at line 82
```

**Comment by paulbalandan** [comment]
Ok. Judging by how `$this->proxyIPs` is injected with value, L68 should be revised to check that `$proxyIPs` should be an array even if empty or not.

**Comment by kenjis** [comment]
It is better to set `[]` if `$proxyIPs = ''`. Many devs do not use Proxy at all.

Or add "$proxyIPs must be an array" to *Mandatory File Changes* in the upgrade guide.

**Comment by kenjis** [comment]
I sent another PR #7620

**Pull request closed without merging**
