### PR TITLE
form helper enctype unescaped

### PR DESCRIPTION
**Pull request by nowackipawel**

### CODE REVIEW

**Comment by nowackipawel** [comment]
```enctype="multipart&#x2F;form-data"``` looks ugly :)

**Comment by samsonasik** [comment]
escaping html attributes is fine, see https://github.com/codeigniter4/CodeIgniter4/issues/345 and https://github.com/codeigniter4/CodeIgniter4/pull/351 that closed.

**Comment by nowackipawel** [comment]
thx for pointing this out. it is just idea... to make html clearer .

**Comment by lonnieezell** [comment]
If you click on the travis Details link you can see what the exact errors that are happening are. 

However, we don't need to complicate the code with special case checks for the sake of making HTML look pretty. It's perfectly functional as is, and safe and accurate.

**Pull request closed without merging**
