### PR TITLE
use SVG logo on Welcome page

### PR DESCRIPTION
**Pull request by totoprayogo1916**
Use SVG like on Official Site.
The SVG's logo grabbed from codeigniter.com and optimized on https://jakearchibald.github.io/svgomg/

before:
image

after:
image

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Review by MGatner — APPROVED** [review]
Looks good. Can you speak to why you lived the image `alt` to a link `title`? I'm no expert but I think those accomplish different things.

**Comment by paulbalandan** [comment]
I think the title to the `<a>` is to serve as tooltip when hovered.

**Comment by totoprayogo1916** [comment]
Instead of the `alt` of the unused image, I move it as `a title`.
The reference of `a title`,  https://html.com/attributes/a-title/

**Comment by kenjis** [comment]
> Instead of the alt of the unused image,

What do you mean by unused? It seems the image (logo) is used.

`alt` and `title` are different things. Why do you remove `alt`?

**Comment by totoprayogo1916** [comment]
when using the `img` tag there is an `alt` attribute, while `svg` not.
so, the `alt` of the `img` tag is not used, then I move it as `title` in `a href`.

**Comment by kenjis** [comment]
Oh, thanks. I got it.

I recommend you use `aria-label`:
```
<svg role="img" aria-label="Visit CodeIgniter.com official website!" ...>
```
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/img_role#svg_and_roleimg

**Comment by totoprayogo1916** [comment]
> I recommend you use `aria-label`

Updated

**Review by kenjis — APPROVED** [review]
Thank you!

**Pull request merged**
