### PR TITLE
Manual cleanup of docblocks and comments

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
- Fix inconsistency in docblock against typehint
- Remove unremoved superfluous doc tags
- Remove unnecessary or redundant doc comments
- Remove unnecessary comments only stating the obvious
- EXTRA: Fix notice in pre-commit hook for missing whitespace

**Checklist:**
- [x] Securely signed commits
- [x] Conforms to style guide

### CODE REVIEW

**Review by MGatner — APPROVED** [review]
😳 This is a massive amount of work. Did you do this all by hand??

**Comment by paulbalandan** [comment]
This is quite a boring task. This is all I can finish in 2 hours. 😅

**Comment by MGatner** [comment]
😍 Totally understand. Did you follow some progression? Leave a note of where you were so we know where to pick back up at some point.

**Comment by paulbalandan** [comment]
Basically, I gave up after Database. That's where all the bulk of unnecessary comments came from. The rest I just skimmed and used find and replace.

**Pull request merged**
