### PR TITLE
ensure load "SYSTEMPATH . Config/Services.php" in system/bootstrap.php

### PR DESCRIPTION
**Pull request by samsonasik**
This should fix the issue reported by @kloukas  https://github.com/codeigniter4/CodeIgniter4/pull/2976#issuecomment-626948222

**Checklist:**
- [x] Securely signed commits

### CODE REVIEW

**Comment by samsonasik** [comment]
applied  move out require_once of AutoloaderConfig from Config\Autoload class to bootstrap as well

**Comment by samsonasik** [comment]
I tested and it works in with and without composer autoload

**Comment by kloukas** [comment]
Yup, that fixed it. Thanks!

**Comment by samsonasik** [comment]
@kloukas than you for the check. @lonnieezell could you verify ? Thank you.

**Comment by Instrye** [comment]
@lonnieezell please check this PR. current develop can't work.
image

**Pull request merged**
