### PR TITLE
chore: add .user-guide.php-cs-fixer.dist.php for sample code in docs

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
- add `.user-guide.php-cs-fixer.dist.php`
- add user guide cs check in git pre-commit hook
- add user guide cs check in GitHub Action
- update `composer cs-fix`

I propose the following before fixing sample code:
- move CI3 sample code in Upgrading into the folder `ci3sample/`
  - we need exclude the CI3 sample code
  - #5771
- use `/* ... */` style comment for explanation of the code result
  - The comments are not normal comments, so it is better not to use `//`
  - #5770

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by paulbalandan** [comment]
I agree with the proposals. Side comment, latest master of php-cs-fixer has its own implementation of `space_after_comment_start` so on next release the use on `//` will be strictly for single-lines only. So, as early as now, multiline comments should start using the `/* */` way and reserve `//` for single-line comments.

**Comment by kenjis** [comment]
> This would then be applied and integrated into the pre-commit hook, right?

I added the check in the pre-commit.

**Comment by kenjis** [comment]
I sent PRs #5770, #5771

**Review by paulbalandan — APPROVED** [review]

**Comment by sfadschm** [comment]
Applying the fixer will then be another PR?

**Comment by kenjis** [comment]
> Applying the fixer will then be another PR?

Yes, because the difference is huge.
But as you say, the code fixes need to be committed soon right after this PR's merging.

**Comment by kenjis** [comment]
I created #5773 to apply the fixer.

**Comment by kenjis** [comment]
Added GitHub Action update.

**Review by paulbalandan — APPROVED** [review]

**Pull request merged**
