### PR TITLE
Merge 4.4 into develop

### PR DESCRIPTION
**Pull request by kenjis**
To release v4.4.0.

### CODE REVIEW

**Comment by neznaika0** [comment]
https://codeigniter.com/user_guide/index.html
I probably need to update the documentation on the site along with this release. The 4.3.7 branch is not available now either.

**Comment by kenjis** [comment]
Screenshot 2023-08-25 13 25 05
Why merging is blocked?
It seems all commits are "Verified".

**Comment by kenjis** [comment]
Ah, 
> This pull request is big! We’re only showing the most recent 250 commits.

**Comment by kenjis** [comment]
@neznaika0 
What do you mean? 
The `4.3.7 branch` does not exist from the beginning.

**Comment by neznaika0** [comment]
Shouldn't it be published?

**Comment by kenjis** [comment]
The user guide is already updated.
https://codeigniter.com/user_guide/changelogs/v4.3.8.html
I'm not sure, but Lonnie did it?

**Comment by lonnieezell** [comment]
@kenjis yeah I updated it. Now that 4.4 is released looks like I should update it again.

**Comment by lonnieezell** [comment]
Well, after the package is created I can. Will check back in a little bit.

**Comment by neznaika0** [comment]
Thanks

**Comment by kenjis** [comment]
`4.4` branch was merged into `develop`.
So now `develop` is for 4.4.x.
And `4.5` branch will be created after releasing v4.4.0.

**Pull request merged**
