### PR TITLE
[ci skip] Guide: RESTful table formatting

### PR DESCRIPTION
**Pull request by MGatner**
**Description**
A few formatting improvements for the RESTful table.

**Checklist:**
- [X] Securely signed commits
- [X] Component(s) with PHPdocs
- n/a Unit testing, with >80% coverage
- [X] User guide updated
- [X] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
I actually don't know how 😮

Is that Sphinx?

**Comment by MGatner** [comment]
I found it. Will check.

**Comment by MGatner** [comment]
It's not working on macOS, I'll have to try it later on a server.

**Comment by jim-parry** [comment]
I had to step out, but am back. WIll try it here

**Comment by jim-parry** [comment]
Looks really good :)

**Pull request merged**
