### PR TITLE
fix: `spark routes` does not show routes at all

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Follow-up #6110

- add loading of `Conig/Routes.php`

Before:
```
+--------+-------+---------+----------------+---------------+
| Method | Route | Handler | Before Filters | After Filters |
+--------+-------+---------+----------------+---------------+
```

After:
```
+--------+-------+------------------------------+----------------+---------------+
| Method | Route | Handler                      | Before Filters | After Filters |
+--------+-------+------------------------------+----------------+---------------+
| GET    | /     | \App\Controllers\Home::index |                | toolbar       |
+--------+-------+------------------------------+----------------+---------------+
```

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by lonnieezell** [comment]
A couple of thoughts:

1- when did this break? I used this on a  4.2.1 install a couple of nights ago and it works fine.
2- this only loads a single routes file - it doesn’t scan all of the namespaces for routes confit files. Or was this one file being missed when it was trying to locate all of the files? If so - we need to figure out why and fix it there.

**Comment by kenjis** [comment]
1. on 4.3 branch. This is because of #6110

2. Yes, but the call of `getRoutes()` scans module routes. So no problem.
https://github.com/codeigniter4/CodeIgniter4/blob/dcfc17e804081e43870a0e9c66df1caa0e0aae0f/system/Commands/Utilities/Routes.php#L100

**Comment by kenjis** [comment]
I tested with Shield and works fine.

```console
$ php spark routes

CodeIgniter v4.2.1 Command Line Tool - Server Time: 2022-07-15 23:33:02 UTC-05:00

+--------+-------------------------+--------------------+--------------------------------------------------------------------+----------------+---------------+
| Method | Route                   | Name               | Handler                                                            | Before Filters | After Filters |
+--------+-------------------------+--------------------+--------------------------------------------------------------------+----------------+---------------+
| GET    | /                       |                    | \App\Controllers\Home::index                                       |                | toolbar       |
| GET    | register                |                    | \CodeIgniter\Shield\Controllers\RegisterController::registerView   |                | toolbar       |
| GET    | login                   |                    | \CodeIgniter\Shield\Controllers\LoginController::loginView         |                | toolbar       |
| GET    | login/magic-link        | magic-link         | \CodeIgniter\Shield\Controllers\MagicLinkController::loginView     |                | toolbar       |
| GET    | login/verify-magic-link | verify-magic-link  | \CodeIgniter\Shield\Controllers\MagicLinkController::verify        |                | toolbar       |
| GET    | logout                  |                    | \CodeIgniter\Shield\Controllers\LoginController::logoutAction      |                | toolbar       |
| GET    | auth/a/show             | auth-action-show   | \CodeIgniter\Shield\Controllers\ActionController::show             |                | toolbar       |
| POST   | register                |                    | \CodeIgniter\Shield\Controllers\RegisterController::registerAction |                | toolbar       |
| POST   | login                   |                    | \CodeIgniter\Shield\Controllers\LoginController::loginAction       |                | toolbar       |
| POST   | login/magic-link        |                    | \CodeIgniter\Shield\Controllers\MagicLinkController::loginAction   |                | toolbar       |
| POST   | auth/a/handle           | auth-action-handle | \CodeIgniter\Shield\Controllers\ActionController::handle           |                | toolbar       |
| POST   | auth/a/verify           | auth-action-verify | \CodeIgniter\Shield\Controllers\ActionController::verify           |                | toolbar       |
+--------+-------------------------+--------------------+--------------------------------------------------------------------+----------------+---------------+
```

**Comment by kenjis** [comment]
This bug has not been released, but it is terrible and I would like to merge it.
Someone please review it.

**Review by MGatner — APPROVED** [review]
Yes, this is correct. I have worked with our strange way of seeding routes recently and this is how you have to do it.

**Pull request merged**
