### PR TITLE
Add DotEnv::parse()

### PR DESCRIPTION
**Pull request by MGatner**
**Description**
Currently `DotEnv` handles all its functionality in one go, using `load()`. This splits out the function so `parse()` returns the `key =>value` array and then `load()` still handles setting the variables. This allows external parsing of `.env` files (particularly for testing purposes). All tests and usage should remain consistent.

**Checklist:**
- [X] Securely signed commits
- [X] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [X] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
I'm baffled by this error. This is working locally. @lonnieezell any ideas? anyone?

**Comment by atishamte** [comment]
Check this. Might be helpful

https://devcentral.nasqueron.org/D1604

**Comment by musmanikram** [comment]
@MGatner I created below PR with all your changes, except `parse()` method return null and array. Please have a look on my PR:
https://github.com/codeigniter4/CodeIgniter4/pull/2589

**Comment by MGatner** [comment]
That's a baffling change to get tests working but I will give it a shot.

**Comment by MGatner** [comment]
Ohhhh I see, I had specified `array` return type but was returning a boolean. Thanks for catching that! Very strange error message but I'm hopeful that was all.

**Comment by musmanikram** [comment]
> Ohhhh I see, I had specified `array` return type but was returning a boolean. Thanks for catching that! Very strange error message but I'm hopeful that was all.

Cool, i hope now your PR will be green also. I will close mine :)

**Comment by MGatner** [comment]
Leave yours! I'll merge it. Just making sure these tests pass (look good) to be sure, then I'll close this.

**Comment by MGatner** [comment]
@musmanikram Your PR has unsigned commits so I actually can't merge it. I will merge this one but another special thanks for troubleshooting and solving this issue!

**Comment by musmanikram** [comment]
@MGatner i am more than happy to help and contributing a to a framework which i am using from last 7 or 8 years

**Pull request merged**
