### PR TITLE
Add post-migration event

### PR DESCRIPTION
**Pull request by MGatner**
**Description**
Adds an event after running migration `latest` or `regress`.

**Checklist:**
- [X] Securely signed commits
- [X] Component(s) with PHPdocs
- [X] Unit testing, with >80% coverage
- [x] User guide updated
- [X] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
I need to update the User Guide before this is merged.

**Comment by MGatner** [comment]
I don't understand why these are passing locally but failing on Travis:
```
ubuntu@ip:/opt/CodeIgniter4$ git status
On branch migrate-event
Your branch is up to date with 'origin/migrate-event'.

ubuntu@ip:/opt/CodeIgniter4$ ./vendor/bin/phpunit tests/system/Database/Migrations/MigrationRunnerTest.php 
PHPUnit 8.5.8 by Sebastian Bergmann and contributors.

......................                                            22 / 22 (100%)

Time: 15.36 seconds, Memory: 32.00 MB

OK (22 tests, 48 assertions)
```

Guess I will have to dig more tomorrow.

**Comment by MGatner** [comment]
I cannot figure out these failures. I'm going to rerun Travis just to be sure.

**Comment by MGatner** [comment]
Can someone else try this one? Tests pass locally for me on two servers, two different drivers, but they continue to fail during TravisCI. Not sure what else to do. @michalsn @paulbalandan @samsonasik

**Comment by samsonasik** [comment]
probably need `@runInSeparateProcess` ?

**Comment by paulbalandan** [comment]
Simple trick. Turn off `Events::simulate()`. I think this was turned on during the Events test. Since it is static, it will persist throughout the tests.

**Comment by MGatner** [comment]
Thanks you two! I bet you're right. Trying it now.

**Comment by MGatner** [comment]
Passing now, yay! Thanks team.

**Review by michalsn — APPROVED** [review]

**Pull request merged**
