### PR TITLE
feat: add Config\View::$enableConditionals to disable Parser conditionals

### LINKED ISSUE #5831: Bug: View parser throws view exception with nested 'if' within javascript code
### PHP Version

8.0

### CodeIgniter4 Version

4.1.8

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

mysql

### What happened?

when parsing a view with inline javascript (within a script tag, specifically an if statement within outer braces {})
the view parser mis-interpretes this code as a view conditional and improperly transforms the code to a php conditional.

### Steps to Reproduce

controller code:
```php
public function test(){
		$parser = service('parser');

        $somedata = [
            'message' => 'massagee'
        ];
        $view = <<<'EOL'
                 <script type="text/javascript">
                     var f = function(){
                         if(true){
                             alert('{message}');
                         }
                     }
                 </script>
                 EOL;

        return $parser->setData($somedata)->renderString($view);
    }
```

error message:
```
You have a syntax error in your Parser tags: <script type="text/javascript">
var f = function()if ((true){
alert('{message): ');
}
}
</script>
```

problem:
the nested javascript if statement has been parsed
and php tags have been placed around it 
(observed by printing the output directly pre-evaluation in the parser class)

### Expected Output

Expected output would be the non-modified javascript,
with the substituted tag within.

```js
<script type="text/javascript">
                     var f = function(){
                         if(true){
                             alert('massagee');
                         }
                     }
                 </script>
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #5831

CI3 Parser does not have conditionals. See https://codeigniter.com/userguide3/libraries/parser.html
CI4 Parser has conditionals, and it is difficult to distinguish if there is JavaScript code in templates.

- add `Config\View::$enalbeConditionals` to disable Parser conditionals
  - The setting is for compatibility with templates that works on CodeIgniter3.

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by totoprayogo1916 — COMMENTED** [review]
Is this a typo?
enable or enalbe?

**Comment by kenjis** [comment]
@totoprayogo1916 Thanks! These are typos. Fixed.

**Comment by kenjis** [comment]
I found another solution: #5842
This PR might not to be needed.

**Comment by kenjis** [comment]
#5842 was merged, so I think this is not needed.

**Pull request closed without merging**
