### PR TITLE
Update array_helper.php

### PR DESCRIPTION
**Pull request by nowackipawel**
Is array sequential  / associative

### CODE REVIEW

**Comment by atishamte** [comment]
Also provide the documentation and test scenarios

**Comment by atishamte** [comment]
With array_key_exists(), I can directly check whether the array is associative or sequential.

**Comment by nowackipawel** [comment]
How about:

[0 => 'a', 'b' => 'c'];

?

**Comment by atishamte** [comment]
This is not an associative array.

**Comment by lonnieezell** [comment]
Sorry. I don't think these have broad enough requirements in day-to-day work, and as @atishamte says - PHP already has tools to help you get the answer you need.

**Pull request closed without merging**
