### PR TITLE
modify: public .htaccess follow REQUEST_SCHEME when rewriting

### PR DESCRIPTION
**Pull request by NicolaeIotu**
**Description**
Explain what you have changed, and why.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
Ref https://httpd.apache.org/docs/trunk/mod/mod_rewrite.html#rewritecond

**Comment by NicolaeIotu** [comment]
The purpose of the block is "# Rewrite "www.example.com -> example.com"", but additionally the scheme is changed to **http**. This makes requests to *https://www.example.com* translate to *http://example.com* which is wrong because a HTTPS only server cannot serve this request.
 
The mistake may be hidden by a few ways:
* the server is HTTP only
* the server is HTTP only, but the frontend is served using specialized tools (i.e. cloud tools) which are able to change incoming HTTPS to HTTP and outgoing HTTP to HTTPS
* the server is able to serve both HTTP and HTTPS
* production .htaccess has additional statements which change HTTP to HTTPS

**Comment by kenjis** [comment]
Why do requests to `https://www.example.com/` translate to `http://example.com/` with `RewriteCond %{HTTPS} !=on`?

```
	# Rewrite "www.example.com -> example.com"
	RewriteCond %{HTTPS} !=on
	RewriteCond %{HTTP_HOST} ^www\.(.+)$ [NC]
	RewriteRule ^ http://%1%{REQUEST_URI} [R=301,L]
```

**Comment by NicolaeIotu** [comment]
My mistake. I'm going to close this PR. It seems your intention is to do the rewriting only for non-https requests which is different from my approach.

Can you please tell me to which branch I should make a pull request for a proposed new feature of CodeIgniter? (which most probably requires changes). Is it **develop**?

**Comment by kenjis** [comment]
It is not my intention, but the current `.htaccess` is like that.

Now `4.5` branch is for new features.
`develop` is only for bug fixes.

**Comment by NicolaeIotu** [comment]
Actually it makes sense: protect **www** for non-https. Thank you very much.

**Pull request closed without merging**
