### PR TITLE
Hotfix 4.1.7

### PR DESCRIPTION
**Pull request by kenjis**
This is for hotfix release. Will be merged into `master`.

# TODO
- [x] Update system/CodeIgniter.php with the new version number: const CI_VERSION = '4.x.x';
- [x] Update user_guide_src/source/conf.py with the new version = '4.x' (if applicable) and release = '4.x.x'
- [x] CHANGELOG.md
- [x] Update CHANGELOG.md release date
- [x] Set the date in user_guide_src/source/changelogs/{version}.rst to format Release Date: January 31, 2021
- [ ] Create a new changelog for the next version at user_guide_src/source/changelogs/{next_version}.rst and add it to index.rst
- [x] If there are additional upgrade steps, create user_guide_src/source/installation/upgrade_{ver}.rst and add it to upgrading.rst

## After merging
- [ ] Merge this branch (or `master`) into `develop`

### CODE REVIEW

**Comment by kenjis** [comment]
What I did:

```
$ git fetch upstream
$ git checkout -b hotfix-4.1.7 upstream/master
```

```
$ git log -b develop --merges 
```

Pick up the merge commits.

```
67d00b3ef762b25b59e8305f1d91bfd71a3b1eeb #5553
a09f7d9f6814ea447ab4029ee99896ea5b0b069e #5554
796acc827b100238c466667c34861b4653d2ea07 #5546
a5d604dc971c2fc383bcf12677bf9c1dd9bc4f23 #5542
e0fd7d4cff0ef925b4ccfb876da1e8a64ece14e3 #5544
a8e271ae4666bb2dd3a51462264b16b07bbe4380 #5536
347ac8e092547dab7c3b575911bcef7c0fc95071 #5527
12877cd742a00ec336bd54b599178e623e570c46 #5537
0755553a4259fbacc799395ca8a5546c5e979c45 #5532
```

```
$ git cherry-pick -m 1 0755553a4259fbacc799395ca8a5546c5e979c45
$ git cherry-pick -m 1 12877cd742a00ec336bd54b599178e623e570c46
$ git cherry-pick -m 1 347ac8e092547dab7c3b575911bcef7c0fc95071
$ git cherry-pick -m 1 a8e271ae4666bb2dd3a51462264b16b07bbe4380
$ git cherry-pick -m 1 e0fd7d4cff0ef925b4ccfb876da1e8a64ece14e3
$ git cherry-pick -m 1 a5d604dc971c2fc383bcf12677bf9c1dd9bc4f23
$ git cherry-pick -m 1 796acc827b100238c466667c34861b4653d2ea07
$ git cherry-pick -m 1 a09f7d9f6814ea447ab4029ee99896ea5b0b069e
$ git cherry-pick -m 1 67d00b3ef762b25b59e8305f1d91bfd71a3b1eeb
```

```
$ git push upstream HEAD 
```

Create #5555 and merge.

**Comment by kenjis** [comment]
#5531 `composer.json` update should have been included the hotfix branch.
Because the previous fix commit in `codeigniter4/framework` was overwritten by the deployment script. 

We have a GitHub Action that watches for a new release. It runs a deployment script: https://github.com/codeigniter4/CodeIgniter4/blob/8449d13724d460a4e5573f49027cd9f862449a29/.github/workflows/deploy-framework.yml#L35-L36
That script (https://github.com/codeigniter4/CodeIgniter4/blob/develop/.github/scripts/deploy-framework) copies all the files from the main repo to framework, but then overwrites a few files with the versions in admin/framework/

**Comment by kenjis** [comment]
This work flow is not good for changelog auto-generation. Cherry-picked PRs is not included generated changelog for `hotfix-4.1.7` branch.

And at the next release, the cherry-picked PRs included in v4.1.7 would probably be included again in auto-generated changelog for `develop` branch.

**Comment by MGatner** [comment]
Since we reformat the changelog manually anyways I don't think that will be a problem, we just need to remember to pull any duplicates!

**Comment by kenjis** [comment]
@MGatner When we need to release a hotfix, we should create the hotfix branch as soon as possible and merge all the fixes into it. I think it is the better work flow.

**Pull request merged**
