### PR TITLE
fix: table view attribute cannot applied to element `td` on header and footer

### LINKED ISSUE #6507: Bug: Table footer will not take tag attributes
### PHP Version

8.1

### CodeIgniter4 Version

4.1.5

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL

### What happened?

**\CodeIgniter\View\Table**
Table footer will not incorporate extra attributes. It assumes the footer cell is `th` rather than `td` (as specified in the default template). This means you can not style the table footer by using element attributes (e.g. class, style).

### Steps to Reproduce

```php
// style wanted for cells containing numbers 
$style = 'background:#F99;text-align:right;width:5em;';
// table data
$data = [
	['item', ['data'=>'count', 'style'=>$style]],
	['shirt', ['data'=>2, 'style'=>$style]],
	['hat', ['data'=>1, 'style'=>$style]]
];
// add footing - summary of table data
$footing = ['total', ['data'=>3, 'style'=>$style]];

echo '<p>Use default template</p>';
$table = new \CodeIgniter\View\Table();
$table->setFooting($footing);
echo $table->generate($data);

echo '<p>Update template footer to use {th} rather then {td}.</p>';
$template = [
	'footing_cell_start' => '<th>',
	'footing_cell_end' => '</th>'
];
$table = new \CodeIgniter\View\Table($template);
$table->setFooting($footing);
echo $table->generate($data);
```

### Expected Output

I expect cells in the footer to be accept attributes in the same manner as cells in the table body or table header. 

### Anything else?

line 365 of System\View\Table
`$temp = str_replace('<th', '<th ' . $key . '="' . $val . '"', $temp);`

{th} should be {td}, if the template is default

---

But, of course, what if the template has been altered by the App? This replacement method is only going to work if the template 'table_footer_start' starts with '<th'.

For now... make it work for the _default_ template. If people change the template, they probably will not use the extra attributes.

### PR DESCRIPTION
**Pull request by ddevsr**
**Description**
Fixed #6507
Supersedes #6511

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by ddevsr** [comment]
image

@kenjis On PC office cant running all sign commit (rebase error), and now i am using export file key to home PC cannot sign gpg. How do I fix this? so that my key id on both pc can be used.

**Comment by kenjis** [comment]
@ddevsr Export private/public keys and import the  keys.

How to export and import keys with GPG
https://linuxhint.com/export-import-keys-with-gpg/

**Comment by ddevsr** [comment]
image
@kenjis still same error

**Comment by ddevsr** [comment]
Okay, i am already import private yesterday. Public key soon

Pada tanggal Sel, 13 Sep 2022 05.13, kenjis ***@***.***>
menulis:

**Pull request closed without merging**
