### PR TITLE
feat: Precise return type inference for `model()` and `config()`

### PR DESCRIPTION
**Pull request by paulbalandan**
**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
Why do you need this?
Of course the current PHPDoc types for them are not perfect, but
I think all return types for them in this repository are now correct without this PR.

If we need this, it should be another package? 
Because we can't use this feature with app starter easily.

**Review by MGatner — CHANGES_REQUESTED** [review]
@paulbalandan I agree with kenjis that this might fit better as a standalone package, or even better as part of DevKit where we already collect a number of these scaffolding tools. 
I'm excited to try it out though! As far as you know is it working as intended?

**Comment by paulbalandan** [comment]
@kenjis @MGatner my initial intention of putting it here is to try it out here to catch any bugs (which it did in https://github.com/codeigniter4/CodeIgniter4/pull/7568/commits/4e18871c123c4e7480265c455468d65e1d31635e). I can pull this up to a standalone package (even better as a phpstan extension package). Just wanted to show it here first to get some reactions on the behavior.

**Comment by MGatner** [comment]
@paulbalandan that makes sense! I guess there is no real way to demonstrate it publicly otherwise. Yes, please proceed - I'm excited for this enhancement!

**Comment by kenjis** [comment]
Yes, without this we can't detect bugs like that!

**Comment by paulbalandan** [comment]
Okay. I'll start the phpstan extension this week. Would `codeigniter/phpstan-codeigniter4` be okay as package name?

**Comment by kenjis** [comment]
It is only for CI4, so the vendor name should be `codeigniter4`?

By the way, when we release v5, will the vendor name be `codeigniter4`?

**Comment by paulbalandan** [comment]
In `coding-standard` it was put in the `codeigniter` vendor name because it's intended to be used in v4 and up (to minimize need of setting up `codeigniter5` org etc.), so I think this should also be the case here.

**Comment by MGatner** [comment]
I have advocated to @lonnieezell that with version 5 we need to take over the generic "CodeIgniter" brand and v3 can start adding the number or finally retire.

**Comment by paulbalandan** [comment]
Closing this for now.

I'll open `codeigniter/phpstan-codeigniter` package soon.

**Comment by kenjis** [comment]
Since v3 is already almost unmaintained, it seems like a good idea to make `codeigniter/framework` v5.

**Pull request closed without merging**
