### PR TITLE
Coveralls Failures

### PR DESCRIPTION
**Pull request by MGatner**
**Description**
The pipeline failures for -7% coverage have been driving me crazy. I'm not sure if this will fit the issue, but I'm going to tinker with it.

**Checklist:**
- [X] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [X] Conforms to style guide

### CODE REVIEW

**Comment by paulbalandan** [comment]
How about using the `phpcov` option?
https://github.com/php-coveralls/php-coveralls#phpcov

**Comment by paulbalandan** [comment]
Although green, this fix is wrong, because the build is "PENDING COMPLETION".
See https://coveralls.io/jobs/107756800

**Comment by MGatner** [comment]
I think it is a bigger issue. Coveralls still has us pegged at "85% coverage", so when the PR results get posted it always sees it as a decrease. I poked around on the site but I'm still unclear what the root problem is.
Screen Shot 2022-10-15 at 1 41 10 PM

**Comment by MGatner** [comment]
> How about using the phpcov option?
I will take a look.

**Comment by MGatner** [comment]
There is some discrepancy between "Builds" (pull requests, 388 total files) and the baselines (`develop`, 377 total files).

**Comment by kenjis** [comment]
> There is some discrepancy between "Builds" (pull requests, 388 total files) and the baselines (develop, 377 total files).

It is the difference between 4.3 and develop.

**Comment by kenjis** [comment]
It seems that *push* has around 85%, but *Pull Request* has around 77% recently.
https://coveralls.io/repos/237520/builds?page=1

But in the past, sometimes *Pull Request* has more than 80% coverage.
https://coveralls.io/repos/237520/builds?page=44

But, the lastest *Pull Request* build also has  84.91% system/ coverage:
https://coveralls.io/builds/53301874

**Comment by kenjis** [comment]
I have no clue.

1. Let's proceed with this for now. The build will be "PENDING COMPLETION", but it is better than now.
2. Switch to another service like https://about.codecov.io/

**Comment by sclubricants** [comment]
If the coveralls for one database driver is running is it possible to exclude the files for all the other drivers? This isn't perfect as some of the implementation is in the base classes but it should help some.

**Comment by kenjis** [comment]
> If the coveralls for one database driver is running is it possible to exclude the files for all the other drivers?

It seems we need to prepare `phpunit.xml` for each DB driver, and use it when running phpunit.

**Pull request closed without merging**
