### PR TITLE
refactor: upgrade to use phpstan 2 and rector 2

### PR DESCRIPTION
**Pull request by samsonasik**
**Description**

This PR upgrade to use PHPStan 2 and Rector 2.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by samsonasik** [comment]
phpstan-codeigniter seems stil require phpstan v1, so in there should be updated first:

```
  Problem 1
    - Root composer.json requires codeigniter/phpstan-codeigniter ^1.4 -> satisfiable by codeigniter/phpstan-codeigniter[v1.4.0, ..., v1.5.1].
    - codeigniter/phpstan-codeigniter[v1.4.0, ..., v1.4.2.70400] require phpstan/phpstan ^1.10 -> found phpstan/phpstan[1.10.0, ..., 1.12.12] but it conflicts with your root composer.json require (^2.0).
```

**Comment by samsonasik** [comment]
Ok, bump to use phpstan-codeigniter 1.5.1 is the way https://github.com/codeigniter4/CodeIgniter4/pull/9322/commits/9b6d9bfd42fd0273d76609048dd06382429c5523

**Comment by samsonasik** [comment]
install seems got codeigniter ^4.5 conflict notice:

```
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires codeigniter/phpstan-codeigniter ^1.5.1 -> satisfiable by codeigniter/phpstan-codeigniter[v1.5.1].
    - codeigniter/phpstan-codeigniter v1.5.1 requires codeigniter4/framework ^4.5 -> found codeigniter4/framework[v4.5.0, ..., v4.5.5] but these were not loaded, likely because it conflicts with another require.
```

ref https://github.com/codeigniter4/CodeIgniter4/actions/runs/12333325314/job/34422197398?pr=9322

@paulbalandan @kenjis  any idea?

**Comment by paulbalandan** [comment]
@samsonasik that should be taken care of in #9299, i just need to get @kenjis ' approval

**Comment by paulbalandan** [comment]
@samsonasik pls rebase in latest develop. probably you would just need to update rector version

**Comment by samsonasik** [comment]
Rebased 👍

**Comment by samsonasik** [comment]
Setup PHP error seems unrelated:

```
==> Setup PHP
✗ PHP Could not setup PHP 8.3
Error: The process '/usr/bin/bash' failed with exit code 1
```

**Review by paulbalandan — APPROVED** [review]
I think this is good to go. I'm merging this.

**Pull request merged**
